objects/Account.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <label>County (Local)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Siebel_Account_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Current Siebel Account Id</description>
        <externalId>true</externalId>
        <inlineHelpText>Siebel Account Id</inlineHelpText>
        <label>Siebel Account ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>County_Local__c</fullName>
        <label>County (Local)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Siebel_Contact_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Contact Id from Siebel</description>
        <externalId>true</externalId>
        <label>Siebel Contact ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MW_Project__c.object
<CustomObject>
    <description>This is the AEG Request and Project Object.</description>
    <fields>
        <fullName>Customer_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary Customer Contact for AEG Request</description>
        <label>Customer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>AEG_Projects_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used as a place holder so that the project can be created from Opty. Will use this field to set the project Id on the opportunity from which it is created.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>AEG_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <description>The Project Status</description>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>PE: Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P{000000}</displayFormat>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>AEG approved project</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Team_Member__c.object
<CustomObject>
    <description>This object is for AE / PE Resource Requests and Tracking (User Story: 317488)</description>
    <label>Project Team Member</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Project Team ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Project_Time_Card__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <inlineHelpText>Use Manage Time Card Entries to change Activity Type</inlineHelpText>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Interaction</fullName>
                </value>
                <value>
                    <fullName>Customer Support</fullName>
                </value>
                <value>
                    <fullName>Content Related Tasks</fullName>
                </value>
                <value>
                    <fullName>Strategy/Planning/Reporting</fullName>
                </value>
                <value>
                    <fullName>Traveling</fullName>
                </value>
                <value>
                    <fullName>PSP: Product Customization</fullName>
                </value>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>Admin</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Hours</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <label>Product Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Application Deployment</fullName>
                </value>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>Computational Biology</fullName>
                </value>
                <value>
                    <fullName>Computational Finance</fullName>
                </value>
                <value>
                    <fullName>Control Systems</fullName>
                </value>
                <value>
                    <fullName>Embedded Code Generation</fullName>
                </value>
                <value>
                    <fullName>HDL Code Generation &amp; Verification</fullName>
                </value>
                <value>
                    <fullName>Image Processing &amp; Computer Vision</fullName>
                </value>
                <value>
                    <fullName>Math, Statistics &amp; Optimization</fullName>
                </value>
                <value>
                    <fullName>MATLAB</fullName>
                </value>
                <value>
                    <fullName>Model Verification &amp; Validation</fullName>
                </value>
                <value>
                    <fullName>Parallel Computing</fullName>
                </value>
                <value>
                    <fullName>Simscape</fullName>
                </value>
                <value>
                    <fullName>Polyspace</fullName>
                </value>
                <value>
                    <fullName>Real-Time Simulation &amp; Test</fullName>
                </value>
                <value>
                    <fullName>Robotics Systems</fullName>
                </value>
                <value>
                    <fullName>Signal Processing Systems</fullName>
                </value>
                <value>
                    <fullName>Simulink and Stateflow</fullName>
                </value>
                <value>
                    <fullName>Test &amp; Measurement</fullName>
                </value>
                <value>
                    <fullName>Wireless Systems</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <description>Pulls the Project Status value from the related project, used in validation rules and time card entry behavior</description>
        <formula>TEXT(Project__r.Project_Status__c)</formula>
        <label>Project Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Week_Date__c</fullName>
        <description>User Will fill Time card for particular date of the week.</description>
        <label>Week Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Week_Ending__c</fullName>
        <label>Week Ending</label>
        <type>Date</type>
    </fields>
    <label>Time Card</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Project Time Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Functional_Role__c</fullName>
        <inlineHelpText>Denotes what role a user plays on a Sales Territory Team.  Used for Oppty assignment and to support collaboration among team members.</inlineHelpText>
        <label>Functional Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inside Sales Rep</fullName>
                </value>
                <value>
                    <fullName>Inside Sales Rep non primary</fullName>
                </value>
                <value>
                    <fullName>National Account Sales Specialist</fullName>
                </value>
                <value>
                    <fullName>Product Overlay Sales Rep</fullName>
                </value>
                <value>
                    <fullName>Sales Development Rep</fullName>
                </value>
                <value>
                    <fullName>Sales Maintenance Rep</fullName>
                </value>
                <value>
                    <fullName>Sales Maintenance Rep non primary</fullName>
                </value>
                <value>
                    <fullName>Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Sales Rep</fullName>
                </value>
                <value>
                    <fullName>Sales Rep Primary</fullName>
                </value>
                <value>
                    <fullName>Sales Specialist</fullName>
                </value>
                <value>
                    <fullName>Sales Support Manager</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Application Engineer</fullName>
                </value>
                <value>
                    <fullName>Pilot Engineer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TimecardControllerTest.cls
/**
 * Modified : Faina Gorelik
 * Date modified: 29 Nov 2016 AtTask #1777908 
 * description: This class contains unit tests for validating the behavior of ProjectDML, ProjectTriggerHandler classes
 * and ProjectMasterTrigger trigger.
 */
@isTest (seeAllData = false)
private with sharing class TimecardControllerTest {

	//re-create custom setting test records when running the test class
	static CustomSettingsBuilder custsettbuild = new CustomSettingsBuilder();

	public static string roleAppENGG='Application Engineer';

	//Get Current weekending Date
	private static Date dayOfWeek(Date dt, Integer dd){
		
		Date dtToCompare = Date.newInstance(1900, 1, dd);
		integer Days = Integer.valueOf(dt.daysBetween(dtToCompare.addDays(1)));
		return dt.addDays(6 - Math.abs(Math.mod(Days, 7)));
		
	}

	static testMethod void TestTimeCardController() {

		//Inserting Bypass trigger custom setting
		custsettbuild.buildBypassTriggerSettings();

		custsettbuild.buildTimeCardControllerList();
		custsettbuild.buildGenSetting();

		//Create User Record
		User u = TestDataBuilder.buildTestUser(1);
		u.Functional_Role__c = '';
		insert u;

		system.runAs(u) {

			Account acc = TestDataBuilder.buildTestAccount(0,UserInfo.getUserId());
			acc.Name = 'Smith';
			acc.BillingCity ='Boston';
			acc.BillingCountry = 'United States';
			acc.BillingCountryCode = 'US';
			acc.BillingPostalCode ='400011';
			acc.BillingStateCode ='AK';
			acc.BillingState ='Alaska';
			acc.BillingStreet = 'MG Street';
			acc.County__c = 'abc';
			acc.Siebel_Account_Id__c = '1-CS15';
			insert acc;


			Contact cont= TestDataBuilder.buildTestContact(0,UserInfo.getUserId(),acc.id);
			cont.MailingCity = 'Bombay';
			cont.MailingCountry = 'India';
			cont.MailingCountryCode = 'IN';
			cont.MailingPostalCode ='400011';
			cont.MailingState ='Maharashtra';
			cont.MailingStateCode = 'MH';
			cont.MailingStreet = 'MG Street';
			cont.County_Local__c = 'abc';
			cont.email ='john@gmail.com';
			cont.Siebel_Contact_Id__c = '1-1JAHOZ';
			insert cont;

			Opportunity opp = TestDataBuilder.buildTestOpportunity(0);
			opp.AccountId = acc.Id;
			insert opp;

			//Create Project Record                      
			List <MW_Project__c> projc =  new List<MW_Project__c>();
			MW_Project__c p1 = TestDataBuilder.buildTestProjectRef(1, Schema.SObjectType.MW_Project__c.getRecordTypeInfosByName().get('Project').getRecordTypeId(), u.Id);
			p1.Customer_Contact__c = cont.Id;
			p1.Opportunity__c = opp.Id;
			//Insert project created 
			projc.add(p1);
			insert projc; 

			//Create Team Member Record 
			Project_Team_Member__c pt1 = TestDataBuilder.buildTestProjectTeamMember(u.Id, p1.id);
			insert pt1;

			//Create Time Card Record
			Project_Time_Card__c ptc1 = TestDataBuilder.buildTestProjectTimeCard(u.id, p1.id);
			ptc1.Status__c = 'Submitted';
			ptc1.Activity_Type__c = 'Customer Interaction';
			ptc1.Product_Group__c = 'MATLAB';
			ptc1.Week_Ending__c = dayOfWeek(Date.today(), 6);
			ptc1.Week_date__c=Date.today();
			ptc1.Hours__c = 0;
			insert ptc1;

			Test.startTest();

			//Test current Page
			PageReference pageRef = Page.ProjectTimecard;
			Test.setCurrentPage(pageRef);

			//Create Time Card Record
			//Project_Time_Card__c ptc = new Project_Time_Card__c();
			ApexPages.StandardController stdTimeCard = new ApexPages.StandardController(ptc1);
			TimecardController tCont = new TimecardController(stdTimeCard);
			tCont.initialise();

			Project_Time_Card__c pp = (Project_Time_Card__c)stdTimeCard.getRecord();
			system.debug(pp.Week_Ending__c);

			Date curDate = Date.today();

			//Test current Date
			system.assertEquals(curDate, pp.Week_date__c);	

			tCont.GotoPrev();
			
			//Test the previous  Date
			system.assertEquals( pp.Week_date__c, curDate.addDays(-1));

			tCont.GotoNext();
			//Test if the  date was reset to the current  date
			system.assertEquals(curDate, pp.Week_date__c);	

			//Test if the weekending date was reset to the current weekending date
			tCont.changeWeekEnding();
			
			system.assertEquals(curDate, pp.Week_date__c);	



			Test.stopTest();		
		}
	}

	static testMethod void TestAddRemRow() {

		//Inserting Bypass trigger custom setting
		custsettbuild.buildBypassTriggerSettings();

		custsettbuild.buildTimeCardControllerList();
		custsettbuild.buildGenSetting();
		//Create User Record
		User u = TestDataBuilder.buildTestUser(1);
		u.Functional_Role__c = roleAppENGG;
		insert u;

		System.runAs(u) {
			Account acc = TestDataBuilder.buildTestAccount(0,UserInfo.getUserId());
			acc.Name = 'Smith';
			acc.BillingCity ='Boston';
			acc.BillingCountry = 'United States';
			acc.BillingCountryCode = 'US';
			acc.BillingPostalCode ='400011';
			acc.BillingStateCode ='AK';
			acc.BillingState ='Alaska';
			acc.BillingStreet = 'MG Street';
			acc.County__c = 'abc';
			acc.Siebel_Account_Id__c = '1-CS15';
			insert acc;


			Contact cont= TestDataBuilder.buildTestContact(0,UserInfo.getUserId(),acc.id);
			cont.MailingCity = 'Bombay';
			cont.MailingCountry = 'India';
			cont.MailingCountryCode = 'IN';
			cont.MailingPostalCode ='400011';
			cont.MailingState ='Maharashtra';
			cont.MailingStateCode = 'MH';
			cont.MailingStreet = 'MG Street';
			cont.County_Local__c = 'abc';
			cont.email ='john@gmail.com';
			cont.Siebel_Contact_Id__c = '1-1JAHOZ';
			insert cont;

			Opportunity opp = TestDataBuilder.buildTestOpportunity(0);
			opp.AccountId = acc.Id;
			insert opp;

			//Create Project Record                      
			List <MW_Project__c> projc =  new List<MW_Project__c>();
			MW_Project__c p1 = TestDataBuilder.buildTestProjectRef(1, Schema.SObjectType.MW_Project__c.getRecordTypeInfosByName().get('Project').getRecordTypeId(), u.Id);
			p1.Project_Status__c='Open';
			p1.Customer_Contact__c = cont.Id;
			p1.Opportunity__c = opp.Id;
			//Insert project created 
			projc.add(p1);
			insert projc; 

			//Create Team Member Record 
			Project_Team_Member__c pt1 = TestDataBuilder.buildTestProjectTeamMember(u.Id, p1.id);
			insert pt1;

			//Create Time Card Record
			Project_Time_Card__c ptc1 = TestDataBuilder.buildTestProjectTimeCard(u.id, p1.id);
			ptc1.Status__c = 'Submitted';
			ptc1.Activity_Type__c = 'Customer Interaction';
			ptc1.Product_Group__c = 'MATLAB';
			ptc1.Week_Ending__c = dayOfWeek(Date.today(), 6);
			ptc1.Week_date__c=Date.today();
			ptc1.Hours__c = 8;
			insert ptc1;
   
			Test.startTest();

			//Test current Page
			PageReference pageRef = Page.ProjectTimecard;
            pageRef.getParameters().put('projectId',p1.Id);	//DMA 10-31-2017 2263533 adding URL parameter for test coverage
			Test.setCurrentPage(pageRef);

			//Create Time Card Record
			ApexPages.StandardController stdTimeCard = new ApexPages.StandardController(ptc1);
			TimecardController tCont = new TimecardController(stdTimeCard);
			tCont.initialise();


			//Test Add Rows
			tCont.addRow();


			system.assertequals(3, tCont.timecardWrapperList.size());

			ApexPages.currentPage().getParameters().put('index', '1');

			//Test Remove Rows
			tCont.removingRow();
			system.assertequals(2, tCont.timecardWrapperList.size());

			//Add row to test remove of submitted row error
			tCont.addRow();

			ApexPages.currentPage().getParameters().put('index', '1');

			//Update record values
			List <TimecardController.TimecardWrapper> NewLst = new  List <TimecardController.TimecardWrapper>();
			for ( TimecardController.TimecardWrapper aa : tCont.timecardWrapperList){
				aa.timecard.Status__c = 'Submitted';
				NewLst.add(aa);
			}
			tCont.timecardWrapperList = NewLst;
			tCont.removingRow(); 

			//Test Clone
			ApexPages.currentPage().getParameters().put('CloneRow', '0');
			tCont.cloneRow();
	
			system.assertequals(3, tCont.timecardWrapperList.size());

			Test.stopTest();     
		}       
	}
        
              
	static testMethod void TestgetDependentActivityPicklist(){
		
		//Inserting Bypass trigger custom setting
		custsettbuild.buildBypassTriggerSettings();
        custsettbuild.buildTimeCardControllerList();
		custsettbuild.buildGenSetting();
		//Create User Record
		User u = TestDataBuilder.buildTestUser(1);
		u.Functional_Role__c = roleAppENGG;
		insert u;

		System.runAs(u) {

			Account acc = TestDataBuilder.buildTestAccount(0,UserInfo.getUserId());
			acc.Name = 'Smith';
			acc.BillingCity ='Boston';
			acc.BillingCountry = 'United States';
			acc.BillingCountryCode = 'US';
			acc.BillingPostalCode ='400011';
			acc.BillingStateCode ='AK';
			acc.BillingState ='Alaska';
			acc.BillingStreet = 'MG Street';
			acc.County__c = 'abc';
			acc.Siebel_Account_Id__c = '1-CS15';
			insert acc;


			Contact cont= TestDataBuilder.buildTestContact(0,UserInfo.getUserId(),acc.id);
			cont.MailingCity = 'Bombay';
			cont.MailingCountry = 'India';
			cont.MailingCountryCode = 'IN';
			cont.MailingPostalCode ='400011';
			cont.MailingState ='Maharashtra';
			cont.MailingStateCode = 'MH';
			cont.MailingStreet = 'MG Street';
			cont.County_Local__c = 'abc';
			cont.email ='john@gmail.com';
			cont.Siebel_Contact_Id__c = '1-1JAHOZ';
			insert cont;

			Opportunity opp = TestDataBuilder.buildTestOpportunity(0);
			opp.AccountId = acc.Id;
			insert opp;

			//Create Project Record                      
			List <MW_Project__c> projc =  new List<MW_Project__c>();
			MW_Project__c p1 = TestDataBuilder.buildTestProjectRef(1, Schema.SObjectType.MW_Project__c.getRecordTypeInfosByName().get('Project').getRecordTypeId(), u.Id);
			p1.Project_Status__c='Open';
			p1.Customer_Contact__c = cont.Id;
			p1.Opportunity__c = opp.Id;
			//Insert project created 
			projc.add(p1);
			insert projc; 

			//Create Team Member Record 
			Project_Team_Member__c pt1 = TestDataBuilder.buildTestProjectTeamMember(u.Id, p1.id);
			insert pt1;

			//Create Time Card Record
			Project_Time_Card__c ptc1 = TestDataBuilder.buildTestProjectTimeCard(u.id, p1.id);
			ptc1.Status__c = 'Submitted';
			ptc1.Activity_Type__c = 'Customer Interaction';
			ptc1.Product_Group__c = 'MATLAB';
			ptc1.Week_Ending__c = dayOfWeek(Date.today(), 6);
			ptc1.Week_date__c=Date.today();
			ptc1.Hours__c = 8;
			insert ptc1;

			Test.startTest();

			//Test current Page
			PageReference pageRef = Page.ProjectTimecard;
			Test.setCurrentPage(pageRef);

			//Create Time Card Record
			ApexPages.StandardController stdTimeCard = new ApexPages.StandardController(ptc1);
			TimecardController tCont = new TimecardController(stdTimeCard);
			tCont.initialise();
			//Test Add Rows
			tCont.addRow();
			system.assertequals(3, tCont.timecardWrapperList.size());
			ApexPages.currentPage().getParameters().put('rowCounter', '0');
			tCont.getDependentActivityPicklist();
			Test.stopTest();
		}
	}

	static testMethod void TestsaveEntriesError() {

		//Inserting Bypass trigger custom setting
		custsettbuild.buildBypassTriggerSettings();

		custsettbuild.buildTimeCardControllerList();
		custsettbuild.buildGenSetting();
		//Create User Record
		User u = TestDataBuilder.buildTestUser(1);
		u.Functional_Role__c = roleAppENGG;
		insert u;

		system.runAs(u) {

			Account acc = TestDataBuilder.buildTestAccount(0,UserInfo.getUserId());
			acc.Name = 'Smith';
			acc.BillingCity ='Boston';
			acc.BillingCountry = 'United States';
			acc.BillingCountryCode = 'US';
			acc.BillingPostalCode ='400011';
			acc.BillingStateCode ='AK';
			acc.BillingState ='Alaska';
			acc.BillingStreet = 'MG Street';
			acc.County__c = 'abc';
			acc.Siebel_Account_Id__c = '1-CS15';
			insert acc;


			Contact cont= TestDataBuilder.buildTestContact(0,UserInfo.getUserId(),acc.id);
			cont.MailingCity = 'Bombay';
			cont.MailingCountry = 'India';
			cont.MailingCountryCode = 'IN';
			cont.MailingPostalCode ='400011';
			cont.MailingState ='Maharashtra';
			cont.MailingStateCode = 'MH';
			cont.MailingStreet = 'MG Street';
			cont.County_Local__c = 'abc';
			cont.email ='john@gmail.com';
			cont.Siebel_Contact_Id__c = '1-1JAHOZ';
			insert cont;

			Opportunity opp = TestDataBuilder.buildTestOpportunity(0);
			opp.AccountId = acc.Id;
			insert opp;

			//Create Project Record                      
			List <MW_Project__c> projc =  new List<MW_Project__c>();
			MW_Project__c p1 = TestDataBuilder.buildTestProjectRef(1, Schema.SObjectType.MW_Project__c.getRecordTypeInfosByName().get('Project').getRecordTypeId(), u.Id);
			p1.Project_Status__c='Open';
			p1.Customer_Contact__c = cont.Id;
			p1.Opportunity__c = opp.Id;
			//Insert project created 
			projc.add(p1);
			insert projc; 

			//Create Team Member Record 
			Project_Team_Member__c pt1 = TestDataBuilder.buildTestProjectTeamMember(u.Id, p1.id);
			insert pt1;

			//Create Time Card Record
			Project_Time_Card__c ptc1 = TestDataBuilder.buildTestProjectTimeCard(u.id, p1.id);
			ptc1.Status__c = 'Submitted';
			ptc1.Activity_Type__c = 'Customer Interaction';
			ptc1.Product_Group__c = 'MATLAB';
			ptc1.Week_Ending__c = dayOfWeek(Date.today(), 6);
			ptc1.Week_date__c=Date.today();
			ptc1.Hours__c = 0;
			insert ptc1;

			Test.startTest();

			//Test current Page
			PageReference pageRef = Page.ProjectTimecard;
			Test.setCurrentPage(pageRef);

			//Create Time Card Record
			ApexPages.StandardController stdTimeCard = new ApexPages.StandardController(ptc1);
			TimecardController tCont = new TimecardController(stdTimeCard);
			tCont.initialise();
			tCont.saveEntries();

			//Test warning of cannot edit a submitted record.
			List<ApexPages.Message> msg = ApexPages.getMessages();
			for (ApexPages.Message msgs : msg)
			{
				system.assertEquals(System.Label.Warning_CannotEdit_Msg, msgs.getDetail());
			}

			Test.stopTest();	
		}
	}

	static testMethod void TestsaveEntries() {

		//Inserting Bypass trigger custom setting
		custsettbuild.buildBypassTriggerSettings();

		custsettbuild.buildTimeCardControllerList();

		custsettbuild.buildGenSetting();
		//Create User Record
		User u = TestDataBuilder.buildTestUser(1);
		u.Functional_Role__c = roleAppENGG;
		insert u;

		system.runAs(u) {
			Account acc = TestDataBuilder.buildTestAccount(0,UserInfo.getUserId());
			acc.Name = 'Smith';
			acc.BillingCity ='Boston';
			acc.BillingCountry = 'United States';
			acc.BillingCountryCode = 'US';
			acc.BillingPostalCode ='400011';
			acc.BillingStateCode ='AK';
			acc.BillingState ='Alaska';
			acc.BillingStreet = 'MG Street';
			acc.County__c = 'abc';
			acc.Siebel_Account_Id__c = '1-CS15';
			insert acc;


			Contact cont= TestDataBuilder.buildTestContact(0,UserInfo.getUserId(),acc.id);
			cont.MailingCity = 'Bombay';
			cont.MailingCountry = 'India';
			cont.MailingCountryCode = 'IN';
			cont.MailingPostalCode ='400011';
			cont.MailingState ='Maharashtra';
			cont.MailingStateCode = 'MH';
			cont.MailingStreet = 'MG Street';
			cont.County_Local__c = 'abc';
			cont.email ='john@gmail.com';
			cont.Siebel_Contact_Id__c = '1-1JAHOZ';
			insert cont;

			Opportunity opp = TestDataBuilder.buildTestOpportunity(0);
			opp.AccountId = acc.Id;
			insert opp;

			//Create Project Record                      
			List <MW_Project__c> projc =  new List<MW_Project__c>();
			MW_Project__c p1 = TestDataBuilder.buildTestProjectRef(1, Schema.SObjectType.MW_Project__c.getRecordTypeInfosByName().get('Project').getRecordTypeId(), u.Id);
			p1.Project_Status__c='Open';
			p1.Customer_Contact__c = cont.Id;
			p1.Opportunity__c = opp.Id;
			//Insert project created 
			projc.add(p1);
			insert projc; 

			//Create Team Member Record 
			Project_Team_Member__c pt1 = TestDataBuilder.buildTestProjectTeamMember(u.Id, p1.id);
			insert pt1;

			//Create Time Card Record
			Project_Time_Card__c ptc1 = TestDataBuilder.buildTestProjectTimeCard(u.id, p1.id);
			ptc1.Status__c = 'New';
			ptc1.Activity_Type__c = 'Customer Interaction';
			ptc1.Product_Group__c = 'MATLAB';
			ptc1.Week_Ending__c = dayOfWeek(Date.today(), 6);
			ptc1.Week_date__c=Date.today();
			ptc1.Hours__c = 8;
			insert ptc1;


			Test.startTest();

			//Test current Page
			PageReference pageRef = Page.ProjectTimecard;
			Test.setCurrentPage(pageRef);

			//Create Time Card Recor
			ApexPages.StandardController stdTimeCard = new ApexPages.StandardController(ptc1);
			TimecardController tCont = new TimecardController(stdTimeCard);
			tCont.initialise();

			//Test os submitting a complete detail record        
			List<ApexPages.Message> msg = ApexPages.getMessages();
			for (ApexPages.Message msgs : msg)
			{
				system.assertEquals(System.Label.Confirm_Save_Msg, msgs.getDetail());
			}

			//Test editing of none Submitted record. 
			List <TimecardController.TimecardWrapper> NewLst = new  List <TimecardController.TimecardWrapper>();
			for ( TimecardController.TimecardWrapper aa : tCont.timecardWrapperList){
				aa.isModified = True;
				aa.timecard.Hours__c = 9;
				NewLst.add(aa);
			}
			tCont.timecardWrapperList = NewLst;

			tCont.saveEntries(); 

			//Test editing of Submitted record. 
			List <TimecardController.TimecardWrapper> NewLst2 = new  List <TimecardController.TimecardWrapper>();
			for ( TimecardController.TimecardWrapper vv : tCont.timecardWrapperList){
				vv.isModified = True;
				vv.timecard.Hours__c = 0;
				NewLst2.add(vv);
			}
			tCont.timecardWrapperList = NewLst2;

			tCont.saveEntries();
			Test.stopTest();	    
		}
	}
}