objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Sector__c</fullName>
        <label>Account Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Junk</fullName>
                </value>
                <value>
                    <fullName>Unvalidated</fullName>
                </value>
                <value>
                    <fullName>Out of Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Enrollment_Code__c.object
<CustomObject>
    <description>This object represents the code associated with an Enterprise Training Agreement and holds the status the enrollment code is in.</description>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <description>Enterprise Training Agreement the Enrollment Code is associated with.</description>
        <inlineHelpText>Enterprise Training Agreement the Enrollment Code is associated with.</inlineHelpText>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Enrollment Codes</relationshipLabel>
        <relationshipName>Enrollment_Codes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Enrollment Code</label>
    <nameField>
        <displayFormat>EC-{0000}</displayFormat>
        <label>Enrollment Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Enterprise_Training_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Enterprise Training Agreements</relationshipLabel>
        <relationshipName>Enterprise_Training_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <label>Max Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Enterprise Training Agreements</relationshipLabel>
        <relationshipName>Enterprise_Training_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enterprise Training Agreement</label>
    <nameField>
        <label>Enterprise Training Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enterprise Training Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EnrollmentCodeTriggerHandlerTest.cls
/*
 * @author          Neha Mahajan
 * @date            05/04/2016
 * @description     Test Class for EnrollmentCodetriggerHandler
 */


@isTest
public class EnrollmentCodeTriggerHandlerTest {
    
    private static testMethod void testEnrollmentCode(){
        
        //re-create custom setting test records when running the test class
         CustomSettingsBuilder custsettbuild = new CustomSettingsBuilder();
        //Inserting Bypass trigger custom setting
         custsettbuild.buildBypassTriggerSettings();
         CTrainingTestDataBuilder testbuild =new CTrainingTestDataBuilder();
         testbuild.buildEnrollmentCodeConfigurationCustomsetting();
        Account AccObj=new Account();
        AccObj.Name='TestAccount';
        AccObj.Account_Status__c='Active';
        AccObj.Account_Sector__c='Commercial';
        insert AccObj;
            
        Contact ConObj=new Contact();
        ConObj.LastName='TestAccountL';
        ConObj.FirstName='TestAccountF';
        ConObj.AccountId=AccObj.id;
        insert ConObj; 
            
        Enterprise_Training_Agreement__c EAObj= new Enterprise_Training_Agreement__c();
        EAObj=CTrainingTestDataBuilder.buildTestETAgreement(1);
        //EAObj.RecordType.Name='Seat-Based';
        EAObj.Max_Seats__c=20;
        EAObj.CurrencyIsoCode='INR';
        EAObj.Account_Name__c=AccObj.Id;
        EAObj.Primary_Contact__c=ConObj.id;
        insert EAObj;
        
        Enrollment_Code__c ECodeObj= new Enrollment_Code__c();
        ECodeObj.Enterprise_Training_Agreement__c=EAObj.id;
        insert ECodeObj;
        
        Enrollment_Code__c EcodeObject=[select id,Code__c from Enrollment_Code__c where id=:ECodeObj.id];
        System.assert(EcodeObject.Code__c!=null);
        
        
    }
}