objects/Account.object
<CustomObject>
    <fields>
        <fullName>Siebel_Territory_ID__c</fullName>
        <description>Territory ID from external rules engine (Siebel).  Used to lookup the internal Salesforce Territory to assign to the Account.</description>
        <label>Siebel Territory ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Industry__c</fullName>
        <label>Territory Industry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Sales_Group__c</fullName>
        <label>Territory Sales Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Sales_Team_Type__c</fullName>
        <label>Territory Sales Team Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/General_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>General custom setting of the org</description>
    <fields>
        <fullName>Default_Opportunity_Owner__c</fullName>
        <description>Default  opportunity owner will be  used in custom lead conversion page for setting default owner for converted opportunity.</description>
        <inlineHelpText>Should be the User&apos;s Alias (to account for differences in querying by name in different locales)</inlineHelpText>
        <label>Default Opportunity Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>General Settings</label>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Revenue_Class__c</fullName>
        <description>Used to assign a revenue class to an opportunity product (line item).  This field is used in roll up summary fields on the opportunity to understand revenue class attribution.</description>
        <label>Revenue Class</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Perpetual</fullName>
                    <default>true</default>
                    <label>Perpetual</label>
                </value>
                <value>
                    <fullName>Term New</fullName>
                </value>
                <value>
                    <fullName>Term Renewal</fullName>
                </value>
                <value>
                    <fullName>SMS</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Unique_Identifier__c</fullName>
        <description>This field will be a combination of Product Base Code, Version and Release</description>
        <externalId>true</externalId>
        <label>Product Unique Identifier</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Quotable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag used to identify if a product is quotable or not.  If this is set to true, the product is passed to quoting or trial systems, if false it will not be.</description>
        <label>Quotable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Revenue_Class__c</fullName>
        <description>Used to assign a revenue class to a product. This is used to set the revenue class for &apos;dummy&apos; products that are used on opportunities.</description>
        <label>Revenue Class</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Perpetual</fullName>
                </value>
                <value>
                    <fullName>Term New</fullName>
                </value>
                <value>
                    <fullName>Term Renewal</fullName>
                </value>
                <value>
                    <fullName>SMS</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Territory2.object
<CustomObject>
    <fields>
        <fullName>Siebel_Territory_ID__c</fullName>
        <description>Territory ID from Siebel that will be used as a lookup value from the Account to assign the appropriate Salesforce Territory.</description>
        <label>Siebel Territory ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Industry__c</fullName>
        <label>Territory Industry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AERO</fullName>
                </value>
                <value>
                    <fullName>AUTO</fullName>
                </value>
                <value>
                    <fullName>CES</fullName>
                </value>
                <value>
                    <fullName>CROSS</fullName>
                </value>
                <value>
                    <fullName>EDU</fullName>
                </value>
                <value>
                    <fullName>EP</fullName>
                </value>
                <value>
                    <fullName>FIN</fullName>
                </value>
                <value>
                    <fullName>GOV</fullName>
                </value>
                <value>
                    <fullName>IAM</fullName>
                </value>
                <value>
                    <fullName>MED</fullName>
                </value>
                <value>
                    <fullName>UNKNOWN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory_Sales_Group__c</fullName>
        <label>Territory Sales Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AMER - House</fullName>
                </value>
                <value>
                    <fullName>APAC - House</fullName>
                </value>
                <value>
                    <fullName>EMEA - House</fullName>
                </value>
                <value>
                    <fullName>EMEA Other</fullName>
                </value>
                <value>
                    <fullName>ETMC Exponenta Ltd</fullName>
                </value>
                <value>
                    <fullName>FIGES</fullName>
                </value>
                <value>
                    <fullName>Gamax</fullName>
                </value>
                <value>
                    <fullName>Hoare Research</fullName>
                </value>
                <value>
                    <fullName>Humusoft</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>MathWorks Australia</fullName>
                </value>
                <value>
                    <fullName>MathWorks China</fullName>
                </value>
                <value>
                    <fullName>MathWorks France</fullName>
                </value>
                <value>
                    <fullName>MathWorks Germany</fullName>
                </value>
                <value>
                    <fullName>MathWorks India</fullName>
                </value>
                <value>
                    <fullName>MathWorks Ireland</fullName>
                </value>
                <value>
                    <fullName>MathWorks Italy</fullName>
                </value>
                <value>
                    <fullName>MathWorks Japan</fullName>
                </value>
                <value>
                    <fullName>MathWorks Korea</fullName>
                </value>
                <value>
                    <fullName>MathWorks Natick</fullName>
                </value>
                <value>
                    <fullName>MathWorks Netherlands</fullName>
                </value>
                <value>
                    <fullName>MathWorks Nordic</fullName>
                </value>
                <value>
                    <fullName>MathWorks Spain</fullName>
                </value>
                <value>
                    <fullName>MathWorks Switzerland</fullName>
                </value>
                <value>
                    <fullName>MathWorks UK</fullName>
                </value>
                <value>
                    <fullName>Mentor Hellas</fullName>
                </value>
                <value>
                    <fullName>NA Comm-Aero</fullName>
                </value>
                <value>
                    <fullName>NA Comm-Aero-Geo So Cal</fullName>
                </value>
                <value>
                    <fullName>NA Comm-Auto</fullName>
                </value>
                <value>
                    <fullName>NA Comm-Auto-Geo MI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory_Sales_Team_Type__c</fullName>
        <label>Territory Sales Team Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Blended</fullName>
                </value>
                <value>
                    <fullName>CMA</fullName>
                </value>
                <value>
                    <fullName>EDU</fullName>
                </value>
                <value>
                    <fullName>Geo</fullName>
                </value>
                <value>
                    <fullName>House</fullName>
                </value>
                <value>
                    <fullName>Major</fullName>
                </value>
                <value>
                    <fullName>Mixed</fullName>
                </value>
                <value>
                    <fullName>Named</fullName>
                </value>
                <value>
                    <fullName>NMA</fullName>
                </value>
                <value>
                    <fullName>UNKNOWN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Functional_Role__c</fullName>
        <inlineHelpText>Denotes what role a user plays on a Sales Territory Team.  Used for Oppty assignment and to support collaboration among team members.</inlineHelpText>
        <label>Functional Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inside Sales Rep</fullName>
                </value>
                <value>
                    <fullName>Inside Sales Rep non primary</fullName>
                </value>
                <value>
                    <fullName>National Account Sales Specialist</fullName>
                </value>
                <value>
                    <fullName>Product Overlay Sales Rep</fullName>
                </value>
                <value>
                    <fullName>Sales Development Rep</fullName>
                </value>
                <value>
                    <fullName>Sales Maintenance Rep</fullName>
                </value>
                <value>
                    <fullName>Sales Maintenance Rep non primary</fullName>
                </value>
                <value>
                    <fullName>Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Sales Rep</fullName>
                </value>
                <value>
                    <fullName>Sales Rep Primary</fullName>
                </value>
                <value>
                    <fullName>Sales Specialist</fullName>
                </value>
                <value>
                    <fullName>Sales Support Manager</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Application Engineer</fullName>
                </value>
                <value>
                    <fullName>Pilot Engineer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/OpportunityAssignmentManagerTest.cls
/*
 *    @description:Class to test the TerritoryAssignmentManager
 */ 
@isTest(seeAlldata=true)
public with sharing class OpportunityAssignmentManagerTest {

    //Re-create custom setting test records when running the test class
    static CustomSettingsBuilder csb = new CustomSettingsBuilder();

    static String SalesMaintenanceRep=System.Label.FunRole_SalesMaintenanceRep;
    static String InsideSalesRep=System.Label.FunRol_InsideSalesRep;
    static String NationalAccountSalesSpecialist=System.Label.FunRole_NationalAccountSalesSpecialist;
    static String SalesRepPrimary=System.Label.FunRole_SalesRepPrimary;
    static String SalesSpecialist=System.Label.FunRole_SalesSpecialist;
    static String Renewal=System.Label.FunRole_Renewal;
    static String Distributor=System.Label.FunRole_Distributort;
    static String SalesManager=System.Label.FunRole_SalesManager;


    static  List<String> functionalRoleList=new  List<String>{SalesSpecialist,SalesManager,Distributor,SalesRepPrimary,NationalAccountSalesSpecialist,InsideSalesRep,SalesMaintenanceRep};


    static map<String,ID> roleUserMap = new map<string,id>();
    
     /*
      @ name    assignOpportunitiesByTerritoryTeamRolesSMSTest 
      @ date    25.July.2014
      @ author  Archana Lohar
      @ param   none.
      @ return  Void. 
      @ description Method to Implement test for assigning Opportunities by TerritoryTeamRole                         
     */

    static testMethod void assignOpportunitiesByTerritoryTeamRolesSMSTest() {

        List<User> userWithRoleLst=new List<User>();
        Set<ID> userSet=new Set<ID>();
        List<userterritory2Association> userAssoObjListToInsert=new List<userterritory2Association>();
        List<Opportunity> optyLst =new List<Opportunity>();
        //Create dummy User
        User usr = TestDataBuilder.buildTestUser(100); 
        PricebookEntry objPriceBookEntry;
        usr.Functional_Role__c = 'Sales Manager'; //SS 3/17/2016 Added to exclude the opp auto assignment process on creation
        insert usr;
        
        //Set ExecuteDML to false
        OpportunityAssignmentManager.setExecuteDML(true);
        OpportunityAssignmentManager.setMassReorg(true);

        //Fetching date from General custom setting
        csb.buildGenSetting();
        csb.buildBypassTriggerSettings();
        General_Settings__c settings = General_Settings__c.getInstance();
        
        System.runAs(usr){   

            //Intialize all variable
            List<Account> accLLst =new List<Account>();
            List<Account> accLLstToUpdate =new List<Account>();
            List<Territory2> territory2Lst =new List<Territory2>();
            List<OpportunityLineItem> lineItemLst =new List<OpportunityLineItem>();
            List<Territory2Model> territory2ModelLst =new List<Territory2Model>();
            Territory2Model model;

            //*************************************Insert Account objects *****************************************//

            for(Integer i=0;i<10;i++){

                Account accL = TestDataBuilder.buildTestAccount(i,UserInfo.getUserId());
                accL.Name = 'Smith' + i;
                accL.Siebel_Territory_ID__c='TestSTI'+i;
                accLLst.add(accL);  

            }


            insert accLLst;


            //*************************************Insert Territory2 Object*****************************************//

            Territory2Type typeTest=[select id from Territory2Type limit 1];

            territory2ModelLst=[select id,state from Territory2Model where state='Active' limit 1];

            if(territory2ModelLst==null || territory2ModelLst.isEmpty()){

                model=TestDataBuilder.buildTestTerritory2Model(0);
                insert model;

            }

            //create Territory record from TestDataBuilder.
            for(Integer i=0;i<10;i++){

                Territory2 dummyTerritory2=TestDataBuilder.buildTestTerritory2(i);
                dummyTerritory2.Siebel_Territory_ID__c='1-UIOPYU'+i;
                dummyTerritory2.Territory_Industry__c='UNKNOWN';
                dummyTerritory2.Territory_Sales_Team_Type__c='Mixed';
                dummyTerritory2.Territory_Sales_Group__c='Latin America';
                //dummyTerritory2.caseAccessLevel='Edit';


                if(territory2ModelLst==null || !territory2ModelLst.isEmpty()){

                    dummyTerritory2.Territory2ModelId=territory2ModelLst[0].id;
                }
                else
                {
                    dummyTerritory2.Territory2ModelId=model.id;
                }
                dummyTerritory2.Territory2TypeId=typeTest.id;

                territory2Lst.add(dummyTerritory2);
            }

            insert territory2Lst;

            //*************************************Insert User (Territory team dummy user) Object*****************************************//

            //Insert User Record with functional roles
            for(Integer i=0;i<functionalRoleList.size();i++){

                //User With Sales Maintenance Rep functional role
                User usrObj = TestDataBuilder.buildTestUser(i); 
                usrObj.Functional_Role__c=functionalRoleList[i];
                userWithRoleLst.add(usrObj);

            }
            //Insert users
            insert userWithRoleLst;
            
            

            //Insert  Record in roleUserMap with functional roles
            for(Integer i=0;i<userWithRoleLst.size();i++){

                roleUserMap.put(userWithRoleLst[i].Functional_Role__c,userWithRoleLst[i].id);
                userSet.add(userWithRoleLst[i].id);

            }


            //*************************************Insert Userterritory2Association Object*****************************************//

            Integer count=7;
            //add users to territory2
            for(Integer i=0;i<7;i++){


                //Add all users to territory2
                for(Integer j=0;j<count;j++){

                    userterritory2Association userAssObj=TestDataBuilder.buildTestUserterritory2Association(userWithRoleLst[j].id,territory2Lst[i].id);
                    userAssoObjListToInsert.add(userAssObj);

                }

                count--;

            }

            insert userAssoObjListToInsert;


            //Get user to set default opportunity custom setting
            //We will query using alias as name had issues with different locales
            List<User> usrObjByName=new List<User>();
            usrObjByName=[select id,name,functional_role__C from User where alias=:settings.Default_Opportunity_Owner__c ];
            
            //User usrObj=TestDataBuilder.buildTestUser(100);
            //insert usrObj;
            
            
            system.debug(usrObjByName+'usrObjByName');

            for(Integer i=0;i<10;i++){

                Opportunity opty = TestDataBuilder.buildTestOpportunity(i);
               
                opty.accountid=accLLst[i].id;
                opty.ownerid=usrObjByName[0].id;
                opty.amount=1000;
                opty.batch_evaluate__c=true;
                optyLst.add(opty);

            }


            insert optyLst;
            
             // Create a new product
            Product2 productObj = new Product2();
            productObj.Name='Additional Client Licenses';
            productObj.IsActive=true;
            productObj.ProductCode='AS';
            productObj.Quotable__c=true;
            productObj.Product_Unique_Identifier__c='Unclassified_Consulting1';
            insert productObj ;


            // Create a pricebook entry for custom pricebook
            PricebookEntry pbe = new PricebookEntry();
            pbe.UseStandardPrice = false;
            pbe.Pricebook2Id=Test.getStandardPricebookId();
            pbe.Product2Id=productObj.id;
            pbe.IsActive=true;
            pbe.UnitPrice=100.0;
            //pbe.UseStandardPrice =true;
            insert pbe;

          for(Integer i=0;i<10;i++){
              
            OpportunityLineItem NewRec = new OpportunityLineItem();
            NewRec.UnitPrice=200;
            NewRec.Quantity=3;
            NewRec.OpportunityId=optyLst[i].Id;
            NewRec.PricebookEntryId=pbe.id;
            NewRec.Revenue_Class__c='SMS';
            //NewRec.Product2id =product.id;
            lineItemLst.add(NewRec);
              
            }
            
            insert lineItemLst;
           
            //************************************* Uptdate Account objects *****************************************//

            for(Integer i=0;i<7;i++){

                Account accL =accLLst[i];
                accL.Siebel_Territory_ID__c=territory2Lst[i].Siebel_Territory_ID__c;
                accLLstToUpdate.add(accL);  

            }

            test.startTest();

            Update accLLstToUpdate;      

            //Check to see if correct territory2 team member is assigned
            List<Opportunity> optyObjLst=[select id,owner.Functional_Role__c from Opportunity 
                                          where id in :optyLst];

            for(Integer i=0;i<optyObjLst.size();i++){

                system.assert(userSet.contains(optyObjLst[i].ownerid)); 

            }


            test.stopTest();

        }
    }

   /*
      @ name    assignOpportunitiesByTerritoryTeamRolesNoNSMSTest 
      @ date    25.July.2014
      @ author  Archana Lohar
      @ param   none.
      @ return  Void. 
      */

    static testMethod void assignOpportunitiesByTerritoryTeamRolesNoNSMSTest() {

        List<User> userWithRoleLst=new List<User>();
        Set<ID> userSet=new Set<ID>();
        List<userterritory2Association> userAssoObjListToInsert=new List<userterritory2Association>();
        List<Opportunity> optyLst =new List<Opportunity>();
        //Create dummy User
        User usr = TestDataBuilder.buildTestUser(100); 
        PricebookEntry objPriceBookEntry;
        usr.Functional_Role__c = 'Sales Manager'; //SS 3/17/2016 Added to exclude the opp auto assignment process on creation
        insert usr;
        
        //Set ExecuteDML to false
        OpportunityAssignmentManager.setExecuteDML(true);
        OpportunityAssignmentManager.setMassReorg(true);

        //Fetching date from General custom setting
        csb.buildGenSetting();
        csb.buildBypassTriggerSettings();
        General_Settings__c settings = General_Settings__c.getInstance();
        
        System.runAs(usr){   

            //Intialize all variable
            List<Account> accLLst =new List<Account>();
            List<Account> accLLstToUpdate =new List<Account>();
            List<Territory2> territory2Lst =new List<Territory2>();
            List<OpportunityLineItem> lineItemLst =new List<OpportunityLineItem>();
            List<Territory2Model> territory2ModelLst =new List<Territory2Model>();
            Territory2Model model;

            //*************************************Insert Account objects *****************************************//

            for(Integer i=0;i<10;i++){

                Account accL = TestDataBuilder.buildTestAccount(i,UserInfo.getUserId());
                accL.Name = 'Smith' + i;
                accL.Siebel_Territory_ID__c='TestSTI'+i;
                accLLst.add(accL);  

            }


            insert accLLst;


            //*************************************Insert Territory2 Object*****************************************//

            Territory2Type typeTest=[select id from Territory2Type limit 1];

            territory2ModelLst=[select id,state from Territory2Model where state='Active' limit 1];

            if(territory2ModelLst==null || territory2ModelLst.isEmpty()){

                model=TestDataBuilder.buildTestTerritory2Model(0);
                insert model;

            }

            //create Territory record from TestDataBuilder.
            for(Integer i=0;i<10;i++){

                Territory2 dummyTerritory2=TestDataBuilder.buildTestTerritory2(i);
                dummyTerritory2.Siebel_Territory_ID__c='1-UIOPYU'+i;
                dummyTerritory2.Territory_Industry__c='UNKNOWN';
                dummyTerritory2.Territory_Sales_Team_Type__c='Mixed';
                dummyTerritory2.Territory_Sales_Group__c='Latin America';
                //dummyTerritory2.caseAccessLevel='Edit';


                if(territory2ModelLst==null || !territory2ModelLst.isEmpty()){

                    dummyTerritory2.Territory2ModelId=territory2ModelLst[0].id;
                }
                else
                {
                    dummyTerritory2.Territory2ModelId=model.id;
                }
                dummyTerritory2.Territory2TypeId=typeTest.id;

                territory2Lst.add(dummyTerritory2);
            }

            insert territory2Lst;

            //*************************************Insert User (Territory team dummy user) Object*****************************************//

            //Insert User Record with functional roles
            for(Integer i=0;i<functionalRoleList.size();i++){

                //User With Sales Maintenance Rep functional role
                User usrObj = TestDataBuilder.buildTestUser(i); 
                usrObj.Functional_Role__c=functionalRoleList[i];
                userWithRoleLst.add(usrObj);

            }
            //Insert users
            insert userWithRoleLst;
            
            

            //Insert  Record in roleUserMap with functional roles
            for(Integer i=0;i<userWithRoleLst.size();i++){

                roleUserMap.put(userWithRoleLst[i].Functional_Role__c,userWithRoleLst[i].id);
                userSet.add(userWithRoleLst[i].id);

            }


            //*************************************Insert Userterritory2Association Object*****************************************//

            Integer count=7;
            //add users to territory2
            for(Integer i=0;i<7;i++){


                //Add all users to territory2
                for(Integer j=0;j<count;j++){

                    userterritory2Association userAssObj=TestDataBuilder.buildTestUserterritory2Association(userWithRoleLst[j].id,territory2Lst[i].id);
                    userAssoObjListToInsert.add(userAssObj);

                }

                count--;

            }

            insert userAssoObjListToInsert;


            //Get user to set default opportunity custom setting
            //We will query using alias as name had issues with different locales
            List<User> usrObjByName=new List<User>();
            usrObjByName=[select id,name,functional_role__C from User where alias=:settings.Default_Opportunity_Owner__c ];
           // usrObjByName[0].functional_role__C='';
            //update usrObjByName;
            
            
            //User usrObj=TestDataBuilder.buildTestUser(100);
            //insert usrObj;
            
            
            system.debug(usrObjByName+'usrObjByName');

            for(Integer i=0;i<10;i++){

                Opportunity opty = TestDataBuilder.buildTestOpportunity(i);
               
                opty.accountid=accLLst[i].id;
                opty.ownerid=usrObjByName[0].id;
                opty.amount=1000;
                opty.batch_evaluate__c=true;
                optyLst.add(opty);

            }


            insert optyLst;
            
            
            //************************************* Uptdate Account objects *****************************************//

            for(Integer i=0;i<7;i++){

                Account accL =accLLst[i];
                accL.Siebel_Territory_ID__c=territory2Lst[i].Siebel_Territory_ID__c;
                accLLstToUpdate.add(accL);  

            }

            test.startTest();

            Update accLLstToUpdate;      

            //Check to see if correct territory2 team member is assigned
            List<Opportunity> optyObjLst=[select id,owner.Functional_Role__c from Opportunity 
                                          where id in :optyLst];

            for(Integer i=0;i<optyObjLst.size();i++){

                system.assert(userSet.contains(optyObjLst[i].ownerid)); 

            }


            test.stopTest();

        }
    }
    
    /*
      @ name    assignOpportunitiesByTerritoryTeamRolesNoNSMSBatchEvaluateTrueTest 
      @ date    25.July.2014
      @ author  Archana Lohar
      @ param   none.
      @ return  Void. 
                      
     */

    static testMethod void assignOpportunitiesByTerritoryTeamRolesNoNSMSBatchEvaluateTrueTest() {

        List<User> userWithRoleLst=new List<User>();
        Set<ID> userSet=new Set<ID>();
        List<userterritory2Association> userAssoObjListToInsert=new List<userterritory2Association>();
        List<Opportunity> optyLst =new List<Opportunity>();
        //Create dummy User
        User usr = TestDataBuilder.buildTestUser(100); 
        PricebookEntry objPriceBookEntry;
        usr.Functional_Role__c = 'Sales Manager'; //SS 3/17/2016 Added to exclude the opp auto assignment process on creation
        insert usr;
        
        //Set ExecuteDML to false
        OpportunityAssignmentManager.setExecuteDML(true);
       // OpportunityAssignmentManager.setMassReorg(true);

        //Fetching date from General custom setting
        csb.buildGenSetting();
        csb.buildBypassTriggerSettings();
        General_Settings__c settings = General_Settings__c.getInstance();
        
        System.runAs(usr){   

            //Intialize all variable
            List<Account> accLLst =new List<Account>();
            List<Account> accLLstToUpdate =new List<Account>();
            List<Territory2> territory2Lst =new List<Territory2>();
            List<OpportunityLineItem> lineItemLst =new List<OpportunityLineItem>();
            List<Territory2Model> territory2ModelLst =new List<Territory2Model>();
            Territory2Model model;

            //*************************************Insert Account objects *****************************************//

            for(Integer i=0;i<10;i++){

                Account accL = TestDataBuilder.buildTestAccount(i,UserInfo.getUserId());
                accL.Name = 'Smith' + i;
                accL.Siebel_Territory_ID__c='TestSTI'+i;
                accLLst.add(accL);  

            }


            insert accLLst;


            //*************************************Insert Territory2 Object*****************************************//

            Territory2Type typeTest=[select id from Territory2Type limit 1];

            territory2ModelLst=[select id,state from Territory2Model where state='Active' limit 1];

            if(territory2ModelLst==null || territory2ModelLst.isEmpty()){

                model=TestDataBuilder.buildTestTerritory2Model(0);
                insert model;

            }

            //create Territory record from TestDataBuilder.
            for(Integer i=0;i<10;i++){

                Territory2 dummyTerritory2=TestDataBuilder.buildTestTerritory2(i);
                dummyTerritory2.Siebel_Territory_ID__c='1-UIOPYU'+i;
                dummyTerritory2.Territory_Industry__c='UNKNOWN';
                dummyTerritory2.Territory_Sales_Team_Type__c='Mixed';
                dummyTerritory2.Territory_Sales_Group__c='Latin America';
                //dummyTerritory2.caseAccessLevel='Edit';


                if(territory2ModelLst==null || !territory2ModelLst.isEmpty()){

                    dummyTerritory2.Territory2ModelId=territory2ModelLst[0].id;
                }
                else
                {
                    dummyTerritory2.Territory2ModelId=model.id;
                }
                dummyTerritory2.Territory2TypeId=typeTest.id;

                territory2Lst.add(dummyTerritory2);
            }

            insert territory2Lst;

            //*************************************Insert User (Territory team dummy user) Object*****************************************//

            //Insert User Record with functional roles
            for(Integer i=0;i<functionalRoleList.size();i++){

                //User With Sales Maintenance Rep functional role
                User usrObj = TestDataBuilder.buildTestUser(i); 
                usrObj.Functional_Role__c=functionalRoleList[i];
                userWithRoleLst.add(usrObj);

            }
            //Insert users
            insert userWithRoleLst;
            
            

            //Insert  Record in roleUserMap with functional roles
            for(Integer i=0;i<userWithRoleLst.size();i++){

                roleUserMap.put(userWithRoleLst[i].Functional_Role__c,userWithRoleLst[i].id);
                userSet.add(userWithRoleLst[i].id);

            }


            //*************************************Insert Userterritory2Association Object*****************************************//

            Integer count=7;
            //add users to territory2
            for(Integer i=0;i<7;i++){


                //Add all users to territory2
                for(Integer j=0;j<count;j++){

                    userterritory2Association userAssObj=TestDataBuilder.buildTestUserterritory2Association(userWithRoleLst[j].id,territory2Lst[i].id);
                    userAssoObjListToInsert.add(userAssObj);

                }

                count--;

            }

            insert userAssoObjListToInsert;


            //Get user to set default opportunity custom setting
            //We will query using alias as name had issues with different locales
            List<User> usrObjByName=new List<User>();
            usrObjByName=[select id,name,functional_role__C from User where alias=:settings.Default_Opportunity_Owner__c ];
           // usrObjByName[0].functional_role__C='';
            //update usrObjByName;
            
            
            //User usrObj=TestDataBuilder.buildTestUser(100);
            //insert usrObj;
            
            
            system.debug(usrObjByName+'usrObjByName');

            for(Integer i=0;i<10;i++){

                Opportunity opty = TestDataBuilder.buildTestOpportunity(i);
               
                opty.accountid=accLLst[i].id;
                opty.ownerid=usrObjByName[0].id;
                opty.amount=1000;
                //opty.batch_evaluate__c=true;
                optyLst.add(opty);

            }


            insert optyLst;
            
            
            //************************************* Uptdate Account objects *****************************************//

            for(Integer i=0;i<7;i++){

                Account accL =accLLst[i];
                accL.Siebel_Territory_ID__c=territory2Lst[i].Siebel_Territory_ID__c;
                accLLstToUpdate.add(accL);  

            }

            test.startTest();

            Update accLLstToUpdate;      

            //Check to see if correct territory2 team member is assigned
            List<Opportunity> optyObjLst=[select id,owner.Functional_Role__c from Opportunity 
                                          where id in :optyLst];

            for(Integer i=0;i<optyObjLst.size();i++){

                system.assert(userSet.contains(optyObjLst[i].ownerid)); 

            }


            test.stopTest();

        }
    }
    
     /*
      @ name    assignOpportunitiesByTerritoryTeamRolesNoNSMSTestBatchEvalueteTrue 
      @ date    25.July.2014
      @ author  Archana Lohar
      @ param   none.
      @ return  Void. 
       */

    static testMethod void assignOpportunitiesByTerritoryTeamRolesNoNSMSTestBatchEvalueteTrue() {

        List<User> userWithRoleLst=new List<User>();
        Set<ID> userSet=new Set<ID>();
        List<userterritory2Association> userAssoObjListToInsert=new List<userterritory2Association>();
        List<Opportunity> optyLst =new List<Opportunity>();
        //Create dummy User
        User usr = TestDataBuilder.buildTestUser(100); 
        PricebookEntry objPriceBookEntry;
        usr.Functional_Role__c = 'Sales Manager'; //SS 3/17/2016 Added to exclude the opp auto assignment process on creation
        insert usr;
        
        //Set ExecuteDML to false
        OpportunityAssignmentManager.setExecuteDML(true);
        OpportunityAssignmentManager.setMassReorg(true);

        //Fetching date from General custom setting
        csb.buildGenSetting();
        csb.buildBypassTriggerSettings();
        General_Settings__c settings = General_Settings__c.getInstance();
        
        System.runAs(usr){   

            //Intialize all variable
            List<Account> accLLst =new List<Account>();
            List<Account> accLLstToUpdate =new List<Account>();
            List<Territory2> territory2Lst =new List<Territory2>();
            List<OpportunityLineItem> lineItemLst =new List<OpportunityLineItem>();
            List<Territory2Model> territory2ModelLst =new List<Territory2Model>();
            Territory2Model model;

            //*************************************Insert Account objects *****************************************//

            for(Integer i=0;i<10;i++){

                Account accL = TestDataBuilder.buildTestAccount(i,UserInfo.getUserId());
                accL.Name = 'Smith' + i;
                accL.Siebel_Territory_ID__c='TestSTI'+i;
                accLLst.add(accL);  

            }


            insert accLLst;


            //*************************************Insert Territory2 Object*****************************************//

            Territory2Type typeTest=[select id from Territory2Type limit 1];

            territory2ModelLst=[select id,state from Territory2Model where state='Active' limit 1];

            if(territory2ModelLst==null || territory2ModelLst.isEmpty()){

                model=TestDataBuilder.buildTestTerritory2Model(0);
                insert model;

            }

            //create Territory record from TestDataBuilder.
            for(Integer i=0;i<10;i++){

                Territory2 dummyTerritory2=TestDataBuilder.buildTestTerritory2(i);
                dummyTerritory2.Siebel_Territory_ID__c='1-UIOPYU'+i;
                dummyTerritory2.Territory_Industry__c='UNKNOWN';
                dummyTerritory2.Territory_Sales_Team_Type__c='Mixed';
                dummyTerritory2.Territory_Sales_Group__c='Latin America';
                //dummyTerritory2.caseAccessLevel='Edit';


                if(territory2ModelLst==null || !territory2ModelLst.isEmpty()){

                    dummyTerritory2.Territory2ModelId=territory2ModelLst[0].id;
                }
                else
                {
                    dummyTerritory2.Territory2ModelId=model.id;
                }
                dummyTerritory2.Territory2TypeId=typeTest.id;

                territory2Lst.add(dummyTerritory2);
            }

            insert territory2Lst;

            //*************************************Insert User (Territory team dummy user) Object*****************************************//

            //Insert User Record with functional roles
            for(Integer i=0;i<functionalRoleList.size();i++){

                //User With Sales Maintenance Rep functional role
                User usrObj = TestDataBuilder.buildTestUser(i); 
                usrObj.Functional_Role__c=functionalRoleList[i];
                userWithRoleLst.add(usrObj);

            }
            //Insert users
            insert userWithRoleLst;
            
            

            //Insert  Record in roleUserMap with functional roles
            for(Integer i=0;i<userWithRoleLst.size();i++){

                roleUserMap.put(userWithRoleLst[i].Functional_Role__c,userWithRoleLst[i].id);
                userSet.add(userWithRoleLst[i].id);

            }


            //*************************************Insert Userterritory2Association Object*****************************************//

            Integer count=7;
            //add users to territory2
            for(Integer i=0;i<7;i++){


                //Add all users to territory2
                for(Integer j=0;j<count;j++){

                    userterritory2Association userAssObj=TestDataBuilder.buildTestUserterritory2Association(userWithRoleLst[j].id,territory2Lst[i].id);
                    userAssoObjListToInsert.add(userAssObj);

                }

                count--;

            }

            insert userAssoObjListToInsert;


            //Get user to set default opportunity custom setting
            //We will query using alias as name had issues with different locales
            List<User> usrObjByName=new List<User>();
            usrObjByName=[select id,name,functional_role__C from User where alias=:settings.Default_Opportunity_Owner__c ];
            //usrObjByName[0].functional_role__C='';
            //update usrObjByName;
            
            
            //User usrObj=TestDataBuilder.buildTestUser(100);
            //insert usrObj;
            
            
            system.debug(usrObjByName+'usrObjByName');

            for(Integer i=0;i<10;i++){

                Opportunity opty = TestDataBuilder.buildTestOpportunity(i);
               
                opty.accountid=accLLst[i].id;
                opty.ownerid=usrObjByName[0].id;
                opty.amount=1000;
                opty.batch_evaluate__c=true;
                optyLst.add(opty);

            }


            insert optyLst;
            
            
            //************************************* Uptdate Account objects *****************************************//

            for(Integer i=0;i<7;i++){

                Account accL =accLLst[i];
                accL.Siebel_Territory_ID__c=territory2Lst[i].Siebel_Territory_ID__c;
                accLLstToUpdate.add(accL);  

            }

            test.startTest();

            Update accLLstToUpdate;      

            //Check to see if correct territory2 team member is assigned
            List<Opportunity> optyObjLst=[select id,owner.Functional_Role__c from Opportunity 
                                          where id in :optyLst];

            for(Integer i=0;i<optyObjLst.size();i++){

                system.assert(userSet.contains(optyObjLst[i].ownerid)); 

            }


            test.stopTest();

        }
    }
}