objects/Account.object
<CustomObject>
    <fields>
        <fullName>Global_Region__c</fullName>
        <label>Global Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office_Channel__c</fullName>
        <label>Office Channel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office_Group__c</fullName>
        <label>Office Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <label>Office</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Siebel_Territory_ID__c</fullName>
        <description>Territory ID from external rules engine (Siebel).  Used to lookup the internal Salesforce Territory to assign to the Account.</description>
        <label>Siebel Territory ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Industry__c</fullName>
        <label>Territory Industry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Sales_Group__c</fullName>
        <label>Territory Sales Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Sales_Team_Type__c</fullName>
        <label>Territory Sales Team Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Territory2.object
<CustomObject>
    <fields>
        <fullName>Global_Region__c</fullName>
        <label>Global Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Office_Channel__c</fullName>
        <label>Office Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Indirect</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Office_Group__c</fullName>
        <label>Office Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMER - House</fullName>
                </value>
                <value>
                    <fullName>APAC - House</fullName>
                </value>
                <value>
                    <fullName>APAC Indirect</fullName>
                </value>
                <value>
                    <fullName>EMEA Direct Non Office</fullName>
                </value>
                <value>
                    <fullName>EMEA - House</fullName>
                </value>
                <value>
                    <fullName>EMEA Indirect</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>MathWorks Australia</fullName>
                </value>
                <value>
                    <fullName>MathWorks China</fullName>
                </value>
                <value>
                    <fullName>MathWorks France</fullName>
                </value>
                <value>
                    <fullName>MathWorks Germany</fullName>
                </value>
                <value>
                    <fullName>MathWorks India</fullName>
                </value>
                <value>
                    <fullName>MathWorks Ireland</fullName>
                </value>
                <value>
                    <fullName>MathWorks Italy</fullName>
                </value>
                <value>
                    <fullName>MathWorks Japan</fullName>
                </value>
                <value>
                    <fullName>MathWorks Korea</fullName>
                </value>
                <value>
                    <fullName>MathWorks Natick</fullName>
                </value>
                <value>
                    <fullName>MathWorks Netherlands</fullName>
                </value>
                <value>
                    <fullName>MathWorks Nordic</fullName>
                </value>
                <value>
                    <fullName>MathWorks Spain</fullName>
                </value>
                <value>
                    <fullName>MathWorks Switzerland</fullName>
                </value>
                <value>
                    <fullName>MathWorks UK</fullName>
                </value>
                <value>
                    <fullName>Natick - EMEA (Direct)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <label>Office</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AMER - House</fullName>
                </value>
                <value>
                    <fullName>APAC - House</fullName>
                </value>
                <value>
                    <fullName>China Overlay</fullName>
                </value>
                <value>
                    <fullName>Componentes Electronicas Ltda</fullName>
                </value>
                <value>
                    <fullName>EMEA Direct Non Office</fullName>
                </value>
                <value>
                    <fullName>EMEA - House</fullName>
                </value>
                <value>
                    <fullName>ETMC Exponenta Ltd</fullName>
                </value>
                <value>
                    <fullName>FIGES</fullName>
                </value>
                <value>
                    <fullName>Gamax Laboratory Solutions Kft</fullName>
                </value>
                <value>
                    <fullName>Humusoft</fullName>
                </value>
                <value>
                    <fullName>India Edu-Gov/Overlay</fullName>
                </value>
                <value>
                    <fullName>MathWorks AB (Sweden)</fullName>
                </value>
                <value>
                    <fullName>MathWorks Australia</fullName>
                </value>
                <value>
                    <fullName>MathWorks China</fullName>
                </value>
                <value>
                    <fullName>MathWorks France</fullName>
                </value>
                <value>
                    <fullName>MathWorks Germany</fullName>
                </value>
                <value>
                    <fullName>MathWorks India</fullName>
                </value>
                <value>
                    <fullName>MathWorks Ireland</fullName>
                </value>
                <value>
                    <fullName>MathWorks Italy</fullName>
                </value>
                <value>
                    <fullName>MathWorks Japan</fullName>
                </value>
                <value>
                    <fullName>MathWorks Korea</fullName>
                </value>
                <value>
                    <fullName>MathWorks Natick</fullName>
                </value>
                <value>
                    <fullName>MathWorks Netherlands</fullName>
                </value>
                <value>
                    <fullName>MathWorks Spain</fullName>
                </value>
                <value>
                    <fullName>MathWorks Switzerland</fullName>
                </value>
                <value>
                    <fullName>MathWorks UK</fullName>
                </value>
                <value>
                    <fullName>Mentor Hellas</fullName>
                </value>
                <value>
                    <fullName>MultiOn Comm/Overlay</fullName>
                </value>
                <value>
                    <fullName>MultiOn Distributor</fullName>
                </value>
                <value>
                    <fullName>Natick - AMER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMER</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Siebel_Territory_ID__c</fullName>
        <description>Territory ID from Siebel that will be used as a lookup value from the Account to assign the appropriate Salesforce Territory.</description>
        <label>Siebel Territory ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Industry__c</fullName>
        <label>Territory Industry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AERO</fullName>
                </value>
                <value>
                    <fullName>AUTO</fullName>
                </value>
                <value>
                    <fullName>CES</fullName>
                </value>
                <value>
                    <fullName>CROSS</fullName>
                </value>
                <value>
                    <fullName>EDU</fullName>
                </value>
                <value>
                    <fullName>EP</fullName>
                </value>
                <value>
                    <fullName>FIN</fullName>
                </value>
                <value>
                    <fullName>GOV</fullName>
                </value>
                <value>
                    <fullName>IAM</fullName>
                </value>
                <value>
                    <fullName>MED</fullName>
                </value>
                <value>
                    <fullName>UNKNOWN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory_Sales_Team_Type__c</fullName>
        <label>Territory Sales Team Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Blended</fullName>
                </value>
                <value>
                    <fullName>CMA</fullName>
                </value>
                <value>
                    <fullName>EDU</fullName>
                </value>
                <value>
                    <fullName>Geo</fullName>
                </value>
                <value>
                    <fullName>House</fullName>
                </value>
                <value>
                    <fullName>Major</fullName>
                </value>
                <value>
                    <fullName>Mixed</fullName>
                </value>
                <value>
                    <fullName>Named</fullName>
                </value>
                <value>
                    <fullName>NMA</fullName>
                </value>
                <value>
                    <fullName>UNKNOWN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Territory_Shadow__c.object
<CustomObject>
    <description>Shadow Territory object to be synced with the Territory2 object for custom rules management</description>
    <fields>
        <fullName>Global_Region__c</fullName>
        <label>Global Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office_Channel__c</fullName>
        <label>Office Channel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office_Group__c</fullName>
        <label>Office Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <label>Office</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Siebel_Territory_ID__c</fullName>
        <label>Siebel Territory ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Industry__c</fullName>
        <label>Territory Industry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Sales_Team_Type__c</fullName>
        <label>Territory Sales Team Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TerritoryRuleCriteriaComponentCtrlTest.cls
/**
 *@author Original: Abhay Verma - Cloud Sherpas/Mathworks, Last Modified:
 *@date Original: 29 Feb 2016, Last Modified: 
 *@description This  is a Test class for 'TerritoryRuleCriteriaComponentController' . 
 *@Revision:
 */

@isTest
public class TerritoryRuleCriteriaComponentCtrlTest{

    //re-create custom setting test records when running the test class
    static CustomSettingsBuilder custsettbuild = new CustomSettingsBuilder();
    
    @testSetup static void insertTestData() {
        
        //Inserting Bypass trigger custom setting
        custsettbuild.buildBypassTriggerSettings();
        //Creating Test user
        User usr = TestDataBuilder.buildTestUser(100);
        //inserting user.
        insert usr;
        
        System.runAs(usr){
            
            List<Territory2> territory2Lst =new List<Territory2>();
            List<Territory2Model> territory2ModelLst =new List<Territory2Model>();
            List<Territory2> territory2LstTest =new List<Territory2>();
            Territory2Model model;
            
            Territory2Type typeTest=[select id from Territory2Type limit 1];
            
            territory2ModelLst=[select id,state from Territory2Model where state='Active' limit 1];
            
            if(territory2ModelLst==null || territory2ModelLst.isEmpty()){
            
            model=TestDataBuilder.buildTestTerritory2Model(0);
            insert model;
            
            }
            
            //create Territory record from TestDataBuilder.
            for(Integer i=0;i<1;i++){
            
            Territory2 dummyTerritory2=TestDataBuilder.buildTestTerritory2(i);         
            dummyTerritory2.Siebel_Territory_ID__c='1-UIOPYU'+i;
            dummyTerritory2.name='TestTerritory';
            dummyTerritory2.DeveloperName='AMER'+i;
            dummyTerritory2.Global_Region__c='International';
            dummyTerritory2.Region__c='omer';
            dummyTerritory2.Office_Group__c='Componentes Electronicas Ltda';
            dummyTerritory2.Office__c='Componentes Electronicas Ltda';
            dummyTerritory2.Office_Channel__c='Indirect';
            dummyTerritory2.Territory_Industry__c='UNKNOWN';
            dummyTerritory2.Territory_Sales_Team_Type__c='Mixed';
            dummyTerritory2.Territory_Sales_Group__c='Latin America';
            
            
            if(territory2ModelLst==null || !territory2ModelLst.isEmpty()){
            
                dummyTerritory2.Territory2ModelId=territory2ModelLst[0].id;
            }
            else
            {
                dummyTerritory2.Territory2ModelId=model.id;
            }
            dummyTerritory2.Territory2TypeId=typeTest.id;
            
            territory2Lst.add(dummyTerritory2);
            }
            insert territory2Lst;
            
        }//End of RunAs(Usr)
    }//End of @testSetup


    /*
      @name         territoryRuleCriteriaComponentTest
      @date         29.Feb.2016
      @author       Abhay Verma
      @param        none.
      @return       pageReference. 
      @description  Method to test the functionality of edit method in 'TerritoryRuleCriteriaComponentController'. 
        */  

    private static testMethod void territoryRuleCriteriaComponentTest(){
        
        
        //create test User
        User usr = TestDataBuilder.buildTestUser(1);
        //insert test user.
        insert usr;
        
        System.runAs(usr){
            //Inserting Bypass trigger custom setting
            custsettbuild.buildBypassTriggerSettings();
            
            //get Territory_Rule_Criteria__c record
            Territory_Shadow__c shadowObj = [select id from Territory_Shadow__c limit 1];
            
            //Creating the Territory Assignment Rule test data.
            Territory_Assignment_Rule__c assignmentRuleObj = new  Territory_Assignment_Rule__c();
            assignmentRuleObj.Territory__c = shadowObj.Id;
            
            //Inserting the assignment rule.
            insert assignmentRuleObj;
            
            //Fetching all the record type Id of Territory Rule Criteria Object.
            Id accountNameRecTypeId = Schema.SObjectType.Territory_Rule_Criteria__c.getRecordTypeInfosByName().get('Account Name').getRecordTypeId();
            Id accountPostalCodeRecTypeId = Schema.SObjectType.Territory_Rule_Criteria__c.getRecordTypeInfosByName().get('Account Postal Code').getRecordTypeId();
            Id accountCityRecTypeId = Schema.SObjectType.Territory_Rule_Criteria__c.getRecordTypeInfosByName().get('Account City').getRecordTypeId();
            Id accountCountryCodeRecTypeId = Schema.SObjectType.Territory_Rule_Criteria__c.getRecordTypeInfosByName().get('Account Country Code').getRecordTypeId();
            Id accountSectorRecTypeId = Schema.SObjectType.Territory_Rule_Criteria__c.getRecordTypeInfosByName().get('Account Sector').getRecordTypeId();
            Id accountStateCodeRecTypeId = Schema.SObjectType.Territory_Rule_Criteria__c.getRecordTypeInfosByName().get('Account State Code').getRecordTypeId();
            
            //List to store the Territory Rule Criteria Object test Record
            List<Territory_Rule_Criteria__c> TRCList = new List<Territory_Rule_Criteria__c>();
            
            //Creating theTerritory Rule Criteria Test data.
            for(Integer i=0;i<=199;i++){
                Territory_Rule_Criteria__c territoryCriteriaObj = TestDataBuilder.buildTerritoryRuleCriteria('Territory Criteria ' +i, assignmentRuleObj.Id);
            
                //Assigning the different record type to different test data records.
                if(i<=34){
                    territoryCriteriaObj.RecordTypeId = accountNameRecTypeId;
                }
                else if(34<i && i<=69){
                    territoryCriteriaObj.RecordTypeId = accountPostalCodeRecTypeId;
                }
                else if(70<i && i<=104){
                    territoryCriteriaObj.RecordTypeId = accountCityRecTypeId;
                }
                if(104<i && i<=139){
                    territoryCriteriaObj.RecordTypeId = accountCountryCodeRecTypeId;
                }
                else if(139<i && i<=174){
                    territoryCriteriaObj.RecordTypeId = accountSectorRecTypeId;
                }
                else{
                    territoryCriteriaObj.RecordTypeId = accountStateCodeRecTypeId;
                }
                TRCList.add(territoryCriteriaObj);
            }
            
            //Inserting the Territory Rule Criteria List.
            insert TRCList;  
            
            //Querying the Territory Rule Criteria List.
            List<Territory_Rule_Criteria__c> insertedTerritoryCriteriaLst = [SELECT Id, Required__c, Score__c, Territory_Assignment_Rule__c FROM Territory_Rule_Criteria__c WHERE Id IN: TRCList];
            
            //Asserting the Territory Rule Criteria List to get inserted or not.
            System.assertEquals(insertedTerritoryCriteriaLst.size(), 200, true);
            
            //Start test
            test.startTest(); 
            
            TerritoryRuleCriteriaComponentController criteriaControllerObj = new TerritoryRuleCriteriaComponentController();
            
            criteriaControllerObj.territoryRuleCriteriaObj = insertedTerritoryCriteriaLst[0];
            criteriaControllerObj.territoryShadowId = shadowObj.Id;
            criteriaControllerObj.territoryRuleCriteriaLst = insertedTerritoryCriteriaLst;
            criteriaControllerObj.territoryRuleCriteriaId = insertedTerritoryCriteriaLst[0].Id;
            criteriaControllerObj.ruleObjId = assignmentRuleObj.Id;
            criteriaControllerObj.criteriaObjId = insertedTerritoryCriteriaLst[0].Id; 
            criteriaControllerObj.show = True;
            
            criteriaControllerObj.getTerritoryRuleCriteriaList();
            //Asserting the territory rule criteria list is populating on the territory summary page.
            System.AssertEquals(criteriaControllerObj.getTerritoryRuleCriteriaList().size(), 200, True);
            
            criteriaControllerObj.getCriteriaValueObjs();
            
            criteriaControllerObj.newTerritoryCriteria();
            criteriaControllerObj.editCriteriaObj();
            
            //Get the url when the Edit link is clicked.
            String nextPage= criteriaControllerObj.editCriteriaObj().getUrl();
            //Asserting if the User redirect to the expected territory rule criteria value page or not.
            System.assertEquals(nextPage,'/'+insertedTerritoryCriteriaLst[0].Id+'/e?isdtp=vw&retURL=%2Fapex%2FTerritorysummary%3Fid%3D'+shadowObj.Id, True);
            
            criteriaControllerObj.deleteCriteriaRule();
            //Querying the Territory Rule Criteria Object to get the Deleted Rule Criteria Record.
            List<Territory_Rule_Criteria__c> deletedTerritoryRuleCriterialst = [SELECT Id FROM Territory_Rule_Criteria__c WHERE ID =:insertedTerritoryCriteriaLst[0].Id];
            //Asserting if the record is deleted or not.
            System.assertEquals(deletedTerritoryRuleCriterialst.size(), 0, True);
            
            
            //Stop Test         
            test.stopTest();
        }//End of Run as User  
    }//End of Method
    
    
    private static testMethod void NoterritoryRuleCriteriaFoundTest(){
        
        
        //create test User
        User usr = TestDataBuilder.buildTestUser(1);
        //insert test user.
        insert usr;
        
        System.runAs(usr){
            //Inserting Bypass trigger custom setting
            custsettbuild.buildBypassTriggerSettings();
            
            //get Territory_Rule_Criteria__c record
            Territory_Shadow__c shadowObj = [select id from Territory_Shadow__c limit 1];
            
            //Creating the Territory Assignment Rule test data.
            Territory_Assignment_Rule__c assignmentRuleObj = new  Territory_Assignment_Rule__c();
            assignmentRuleObj.Territory__c = shadowObj.Id;
            
            //Inserting the assignment rule.
            insert assignmentRuleObj;
            
            //Start test
            test.startTest(); 
            
            TerritoryRuleCriteriaComponentController criteriaControllerObj = new TerritoryRuleCriteriaComponentController();
            
            criteriaControllerObj.territoryRuleCriteriaObj = null;
            criteriaControllerObj.territoryShadowId = shadowObj.Id;
            criteriaControllerObj.territoryRuleCriteriaLst = null;
            criteriaControllerObj.territoryRuleCriteriaId = null;
            criteriaControllerObj.ruleObjId = assignmentRuleObj.Id;
            criteriaControllerObj.criteriaObjId = null; 
            criteriaControllerObj.show = True;
            criteriaControllerObj.getTerritoryRuleCriteriaList();
            criteriaControllerObj.getCriteriaValueObjs();
            criteriaControllerObj.editCriteriaObj();
            criteriaControllerObj.newTerritoryCriteria();
            criteriaControllerObj.deleteCriteriaRule();
            
            //Asserting the territory rule criteria list is not presented on the territory summary page.
            System.AssertEquals(criteriaControllerObj.getTerritoryRuleCriteriaList(), null, True);
            //Stop Test         
            test.stopTest();
        }//End of Run as User  
    }//End of Method
    
     
}//End of Class