objects/Account.object
<CustomObject>
    <fields>
        <fullName>Global_Region__c</fullName>
        <label>Global Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Territory_ID__c</fullName>
        <description>Logical unique identifier for a Territory - used as key between systems (Salesforce, CDS, Warehouse, etc.)
Used to lookup Territory2Id for creating assignments to Territory</description>
        <label>Master Territory ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office_Channel__c</fullName>
        <label>Office Channel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office_Group__c</fullName>
        <label>Office Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <label>Office</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Siebel_Territory_ID__c</fullName>
        <description>Territory ID from external rules engine (Siebel).  Used to lookup the internal Salesforce Territory to assign to the Account.</description>
        <label>Siebel Territory ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Industry__c</fullName>
        <label>Territory Industry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Name__c</fullName>
        <description>Internal Salesforce Territory Name.  Populated by looking up the Salesforce Territory Name through the External_Territory_ID__c field.</description>
        <label>Territory Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Sales_Group__c</fullName>
        <label>Territory Sales Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Sales_Team_Type__c</fullName>
        <label>Territory Sales Team Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Territory2.object
<CustomObject>
    <fields>
        <fullName>Global_Region__c</fullName>
        <label>Global Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Master_Territory_ID__c</fullName>
        <inlineHelpText>Logical unique identifier for a Territory - used as key between systems (Salesforce, CDS, Warehouse, etc.)</inlineHelpText>
        <label>Master Territory ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office_Channel__c</fullName>
        <label>Office Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Indirect</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Office_Group__c</fullName>
        <label>Office Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMER - House</fullName>
                </value>
                <value>
                    <fullName>APAC - House</fullName>
                </value>
                <value>
                    <fullName>APAC Indirect</fullName>
                </value>
                <value>
                    <fullName>EMEA Direct Non Office</fullName>
                </value>
                <value>
                    <fullName>EMEA - House</fullName>
                </value>
                <value>
                    <fullName>EMEA Indirect</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>MathWorks Australia</fullName>
                </value>
                <value>
                    <fullName>MathWorks China</fullName>
                </value>
                <value>
                    <fullName>MathWorks France</fullName>
                </value>
                <value>
                    <fullName>MathWorks Germany</fullName>
                </value>
                <value>
                    <fullName>MathWorks India</fullName>
                </value>
                <value>
                    <fullName>MathWorks Ireland</fullName>
                </value>
                <value>
                    <fullName>MathWorks Italy</fullName>
                </value>
                <value>
                    <fullName>MathWorks Japan</fullName>
                </value>
                <value>
                    <fullName>MathWorks Korea</fullName>
                </value>
                <value>
                    <fullName>MathWorks Natick</fullName>
                </value>
                <value>
                    <fullName>MathWorks Netherlands</fullName>
                </value>
                <value>
                    <fullName>MathWorks Nordic</fullName>
                </value>
                <value>
                    <fullName>MathWorks Spain</fullName>
                </value>
                <value>
                    <fullName>MathWorks Switzerland</fullName>
                </value>
                <value>
                    <fullName>MathWorks UK</fullName>
                </value>
                <value>
                    <fullName>Natick - EMEA (Direct)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <label>Office</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AMER - House</fullName>
                </value>
                <value>
                    <fullName>APAC - House</fullName>
                </value>
                <value>
                    <fullName>China Overlay</fullName>
                </value>
                <value>
                    <fullName>Componentes Electronicas Ltda</fullName>
                </value>
                <value>
                    <fullName>EMEA Direct Non Office</fullName>
                </value>
                <value>
                    <fullName>EMEA - House</fullName>
                </value>
                <value>
                    <fullName>ETMC Exponenta Ltd</fullName>
                </value>
                <value>
                    <fullName>FIGES</fullName>
                </value>
                <value>
                    <fullName>Gamax Laboratory Solutions Kft</fullName>
                </value>
                <value>
                    <fullName>Humusoft</fullName>
                </value>
                <value>
                    <fullName>India Edu-Gov/Overlay</fullName>
                </value>
                <value>
                    <fullName>MathWorks AB (Sweden)</fullName>
                </value>
                <value>
                    <fullName>MathWorks Australia</fullName>
                </value>
                <value>
                    <fullName>MathWorks China</fullName>
                </value>
                <value>
                    <fullName>MathWorks France</fullName>
                </value>
                <value>
                    <fullName>MathWorks Germany</fullName>
                </value>
                <value>
                    <fullName>MathWorks India</fullName>
                </value>
                <value>
                    <fullName>MathWorks Ireland</fullName>
                </value>
                <value>
                    <fullName>MathWorks Italy</fullName>
                </value>
                <value>
                    <fullName>MathWorks Japan</fullName>
                </value>
                <value>
                    <fullName>MathWorks Korea</fullName>
                </value>
                <value>
                    <fullName>MathWorks Natick</fullName>
                </value>
                <value>
                    <fullName>MathWorks Netherlands</fullName>
                </value>
                <value>
                    <fullName>MathWorks Spain</fullName>
                </value>
                <value>
                    <fullName>MathWorks Switzerland</fullName>
                </value>
                <value>
                    <fullName>MathWorks UK</fullName>
                </value>
                <value>
                    <fullName>Mentor Hellas</fullName>
                </value>
                <value>
                    <fullName>MultiOn Comm/Overlay</fullName>
                </value>
                <value>
                    <fullName>MultiOn Distributor</fullName>
                </value>
                <value>
                    <fullName>Natick - AMER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMER</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Siebel_Territory_ID__c</fullName>
        <description>Territory ID from Siebel that will be used as a lookup value from the Account to assign the appropriate Salesforce Territory.</description>
        <label>Siebel Territory ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Industry__c</fullName>
        <label>Territory Industry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AERO</fullName>
                </value>
                <value>
                    <fullName>AUTO</fullName>
                </value>
                <value>
                    <fullName>CES</fullName>
                </value>
                <value>
                    <fullName>CROSS</fullName>
                </value>
                <value>
                    <fullName>EDU</fullName>
                </value>
                <value>
                    <fullName>EP</fullName>
                </value>
                <value>
                    <fullName>FIN</fullName>
                </value>
                <value>
                    <fullName>GOV</fullName>
                </value>
                <value>
                    <fullName>IAM</fullName>
                </value>
                <value>
                    <fullName>MED</fullName>
                </value>
                <value>
                    <fullName>UNKNOWN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory_Sales_Group__c</fullName>
        <label>Territory Sales Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AMER - House</fullName>
                </value>
                <value>
                    <fullName>APAC - House</fullName>
                </value>
                <value>
                    <fullName>EMEA - House</fullName>
                </value>
                <value>
                    <fullName>EMEA Other</fullName>
                </value>
                <value>
                    <fullName>ETMC Exponenta Ltd</fullName>
                </value>
                <value>
                    <fullName>FIGES</fullName>
                </value>
                <value>
                    <fullName>Gamax</fullName>
                </value>
                <value>
                    <fullName>Hoare Research</fullName>
                </value>
                <value>
                    <fullName>Humusoft</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>MathWorks Australia</fullName>
                </value>
                <value>
                    <fullName>MathWorks China</fullName>
                </value>
                <value>
                    <fullName>MathWorks France</fullName>
                </value>
                <value>
                    <fullName>MathWorks Germany</fullName>
                </value>
                <value>
                    <fullName>MathWorks India</fullName>
                </value>
                <value>
                    <fullName>MathWorks Ireland</fullName>
                </value>
                <value>
                    <fullName>MathWorks Italy</fullName>
                </value>
                <value>
                    <fullName>MathWorks Japan</fullName>
                </value>
                <value>
                    <fullName>MathWorks Korea</fullName>
                </value>
                <value>
                    <fullName>MathWorks Natick</fullName>
                </value>
                <value>
                    <fullName>MathWorks Netherlands</fullName>
                </value>
                <value>
                    <fullName>MathWorks Nordic</fullName>
                </value>
                <value>
                    <fullName>MathWorks Spain</fullName>
                </value>
                <value>
                    <fullName>MathWorks Switzerland</fullName>
                </value>
                <value>
                    <fullName>MathWorks UK</fullName>
                </value>
                <value>
                    <fullName>Mentor Hellas</fullName>
                </value>
                <value>
                    <fullName>NA Comm-Aero</fullName>
                </value>
                <value>
                    <fullName>NA Comm-Aero-Geo So Cal</fullName>
                </value>
                <value>
                    <fullName>NA Comm-Auto</fullName>
                </value>
                <value>
                    <fullName>NA Comm-Auto-Geo MI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/Territory2Dml.cls
/**
 *author Original: Archana Lohar - Cloud Sherpas/Mathworks, Last Modified: Archana Lohar - Cloud Sherpas/Mathworks, Faina Gorelik
 *date Original: 22 October 2014, Last Modified: 22 October 2014, 16 August 2016
 *description This trigger is used to handle different trigger actions for Territory2 
 *revision: added Master_Territory_id__c to the queries
 */
global class Territory2Dml implements Database.Batchable<sObject> {

  //Instantiate SiebelTerritoryIdToTerritory2
  Map<String,Territory2> SiebelTerritoryIdToTerritory2=new map<String,Territory2>();

  General_Settings__c settings;

  //AccountList To Update fields
  List<Account> accListToUpdate=new List<Account>();

  global Territory2Dml(Map<String,Territory2> STIToTerritory2Map) {

    SiebelTerritoryIdToTerritory2 = STIToTerritory2Map;
  }

  global Database.QueryLocator start(Database.BatchableContext BC) { 

    return DataBase.getQueryLocator([select id,Siebel_Territory_ID__c,Global_Region__c,Territory_Name__c,
                                     Region__c,Office_Group__c,Office__c,Office_Channel__c,
                                     Territory_Industry__c,Territory_Sales_Group__c,Territory_Sales_Team_Type__c,
                                     Account_Territory_Sector__c,Account_Territory_Type__c,Master_Territory_Id__c
                                     from Account 
                                     where is_individual_account__c = false and siebel_territory_id__c != null and Siebel_Territory_ID__c in :SiebelTerritoryIdToTerritory2.keyset()]);

  }
  global void execute(Database.BatchableContext BC,List<Account> accObjListToSync) {

    for(Account accToUpdate:accObjListToSync){

      Territory2 territoryObj;

      if(SiebelTerritoryIdToTerritory2.get(accToUpdate.Siebel_Territory_ID__c)!=null){

        territoryObj=siebelTerritoryIdToTerritory2.get(accToUpdate.Siebel_Territory_ID__c);

        //Populate fields of Territory2 to Account
        accToUpdate.Territory_Name__c=territoryObj.name;
        accToUpdate.Global_Region__c=territoryObj.Global_Region__c;
        accToUpdate.Region__c=territoryObj.Region__c;
        accToUpdate.Office_Group__c=territoryObj.Office_Group__c;
        accToUpdate.Office__c=territoryObj.Office__c;
        accToUpdate.Office_Channel__c=territoryObj.Office_Channel__c;
        accToUpdate.Territory_Industry__c=territoryObj.Territory_Industry__c;
        accToUpdate.Territory_Sales_Group__c=territoryObj.Territory_Sales_Group__c;
        accToUpdate.Territory_Sales_Team_Type__c=territoryObj.Territory_Sales_Team_Type__c;
        accToUpdate.Account_Territory_Sector__c=territoryObj.Territory_Sector__c;
        accToUpdate.Account_Territory_Type__c= territoryObj.Territory2Type.MasterLabel;
        accToUpdate.Master_Territory_Id__c = territoryObj.Master_Territory_Id__c; //fg

        //add the account to update
        accListToUpdate.add(accToUpdate);
        Logger.debug(accToUpdate.Id);

      }//if

    }//for

    if(!accListToUpdate.isEmpty())
    {

      try{
        Update accListToUpdate;
      }
      catch (System.DmlException e) {
        for (Integer i = 0; i < e.getNumDml(); i++) {
          //capture Dml  Process exception 
          Logger.debugException('DmlException:'+e.getDmlMessage(i)+ 'for ID:'+e.getDmlId(i));
        }
      }
    }//if

  }
  global void finish(Database.BatchableContext BC) {
    //Send an email to the User after your batch completes
    String emailSubject = System.Label.Territory2Dml_batch_apex_message_subject;
    String emailBody = System.Label.Territory2Dml_batch_apex_message_emailbody;
    settings=General_Settings__c.getInstance();
    List<String> emailAddressList = settings.Emailaddress_Territory2Dml__c.split(',');
    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
    mail.setToAddresses(emailAddressList);
    mail.setSubject(emailSubject);
    mail.setPlainTextBody(emailBody);
    Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
  }
}