objects/Account.object
<CustomObject>
    <fields>
        <fullName>Siebel_Territory_ID__c</fullName>
        <description>Territory ID from external rules engine (Siebel).  Used to lookup the internal Salesforce Territory to assign to the Account.</description>
        <label>Siebel Territory ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TA_Attempts__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of attempts made to run the territory assignment on the account</description>
        <inlineHelpText>Number of attempts made to run the territory assignment on the account.</inlineHelpText>
        <label>TA_Attempts</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <description>Hyperlink formula to the sales roster page</description>
        <formula>IF(
    Is_Individual_Account__c
    ,&quot;N/A&quot;
    ,IF(
        NOT(ISBLANK(Salesforce_Territory_Id__c))
        ,HYPERLINK(&quot;/apex/viewterritoryteams?territoryId=&quot;&amp; Salesforce_Territory_Id__c , Territory_Name__c)
        ,IF(
            AND(
                OR(
					AND(
						$Setup.Territory_Settings__c.Territory_Assignment_Lookup_Field__c == &quot;Siebel&quot;
						,NOT(ISBLANK(Siebel_Territory_ID__c))  
						,Siebel_Territory_ID__c != &apos;0-5220&apos; 
					)
					,AND(
						$Setup.Territory_Settings__c.Territory_Assignment_Lookup_Field__c == &quot;Master&quot;
						,NOT(ISBLANK(Master_Territory_ID__c))  
					)				
				)				
                ,ISBLANK(Salesforce_Territory_Id__c)
                ,OR(
                    TA_Attempts__c == 0
                    ,ISBLANK(TA_Attempts__c)
                )                
            )
            ,&quot;Assignment Error&quot;
            ,IF(
                AND(
                    OR(
						AND(
							$Setup.Territory_Settings__c.Territory_Assignment_Lookup_Field__c == &quot;Siebel&quot;
							,NOT(ISBLANK(Siebel_Territory_ID__c))  
							,Siebel_Territory_ID__c != &apos;0-5220&apos;  
						)
						,AND(
							$Setup.Territory_Settings__c.Territory_Assignment_Lookup_Field__c == &quot;Master&quot;
							,NOT(ISBLANK(Master_Territory_ID__c))  
						)				
					)	
                    ,ISBLANK(Salesforce_Territory_Id__c)
                    ,TA_Attempts__c &gt; 0
                    ,TA_Attempts__c &lt;= $Setup.Territory_Settings__c.Max_TA_Attempts__c
                )
                ,&quot;Pending Assignment - Retry&quot;
                ,IF(
                    AND(
                        OR(
							AND(
								$Setup.Territory_Settings__c.Territory_Assignment_Lookup_Field__c == &quot;Siebel&quot;
								,NOT(ISBLANK(Siebel_Territory_ID__c))  
								,Siebel_Territory_ID__c != &apos;0-5220&apos;  
							)
							,AND(
								$Setup.Territory_Settings__c.Territory_Assignment_Lookup_Field__c == &quot;Master&quot;
								,NOT(ISBLANK(Master_Territory_ID__c))  
							)				
						)	
                        ,ISBLANK(Salesforce_Territory_Id__c)
                        ,TA_Attempts__c &gt; $Setup.Territory_Settings__c.Max_TA_Attempts__c
                    )
                    ,&quot;Pending Assignment - Threshold Exceeded&quot;
                    ,&quot;Pending Assignment&quot;                             
                )
            )
        )
    )
)</formula>
        <label>Territory</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Territory_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom settings related around territory</description>
    <fields>
        <fullName>Assignment_Status__c</fullName>
        <description>The value of the Account territory status(Assignment Error, Pending Retry, etc) to be processed for retry</description>
        <inlineHelpText>The value of the Account territory status(Assignment Error, Pending Retry, etc) to be processed for retry</inlineHelpText>
        <label>Assignment Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_TA_Attempts__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Maximum number of attempts to try to run the territory assignment on the account</description>
        <inlineHelpText>Maximum number of attempts to try to run the territory assignment on the account</inlineHelpText>
        <label>Max TA Attempts</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TA_Retry_Batch_Size__c</fullName>
        <description>Batch size of the job when executing the territory assignment retry logic</description>
        <inlineHelpText>Batch size of the job when executing the territory assignment retry logic</inlineHelpText>
        <label>TA Retry Batch Size</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Territory_Assignment_Lookup_Field__c</fullName>
        <defaultValue>&quot;Siebel&quot;</defaultValue>
        <description>Switch to use for changing between using Master Territory ID and Siebel Territory ID for looking up corresponding Salesforce Territory2 ID for assignment.  Should not be needed and can be removed after TM solution based on Salesforce/CDS engine goes live - sometime in 2017.</description>
        <inlineHelpText>Field to use for looking up the Salesforce Territory2 record for doing assignments.  Valid options are &quot;Master&quot; or &quot;Siebel&quot;.</inlineHelpText>
        <label>Territory Assignment Lookup Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Territory Settings</label>
</CustomObject>

classes/RetryTerritoryAssignmentSchedulable.cls
/**
 *author Original: Archana Lohar - Cloud Sherpas/Mathworks, Last Modified: kishore AN - Cloud Sherpas/Mathworks, Faina Gorelik
 *date Original: 19 Jan 2015, Last Modified:19 Jan 2015, 20 November 2015 AtTask 1772050 , 12 January 2016 AtTask 1877463 
 *description : Batch class for Retry Territory Assignment*/
global class RetryTerritoryAssignmentSchedulable implements Schedulable, Database.Batchable<sObject>{

    //String will hold the query
    global final String Query;
    global static Territory_Settings__c territorySettings = Territory_Settings__c.getInstance();

    /**
     *author Original: Archana Lohar - Cloud Sherpas/Mathworks, Last Modified: kishore AN - Cloud Sherpas/Mathworks
     *date Original: 19 Jan 2015, Last Modified:19 Jan 2015 
     *description : Constructor which initialises the Query*/   
    global RetryTerritoryAssignmentSchedulable(){
        Query = 'SELECT ID FROM ACCOUNT'+
        ' WHERE Territory__c = \''+ territorySettings.Assignment_Status__c + '\' AND'+
        ' TA_Attempts__c >= 1 AND TA_Attempts__c <='+territorySettings.Max_TA_Attempts__c +
        '  ORDER BY siebel_territory_Id__c';    
    }//RetryTerritoryAssignmentSchedulable

    /**
     *author Original: Archana Lohar - Cloud Sherpas/Mathworks, Last Modified: 
     *date Original: 19 Jan 2015, Last Modified:19 Jan 2015 
     *description : Start method
     */
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }//start

    /**
     *author Original: Archana Lohar - Cloud Sherpas/Mathworks, Last Modified: 
     *date Original: 19 Jan 2015, Last Modified:19 Jan 2015 
     *description : BatchableContext Execute method
     */
    global void execute(Database.BatchableContext BC, List<sObject> scope){

        List<Account> acctIds = new List<Account>();

        for(sobject s : scope){
            Account acct = (Account)s;
            acctIds.add(acct);
        }//for

        if (territorySettings.Territory_Assignment_Lookup_Field__c =='Master'){
            TerritoryAssignmentManager.assignAccountsToTerritoryMaster(acctIds); //fg AtTask 1877463 
        }
        else // will be removed after TM golive
        {
            TerritoryAssignmentManager.assignAccountsToTerritory(acctIds);
        }
     //  TerritoryAssignmentManager.assignAccountsToTerritory(acctIds); //fg AtTask 1772050 
       // TerritoryAssignmentManager.assignAccountsToTerritoryMaster(acctIds);// fg 1859101 
       
        
        AccountDML accDml=new AccountDML();
        accDml.assignOpportunitiesByRole(acctIds);

    }//execute

    /**
     *author Original: Archana Lohar - Cloud Sherpas/Mathworks, Last Modified: kishore AN - Cloud Sherpas/Mathworks
     *date Original: 19 Jan 2015, Last Modified:19 Jan 2015 
     *description : SchedulableContext Execute method with the batch size as defined in the Territory Settings custom settings
     */
    global void execute(SchedulableContext ctx){
        //get the batch size from the custom settings and use it to execute the job
        Integer batchSize = territorySettings.TA_Retry_Batch_Size__c.intValue();       
        ID batchprocessid = Database.executeBatch(this,batchSize);
    }//execute   

    /**
     *author Original: Archana Lohar - Cloud Sherpas/Mathworks, Last Modified: 
     *date Original: 19 Jan 2015, Last Modified:19 Jan 2015 
     *description : Finish method*/
    global void finish(Database.BatchableContext BC){
    }//finish

}//RetryTerritoryAssignmentSchedulable class