objects/Account.object
<CustomObject>
    <fields>
        <fullName>Master_Territory_ID__c</fullName>
        <description>Logical unique identifier for a Territory - used as key between systems (Salesforce, CDS, Warehouse, etc.)
Used to lookup Territory2Id for creating assignments to Territory</description>
        <label>Master Territory ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Siebel_Territory_ID__c</fullName>
        <description>Territory ID from external rules engine (Siebel).  Used to lookup the internal Salesforce Territory to assign to the Account.</description>
        <label>Siebel Territory ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Industry__c</fullName>
        <label>Territory Industry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Sales_Group__c</fullName>
        <label>Territory Sales Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Sales_Team_Type__c</fullName>
        <label>Territory Sales Team Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/General_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>General custom setting of the org</description>
    <label>General Settings</label>
</CustomObject>

objects/Get_Feedback__c.object
<CustomObject>
    <description>used to capture survey results from Get Feedback</description>
    <fields>
        <fullName>Service_Case_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service - Case Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Get_Feedback1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Primary_Sales_Rep_email__c</fullName>
        <description>to capture the Primary Sales Rep&apos;s email address for the Account on the associated case.  the address will be used to send an email to the rep on the creation of a Service Survey</description>
        <label>Service - Primary Sales Rep email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Get Feedback</relationshipLabel>
        <relationshipName>Get_Feedback</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Get Feedback</label>
    <nameField>
        <label>Get Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Get Feedback</pluralLabel>
    <recordTypes>
        <fullName>service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Territory2.object
<CustomObject>
    <fields>
        <fullName>Master_Territory_ID__c</fullName>
        <inlineHelpText>Logical unique identifier for a Territory - used as key between systems (Salesforce, CDS, Warehouse, etc.)</inlineHelpText>
        <label>Master Territory ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Siebel_Territory_ID__c</fullName>
        <description>Territory ID from Siebel that will be used as a lookup value from the Account to assign the appropriate Salesforce Territory.</description>
        <label>Siebel Territory ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Industry__c</fullName>
        <label>Territory Industry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AERO</fullName>
                </value>
                <value>
                    <fullName>AUTO</fullName>
                </value>
                <value>
                    <fullName>CES</fullName>
                </value>
                <value>
                    <fullName>CROSS</fullName>
                </value>
                <value>
                    <fullName>EDU</fullName>
                </value>
                <value>
                    <fullName>EP</fullName>
                </value>
                <value>
                    <fullName>FIN</fullName>
                </value>
                <value>
                    <fullName>GOV</fullName>
                </value>
                <value>
                    <fullName>IAM</fullName>
                </value>
                <value>
                    <fullName>MED</fullName>
                </value>
                <value>
                    <fullName>UNKNOWN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory_Sales_Group__c</fullName>
        <label>Territory Sales Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AMER - House</fullName>
                </value>
                <value>
                    <fullName>APAC - House</fullName>
                </value>
                <value>
                    <fullName>EMEA - House</fullName>
                </value>
                <value>
                    <fullName>EMEA Other</fullName>
                </value>
                <value>
                    <fullName>ETMC Exponenta Ltd</fullName>
                </value>
                <value>
                    <fullName>FIGES</fullName>
                </value>
                <value>
                    <fullName>Gamax</fullName>
                </value>
                <value>
                    <fullName>Hoare Research</fullName>
                </value>
                <value>
                    <fullName>Humusoft</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>MathWorks Australia</fullName>
                </value>
                <value>
                    <fullName>MathWorks China</fullName>
                </value>
                <value>
                    <fullName>MathWorks France</fullName>
                </value>
                <value>
                    <fullName>MathWorks Germany</fullName>
                </value>
                <value>
                    <fullName>MathWorks India</fullName>
                </value>
                <value>
                    <fullName>MathWorks Ireland</fullName>
                </value>
                <value>
                    <fullName>MathWorks Italy</fullName>
                </value>
                <value>
                    <fullName>MathWorks Japan</fullName>
                </value>
                <value>
                    <fullName>MathWorks Korea</fullName>
                </value>
                <value>
                    <fullName>MathWorks Natick</fullName>
                </value>
                <value>
                    <fullName>MathWorks Netherlands</fullName>
                </value>
                <value>
                    <fullName>MathWorks Nordic</fullName>
                </value>
                <value>
                    <fullName>MathWorks Spain</fullName>
                </value>
                <value>
                    <fullName>MathWorks Switzerland</fullName>
                </value>
                <value>
                    <fullName>MathWorks UK</fullName>
                </value>
                <value>
                    <fullName>Mentor Hellas</fullName>
                </value>
                <value>
                    <fullName>NA Comm-Aero</fullName>
                </value>
                <value>
                    <fullName>NA Comm-Aero-Geo So Cal</fullName>
                </value>
                <value>
                    <fullName>NA Comm-Auto</fullName>
                </value>
                <value>
                    <fullName>NA Comm-Auto-Geo MI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory_Sales_Team_Type__c</fullName>
        <label>Territory Sales Team Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Blended</fullName>
                </value>
                <value>
                    <fullName>CMA</fullName>
                </value>
                <value>
                    <fullName>EDU</fullName>
                </value>
                <value>
                    <fullName>Geo</fullName>
                </value>
                <value>
                    <fullName>House</fullName>
                </value>
                <value>
                    <fullName>Major</fullName>
                </value>
                <value>
                    <fullName>Mixed</fullName>
                </value>
                <value>
                    <fullName>Named</fullName>
                </value>
                <value>
                    <fullName>NMA</fullName>
                </value>
                <value>
                    <fullName>UNKNOWN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Functional_Role__c</fullName>
        <inlineHelpText>Denotes what role a user plays on a Sales Territory Team.  Used for Oppty assignment and to support collaboration among team members.</inlineHelpText>
        <label>Functional Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inside Sales Rep</fullName>
                </value>
                <value>
                    <fullName>Inside Sales Rep non primary</fullName>
                </value>
                <value>
                    <fullName>National Account Sales Specialist</fullName>
                </value>
                <value>
                    <fullName>Product Overlay Sales Rep</fullName>
                </value>
                <value>
                    <fullName>Sales Development Rep</fullName>
                </value>
                <value>
                    <fullName>Sales Maintenance Rep</fullName>
                </value>
                <value>
                    <fullName>Sales Maintenance Rep non primary</fullName>
                </value>
                <value>
                    <fullName>Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Sales Rep</fullName>
                </value>
                <value>
                    <fullName>Sales Rep Primary</fullName>
                </value>
                <value>
                    <fullName>Sales Specialist</fullName>
                </value>
                <value>
                    <fullName>Sales Support Manager</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Application Engineer</fullName>
                </value>
                <value>
                    <fullName>Pilot Engineer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/GetAccntPrimarySalesRepTest.cls
/**
 *@author Original: Shweta Shanbhag - Mathworks
 *@date Original:9/6/2016
 *@description: Test class for getaccntprimarysalesrep class
 */


@isTest(seeAlldata=true)
public class GetAccntPrimarySalesRepTest {
          
private static testmethod void UpdategetFBsalesrepemail()
{
    CustomSettingsBuilder csb = new CustomSettingsBuilder();
    String SalesRepPrimary=System.Label.FunRole_SalesRepPrimary;
    String SalesManager=System.Label.FunRole_SalesManager;
     List<String> functionalRoleList=new  List<String>{SalesManager,SalesRepPrimary};
    List<User> userWithRoleLst=new List<User>();
    List<userterritory2Association> userAssoObjListToInsert=new List<userterritory2Association>();
    User usr = TestDataBuilder.buildTestUser(100); 
    insert usr;
    
     	csb.buildBypassTriggerSettings();
        csb.buildGenSetting();
        csb.buildTerritorySettings();
        General_Settings__c settings = General_Settings__c.getInstance(UserInfo.getOrganizationId());

     System.runAs(usr){ 
         
         List<Account> accLLst =new List<Account>();
         List<Account> accLLstUpdate =new List<Account>();
         List<Territory2> territory2Lst =new List<Territory2>();
         List<Territory2Model> territory2ModelLst =new List<Territory2Model>();
         List<Get_Feedback__c> GetFbLst = new List<Get_Feedback__c>();
         List<Id> GetFBIdList = new List<ID>();         
         Territory2Model model;
         
 //*************************************Insert Account objects *****************************************//

            for(Integer i=0;i<10;i++){
                Account accL = TestDataBuilder.buildTestAccount(i,UserInfo.getUserId());
                accL.Name = 'Smith' + i;
                accL.Siebel_Territory_ID__c='TestSTI'+i;
                accLLst.add(accL);  
            }
          insert accLLst;
         
  //*************************************Insert Territory2 Object*****************************************//        
         
         
          Territory2Type typeTest=[select id from Territory2Type limit 1];
          territory2ModelLst=[select id,state from Territory2Model where state='Active' limit 1];
    
            if(territory2ModelLst==null || territory2ModelLst.isEmpty()){
                model=TestDataBuilder.buildTestTerritory2Model(0);
                insert model;
            }
         
         for(Integer i=0;i<1;i++){
                Territory2 dummyTerritory2=TestDataBuilder.buildTestTerritory2(i);
                dummyTerritory2.Siebel_Territory_ID__c='1-UIOPYU'+i;
                dummyTerritory2.Territory_Industry__c='UNKNOWN';
                dummyTerritory2.Territory_Sales_Team_Type__c='Mixed';
                dummyTerritory2.Territory_Sales_Group__c='Latin America';
  
                if(territory2ModelLst==null || !territory2ModelLst.isEmpty()){
                    dummyTerritory2.Territory2ModelId=territory2ModelLst[0].id;
                }
                else
                {
                    dummyTerritory2.Territory2ModelId=model.id;
                }
                dummyTerritory2.Territory2TypeId=typeTest.id;
                territory2Lst.add(dummyTerritory2);
            }
            insert territory2Lst;

//*************************************Insert User (Territory team dummy user) Object*****************************************//

            //Insert User Record with functional roles
            for(Integer i=0;i<functionalRoleList.size();i++){
                User usrObj = TestDataBuilder.buildTestUser(i); 
                usrObj.Functional_Role__c=functionalRoleList[i];
                userWithRoleLst.add(usrObj);
            }
            insert userWithRoleLst;

  //*************************************Insert Userterritory2Association Object*****************************************//

            Integer count=2;
            //add users to territory2
            for(Integer i=0;i<1;i++){
      
                for(Integer j=0;j<count;j++){
                    userterritory2Association userAssObj=TestDataBuilder.buildTestUserterritory2Association(userWithRoleLst[j].id,territory2Lst[i].id);
                    userAssoObjListToInsert.add(userAssObj);
                }
                count--;
            }

            insert userAssoObjListToInsert;
            
         
      
       for(Integer i=0;i<10;i++){
                Account acc = acclLst[i];
                acc.Siebel_Territory_ID__c=territory2Lst[0].Siebel_Territory_ID__c;
                acc.Master_Territory_ID__c=territory2Lst[0].Master_Territory_ID__c;

                accLLstUpdate.add(acc);  

            }
          update accLLstUpdate; 
         
         
  //*************************************Insert Case Object*****************************************//       
         
          
              Case caserec = TestDataBuilder.buildTestCase('Open');
              caserec.AccountId = accLLst[0].id;
           	  caserec.OwnerId = usr.Id;
       		  insert caserec;
         
  //*************************************Insert GetFeedback Object*****************************************//   
  		 Id getFBServiceRecTypeId = Schema.SObjectType.Get_Feedback__c.getRecordTypeInfosByName().get('Service').getRecordTypeId();
        
          for(Integer i=0;i<10;i++){
              Get_Feedback__c getFBObj = TestDataBuilder.buildgetfeedback(i);
              getFBObj.RecordTypeId = getFBServiceRecTypeId;
              getFBObj.case__c = caserec.id;
              getFBObj.Service_Primary_Sales_Rep_email__c = '';
              getFBObj.Service_Case_Owner__c = usr.Id;
              GetFbLst.add(getFBObj);    
          }
         
         insert GetFbLst;
         
         for(Get_Feedback__c getFBObj2: GetFbLst )
         {
             GetFBIdList.add(getFBObj2.id);
         }
        
         test.StartTest();
         
         GetAccntPrimarySalesRep.getPrimarySalesRepEmail(GetFBIdList);
         
         Test.stopTest();
         
         List<Get_Feedback__c> GetFBUpdLst = [Select id, Service_Primary_Sales_Rep_email__c from  Get_Feedback__c where id in: GetFBIdList];
         for(Integer i=0;i<10;i++){
        
         System.assertNotEquals(GetFBUpdLst[i].Service_Primary_Sales_Rep_email__c, null);
         
         }
     }
    
}
    
}