objects/Account.object
<CustomObject>
    <fields>
        <fullName>Global_Region__c</fullName>
        <label>Global Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Territory_ID__c</fullName>
        <description>Logical unique identifier for a Territory - used as key between systems (Salesforce, CDS, Warehouse, etc.)
Used to lookup Territory2Id for creating assignments to Territory</description>
        <label>Master Territory ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office_Channel__c</fullName>
        <label>Office Channel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office_Group__c</fullName>
        <label>Office Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <label>Office</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Siebel_Territory_ID__c</fullName>
        <description>Territory ID from external rules engine (Siebel).  Used to lookup the internal Salesforce Territory to assign to the Account.</description>
        <label>Siebel Territory ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Industry__c</fullName>
        <label>Territory Industry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Name__c</fullName>
        <description>Internal Salesforce Territory Name.  Populated by looking up the Salesforce Territory Name through the External_Territory_ID__c field.</description>
        <label>Territory Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Sales_Group__c</fullName>
        <label>Territory Sales Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Sales_Team_Type__c</fullName>
        <label>Territory Sales Team Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Territory2.object
<CustomObject>
    <fields>
        <fullName>Global_Region__c</fullName>
        <label>Global Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Master_Territory_ID__c</fullName>
        <inlineHelpText>Logical unique identifier for a Territory - used as key between systems (Salesforce, CDS, Warehouse, etc.)</inlineHelpText>
        <label>Master Territory ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office_Channel__c</fullName>
        <label>Office Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Indirect</fullName>
                </value>
                <value>
                    <fullName>Office</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Office_Group__c</fullName>
        <label>Office Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMER - House</fullName>
                </value>
                <value>
                    <fullName>APAC - House</fullName>
                </value>
                <value>
                    <fullName>APAC Indirect</fullName>
                </value>
                <value>
                    <fullName>EMEA Direct Non Office</fullName>
                </value>
                <value>
                    <fullName>EMEA - House</fullName>
                </value>
                <value>
                    <fullName>EMEA Indirect</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>MathWorks Australia</fullName>
                </value>
                <value>
                    <fullName>MathWorks China</fullName>
                </value>
                <value>
                    <fullName>MathWorks France</fullName>
                </value>
                <value>
                    <fullName>MathWorks Germany</fullName>
                </value>
                <value>
                    <fullName>MathWorks India</fullName>
                </value>
                <value>
                    <fullName>MathWorks Ireland</fullName>
                </value>
                <value>
                    <fullName>MathWorks Italy</fullName>
                </value>
                <value>
                    <fullName>MathWorks Japan</fullName>
                </value>
                <value>
                    <fullName>MathWorks Korea</fullName>
                </value>
                <value>
                    <fullName>MathWorks Natick</fullName>
                </value>
                <value>
                    <fullName>MathWorks Netherlands</fullName>
                </value>
                <value>
                    <fullName>MathWorks Nordic</fullName>
                </value>
                <value>
                    <fullName>MathWorks Spain</fullName>
                </value>
                <value>
                    <fullName>MathWorks Switzerland</fullName>
                </value>
                <value>
                    <fullName>MathWorks UK</fullName>
                </value>
                <value>
                    <fullName>Natick - EMEA (Direct)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <label>Office</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AMER - House</fullName>
                </value>
                <value>
                    <fullName>APAC - House</fullName>
                </value>
                <value>
                    <fullName>China Overlay</fullName>
                </value>
                <value>
                    <fullName>Componentes Electronicas Ltda</fullName>
                </value>
                <value>
                    <fullName>EMEA Direct Non Office</fullName>
                </value>
                <value>
                    <fullName>EMEA - House</fullName>
                </value>
                <value>
                    <fullName>ETMC Exponenta Ltd</fullName>
                </value>
                <value>
                    <fullName>FIGES</fullName>
                </value>
                <value>
                    <fullName>Gamax Laboratory Solutions Kft</fullName>
                </value>
                <value>
                    <fullName>Humusoft</fullName>
                </value>
                <value>
                    <fullName>India Edu-Gov/Overlay</fullName>
                </value>
                <value>
                    <fullName>MathWorks AB (Sweden)</fullName>
                </value>
                <value>
                    <fullName>MathWorks Australia</fullName>
                </value>
                <value>
                    <fullName>MathWorks China</fullName>
                </value>
                <value>
                    <fullName>MathWorks France</fullName>
                </value>
                <value>
                    <fullName>MathWorks Germany</fullName>
                </value>
                <value>
                    <fullName>MathWorks India</fullName>
                </value>
                <value>
                    <fullName>MathWorks Ireland</fullName>
                </value>
                <value>
                    <fullName>MathWorks Italy</fullName>
                </value>
                <value>
                    <fullName>MathWorks Japan</fullName>
                </value>
                <value>
                    <fullName>MathWorks Korea</fullName>
                </value>
                <value>
                    <fullName>MathWorks Natick</fullName>
                </value>
                <value>
                    <fullName>MathWorks Netherlands</fullName>
                </value>
                <value>
                    <fullName>MathWorks Spain</fullName>
                </value>
                <value>
                    <fullName>MathWorks Switzerland</fullName>
                </value>
                <value>
                    <fullName>MathWorks UK</fullName>
                </value>
                <value>
                    <fullName>Mentor Hellas</fullName>
                </value>
                <value>
                    <fullName>MultiOn Comm/Overlay</fullName>
                </value>
                <value>
                    <fullName>MultiOn Distributor</fullName>
                </value>
                <value>
                    <fullName>Natick - AMER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMER</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Siebel_Territory_ID__c</fullName>
        <description>Territory ID from Siebel that will be used as a lookup value from the Account to assign the appropriate Salesforce Territory.</description>
        <label>Siebel Territory ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Industry__c</fullName>
        <label>Territory Industry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AERO</fullName>
                </value>
                <value>
                    <fullName>AUTO</fullName>
                </value>
                <value>
                    <fullName>CES</fullName>
                </value>
                <value>
                    <fullName>CROSS</fullName>
                </value>
                <value>
                    <fullName>EDU</fullName>
                </value>
                <value>
                    <fullName>EP</fullName>
                </value>
                <value>
                    <fullName>FIN</fullName>
                </value>
                <value>
                    <fullName>GOV</fullName>
                </value>
                <value>
                    <fullName>IAM</fullName>
                </value>
                <value>
                    <fullName>MED</fullName>
                </value>
                <value>
                    <fullName>UNKNOWN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory_Sales_Team_Type__c</fullName>
        <label>Territory Sales Team Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Blended</fullName>
                </value>
                <value>
                    <fullName>CMA</fullName>
                </value>
                <value>
                    <fullName>EDU</fullName>
                </value>
                <value>
                    <fullName>Geo</fullName>
                </value>
                <value>
                    <fullName>House</fullName>
                </value>
                <value>
                    <fullName>Major</fullName>
                </value>
                <value>
                    <fullName>Mixed</fullName>
                </value>
                <value>
                    <fullName>Named</fullName>
                </value>
                <value>
                    <fullName>NMA</fullName>
                </value>
                <value>
                    <fullName>UNKNOWN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Functional_Role__c</fullName>
        <inlineHelpText>Denotes what role a user plays on a Sales Territory Team.  Used for Oppty assignment and to support collaboration among team members.</inlineHelpText>
        <label>Functional Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inside Sales Rep</fullName>
                </value>
                <value>
                    <fullName>Inside Sales Rep non primary</fullName>
                </value>
                <value>
                    <fullName>National Account Sales Specialist</fullName>
                </value>
                <value>
                    <fullName>Product Overlay Sales Rep</fullName>
                </value>
                <value>
                    <fullName>Sales Development Rep</fullName>
                </value>
                <value>
                    <fullName>Sales Maintenance Rep</fullName>
                </value>
                <value>
                    <fullName>Sales Maintenance Rep non primary</fullName>
                </value>
                <value>
                    <fullName>Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Sales Rep</fullName>
                </value>
                <value>
                    <fullName>Sales Rep Primary</fullName>
                </value>
                <value>
                    <fullName>Sales Specialist</fullName>
                </value>
                <value>
                    <fullName>Sales Support Manager</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Application Engineer</fullName>
                </value>
                <value>
                    <fullName>Pilot Engineer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/MassReassignOpportunitiesControllerTest.cls
/*
 *    @description: tests the MassReassignOpportunitiesController
 */ 
@isTest(seeAllData=true)/*for Territory2 object*/
public with sharing class MassReassignOpportunitiesControllerTest {

    //re-create custom setting test records when running the test class
    static CustomSettingsBuilder csb = new CustomSettingsBuilder();

    /*
    @ name    testReassign
    @ date    6.August.2014
    @ author  Archana Lohar
    @ param   none.
    @ return  Void. 
    @ description :This method tests assigning opportunity to new user
     */ 
    public static testmethod void testReassignWithTask(){
        
        csb.buildBypassTriggerSettings();
        csb.buildGenSetting();

        //Create dummy User
        User usr = TestDataBuilder.buildTestUser(1);
        usr.Functional_Role__c = 'Sales Manager'; //SS 3/16/2016 Added to exclude the opp auto assignment process on creation
        insert usr;

        System.runAs(usr){   

            //Create Dummy Data
            createDummyDataWithTask(usr); 

            MassReassignOpportunitiesController controller = new MassReassignOpportunitiesController();

            Test.startTest();
            
            System.debug(usr.id+'inserted user id');
            System.debug(UserInfo.getUserId()+'UserInfo.getUserId()');
            
            //Enter Search Criteria
            controller.searchRecord.stageName = 'Discover';
            controller.searchRecord.name = 'testOpty';
            controller.helperRecord.ClosedDate_From__c=System.today();
            controller.helperRecord.ClosedDate_To__c=System.today()+2;
            controller.helperRecord.From__c=System.today();
            controller.helperRecord.To__c=System.today()+1;
            controller.searchRecord.Type = 'testType';
            controller.searchRecord.ownerId = usr.id;
            controller.searchRecordByAccountFields.name = 'TestAccount123';
            controller.searchRecordByAccountFields.Territory_name__c = 'testTerritoryUpdated';
            
            
            controller.refreshOptyListBySearch();

            System.assert(controller.optyList.size()>0);

            controller.optyList[0].selected = true;
            
            //Insert new User to assign
            User usrTest = TestDataBuilder.buildTestUser(2);
            insert usrTest;
            
            
            
            //Assign new user to Opportunity
            controller.helperRecord.Assign_to__c = usrTest.id;
            controller.Assign();
            
        
            //Check whether new user has been assigned to opporunity
            Opportunity optyToTest= [select id,ownerId
                                     from Opportunity 
                                     where ownerid=:usrTest.id limit 1];
            
            System.assert(optyToTest!=null);
            
            Task taskToTest= [select id,ownerId
                                     from Task 
                                     where ownerid=:usrTest.id limit 1];
                                     
            System.assert(taskToTest.ownerid!=UserInfo.getUserId());
            

            Test.stopTest();

        }


    }

    /*
    @ name    createDummyDataWithTask
    @ date    6.August.2014
    @ author  Archana Lohar
    @ param   none.
    @ return  Void. 
    @ description :This method creates Dummy Contact and Dummy Account
     */ 
    private static void createDummyDataWithTask(User usr){

        //Create Dummy Data
        Integer index=0;



        //***********Insert Territory2*****************//
        Territory2Type typeTest=[select id from Territory2Type limit 1];

        Territory2Model territory2Model=[select id,state from Territory2Model where state='Active' limit 1];


        //create Territory record from TestDataBuilder
        Territory2 dummyTerritory2=TestDataBuilder.buildTestTerritory2(index);
        dummyTerritory2.Siebel_Territory_ID__c='1-New'+index;
        dummyTerritory2.Master_Territory_ID__c = 'TM-New' +index;
        dummyTerritory2.DeveloperName='dev1'+index;
        dummyTerritory2.Global_Region__c='International';
        dummyTerritory2.Region__c='omer';
        dummyTerritory2.Office_Group__c='Componentes Electronicas Ltda';
        dummyTerritory2.Office__c='Componentes Electronicas Ltda';
        dummyTerritory2.Office_Channel__c='Indirect';
        dummyTerritory2.Territory_Industry__c='UNKNOWN';
        dummyTerritory2.Territory_Sales_Team_Type__c='Mixed';
        dummyTerritory2.Territory_Sales_Group__c='Latin America';
        dummyTerritory2.Name='testTerritoryUpdated';
        dummyTerritory2.CaseAccessLevel='Edit';


        dummyTerritory2.Territory2ModelId=territory2Model.id;

        dummyTerritory2.Territory2TypeId=typeTest.id;

        insert dummyTerritory2;


        Account accObj = TestDataBuilder.buildTestAccount(index,UserInfo.getUserId());
        accObj.BillingCity ='Rio De Janeiro';
        accObj.BillingCountryCode = 'US';
        accObj.BillingCountry = 'United States';
        accObj.BillingStateCode = 'NY';
        accObj.BillingState = 'New York';
        accObj.CDS_Account_Id__c='c12345';
        accObj.name='TestAccount123';
        accObj.siebel_territory_id__c='1-New'+index;
        accObj.Master_Territory_ID__c = 'TM-New' +index;


        insert accObj;

        Opportunity testOpty = new Opportunity();
        testOpty.StageName = 'Discover';
        testOpty.CloseDate = System.today()+1;
        testOpty.AccountId=accObj.Id;
        testOpty.Name='testOpty';
        testOpty.Type = 'testType';
        testOpty.ownerId = usr.id;
        insert testOpty;
       
        Task taskObj = TestDataBuilder.buildTestTask(UserInfo.getUserId(),'In Progress','TO DO', 'call');
            taskObj.Priority='ASAP';
            taskObj.whatid=testOpty.Id;
            insert taskObj;

    }
    
    /*
    @ name    testReassign
    @ date    6.August.2014
    @ author  Archana Lohar
    @ param   none.
    @ return  Void. 
    @ description :This method tests assigning opportunity to new user
     */ 
    public static testmethod void testReassignWithActivity(){
        
        csb.buildBypassTriggerSettings();
        csb.buildGenSetting();

        //Create dummy User
        User usr = TestDataBuilder.buildTestUser(1);
        insert usr;

        System.runAs(usr){   

            Test.startTest();
            
            //Create Dummy Data
            createDummyDataWithActivity(usr); 

            MassReassignOpportunitiesController controller = new MassReassignOpportunitiesController();

           
            
            //Enter Search Criteria
            controller.searchRecord.stageName = 'Discover';
            controller.searchRecord.name = 'testOpty1';
            controller.helperRecord.ClosedDate_From__c=System.today();
            controller.helperRecord.ClosedDate_To__c=System.today()+2;
            controller.helperRecord.From__c=System.today();
            controller.helperRecord.To__c=System.today()+1;
            controller.searchRecord.Type = 'testType1';
            //controller.searchRecord.ownerId = usr.id;
            controller.searchRecordByAccountFields.name = 'TestAccount123';
            controller.searchRecordByAccountFields.territory_name__c= 'testTerritoryUpdated';
            
            
            controller.refreshOptyListBySearch();

            System.assert(controller.optyList.size()>0);

            controller.optyList[0].selected = true;
            
            //Insert new User to assign
            User usrTest = TestDataBuilder.buildTestUser(2);
            insert usrTest;
            
            
            
            //Assign new user to Opportunity
            controller.helperRecord.Assign_to__c = usrTest.id;
            controller.Assign();
            
        
            //Check whether new user has been assigned to opporunity
            Opportunity optyToTest= [select id,ownerId
                                     from Opportunity 
                                     where ownerid=:usrTest.id limit 1];
            
            System.assert(optyToTest!=null);
            
            List<Event> eventToTest= [select id,ownerId
                                     from Event 
                                     where ownerid=:usrTest.id limit 1];
                                     
          
            System.assert(eventToTest!=null);

            Test.stopTest();

        }


    }


/*
    @ name    createDummyDataWithActivity
    @ date    12.December.2014
    @ author  Archana Lohar
    @ param   none.
    @ return  Void. 
    @ description :This method creates Dummy Contact and Dummy Account
     */ 
    private static void createDummyDataWithActivity(User usr){

        //Create Dummy Data
        Integer index=0;



        //***********Insert Territory2*****************//
        Territory2Type typeTest=[select id from Territory2Type limit 1];

        Territory2Model territory2Model=[select id,state from Territory2Model where state='Active' limit 1];


        //create Territory record from TestDataBuilder
        Territory2 dummyTerritory2=TestDataBuilder.buildTestTerritory2(index);
        dummyTerritory2.Siebel_Territory_ID__c='1-New'+index;
        dummyTerritory2.Master_Territory_ID__c = 'TM-New' +index;
        dummyTerritory2.DeveloperName='dev1'+index;
        dummyTerritory2.Global_Region__c='International';
        dummyTerritory2.Region__c='omer';
        dummyTerritory2.Office_Group__c='Componentes Electronicas Ltda';
        dummyTerritory2.Office__c='Componentes Electronicas Ltda';
        dummyTerritory2.Office_Channel__c='Indirect';
        dummyTerritory2.Territory_Industry__c='UNKNOWN';
        dummyTerritory2.Territory_Sales_Team_Type__c='Mixed';
        dummyTerritory2.Territory_Sales_Group__c='Latin America';
        dummyTerritory2.Name='testTerritoryUpdated';
        dummyTerritory2.CaseAccessLevel='Edit';


        dummyTerritory2.Territory2ModelId=territory2Model.id;

        dummyTerritory2.Territory2TypeId=typeTest.id;

        insert dummyTerritory2;


        Account accObj = TestDataBuilder.buildTestAccount(index,UserInfo.getUserId());
        accObj.BillingCity ='Rio De Janeiro';
        accObj.BillingCountryCode = 'US';
        accObj.BillingCountry = 'United States';
        accObj.BillingStateCode = 'NY';
        accObj.BillingState = 'New York';
        accObj.CDS_Account_Id__c='c12345';
        accObj.name='TestAccount123111';
        accObj.siebel_territory_id__c='1-New'+index;
        accObj.Master_Territory_ID__c = 'TM-New' +index;


        insert accObj;
        
        List<Account> newAccount = new List<Account>([SELECT Id, Territory_Name__c FROM Account WHERE Id =: accObj.Id]);
        
        System.assertEquals('testTerritoryUpdated', newAccount[0].Territory_Name__c);
        
        Opportunity testOpty = new Opportunity();
        testOpty.StageName = 'Discover';
        testOpty.CloseDate = System.today()+1;
        testOpty.AccountId=accObj.Id;
        testOpty.Name='testOpty1';
        testOpty.Type = 'testType1';
        testOpty.ownerId = UserInfo.getUserId();
        insert testOpty;
       
        Event eventObj = TestDataBuilder.buildTestEvent(UserInfo.getUserId(),'call');
        eventObj.whatid=testOpty.Id;
        insert eventObj;
       
    }     


}