objects/Allowed_Domains__c.object
<CustomObject>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Allowed Domains</relationshipLabel>
        <relationshipName>Allowed_Domains</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Allowed Domain</label>
    <nameField>
        <label>Allowed Domain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allowed Domains</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Course_Code__c</fullName>
        <label>Part Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <label>Max Seats</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sponsor_Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sponsor Office</label>
        <referenceTo>Sponsor_Office__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <description>Contact Preferred Language</description>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Swedish</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Portuguese</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Course_Code__c</fullName>
        <label>Part Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <recordTypes>
        <fullName>Training</fullName>
        <active>true</active>
        <description>Record type to create non certification course</description>
        <label>Training</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Enrollee_Blacklist__c.object
<CustomObject>
    <description>Holds the email address that should be denied access to enrollments.</description>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Enrollee Blacklist</relationshipLabel>
        <relationshipName>Enrollee_Blacklist</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Enrollee Blacklist</label>
    <nameField>
        <displayFormat>EBL-{0000}</displayFormat>
        <label>Enrollee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollee Blacklist</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Enrollment_Code__c.object
<CustomObject>
    <description>This object represents the code associated with an Enterprise Training Agreement and holds the status the enrollment code is in.</description>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <description>Enterprise Training Agreement the Enrollment Code is associated with.</description>
        <inlineHelpText>Enterprise Training Agreement the Enrollment Code is associated with.</inlineHelpText>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Enrollment Codes</relationshipLabel>
        <relationshipName>Enrollment_Codes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Enrollment Code</label>
    <nameField>
        <displayFormat>EC-{0000}</displayFormat>
        <label>Enrollment Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Enrollment_Request__c.object
<CustomObject>
    <description>Staging object to ingest requests for class enrollment under Enterprise Training Agreements from multiple sources including manual internal enrollments, self-enrollments via a portal and bulk enrollments via a file load. Records that are processed through this object will ultimately result in records being created in the Enrollment object.</description>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>Not a direct lookup to Course object so requests can be made via the Code rather than requiring the Salesforce ID of the Course</description>
        <inlineHelpText>Code used to identify the Course the Enrollment Code is being made for - this code plus the Language and Format will identify the specific Class to enroll in</inlineHelpText>
        <label>Course Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Training agreement the Enrollment should be created under</inlineHelpText>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Enrollment Requests</relationshipLabel>
        <relationshipName>Enrollment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Language_Code__c</fullName>
        <inlineHelpText>ISO Code of the Language the Enrollment Request is for - used to identify the correct Class when combined with the Course Code and Format</inlineHelpText>
        <label>Language Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Enrollment Request</label>
    <nameField>
        <displayFormat>ER-{0}</displayFormat>
        <label>Enrollment Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Enterprise_Training_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Language to display content in on self-enrollment portal</inlineHelpText>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Enterprise Training Agreements</relationshipLabel>
        <relationshipName>Enterprise_Training_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <label>Max Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sponsor_Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sponsor Office</label>
        <referenceTo>Sponsor_Office__c</referenceTo>
        <relationshipLabel>Enterprise Training Agreements</relationshipLabel>
        <relationshipName>Enterprise_Training_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Term_End_Date__c</fullName>
        <description>Agreement expiration date</description>
        <label>Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Term_Start_Date__c</fullName>
        <description>The date the agreement becomes effective</description>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <label>Enterprise Training Agreement</label>
    <nameField>
        <label>Enterprise Training Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enterprise Training Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Language__c.object
<CustomObject>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <label>ISO Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language_Code__c</fullName>
        <label>Language Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language_Display_Name__c</fullName>
        <inlineHelpText>Name that should be displayed to external users when viewing the Language of a Course/Class</inlineHelpText>
        <label>Language Display Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_ISO_Code__c</fullName>
        <description>The universal ISO language code.</description>
        <inlineHelpText>The universal ISO language code.</inlineHelpText>
        <label>Salesforce ISO Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Language</label>
    <nameField>
        <label>Language</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Language_Display_Name__c.object
<CustomObject>
    <description>Contains the display names</description>
    <fields>
        <fullName>Display_Name__c</fullName>
        <label>Display Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Language Display Names</relationshipLabel>
        <relationshipName>Language_Display_Names</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Language_code__c</fullName>
        <label>Language_code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Language Display Name</label>
    <nameField>
        <label>Language Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Language Display Names</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sponsor_Office__c.object
<CustomObject>
    <fields>
        <fullName>Display_Name__c</fullName>
        <label>Display Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FAQ_Link__c</fullName>
        <label>FAQ Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>MATLAB_Academy_URL__c</fullName>
        <label>MATLAB Academy URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Training_URL__c</fullName>
        <label>Training URL</label>
        <type>Url</type>
    </fields>
    <label>Sponsor Office</label>
    <nameField>
        <label>Sponsor Office</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sponsor Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Training_Agreement_Class_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Training_Agreement_Class_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Agreement Class Relationship</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Training Agreement Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Agreement Class Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EnrollmentConfirmationControllerTest.cls
/** 
 *@author Original: Sagar Talele - Accenture/Mathworks, Last Modified: 
 *@date Original: 18 May 2016, Last Modified: 18 May 2016
 *@description This  is handler class for 'EnrollmentConfirmationController' . 
 */ 

@isTest
private class EnrollmentConfirmationControllerTest{
    //re-create custom setting test records when running the test class
    static CustomSettingsBuilder custsettbuild = new CustomSettingsBuilder();
    static CTrainingCustomSettingBuilder cTrainSettingBuilder = new CTrainingCustomSettingBuilder();
    
    private static final Integer ETAREEMENT_COUNT = 10;
    private static final Integer ENROLLMENT_CODE_COUNT = 10;
    private static final Integer CLASS_COUNT = 10;
    private static final Integer LANG_COUNT = 2;
    private static final Integer ENROL_COUNT = 2;
    private static final Integer COURSE_COUNT = 10;
    private static final Integer ETAREL_COUNT = 10;
    private static final Integer ALLOWED_DOMAIN_COUNT = 2;
    private static final Integer ENROL_REQ_COUNT = 10;
    private static final Integer CONTACT_COUNT = 10;
    private static User usr {get;set;}
    /**
    * @author Original: Sagar Talele
    * @date Original:18 May 2016 , Last Modified: 18 May 2016
    * @description Method that create the setup test data.
    * @param : 
    */
    static void setUpData(){
        // private static User usr {get;set;}
        usr = TestDataBuilder.buildTestUser(1);
        insert usr;
        
        System.RunAs(usr){
        
            //Inserting Bypass trigger custom setting
            custsettbuild.buildBypassTriggerSettings();
            //re-create the Enrollment Code Configuration Setting
            cTrainSettingBuilder.buildEnrollmentCodeConfiguration();
            
             List<Language__c> langLst = new List<Language__c>();
            
            //create Language__c record from CTrainingTestDataBuilder.
            for(Integer i=0; i<LANG_COUNT; i++){
                Language__c langObj = CTrainingTestDataBuilder.buildTestLanguage(i);
                langObj.SF_ISO_Code__c = (i==0 ? 'en_US' : 'ja');
                langObj.Language_Code__c=(i==0 ? 'en' : 'ja');
                langObj.ISO_Code__c =(i==0 ? 'en' : 'ja');
                langLst.add(langObj);
            }
            insert langLst;
            
            //Create display language test data
            List<Language_Display_Name__c> dispLangLst = new List<Language_Display_Name__c>();
            
            Language_Display_Name__c dispLangObj = new Language_Display_Name__c();
            dispLangObj.Name = 'en';
            dispLangObj.Language__c = langLst[0].Id;
            dispLangObj.Display_name__c = 'English';
            dispLangObj.language_Code__c = 'en';
            
            dispLangLst.add(dispLangObj);
            
            Language_Display_Name__c dispLangObj1 = new Language_Display_Name__c();
            dispLangObj1.Name = 'ja';
            dispLangObj1.Language__c = langLst[0].id;
            dispLangObj1.Display_name__c = 'Japanese';
            dispLangObj1.language_Code__c = 'ja';
            
            dispLangLst.add(dispLangObj1); 
            
            insert dispLangLst;
            
           //test data list of sponsor office
            List<Sponsor_Office__c > sponsorOffList = new List<Sponsor_Office__c >();
            for(Integer j=0;j<ETAREEMENT_COUNT;j++ ){
                Sponsor_Office__c sponsor = CTrainingTestDataBuilder.buildTestSponsorOffice(j,langLst[0].Id);
                sponsor.Training_URL__c = 'traning@testUrl.com';
                sponsor.MATLAB_Academy_URL__c= 'matlabAcademy@testUrl.com';
                sponsor.FAQ_Link__c = 'faqPageUrl@linkTest.com';
                sponsorOffList.add(sponsor);    
               
            }
            insert sponsorOffList;
            
            //Creating the Enterprise_Training_Agreement__c test data.
            List<Enterprise_Training_Agreement__c> ETagreeemntLst = new List<Enterprise_Training_Agreement__c>();
            for(Integer i=0;i<ETAREEMENT_COUNT;i++){
                //Create Test Data for Enterprise Training Agreement
                Enterprise_Training_Agreement__c eTAgreementObj = CTrainingTestDataBuilder.buildTestETAgreement(i);
                Id etraAgrerecTypeId = Schema.SObjectType.Enterprise_Training_Agreement__c.getRecordTypeInfosByName().get('Seat-Based').getRecordTypeId();
                ETAgreementObj.recordTypeId = etraAgrerecTypeId;
                ETAgreementObj.Max_Seats__c = 1;
                ETAgreementObj.Term_Start_Date__c = Date.Today().addDays(-2);
                ETAgreementObj.Term_End_Date__c = Date.Today().addDays(-1);
                ETAgreementObj.Sponsor_Office__c = sponsorOffList[i].Id;
                ETAgreementObj.Language__c = langLst[0].Id;
                ETagreeemntLst.add(ETAgreementObj);
            }
            insert ETagreeemntLst;
            
            //Creating the Course__c test data.
            Id courserecTypeId = Schema.SObjectType.Course__c.getRecordTypeInfosByName().get('Training').getRecordTypeId();
            List<Course__c> courseLst = new List<Course__c>();
            for(Integer i=0; i<COURSE_COUNT; i++){
                Course__c courseObj = CTrainingTestDataBuilder.buildTestCourse(i);
                courseObj.recordTypeId = courserecTypeId;
                courseObj.Course_Code__c = 'TESTCODE'+i;
                courseLst.add(courseObj);
            }
            insert courseLst;
            
            //Creating the Course__c to test Class Not Part of Training Agreement  Exception Reason.
            //Id courserecTypeId = Schema.SObjectType.Course__c.getRecordTypeInfosByName().get('Self-Paced').getRecordTypeId();
            List<Course__c> courseLst1 = new List<Course__c>();
            for(Integer i=0; i<COURSE_COUNT; i++){
                Course__c courseObj = CTrainingTestDataBuilder.buildTestCourse(i);
                courseObj.recordTypeId = courserecTypeId;
                courseObj.Course_Code__c = 'TEST'+i;
                courseLst1.add(courseObj);
            }
            insert courseLst1;
            
            //Creating the Class__c test data.
            List<Class__c> clssLst = new List<Class__c>();    
            Id classrecTypeId = Schema.SObjectType.Class__c.getRecordTypeInfosByName().get('Self-Paced').getRecordTypeId();    
            //Creating the test data for Class Object. 
            for(Integer i=0;i<CLASS_COUNT;i++){            
                Class__c clssObj = CTrainingTestDataBuilder.buildTestClass(i, courseLst[i].Id, langLst[0].Id);
                clssObj.Max_Seats__c  = 500;
                clssObj.recordTypeId = classrecTypeId;
                clssObj.Status__c='Active';
                clssLst.add(clssObj);
            }
            insert clssLst;
            
            //Creating the Class__c to test Class Not Part of Training Agreement  Exception Reason.
            List<Class__c> clssLst1 = new List<Class__c>();    
            //Id classrecTypeId = Schema.SObjectType.Class__c.getRecordTypeInfosByName().get('Self-Paced').getRecordTypeId();    
            //Creating the test data for Class Object. 
            for(Integer i=0;i<CLASS_COUNT;i++){            
                Class__c clssObj = CTrainingTestDataBuilder.buildTestClass(i, courseLst1[i].Id, langLst[0].Id);
                clssObj.Max_Seats__c  = 500;
                clssObj.recordTypeId = classrecTypeId;
                clssLst1.add(clssObj);
            }
            insert clssLst1;
            
            //Creating the Training_Agreement_Class_Relationship__c test data.
            List<Enterprise_Training_Agreement__c> etaLst = [SELECT Id, Is_Active__c FROM Enterprise_Training_Agreement__c];
            List<Training_Agreement_Class_Relationship__c> TACRelLst = new List<Training_Agreement_Class_Relationship__c>(); 
            for(Integer i=0;i<ETAREL_COUNT;i++){
                Training_Agreement_Class_Relationship__c TACRelObj;
                TACRelObj = CTrainingTestDataBuilder.buildTestTAClassRelationship(clssLst[i].Id, ETagreeemntLst[i].Id);
                TACRelLst.add(TACRelObj);
            }
            insert TACRelLst;  
            
            
            Account acc = TestDataBuilder.buildTestAccount(1, usr.Id);
            insert acc;
                    
            List<Contact> conList = new List<Contact>();
            for(Integer i=0; i<CONTACT_COUNT; i++){  
                Contact con = TestDataBuilder.buildTestContact(i, usr.Id, acc.Id); 
                con.email = 'test'+i+'@test.com';
                conList.add(con);
            }
            insert conList;
             
            System.debug('Con Obj List ## ' +conList);
            List<Enrollee_Blacklist__c> enroleeBlackLst = new List<Enrollee_Blacklist__c>();
            //Create test data for Enrollee BlackList
            for(Enterprise_Training_Agreement__c etaObj : ETagreeemntLst){
                Enrollee_Blacklist__c eBlackLstObj = new Enrollee_Blacklist__c();
                eBlackLstObj.Email__c = 'dummyEmail@testmail.com';
                eBlackLstObj.Enterprise_Training_Agreement__c = etaObj.Id;
                eBlackLstObj.Notes__c = 'Test Notes';
                enroleeBlackLst.add(eBlackLstObj);
            }
            insert enroleeBlackLst;
            
            List<Allowed_Domains__c> allowedDomainsLst = new List<Allowed_Domains__c>();
            //Create Test data for the Allowed_Domains__c  Object.
            for(Enterprise_Training_Agreement__c etaObj : ETagreeemntLst){ 
                Allowed_Domains__c allowedDomainsObj = new Allowed_Domains__c();
                    
                allowedDomainsObj.Enterprise_Training_Agreement__c = etaObj.Id;
                allowedDomainsObj.Name = usr.Email.substringAfter('@');
                allowedDomainsLst.add(allowedDomainsObj);    
            }
            insert allowedDomainsLst; 
            
            //Disable the EnrollmentCode Trigger to create bulk code.
            Bypass_Triggers__c bypassTriggerObj = [SELECT Trigger_Objects__c, Triggers_Disabled__c FROM Bypass_Triggers__c];
            bypassTriggerObj.Triggers_Disabled__c = True;
            bypassTriggerObj.Trigger_Objects__c = 'EnrollmentCode';
            update bypassTriggerObj;            
            
            List<Enrollment_Code__c> enrolCodeLst = new List<Enrollment_Code__c>();
            //Create Test Data for Enrollment Code
            for(Integer i=0; i<ENROLLMENT_CODE_COUNT; i++){
                Enrollment_Code__c enrolCode = CTrainingTestDataBuilder.buildTestEnrollmentCode(ETagreeemntLst[i].Id);
                enrolCode.Status__c = 'Revoked';
                enrolCode.Code__c = String.valueOf(i);
                enrolCodeLst.add(enrolCode);
            }
            insert enrolCodeLst;
            
            List<Enrollment_Request__c> enrollReqList = new List<Enrollment_Request__c>();
            for(Integer i=0; i<ENROLLMENT_CODE_COUNT; i++){
                Enrollment_Request__c enrollObj = new Enrollment_Request__c();
                enrollObj.Class__c = TACRelLst[i].Class__c;
                enrollObj.Contact__c = conList[i].Id;
                enrollObj.Email__c = conList[i].Email;
                enrollObj.Enterprise_Training_Agreement__c = TACRelLst[i].Enterprise_Training_Agreement__c ;
                enrollReqList.add(enrollObj);
            }
            insert enrollReqList;
            
            
            
        }//End of Run As
    }//End of Method
    
     /**
     * @author Original: Saagr Talele 
     * @date Original:18 May 2016 , Last Modified: 18 May 2016
     * @description Method to test controller method EnrollName
     * @param : 
     */
    
    private static testMethod void EnrollNameTest(){
        EnrollmentConfirmationControllerTest.setUpData();
        Enrollment_Request__c enrollrequest = [Select Id,Class__c,Class__r.Course__r.Name,Email__c,Enterprise_Training_Agreement__c,Contact__c,Batch_ID__c
                                             From Enrollment_Request__c limit 1];
       
        
        System.RunAs(usr){
        System.assertEquals(enrollrequest!= null,true);
        EnrollmentConfirmationController controller = new EnrollmentConfirmationController();
        controller.enrollReqId = enrollrequest.Id;
        String enrolleName = controller.getEnrollName();
        System.assertEquals(enrolleName!= null,true);
        controller.lang = 'ja';//'en_US';
        String lang = controller.language;
         
           
        }
        
    }
    
         /**
     * @author Original: Shweta Shanbhag 
     * @date Original:August 2 2016 , Last Modified: August 2 2016
     * @description Method to test controller method EnrollName for ETA with Japanese language
     * @param : 
     */
    
    private static testMethod void EnrollNameTest_JP(){
        EnrollmentConfirmationControllerTest.setUpData();
        Enrollment_Request__c enrollrequest = [Select Id,Class__c,Class__r.Course__r.Name,Email__c,Enterprise_Training_Agreement__c,Contact__c,
                                               Batch_ID__c,Enterprise_Training_Agreement__r.Language__r.SF_ISO_Code__c,
                                               Contact__r.LastName, Contact__r.FirstName
                                             From Enrollment_Request__c limit 1];
       
        Enterprise_Training_Agreement__c etagreement = [Select Id, Language__c, Name from Enterprise_Training_Agreement__c where Id =:enrollrequest.Enterprise_Training_Agreement__c ];
       
        Language__c langdata = [Select Id from Language__c where Language_Code__c=: 'ja' ];
        
        
        etagreement.Language__c = langdata.Id;
       
        update etagreement;
        String EnrolleNamefromContact = enrollrequest.contact__r.LastName + ' '+enrollrequest.contact__r.FirstName;
        
        System.RunAs(usr){
        System.assertEquals(enrollrequest!= null,true);
        EnrollmentConfirmationController controller = new EnrollmentConfirmationController();
        controller.enrollReqId = enrollrequest.Id;
        String enrolleName = controller.getEnrollName();
        System.assertEquals(enrolleName, EnrolleNamefromContact);
            
        controller.lang = 'xx';
        String lang = controller.language;

        }
        
    }
    /**
     * @author Original: Saagr Talele 
     * @date Original:18 May 2016 , Last Modified: August 2 2016
     * @description Method to test RealatedEtaCourses controller method
     * @param : 
     */
    
    private static testMethod void RelatedEtaCoursesTest(){
        EnrollmentConfirmationControllerTest.setUpData();
        List<Training_Agreement_Class_Relationship__c> TACRelLst = new List<Training_Agreement_Class_Relationship__c>(); 
       Enrollment_Request__c enrollrequest = [Select Id,Class__c,Class__r.Course__r.Name,Email__c,Enterprise_Training_Agreement__c,Contact__c,Batch_ID__c
                                             From Enrollment_Request__c  limit 1];
        enrollrequest.Status__c = 'Pending Notification';
        update enrollrequest;
        
       system.assertEquals(enrollrequest != null,true);                                    
       TACRelLst = [Select id,Class__c,Enterprise_Training_Agreement__c 
                            From Training_Agreement_Class_Relationship__c limit 1 ];

        system.assertEquals(TACRelLst != null,true);
     
        EnrollmentConfirmationController controller = new EnrollmentConfirmationController();
        controller.enrollReq= enrollrequest;
        controller.enrollReqId = enrollrequest.Id;
        String enrolleName = controller.getEnrollName();
        String etaCourse = controller.getRelatedEtaCourses();
     
        controller.lang = null;
        String lang = controller.language;
    }
    
    /**
     * @author Original: Shweta Shanbhag
     * @date Original:August 2 2016 , Last Modified: August 2 2016
     * @description Method to test RealatedEtaCourses controller method when the lang record does not exist on language display object
     * @param : 
     */
     private static testMethod void RelatedEtaCoursesTest_DefaultLang(){
        EnrollmentConfirmationControllerTest.setUpData();
        List<Training_Agreement_Class_Relationship__c> TACRelLst = new List<Training_Agreement_Class_Relationship__c>(); 
       Enrollment_Request__c enrollrequest = [Select Id,Class__c,Class__r.Course__r.Name,Email__c,Enterprise_Training_Agreement__c,Contact__c,Batch_ID__c
                                             From Enrollment_Request__c  limit 1];
        enrollrequest.Status__c = 'Pending Notification';
        update enrollrequest;
         
        Enterprise_Training_Agreement__c etagreement = [Select Id, Language__c, Name from Enterprise_Training_Agreement__c where Id =:enrollrequest.Enterprise_Training_Agreement__c ];
       
        Language__c langdata = [Select Id,Language_Code__c, SF_ISO_Code__c, ISO_Code__c from Language__c where Language_Code__c=: 'ja' ];
        
         langdata.SF_ISO_Code__c = 'nl';
        langdata.ISO_Code__c = 'nl';
        langdata.Language_Code__c = 'nl';
         
        update langdata;
        
        etagreement.Language__c = langdata.Id;
       
        update etagreement;
        
       system.assertEquals(enrollrequest != null,true);                                    
       TACRelLst = [Select id,Class__c,Enterprise_Training_Agreement__c 
                            From Training_Agreement_Class_Relationship__c limit 1 ];

        system.assertEquals(TACRelLst != null,true);
     
        EnrollmentConfirmationController controller = new EnrollmentConfirmationController();
        controller.enrollReq= enrollrequest;
        controller.enrollReqId = enrollrequest.Id;
        String etaCourse = controller.getRelatedEtaCourses();
     
    }
    /**
     * @author Original: Saagr Talele 
     * @date Original:18 May 2016 , Last Modified: 18 May 2016
     * @description Method to test termEndDate controller method
     * @param : 
     */
    
    private static testMethod void termEndDateTest(){
        EnrollmentConfirmationControllerTest.setUpData();
        List<Training_Agreement_Class_Relationship__c> TACRelLst = new List<Training_Agreement_Class_Relationship__c>(); 
        Enrollment_Request__c enrollrequest = [Select Id,Class__c, Contact__c,Email__c,Enterprise_Training_Agreement__c,Enterprise_Training_Agreement__r.Term_End_Date__c
                                             From Enrollment_Request__c limit 1];
        enrollrequest.Status__c = 'Pending Notification';
        update enrollrequest;
        
        TACRelLst = [Select id,Class__c,Enterprise_Training_Agreement__c 
                            From Training_Agreement_Class_Relationship__c limit 1 ];
        //System.assertEquals(enrollrequest!= null,true);
        system.assertEquals(TACRelLst != null,true);
        // System.RunAs(usr){
        EnrollmentConfirmationController controller = new EnrollmentConfirmationController();
        controller.enrollReq= enrollrequest;
        String termEndDate = controller.gettermEndDate();
        System.assertEquals(termEndDate!= null,true);
        //}
        
    }
    /**
     * @author Original: Saagr Talele 
     * @date Original:2 June 2016 , Last Modified: 2 June 2016
     * @description Method to test getTrainingUrl controller method
     * @param : 
     */
    private static testMethod void TrainingUrlTest(){
         EnrollmentConfirmationControllerTest.setUpData();
          List<Training_Agreement_Class_Relationship__c> TACRelLst = new List<Training_Agreement_Class_Relationship__c>(); 
        Enrollment_Request__c enrollrequest = [Select Id,Class__c,Email__c,Enterprise_Training_Agreement__r.Sponsor_Office__r.Training_URL__c,Enterprise_Training_Agreement__c,Enterprise_Training_Agreement__r.Term_End_Date__c
                                             From Enrollment_Request__c limit 1];
        TACRelLst = [Select id,Class__c,Enterprise_Training_Agreement__c 
                            From Training_Agreement_Class_Relationship__c limit 1 ];
        //System.assertEquals(enrollrequest!= null,true);
        system.assertEquals(TACRelLst != null,true);
        
        EnrollmentConfirmationController controller = new EnrollmentConfirmationController();
        controller.enrollReq= enrollrequest;
        String trainingUrl = controller.getTrainingUrl();
        System.assertEquals(trainingUrl != null,true);
        enrollrequest.Enterprise_Training_Agreement__r.Sponsor_Office__r.Training_URL__c = '';
        update enrollrequest;
        EnrollmentConfirmationController controllerObj = new EnrollmentConfirmationController();
        controllerObj.enrollReq= enrollrequest;
        String trainingUrlSetting = controllerObj.getTrainingUrl();
        System.assertEquals(trainingUrlSetting != null,true);
        
    }
    /**
     * @author Original: Saagr Talele 
     * @date Original:10 June 2016 , Last Modified: 10 June 2016
     * @description Method to test getMatlabAcademyUrl controller method
     * @param : 
     */
    private static testMethod void MatlabAcademyUrlTest(){
         EnrollmentConfirmationControllerTest.setUpData();
          List<Training_Agreement_Class_Relationship__c> TACRelLst = new List<Training_Agreement_Class_Relationship__c>(); 
        Enrollment_Request__c enrollrequest = [Select Id,Class__c,Email__c,
                                                        Enterprise_Training_Agreement__r.Sponsor_Office__r.Training_URL__c,
                                                        Enterprise_Training_Agreement__c,
                                                        Enterprise_Training_Agreement__r.Term_End_Date__c,
                                                        Enterprise_Training_Agreement__r.Sponsor_Office__r.MATLAB_Academy_URL__c
                                             From Enrollment_Request__c limit 1];
        TACRelLst = [Select id,Class__c,Enterprise_Training_Agreement__c 
                            From Training_Agreement_Class_Relationship__c limit 1 ];
        //System.assertEquals(enrollrequest!= null,true);
        system.assertEquals(TACRelLst != null,true);
        
        EnrollmentConfirmationController controller = new EnrollmentConfirmationController();
        controller.enrollReq= enrollrequest;
        String trainingUrl = controller.getMatlabAcademyUrl();
        System.assertEquals(trainingUrl != null,true);
        enrollrequest.Enterprise_Training_Agreement__r.Sponsor_Office__r.MATLAB_Academy_URL__c = '';
        update enrollrequest;
        EnrollmentConfirmationController controllerObj = new EnrollmentConfirmationController();
        controllerObj.enrollReq= enrollrequest;
        String trainingUrlSetting = controllerObj.getMatlabAcademyUrl();
        System.assertEquals(trainingUrlSetting != null,true);
        
    }
    /**
     * @author Original: Saagr Talele 
     * @date Original:20 July 2016 , Last Modified: 20 July 2016
     * @description Method to test getFAQPageUrl controller method
     * @param : 
     */
    private static testMethod void FAQPageUrlTest(){
        EnrollmentConfirmationControllerTest.setUpData();
        Enrollment_Request__c enrollrequest = [Select Id,Class__c,Email__c,
                                                        Enterprise_Training_Agreement__r.Sponsor_Office__r.Training_URL__c,
                                                        Enterprise_Training_Agreement__c,
                                                        Enterprise_Training_Agreement__r.Term_End_Date__c,
                                                        Enterprise_Training_Agreement__r.Sponsor_Office__r.FAQ_Link__c
                                             From Enrollment_Request__c limit 1];
        
        EnrollmentConfirmationController controller = new EnrollmentConfirmationController();
        controller.enrollReq= enrollrequest;
        String faqUrl = controller.getFAQPageUrl();
        System.assertEquals(faqUrl != null,true);
        enrollrequest.Enterprise_Training_Agreement__r.Sponsor_Office__r.FAQ_Link__c = '';
        update enrollrequest;
        EnrollmentConfirmationController controllerObj = new EnrollmentConfirmationController();
        controllerObj.enrollReq= enrollrequest;
        String faqUrlSetting = controllerObj.getFAQPageUrl();
        System.assertEquals(faqUrlSetting != null,true);
    }
}