objects/Allowed_Domains__c.object
<CustomObject>
    <fields>
        <fullName>Allow_Sub_Domain__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field decides whether sub Doamin is allowed or not or particular Enterprise Training Agreements</description>
        <inlineHelpText>When checked, also matches on any sub-domain of the value entered (e.g.: students.university.edu will be allowed when university.edu is the allowed domain) Do not check if explicit sub-domains are required; add them as allowed domains individually.</inlineHelpText>
        <label>Allow Sub Domain</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Allowed Domains</relationshipLabel>
        <relationshipName>Allowed_Domains</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Allowed Domain</label>
    <nameField>
        <label>Allowed Domain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allowed Domains</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <label>Max Seats</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Mark for Deletion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <default>true</default>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <recordTypes>
        <fullName>Training</fullName>
        <active>true</active>
        <description>Record type to create non certification course</description>
        <label>Training</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Enrollee_Blacklist__c.object
<CustomObject>
    <description>Holds the email address that should be denied access to enrollments.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Enrollee Blacklist</relationshipLabel>
        <relationshipName>Enrollee_Blacklist</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Enrollee Blacklist</label>
    <nameField>
        <displayFormat>EBL-{0000}</displayFormat>
        <label>Enrollee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollee Blacklist</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Enrollment__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <formula>Enrollee_Name__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enrollment_Code__c</fullName>
        <label>Enrollment Code</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Enrollment_Code__c.object
<CustomObject>
    <description>This object represents the code associated with an Enterprise Training Agreement and holds the status the enrollment code is in.</description>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <description>Enterprise Training Agreement the Enrollment Code is associated with.</description>
        <inlineHelpText>Enterprise Training Agreement the Enrollment Code is associated with.</inlineHelpText>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Enrollment Codes</relationshipLabel>
        <relationshipName>Enrollment_Codes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Code</label>
    <nameField>
        <displayFormat>EC-{0000}</displayFormat>
        <label>Enrollment Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Enrollment_Request__c.object
<CustomObject>
    <description>Staging object to ingest requests for class enrollment under Enterprise Training Agreements from multiple sources including manual internal enrollments, self-enrollments via a portal and bulk enrollments via a file load. Records that are processed through this object will ultimately result in records being created in the Enrollment object.</description>
    <fields>
        <fullName>Email__c</fullName>
        <inlineHelpText>Email Address of the Enrollee - used to find the Contact in Salesforce or CDS if the Contact is not identified explicitly</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Enrollment_Code__c</fullName>
        <description>This is not a direct lookup to the Enrollment Code object so it can support querying for records by the Code itself rather than requiring the Salesforce ID of the Code.</description>
        <inlineHelpText>Code used to identify the Enterprise Training Agreement the Enrollment Request should be made for</inlineHelpText>
        <label>Enrollment Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Training agreement the Enrollment should be created under</inlineHelpText>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Enrollment Requests</relationshipLabel>
        <relationshipName>Enrollment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Pending Notification</fullName>
                </value>
                <value>
                    <fullName>Process Manually</fullName>
                </value>
                <value>
                    <fullName>No Action Planned</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Exception</fullName>
                </value>
                <value>
                    <fullName>Reprocess</fullName>
                </value>
                <value>
                    <fullName>Pending CDS Lookup</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Request</label>
    <nameField>
        <displayFormat>ER-{0}</displayFormat>
        <label>Enrollment Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Enterprise_Training_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <description>Check if the Agreement is Active or not. It is based on start date and end date.</description>
        <formula>(TODAY() &gt;=  Term_Start_Date__c ) &amp;&amp; ( TODAY() &lt;=  Term_End_Date__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <label>Max Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Enterprise Training Agreement</label>
    <nameField>
        <label>Enterprise Training Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enterprise Training Agreements</pluralLabel>
    <recordTypes>
        <fullName>Unlimited</fullName>
        <active>true</active>
        <description>Unlimited Seats</description>
        <label>Unlimited</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Training_Agreement_Class_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Training_Agreement_Class_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Agreement Class Relationship</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Training Agreement Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Agreement Class Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Training_Agreement_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings related to Enterprise Training Agreements for Customer Training</description>
    <fields>
        <fullName>Character_Set__c</fullName>
        <description>Set of characters to be used (semicolon delimited) to generate the Enrollment Code for Enterprise Training Agreement.</description>
        <inlineHelpText>Set of characters to be used (semicolon delimited) to generate the Enrollment Code for Enterprise Training Agreement.</inlineHelpText>
        <label>Character Set</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Code_Length__c</fullName>
        <description>The desired length of the Enrollment Code. Defaults to 12. Advised to keep this greater than 8 to avoid collisions.</description>
        <inlineHelpText>The desired length of the Enrollment Code. Defaults to 12. Advised to keep this greater than 8 to avoid collisions.</inlineHelpText>
        <label>Code Length</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Training Agreement Settings</label>
</CustomObject>

classes/TrainingUtil.cls
/**
 * @author      Pranav Raulkar
 * @date        23/03/2016
 * @description This class houses utility methods for the Mathworks TAH module
 * @revision    1.0 - Initial version
 */
public without sharing class TrainingUtil {
    /* The Enrollment Code Configuration custom setting org wide defaults */
    public static final Training_Agreement_Settings__c ENROLL_CODE_CONFIG = Training_Agreement_Settings__c.getOrgDefaults();
    
    /* Utility Constants Section */
    public static final String ECODE_URL_PARAM_KEY = 'code';
    public static final String LANGUAGE_URL_PARAM_KEY = 'ln';
    public static final String DEFAULT_LANGUAGE_CODE = 'en_US';
    public static final String DEFAULT_LANGUAGE_ISOCODE = 'en';
    
    public static final String STATUS_ACTIVE = 'Active';
        
    /* Constant use to test the Duplicate Code in test class */
    public static Boolean testDuplicateSwitch = False;

    /**
    *    @author         Pranav Raulkar
    *    @date           23/03/2016
    *    @description    Enum to store the enrollment code validation status.
    */
    public enum ValidationStatus {
        VALID,
        NON_EXISTENT,
        REVOKED,
        INACTIVE_ETA_CODE       
    }
    
    /* Custom exception to use for TrainingUtil */
    public class TrainingUtilException extends Exception { }

    /**
    *    @author         Pranav Raulkar
    *    @date           23/03/2016
    *    @description    This method generates an random enrollment code to be associated 
    *                    with an Enterprise Training Agreement. 
    *
    *                    The charset considered while generating the randome code is 
    *                    specified by Character_Set__c and the desired length of the code is 
    *                    specified by Code_Length__c from the Training_Agreement_Settings__c
    *                    Hierarchy Custom Setting.
    *
    *                    The method makes sure that the enrollment code retured is unique
    *                    by looking up on the existing enrollment codes for possible 
    *                    collisions.
    *    @return         String
    */
    public static String generateEnrollmentCode() {
        Logger.push('TrainingUtil', 'generateEnrollmentCode');

        String newEnrollmentCode = '';
        
        if(ENROLL_CODE_CONFIG != null) {
            // Get the charset
            List<String> eCodeCharset = ENROLL_CODE_CONFIG.Character_Set__c.split(';');
            
            // Get the charset size
            Integer upperLimit = eCodeCharset.size();
            
            // Generate random code from charset
            for(Integer i = 0; i < ENROLL_CODE_CONFIG.Code_Length__c; i++) {
                newEnrollmentCode += eCodeCharset[randomWithLimit(upperLimit)];
            }

            // Check for possible collisions and re-generate the enrollment code if required
            if(isDuplicate(newEnrollmentCode)) {
                generateEnrollmentCode();                
            }
        } else {
            Logger.debugException(System.Label.CP_ENROLL_Enrollment_Code_Configuration_Missing_Setup);
            
            // Missing custom setting setup
            throw new TrainingUtilException(System.Label.CP_ENROLL_Enrollment_Code_Configuration_Missing_Setup);
        }   
        
        Logger.pop();

        return newEnrollmentCode;
    }
    
    /**
    *    @author        Pranav Raulkar
    *    @date          23/03/2016
    *    @description   Returns a random number between Zero and Maximum number of of unique 
    *                   characters used in construction of enrollment code
    *    @param         upperLimit - The number of unique characters used in construction of 
    *                   enrollment code
    *    @return        Integer
    */
    private static Integer randomWithLimit(Integer upperLimit) {
        Logger.push('TrainingUtil', 'randomWithLimit');
        Integer rand = Math.round(Math.random() * 1000);
        Logger.pop();        
        return Math.mod(rand, upperLimit);
    }

    /**
    *    @author        Pranav Raulkar
    *    @date          23/03/2016
    *    @description   Performs collision detection against existing 
    *                   Enterprise Training Agreement enrollment codes.
    *
    *                   The enrollment codes will not be generated in bulk? SOQL Limits?
    *    @param         enrollmentCode - The enrollment code to check for collision
    *    @return        Boolean
    */
    private static Boolean isDuplicate(String enrollmentCode) {
        Logger.push('TrainingUtil', 'isDuplicate');
        Integer matchCount = Database.countQuery('Select COUNT() FROM Enrollment_Code__c Where Code__c = :enrollmentCode');
        Logger.pop();
        
        return matchCount >= 1;
    }

    /**
    *    @author        Pranav Raulkar
    *    @date          26/03/2016
    *    @description   Returns true/false if the logged in enrollee is blacklisted for the ETA
    *    @param         etaId - The enterprise training agreement id
    *    @Return        Boolean
    */
    public static Boolean isEnrolleeBlacklisted(String etaId, String enrolleeEmail) {
        Logger.push('TrainingUtil', 'isEnrolleeBlacklisted');
        Integer matchCount = Database.countQuery('Select COUNT() FROM Enrollee_Blacklist__c Where Email__c = :enrolleeEmail AND Enterprise_Training_Agreement__c = :etaId');
        Logger.pop();
        
        return matchCount >= 1;
    }

    /**
    *    @author        Pranav Raulkar
    *    @date          26/03/2016
    *    @description   Returns true/false if the logged in enrollee email domain is in allowed domain for the ETA
    *    @param         etaId - The enterprise training agreement id
    *    @return        Boolean
    *    @version       Pranav Raulkar  : (Initial version)
    *                   Sagar talele    : Returns true if the logged in enrollee email domain is in allowed domain for the ETA
    *                                     and also if sub-domain is allowed.
    *                   Pranav Raulkar  : Cleaned up code. Removed all debug statements and fixed local variable naming and casing.
    *                                     Removed redundant UserInfo calls and return statements.
    *                                     Removed == checks on string. Added logger push pop.     
    *                   Archana suryawanshi  : Modified the code to validate the allowed domain if it is more than 1 
    *                                     levels deep if the allow sub domain flag is set to true.     
    */
     public static Boolean isEnrolleeFromAllowedDomain(String etaId) {
        Logger.push('TrainingUtil', 'isEnrolleeFromAllowedDomain');

        Boolean isEnrolleeFromAllowedDomain = false;

        List<Allowed_Domains__c> allowDomainList = new List<Allowed_Domains__c>();

        String userEmail = UserInfo.getUserEmail();
         
        system.debug('userEmail'+'userEmailuserEmailuserEmailuserEmail');
       
        String enrolleeEmailDomain = userEmail.split('@')[1];
        
        allowDomainList = [SELECT Id, Name, Allow_Sub_Domain__c
                            FROM Allowed_Domains__c 
                            WHERE  Enterprise_Training_Agreement__c = :etaId];
        
        for(Allowed_Domains__c ad : allowDomainList) {
            if(ad.Allow_Sub_Domain__c) {
                if(enrolleeEmailDomain.endsWith(ad.Name)) {
                    isEnrolleeFromAllowedDomain = true;
                }         
            } else {
                if(enrolleeEmailDomain.compareTo(ad.Name) == 0){
                    isEnrolleeFromAllowedDomain = true;
                }
            }
        }

        Logger.pop();

        return isEnrolleeFromAllowedDomain;
    }

    /**
    *    @author        Pranav Raulkar
    *    @date          26/03/2016
    *    @description   This method takes in the random code and returns the Enrollment Code instance.
    *    @param         eCode - The enrollment code
    *    @return        Enrollment_Code__c
    */
    public static Enrollment_Code__c getEnrollmentCode(String code) {
        Logger.push('TrainingUtil', 'getEnrollmentCode');

        List<Enrollment_Code__c> eCodeList = [SELECT Status__c, Code__c,
                                                Enterprise_Training_Agreement__r.Max_Seats__c,
                                                Enterprise_Training_Agreement__r.RecordTypeId,
                                                Enterprise_Training_Agreement__r.Is_Active__c,
                                                Enterprise_Training_Agreement__r.Language__r.SF_ISO_Code__c,
                                                Enterprise_Training_Agreement__r.Language__r.Show_Names_By__c,
                                                Enterprise_Training_Agreement__r.Self_Enrollment_Content__c,
                                                Enterprise_Training_Agreement__r.Account_Name__r.Name,
                                                Enterprise_Training_Agreement__r.Term_End_Date__c
                                                FROM Enrollment_Code__c
                                                WHERE Code__c = :code 
                                                Limit 1];

        Logger.pop();
        
        return eCodeList.isEmpty() ? null : eCodeList[0];
    }

    /**
    *    @author        Pranav Raulkar
    *    @date          26/03/2016
    *    @description   The method performs the enrollment code validation as per following -
    *                   1.  Check if enrollment code is of proper length, if not display error.
    *                   2.  Check if the enrollment code exixts
    *                       2.1 If exists, check if it's active else display error
    *                       2.2 If active, check if the associated Enterprise Training Agreement is Active,
    *                           In which case we have a valid enrollment code. If not, display error
    *    @param         eCode - The enrollment code to perform validate
    *    @return        ValidationStatus
    */
    public static ValidationStatus validateEnrollmentCode(Enrollment_Code__c eCode) {
        Logger.push('TrainingUtil', 'validateEnrollmentCode');
        
        ValidationStatus status = ValidationStatus.NON_EXISTENT;
        
        if(eCode != null) {
            if('Active'.equalsIgnoreCase(eCode.Status__c)) {
                if(eCode.Enterprise_Training_Agreement__r.Is_Active__c) {
                    status = ValidationStatus.VALID;
                } else {
                    status = ValidationStatus.INACTIVE_ETA_CODE;
                }
            } else {
                status = ValidationStatus.REVOKED;
            }
        }

        Logger.pop();

        return status;
    }

    /**
    *    @author        Pranav Raulkar
    *    @date          14/04/2016
    *    @description   Get the logged in user contact id
    *    @return        Id
    */
    public static Id getLoggedInUserContactId() {
        Logger.push('TrainingUtil', 'getLoggedInUserContactId');
        User loggedInUser = [SELECT ContactId FROM User WHERE Id = :UserInfo.getUserId()];
        Logger.pop();
        
        return loggedInUser.ContactId;
    }

    /*
        @author         Pranav Raulkar
        @date           14/04/2016
        @description    Get the logged in user contact id
        @returns        Id
    */
    public static Boolean doesLanguageExist(String urlIsoCode) {
        Logger.push('TrainingUtil', 'doesLanguageExist');
        Integer matchCount = Database.countQuery('Select COUNT() FROM Language__c Where SF_ISO_Code__c = :urlIsoCode');
        Logger.pop();

        return matchCount >= 1;
    }

    /**
    *    @author        Archana Suryawanshi
    *    @date          25/04/2016
    *    @description   The method performs the enrollment code validation as per following -
    *                   1.  Check if enrollment code is of proper length, if not display error.
    *                   2.  Check if the enrollment code exixts
    *                       2.1 If exists, check if it's active else display error
    *                       2.2 If active, check if the associated Enterprise Training Agreement is Active,
    *                           In which case we have a valid enrollment code. If not, display error
    *    @param         Set of Enrollment_Code__c - The enrollment codes to perform validate
    *    @return        Map of Enrollment_Code__c to ValidationStatus
    *    @version       Pranav Raulkar: Correct method name in logger push
    *                                   Moved initialization of status inside for loop
    *                                   Replaced 'Active' with TrainingUtil.STATUS_ACTIVE
    *                                   Changed the parameter type from List to Set
    *                                   Added comments
    */
    public static Map<Id, ValidationStatus> validateEnrollmentCodes(Set<Enrollment_Code__c> eCodeSet) {
        Logger.push('TrainingUtil', 'validateEnrollmentCodes');
        
        Map<Id,ValidationStatus> validatedEcodeMap = new Map<Id, ValidationStatus>();
        
        for(Enrollment_Code__c eCode : eCodeSet) { 
            // Validation status must be reset for each enrollment code being processed         
            ValidationStatus status = ValidationStatus.NON_EXISTENT;

            if(eCode != null) {
                if(TrainingUtil.STATUS_ACTIVE.equalsIgnoreCase(eCode.Status__c)) {
                    if(eCode.Enterprise_Training_Agreement__r.Is_Active__c) {
                        status = ValidationStatus.VALID;
                    } else {
                        status = ValidationStatus.INACTIVE_ETA_CODE;
                    }
                } else {
                    status = ValidationStatus.REVOKED;
                }
                
                validatedEcodeMap.put(eCode.id, status);
            }
        }

        Logger.pop();

        return validatedEcodeMap;
    }
    
    /**
    *    @author         Pranav Raulkar
    *    @date           26/04/2016
    *    @description    Returns a map of email & true/false if the logged in enrollee is blacklisted for the ETA
    *    @param          etaIdSet - Set of ETAs. 
    *                    enrolleeEmailSet - Set of email Ids to check for blacklist.
    *    @return         Map<String, Boolean>
    *    @version        Archana Suryawanshi :Changed return type from Map<String, Boolean> to Map<id,Map<string,Boolean>
    */
    public static  Map<id,Map<string,Boolean>> areEnrolleeBlacklisted(Set<String> etaIdSet, Set<String> enrolleeEmailSet) {
        Logger.push('TrainingUtil', 'areEnrolleeBlacklisted');

        Map<id,Map<string,Boolean>> blacklistResultMap = new  Map<id,Map<string,Boolean>>();

        for(Enrollee_Blacklist__c eb : [SELECT Id, Email__c,Enterprise_Training_Agreement__c FROM Enrollee_Blacklist__c 
                                        WHERE Enterprise_Training_Agreement__c IN :etaIdSet 
                                        OR Email__c IN :enrolleeEmailSet]) {
            if(!blacklistResultMap.containskey(eb.Enterprise_Training_Agreement__c)) {
                if(enrolleeEmailSet.contains(eb.Email__c)){
                    blacklistResultMap.put(eb.Enterprise_Training_Agreement__c,new Map<string,Boolean>{eb.Email__c=>true});
                }
            }
           
        }

        Logger.pop();
        
        return blacklistResultMap;
    }
    
  /**
    *    @author        Archana Suryawanshi
    *    @date          26/04/2016
    *    @description   Returns Map allowedDomainResultMap - true/false if the logged in enrollee email domain is in allowed domain for the ETA
    *    @param         etaIdToEnrolleeEmailMap - Map of The enterprise training agreement id to Enrollee email
    *    @return        Map<String,Boolean> - Map of Enrollee email to boolean(allowed domain)
    *    @version       Archana Suryawanshi  : (Initial version)
    * *                 Archana suryawanshi  : Modified the code to validate the allowed domain if it is more than 1 
    *                                          levels deep if the allow sub domain flag is set to true.     
    */
   
     public static Map<id,Map<string,Boolean>> areEnrolleeFromAllowedDomain(Map<Id,String> etaIdToEnrolleeEmailMap) {
        Logger.push('TrainingUtil', 'areEnrolleeFromAllowedDomain');

        Boolean isEnrolleeFromAllowedDomain = false;
        List<Allowed_Domains__c> allowDomainList = new List<Allowed_Domains__c>();
        Map<id,Map<string,Boolean>> allowedDomainResultMap = new Map<id,Map<string,Boolean>>();
      
         for(Allowed_Domains__c adObj:[SELECT Id, Name, Allow_Sub_Domain__c,Enterprise_Training_Agreement__c
                                       FROM Allowed_Domains__c 
                                       where Enterprise_Training_Agreement__c in :etaIdToEnrolleeEmailMap.keySet()]){   
          if(etaIdToEnrolleeEmailMap.get(adObj.Enterprise_Training_Agreement__c)!=null){
                                           
            String enrolleeEmail = etaIdToEnrolleeEmailMap.get(adObj.Enterprise_Training_Agreement__c);
            String enrolleeEmailDomain = etaIdToEnrolleeEmailMap.get(adObj.Enterprise_Training_Agreement__c).split('@')[1]; 

            if(adObj.Allow_Sub_Domain__c) {
                if(enrolleeEmailDomain.endsWith(adObj.Name)) {
                    allowedDomainResultMap.put(adObj.Enterprise_Training_Agreement__c,new Map<string,Boolean>{enrolleeEmail=>true});
                }                 
            } else {
                if(enrolleeEmailDomain.compareTo(adObj.Name) == 0){
                    allowedDomainResultMap.put(adObj.Enterprise_Training_Agreement__c,new Map<string,Boolean>{enrolleeEmail=>true});
                }
            }
            
        }

        Logger.pop();
    }
        return allowedDomainResultMap;
    }
    
    /**
    *    @author        Sagar Talele
    *    @date          26/04/2016
    *    @description   Get the logged in user's contact ids
    *    @return        Map of String,id
    */
    public static Map<String,Id> getLoggedInUserContactIds(Set<String> emailSet) {
        Logger.push('TrainingUtil', 'getLoggedInUserContactIds');
        List<User> loggedInUser = new List<User>();
        Map<String,Id> userEmailToConIdMap = new Map<String,Id>();
        loggedInUser = [SELECT ContactId,Email FROM User WHERE Email IN :emailSet];
        for(User userObj : loggedInUser){
            userEmailToConIdMap.put(userObj.Email,userObj.ContactId);
        }
        Logger.pop();
        
        return userEmailToConIdMap;
    }

    /**
    *    @author        Pranav Raulkar
    *    @date          26/04/2016
    *    @description   Returns all Training Agreement Class Relationship associated with an ETA
    *    @param         etaIdSet - Set of Enterprise Training Agreement Ids
    *    @return        List<Training_Agreement_Class_Relationship__c>
    */
    public static List<Training_Agreement_Class_Relationship__c> getTrainingAgreementClassRelationForETA(Set<Id> etaIdSet) {
        Logger.push('TrainingUtil', 'getTrainingAgreementClassRelationForETA');
        List<Training_Agreement_Class_Relationship__c> tacRelList = [SELECT Class__r.Course__c,Class__c,Class__r.Course_Code__c,class__r.Enrollee_Seats_Taken__c,
                                                                    Class__r.Format_Of_Class__c,Class__r.Language__r.Language_Code__c,Class__r.status__c,
                                                                    Enterprise_Training_Agreement__r.Max_Seats__c 
                                                                    FROM Training_Agreement_Class_Relationship__c
                                                                    WHERE Enterprise_Training_Agreement__c IN :etaIdSet];
        Logger.pop();
        return tacRelList;
    }

    /**
    *    @author        Pranav Raulkar
    *    @date          26/04/2016
    *    @description   Returns all Training Agreement Class Relationship associated with an ETA
    *    @param         etaIdSet - Set of Enterprise Training Agreement Ids
    *                   enrolleeEmailSet - Set of enrollee email ids to get the enrollments for
    *                   enrollmentStatus - The status for which to get the enrollments for
    *    @return        Map<Id, List<Enrollment__c>>
    */
    public static Map<Id, List<Enrollment__c>> getEnrollmentsForETA(Set<Id> etaIdSet, Set<String> enrolleeEmailSet, String enrollmentStatus) {
        Logger.push('TrainingUtil', 'getEnrollmentsForETA');
        
        Map<Id, List<Enrollment__c>> etaEnrollmentMap = new Map<Id, List<Enrollment__c>>();

        for(Enrollment__c enrollment : [SELECT Class__c, Class__r.Course__c, CreatedDate, Enterprise_Training_Agreement__c
                                        FROM Enrollment__c 
                                        WHERE Enterprise_Training_Agreement__c IN :etaIdSet
                                        AND Enrollment_Status__c = :enrollmentStatus
                                        AND Enrollee_Name__r.Email IN :enrolleeEmailSet]) {
            if(etaEnrollmentMap.containsKey(enrollment.Enterprise_Training_Agreement__c)) {
                etaEnrollmentMap.get(enrollment.Enterprise_Training_Agreement__c).add(enrollment);
            } else {
                etaEnrollmentMap.put(enrollment.Enterprise_Training_Agreement__c, new List<Enrollment__c> { enrollment });
            }
        }
        
        Logger.pop();
        
        return etaEnrollmentMap;
    }

    /**
    *    @author        Pranav Raulkar
    *    @date          02/05/2016
    *    @description   Returns count of seats taken for each class in an eta
    *    @param         etaIdSet - Set of Enterprise Training Agreement Ids
    *                   classIdSet - Set of class Ids
    *                   In case there are no enrollments for a class for an ETA, you should be checking if the inner map is null.
    *    @return        Map<Id, Map<Id, Integer>>
    */
    public static Map<Id, Map<Id, Integer>> getConsumedSeatCountForETA(Set<Id> etaIdSet, Set<Id> classIdSet) {
        Logger.push('TrainingUtil', 'getConsumedSeatCountForETA');

        Map<Id, Map<Id, Integer>> etaClassCountMap;

        if(etaIdSet != null && !etaIdSet.isEmpty()) {
            Set<Id> recTypeIdSet = new Set<Id> {
                Schema.SObjectType.Enterprise_Training_Agreement__c.getRecordTypeInfosByName().get('Seat-Based').getRecordTypeId(),
                Schema.SObjectType.Enterprise_Training_Agreement__c.getRecordTypeInfosByName().get('Unlimited').getRecordTypeId()
            };

            Set<String> statusSet = new Set<String> {
                'Registered', 'Registered - Awaiting Payment', 'Completed'
            };

            List<Enrollment__c> enrollmentList = [SELECT Class__c, Enterprise_Training_Agreement__c FROM Enrollment__c 
                                                    WHERE Class__c = :classIdSet 
                                                    AND Enterprise_Training_Agreement__c IN :etaIdSet 
                                                    AND Enterprise_Training_Agreement__r.RecordTypeId IN :recTypeIdSet 
                                                    AND Enrollment_Status__c IN :statusSet];

            etaClassCountMap = new Map<Id, Map<Id, Integer>>();

            for(Enrollment__c enrollment : enrollmentList) {
                Id classId = enrollment.Class__c;
                Id etaId = enrollment.Enterprise_Training_Agreement__c;

                if(etaClassCountMap.containsKey(etaId)) {
                    Map<Id, Integer> classCountMap = etaClassCountMap.get(etaId);
                    if(classCountMap.containsKey(classId)) {
                        Integer count = classCountMap.get(classId);
                        classCountMap.put(classId, ++count);
                    } else {
                        classCountMap.put(classId, 1);
                    }  
                    etaClassCountMap.put(etaId, classCountMap);                  
                } else {
                    etaClassCountMap.put(etaId, new Map<Id, Integer> { classId => 1 });
                }
            }
        }

        Logger.pop();

        return etaClassCountMap;
    }

    /**
    *    @author        Pranav Raulkar
    *    @date          04-May-2016
    *    @description   Creates a version 3 GUID
    *    @return        String
    */
    public static String generateGUID() {
        Logger.push('TrainingUtil', 'generateGUID');

        Blob aesKey = Crypto.generateAesKey(128);
        String hexAesKey = EncodingUtil.convertToHex(aesKey);

        Logger.pop();

        return String.join(new List<String> {
            hexAesKey.substring(0, 8),
            hexAesKey.substring(8, 12),
            hexAesKey.substring(12, 16),
            hexAesKey.substring(16, 20),
            hexAesKey.substring(20)
        }, '-');
    }
    
    /**
    *    @author        Abhay Verma
    *    @date          05-May-2016
    *    @description   Creates Enrollment from a non exceptional enrollment request object.
    *    @return        List<Enrollment__c>
    */    
    public static List<Enrollment__c> createEnrollmentFromEnrollmentRequest(List<Enrollment_Request__c> enrolReqLst) {
        Logger.push('TrainingUtil', 'createEnrollmentFromEnrollmentRequest');

        List<Enrollment__c> enrolLst = new List<Enrollment__c>();

        if(enrolReqLst != null && enrolReqLst.size() >0) {        
            // Iterate over the enrollment request list and create enrollment with the respected values.
            for(Enrollment_Request__c enrolReqObj : enrolReqLst) {                
                Enrollment__c enrolObj = new Enrollment__c();
                enrolObj.Start_Date__c = enrolReqObj.Enterprise_Training_Agreement__r.Term_Start_Date__c > Date.Today() ? enrolReqObj.Enterprise_Training_Agreement__r.Term_Start_Date__c : Date.Today();
                enrolObj.End_Date__c = enrolReqObj.Enterprise_Training_Agreement__r.Term_End_Date__c;
                enrolObj.Send_Email__c = false;
                enrolObj.Enrollment_Status__c = 'Registered';
                enrolObj.Enrollee_Name__c = enrolReqObj.Contact__c;
                enrolObj.Enterprise_Training_Agreement__c = enrolReqObj.Enterprise_Training_Agreement__c;
                enrolObj.Class__c = enrolReqObj.Class__c;
                enrolObj.CurrencyIsoCode = enrolReqObj.Enterprise_Training_Agreement__r.CurrencyIsoCode;
                enrolObj.Order_Number__c = enrolReqObj.Enterprise_Training_Agreement__r.Order_Number__c;
                enrolObj.Enrollment_Code__c = enrolReqObj.Enrollment_Code__c;
                enrolObj.Seat_Price__c = 0.00; 
                enrolObj.Source__c = enrolReqObj.Source__c;
                enrolLst.add(enrolObj);
            }
        }

        Logger.pop();
        
        return enrolLst;
    }
}