objects/Allowed_Domains__c.object
<CustomObject>
    <fields>
        <fullName>Allow_Sub_Domain__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field decides whether sub Doamin is allowed or not or particular Enterprise Training Agreements</description>
        <inlineHelpText>When checked, also matches on any sub-domain of the value entered (e.g.: students.university.edu will be allowed when university.edu is the allowed domain) Do not check if explicit sub-domains are required; add them as allowed domains individually.</inlineHelpText>
        <label>Allow Sub Domain</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Allowed Domains</relationshipLabel>
        <relationshipName>Allowed_Domains</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Allowed Domain</label>
    <nameField>
        <label>Allowed Domain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allowed Domains</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Course_Code__c</fullName>
        <label>Part Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <label>Max Seats</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <description>Contact Preferred Language</description>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Swedish</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Portuguese</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Course_Code__c</fullName>
        <label>Part Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <recordTypes>
        <fullName>Training</fullName>
        <active>true</active>
        <description>Record type to create non certification course</description>
        <label>Training</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Course_Language__c.object
<CustomObject>
    <fields>
        <fullName>Course_Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Course Languages</relationshipLabel>
        <relationshipName>Course_Languages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Languages</relationshipLabel>
        <relationshipName>Course_Languages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course Language</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Course Language Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Enrollment__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>Class_Enrollees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <formula>Class__r.Course_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Course Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enrollee_Name__c</fullName>
        <label>Enrollee Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Class Enrollments</relationshipLabel>
        <relationshipName>Class_Enrollees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Enrollment_Status__c</fullName>
        <label>Enrollment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Awaiting Payment</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Class Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
                <value>
                    <fullName>No Show-Bill</fullName>
                </value>
                <value>
                    <fullName>Registered - Awaiting Payment</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>!!! CHECK ME !!! -</fullName>
                </value>
                <value>
                    <fullName>!!! CHECK ME !!! -*** Unselected ***</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Enterprise_Training_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Enterprise Training Agreements</relationshipLabel>
        <relationshipName>Enterprise_Training_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Language to display content in on self-enrollment portal</inlineHelpText>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Enterprise Training Agreements</relationshipLabel>
        <relationshipName>Enterprise_Training_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <label>Max Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Enterprise Training Agreement</label>
    <nameField>
        <label>Enterprise Training Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enterprise Training Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Language__c.object
<CustomObject>
    <fields>
        <fullName>SF_ISO_Code__c</fullName>
        <description>The universal ISO language code.</description>
        <inlineHelpText>The universal ISO language code.</inlineHelpText>
        <label>Salesforce ISO Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Language</label>
    <nameField>
        <label>Language</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Training_Agreement_Class_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Class__c.Format_Of_Class__c</field>
                <operation>equals</operation>
                <value>Self-Paced</value>
            </filterItems>
            <filterItems>
                <field>Class__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enterprise Agreement</relationshipLabel>
        <relationshipName>Training_Agreement_Class</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>Part Number</description>
        <formula>Class__r.Course__r.Course_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Part Number</inlineHelpText>
        <label>Course Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Training_Agreement_Class_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Agreement Class Relationship</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Training Agreement Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Agreement Class Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CourseControllerTest.cls
@isTest
public class CourseControllerTest {
	private static CustomSettingsBuilder custsettbuild = new CustomSettingsBuilder();
    private static CTrainingCustomSettingBuilder cTrainSettingBuilder = new CTrainingCustomSettingBuilder();

    private static List<Account> accountList;
    private static List<Contact> contactList;

    private static List<Language__c> languageList;
    private static List<Enterprise_Training_Agreement__c> etaList;
    private static List<Course__c> courseList;
    private static List<Course_Language__c> courseLangList;
    private static List<Class__c> classList;
    private static List<Training_Agreement_Class_Relationship__c> tacRelationshipList;
    private static List<Allowed_Domains__c> allowedDomainsList;
    private static List<Enrollment__c> enrollmentList;
    
    static void setupData() {
        custsettbuild.buildBypassTriggerSettings();
        cTrainSettingBuilder.buildEnrollmentCodeConfiguration();

        // INSERT ACCOUNT
        accountList = new List<Account>();
        for(Integer i = 0; i < 2; i++){
            accountList.add(TestDataBuilder.buildTestAccount(i, UserInfo.getUserId()));            
        }
        insert accountList;

        // INSERT CONTACT
        contactList = new List<Contact>();
        for(Integer i = 0; i < 2; i++) {
            Contact contact = TestDataBuilder.buildTestContact(i, UserInfo.getUserId(), accountList[i].Id);
            contact.Email = 'test_contact_mw' + i + '@testmailtest.com';
            contactList.add(contact);            
        }
        insert contactList;

        // INSERT LANGUAGE
        languageList = new List<Language__c>();
        languageList.add(CTrainingTestDataBuilder.buildTestLanguage(0));
        languageList[0].SF_ISO_Code__c = 'en_US';
        insert languageList;

        // INSERT ENTERPRISE TRAINING AGREEMENT
        Id etaSeatBasedTypeId = Schema.SObjectType.Enterprise_Training_Agreement__c.getRecordTypeInfosByName().get('Seat-Based').getRecordTypeId();

        etaList = new List<Enterprise_Training_Agreement__c>();
        for(Integer i = 0; i < 2; i++) {
            Enterprise_Training_Agreement__c eta = CTrainingTestDataBuilder.buildTestETAgreement(i);
            eta.Account_Name__c = accountList[i].Id;
            eta.RecordTypeId = etaSeatBasedTypeId;
            eta.Max_Seats__c = 10;
            eta.Language__c = languageList[0].Id;
            etaList.add(eta);
        }
        insert etaList;

        // INSERT COURSE
        Id courseSeatBasedTypeId = Schema.SObjectType.Course__c.getRecordTypeInfosByName().get('Training').getRecordTypeId();

        courseList = new List<Course__c>();
        for(Integer i = 0; i < 10; i++) {
            Course__c course = CTrainingTestDataBuilder.buildTestCourse(i);
            course.RecordTypeId = courseSeatBasedTypeId;
            course.Course_Code__c = 'CC' + i;
            courseList.add(course);
        }
        insert courseList;

        // INSERT CLASS
        Integer classI = 0;
        Id classSeatBasedTypeId = Schema.SObjectType.Class__c.getRecordTypeInfosByName().get('Self-Paced').getRecordTypeId();
        
        classList = new List<Class__c>();
        for(Course__c course : courseList){
            Class__c cl = CTrainingTestDataBuilder.buildTestClass(classI++, course.Id, languageList[0].Id);
            cl.Max_Seats__c  = 10;
            cl.RecordTypeId = classSeatBasedTypeId;
            classList.add(cl);
        }
        insert classList;

        // INSERT Training Agreement Relationship
        tacRelationshipList = new List<Training_Agreement_Class_Relationship__c>(); 
        for(Enterprise_Training_Agreement__c eta : etaList){
            for(Class__c cl : classList) { 
                Training_Agreement_Class_Relationship__c tacr = CTrainingTestDataBuilder.buildTestTAClassRelationship(cl.Id, eta.Id);
                tacRelationshipList.add(tacr);
            }
        }
        insert tacRelationshipList;

        // INSERT ALLOWED DOMAIN
        allowedDomainsList = new List<Allowed_Domains__c>();
        for(Enterprise_Training_Agreement__c eta : etaList) {
            //String email = (String) UserInfo.getUserEmail();
            String email = contactList[0].email;

            Allowed_Domains__c ad = new Allowed_Domains__c();                
            ad.Enterprise_Training_Agreement__c = eta.Id;
            ad.Name = email.substringAfter('@');
            ad.Allow_Sub_Domain__c = true;
            allowedDomainsList.add(ad);
        }
        insert allowedDomainsList;

        // CREATE ENROLLMENTS
        enrollmentList = new List<Enrollment__c>();
        for(Enterprise_Training_Agreement__c eta : etaList) {
            for(Integer i = 0; i < 5; i++) {
                Enrollment__c en = new Enrollment__c();
                en.Enterprise_Training_Agreement__c = eta.Id;
                en.Class__c = classList[i].Id;
                en.Enrollee_Name__c = contactList[0].Id;
                en.Enrollment_Status__c = 'Registered';
                enrollmentList.add(en);
            }           
        }
        insert enrollmentList;
    }

    private static testMethod void courseLanguageList_test() {
    	setupData();

    	Test.startTest();

		CourseController controller = new CourseController();
		System.assert(controller.courseLanguageList.size() == 0);

		controller.etAgreementID = etaList[0].Id;
		controller.language = 'en_US';
		System.assert(controller.courseLanguageList.size() != 1);

    	Test.stopTest();
    }
}