objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Mark for Deletion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <default>true</default>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <recordTypes>
        <fullName>Training</fullName>
        <active>true</active>
        <description>Record type to create non certification course</description>
        <label>Training</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Enterprise_Training_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Language to display content in on self-enrollment portal</inlineHelpText>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Enterprise Training Agreements</relationshipLabel>
        <relationshipName>Enterprise_Training_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>License_ID__c</fullName>
        <description>Used by Eloqua marketing program to identify LEUs</description>
        <inlineHelpText>License ID corresponding to the TAH/Unlimited license agreement to use for identifying Licensed End Users to notify of access to training under this agreement when the &quot;Enable LEU Campaigns&quot; box is checked</inlineHelpText>
        <label>License ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Enterprise Training Agreement</label>
    <nameField>
        <label>Enterprise Training Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enterprise Training Agreements</pluralLabel>
    <recordTypes>
        <fullName>Unlimited</fullName>
        <active>true</active>
        <description>Unlimited Seats</description>
        <label>Unlimited</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Language__c.object
<CustomObject>
    <label>Language</label>
    <nameField>
        <label>Language</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Training_Agreement_Class_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Class__c.Format_Of_Class__c</field>
                <operation>equals</operation>
                <value>Self-Paced</value>
            </filterItems>
            <filterItems>
                <field>Class__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enterprise Agreement</relationshipLabel>
        <relationshipName>Training_Agreement_Class</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Training_Agreement_Class_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Agreement Class Relationship</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Training Agreement Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Agreement Class Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TrainingAgreementClassTriggerHandlerTest.cls
/**
 *author Original: Faina Gorelik - MathWorks
 *date Original: 28 September 2017, Last Modified: 
 *description This  is handler class for TrainingAgreementClassTriggerHandler, not validation for Assert since we are not getting back any response after the call
 */

@isTest
public class TrainingAgreementClassTriggerHandlerTest {
    
static CustomSettingsBuilder custsettbuild = new CustomSettingsBuilder();
// create new ETA
private static testMethod void updateTAgreementClassRelationshipTest(){// fg test Course Manager integration when the existing license has been udpated
        
            //Inserting Bypass trigger custom setting
         custsettbuild.buildBypassTriggerSettings();
         //Create test user
         User usr = TestDataBuilder.buildTestUser(1);
            insert usr;
       System.runAs(usr){
              test.startTest();
             //create Course__c record from CTrainingTestDataBuilder.
             Course__c courseObj = CTrainingTestDataBuilder.buildTestCourse(0);
             insert courseObj;
             Course__c courseInt = [Select Id, Name From Course__c where id =: courseObj.Id];
             System.assert(courseInt != null);
             
             
             //create Language__c record from CTrainingTestDataBuilder.
             Language__c langObj = CTrainingTestDataBuilder.buildTestLanguage(1);
             insert langObj;
             Language__c langInt = [Select Id from Language__c where id =:langObj.Id];
             System.assert(langInt != null);
             
             Id recTypeId = [Select Id From RecordType  Where (SobjectType = 'Class__c') AND (RecordType.Name ='Self-Paced') LIMIT 1].Id;
             //intialize class list to create multiple records for class.
             List<Class__c> classList = new List<Class__c>();
             for(Integer i=0;i<3;i++){
                 Class__c classObj =CTrainingTestDataBuilder.buildTestClass(i,courseObj.Id,langObj.Id);
                 classObj.recordTypeId = recTypeId ;
                 classObj.Status__c = 'Active';
                 classList.add(classObj);
             }
             insert classList;
             System.assertEquals(classList.size(),3);
             List<RecordType> recTypeList = new List<RecordType>();
             Id etAgrrementRecTypeId = [Select ID, Name From RecordType Where sObjectType = 'Enterprise_Training_Agreement__c' AND RecordType.Name ='Unlimited' limit 1].Id;
             //intialize class list to create multiple records for Enterprise Training Agreement.
             List<Enterprise_Training_Agreement__c> ETAgreementList = new List<Enterprise_Training_Agreement__c>();
             for(Integer i=0;i<3;i++){
                 Enterprise_Training_Agreement__c ETAgreementObj = CTrainingTestDataBuilder.buildTestETAgreement(1);
                 ETAgreementObj.RecordTypeId = etAgrrementRecTypeId ; 
                 if (i==2){// to cover http call on insert
                     ETAgreementObj.License_ID__c ='099902';
                 }
                 ETAgreementList.add(ETAgreementObj);
                 
             }    
        //   
           StaticResourceCallOutMock multimockcallMAOTS = new StaticResourceCalloutMock();
           multimockcallMAOTS.setStaticResource('MockResponseCourseManager');     
           multimockcallMAOTS.setStatusCode(200);
           multimockcallMAOTS.setHeader('x-mw-authentication', 'LEARN-MATLAB');
           multimockcallMAOTS.setHeader('OrganizationID', UserInfo.getOrganizationId()); 
           string url = 'https://sf-ext-msg-dev.mathworks.com/course-manager/service/v1/license-enrollments/099902';
           test.setMock(HttpCalloutMock.class, multimockcallMAOTS);
           //
             insert ETAgreementList ;
            
          // build new course
            Course__c courseObjNew = CTrainingTestDataBuilder.buildTestCourse(1);
            insert courseObjnew;
            Course__c courseIntNew = [Select Id, Name From Course__c where id =: courseObjNew.Id];
            
            // add new class associated with the new course
             List<Class__c> classListNew = new List<Class__c>();
            for(Integer i=0;i<3;i++){
                Class__c classObjNew =CTrainingTestDataBuilder.buildTestClass(i,courseObjNew.Id,langObj.Id);
                classObjNew.recordTypeId = recTypeId ;
                classObjNew.Status__c = 'Active';
                classListNew.add(classObjNew);
            }
            insert classListNew;
           // add new class to the relationship table
           Training_Agreement_Class_Relationship__c TARelRecord = new Training_Agreement_Class_Relationship__c();
           List<Class__c> ETRelClass = new List<Class__c>();  
           ETRelClass = [select Id  From Class__C where Id =:classListNew[0].Id];
           TARelRecord.Class__c = ETRelClass[0].Id;
           TARelRecord.Enterprise_Training_Agreement__c = ETAgreementList[0].Id;
           StaticResourceCallOutMock multimockcallMAOTSNew = new StaticResourceCalloutMock();
           multimockcallMAOTSNew.setStaticResource('MockResponseCourseManager');     
           multimockcallMAOTSNew.setStatusCode(200);
           multimockcallMAOTSNew.setHeader('x-mw-authentication', 'LEARN-MATLAB');
           multimockcallMAOTSNew.setHeader('OrganizationID', UserInfo.getOrganizationId()); 
           string urlnew = 'https://sf-ext-msg-dev.mathworks.com/course-manager/service/v1/license-enrollments/099902';
           test.setMock(HttpCalloutMock.class, multimockcallMAOTSNew);
           insert TARelRecord;
            test.stopTest();
        }
    }
    
}