objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <description>Contact Preferred Language</description>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Swedish</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Portuguese</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Course_Language__c.object
<CustomObject>
    <fields>
        <fullName>Course_Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Course Languages</relationshipLabel>
        <relationshipName>Course_Languages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Languages</relationshipLabel>
        <relationshipName>Course_Languages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Localized_Course_Name__c</fullName>
        <inlineHelpText>Translated version of the English Course Name into the Language this record represents</inlineHelpText>
        <label>Localized Course Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Course Language</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Course Language Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Enrollment__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>Class_Enrollees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Enrollee_Name__c</fullName>
        <label>Enrollee Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Class Enrollments</relationshipLabel>
        <relationshipName>Class_Enrollees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Enrollment_Status__c</fullName>
        <label>Enrollment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Awaiting Payment</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Class Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
                <value>
                    <fullName>No Show-Bill</fullName>
                </value>
                <value>
                    <fullName>Registered - Awaiting Payment</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>!!! CHECK ME !!! -</fullName>
                </value>
                <value>
                    <fullName>!!! CHECK ME !!! -*** Unselected ***</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bulk Enrollment</fullName>
                </value>
                <value>
                    <fullName>Manual Enrollment</fullName>
                </value>
                <value>
                    <fullName>Self-Enrollment Portal</fullName>
                </value>
                <value>
                    <fullName>Commerce Enrollment</fullName>
                </value>
                <value>
                    <fullName>External Enrollment</fullName>
                </value>
                <value>
                    <fullName>Migration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Enrollment_Request__c.object
<CustomObject>
    <description>Staging object to ingest requests for class enrollment under Enterprise Training Agreements from multiple sources including manual internal enrollments, self-enrollments via a portal and bulk enrollments via a file load. Records that are processed through this object will ultimately result in records being created in the Enrollment object.</description>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Class to enroll Contact in</inlineHelpText>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enrollment Requests</relationshipLabel>
        <relationshipName>Enrollment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Contact to be enrolled</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Enrollment Requests</relationshipLabel>
        <relationshipName>Enrollment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Resulting Enrollment record from this Enrollment Request - should be set after email notification is sent</inlineHelpText>
        <label>Enrollment</label>
        <referenceTo>Enrollment__c</referenceTo>
        <relationshipLabel>Enrollment Requests</relationshipLabel>
        <relationshipName>Enrollment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Training agreement the Enrollment should be created under</inlineHelpText>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Enrollment Requests</relationshipLabel>
        <relationshipName>Enrollment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <inlineHelpText>How did this Enrollment Request get added to the queue?</inlineHelpText>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bulk Enrollment</fullName>
                </value>
                <value>
                    <fullName>Manual Enrollment</fullName>
                </value>
                <value>
                    <fullName>Self-Enrollment Portal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Request</label>
    <nameField>
        <displayFormat>ER-{0}</displayFormat>
        <label>Enrollment Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Enterprise_Training_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Enterprise Training Agreements</relationshipLabel>
        <relationshipName>Enterprise_Training_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Language to display content in on self-enrollment portal</inlineHelpText>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Enterprise Training Agreements</relationshipLabel>
        <relationshipName>Enterprise_Training_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enterprise Training Agreement</label>
    <nameField>
        <label>Enterprise Training Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enterprise Training Agreements</pluralLabel>
    <recordTypes>
        <fullName>Unlimited</fullName>
        <active>true</active>
        <description>Unlimited Seats</description>
        <label>Unlimited</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Language_Display_Name__c.object
<CustomObject>
    <description>Contains the display names</description>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Language Display Names</relationshipLabel>
        <relationshipName>Language_Display_Names</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Language Display Name</label>
    <nameField>
        <label>Language Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Language Display Names</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Training_Agreement_Class_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Class__c.Format_Of_Class__c</field>
                <operation>equals</operation>
                <value>Self-Paced</value>
            </filterItems>
            <filterItems>
                <field>Class__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enterprise Agreement</relationshipLabel>
        <relationshipName>Training_Agreement_Class</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Training_Agreement_Class_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Agreement Class Relationship</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Training Agreement Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Agreement Class Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EnrollmentPageController.cls
/**
* @author       Pranav Raulkar
* @date         27-May-2016
* @description  
* @revision     Initial version
*/
public with sharing class EnrollmentPageController {
    public Boolean isError      { get; set; }

    public Boolean showETALookup    { get; set; }
    public Boolean showClassLookup  { get; set; }

    public Enrollment__c enrollment                 { get; set; }
    public Enrollment_Request__c enrollmentRequest  { get; set; }

    // URL Parameters
    public String retURL        { get; set; }
    public String enrolleeId    { get; set; }
    public String etaId         { get; set; }
    public String classId       { get; set; }
    public String errorMessage  { get; set; }

    // Table maps
    public Map<Id, RequestWrapper> enrolledClassesMap   { get; set; }
    public Map<Id, RequestWrapper> availableClassesMap  { get; set; }

    // Wrapper for listing classes associated witl ETA and available for enrollment
    @testvisible
    class RequestWrapper implements Comparable {
        public Boolean isNewEnrollment { get; set; }
        public Enrollment__c enrollment { get; set; }
        public Class__c etaclass { get; set; }
        public Course__c course { get; set; }
        public Course_Language__c courseLanguage { get; set; }

        public Integer compareTo(Object compareTo) {
            RequestWrapper rw = (RequestWrapper) compareTo;
            if(this.courseLanguage.Localized_Course_Name__c == rw.courseLanguage.Localized_Course_Name__c) return 0; 
            if(this.courseLanguage.Localized_Course_Name__c > rw.courseLanguage.Localized_Course_Name__c) return 1; 
            return -1;
        }
    }

    /**
    * @author       Pranav Raulkar
    * @date         27-May-2016
    * @description  Constructor.
    * @revision     Initial version
    */
    public EnrollmentPageController() {
        Logger.push('EnrollmentPageController', 'EnrollmentPageController');

        readURLParams();
        initVars(); 
        updateVisibility(); 

        Logger.pop();
    }

    /**
    * @author       Pranav Raulkar
    * @date         27-May-2016
    * @description  This method intializes variables.
    * @revision     Initial version
    */
    private void initVars() {
        Logger.push('EnrollmentPageController', 'initVars');

        // Initialize enrollmrnt assuming we have a Enrollee and a specific Class selected
        enrollment = new Enrollment__c();
        
        // Initialize Enrollment Request assuming we have a Enrollee and ETA with multiple Classes selected
        // The lookups on the page are controlled by enrollmentRequest, hence initializing them on load if 
        // the id's are passed via URL 
        enrollmentRequest = new Enrollment_Request__c();
        enrollmentRequest.Contact__c = enrolleeId;
        enrollmentRequest.Enterprise_Training_Agreement__c = etaId;
        enrollmentRequest.Class__c = classId;

        enrolledClassesMap = new Map<Id, RequestWrapper>();
        availableClassesMap = new Map<Id, RequestWrapper>();

        isError = false;
        errorMessage = '';

        Logger.pop();
    }

    /**
    * @author       Pranav Raulkar
    * @date         27-May-2016
    * @description  This method reads the URL parameters and inits class variables.
    * @revision     Initial version
    */
    private void readURLParams() {
        Logger.push('EnrollmentPageController', 'readURLParams');

        Map<String, String> pageParams = ApexPages.currentPage().getParameters();

        // In case we have come from the tab, return URL is home page
        retURL      = (pageParams.get('retURL') == null ? '/home/home.jsp' : pageParams.get('retURL'));
        enrolleeId  = pageParams.get('en');
        etaId       = pageParams.get('ea');
        classId     = pageParams.get('cl');

        Logger.pop();
    }

    /**
    * @author       Pranav Raulkar
    * @date         27-May-2016
    * @description  This method updates the variables controlling the visibility of ETA and Class content on page
    * @revision     Initial version
    */
    public void updateVisibility() {
        Logger.push('EnrollmentPageController', 'updateVisibility');

        isError = false;
        errorMessage = '';
        
        enrolledClassesMap.clear();
        availableClassesMap.clear();

        if(enrollmentRequest.Enterprise_Training_Agreement__c == null && enrollmentRequest.Class__c == null) {
            showETALookup = true;
            showClassLookup = true;
        } else if(enrollmentRequest.Enterprise_Training_Agreement__c != null && enrollmentRequest.Class__c == null) {
            showETALookup = true;
            showClassLookup = false;
            
            if(enrollmentRequest.Contact__c!= null){
                // Check for allowed domain and blacklist
                Boolean isBlacklisted = isEnrolleBlacklisted();
                Boolean isAllowedDomain = isEnrolleFromAllowedDomain();
    
                if(isBlacklisted) {
                    isError = true;
                    errorMessage = System.Label.CP_ENROLL_BlacklistedEnrollee;
                } 
    
                if(!isAllowedDomain) {
                    Enterprise_Training_Agreement__c eta = getETARecord();
                    isError = true;
                    errorMessage = String.format(System.Label.CP_ENROLL_EmailNotInAllowedDomain, new List<String> { eta.Account_Name__r.Name, eta.Account_Name__r.Name });
                } 
    
                if(!isBlacklisted && isAllowedDomain && enrollmentRequest.Contact__c != null) {
                    Map<Id, RequestWrapper> allClassesMap = getAllETAClasses();
                    loadAvailableAndEnrolledClasses(allClassesMap);
                }
            }
        } else if(enrollmentRequest.Enterprise_Training_Agreement__c == null && enrollmentRequest.Class__c != null) {
            showETALookup = false;
            showClassLookup = true;
        }

        Logger.pop();
    }

    /**
    * @author       Pranav Raulkar
    * @date         27-May-2016
    * @description  This method creates a new enrollment.
    * @revision     Initial version
    */
    public PageReference createNewEnrollment() {
         
        Logger.push('EnrollmentPageController', 'createNewEnrollment');

        PageReference returnPage = null;

        isError = false;
        errorMessage = '';

        enrollment.Enrollee_Name__c = enrollmentRequest.Contact__c;
        enrollment.Class__c = enrollmentRequest.Class__c;
        enrollment.Source__c = 'Manual Enrollment'; //SS 11/7/16 #1747653 - Set the source when creating enrollment manually


        if(String.isEmpty(enrollment.Enrollee_Name__c) || String.isEmpty(enrollment.Enrollment_Status__c)) {
            isError = true;
            errorMessage = System.Label.CP_ENROLL_RequiredFieldsMissing;
            return null;
        }
       try {
        
            insert enrollment;
            
            if(enrollment.Enterprise_Training_Agreement__c == null){
                returnPage = new PageReference('/'+enrollment.Id);
               
            }
            System.debug('## enrollment: ' + enrollment);
        
            //returnPage = gotoReturnURL();
        } catch(DmlException dmlEx) {
            Logger.debugException(dmlEx);

            isError = true;
            errorMessage = (dmlEx.getMessage().replace('Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION,','')).replace(': []', '');
          
        }

        Logger.pop();

       return returnPage;
    }

    /**
    * @author       Pranav Raulkar
    * @date         27-May-2016
    * @description  This method creates new enrollment requests for selected classes.
    * @revision     Initial version
    */
    public PageReference createNewEnrollmentRequest() {
        Logger.push('EnrollmentPageController', 'createNewEnrollmentRequest');

        PageReference returnPage = null;

        isError = false;
        errorMessage = '';

        if(String.isEmpty(enrollmentRequest.Contact__c)) {
            isError = true;
            errorMessage = System.Label.CP_ENROLL_RequiredFieldsMissing;
            return null;
        }

        Contact contact = [SELECT FirstName, LastName, Email FROM Contact WHERE Id = :enrollmentRequest.Contact__c LIMIT 1];

        List<Enrollment_Request__c> newenrollmentRequestList = new List<Enrollment_Request__c>();

        for(RequestWrapper cw : availableClassesMap.values()) {
            if(cw.isNewEnrollment) {
                Enrollment_Request__c eReq = new Enrollment_Request__c();

                eReq.First_Name__c      = contact.FirstName;
                eReq.Last_Name__c       = contact.LastName;
                eReq.Email__c           = contact.Email;
                eReq.Contact__c         = enrollmentRequest.Contact__c;
                eReq.Status__c          = 'New';
                eReq.Source__c          = 'Manual Enrollment';
                eReq.Class__c           = cw.etaclass.Id;
                eReq.Class_Format__c    = cw.etaclass.Format_Of_Class__c;
                eReq.Course_Code__c     = cw.etaclass.Course_Code__c;
                eReq.Language_Code__c   = cw.etaclass.Language__r.Language_Code__c;
                eReq.Enterprise_Training_Agreement__c = enrollmentRequest.Enterprise_Training_Agreement__c;

                newenrollmentRequestList.add(eReq);
            }
        }

        try {
            insert newenrollmentRequestList;

            returnPage = gotoReturnURL();
        } catch(DmlException dmlEx) {
            Logger.debugException(dmlEx);

            isError = true;
            errorMessage = dmlEx.getMessage();
        }
        Logger.pop();

        return returnPage;
    }

    /**
    * @author       Pranav Raulkar
    * @date         27-May-2016
    * @description  Navigates back to the originating place/home page on cancel operation
    * @revision     Initial version
    */
    public PageReference gotoReturnURL() {
        Logger.push('EnrollmentPageController', 'gotoReturnURL');

        PageReference returnPage = new PageReference(retURL);
        returnPage.setRedirect(true);

        Logger.pop();

        return returnPage;
    }

    public Map<Id, RequestWrapper> getAllETAClasses() {
        Logger.push('EnrollmentPageController', 'getAllETAClasses');

        Map<Id, Id> classCourseMap = new Map<Id, Id>();
        Map<Id, Id> courseClassMap = new Map<Id, Id>();
        Map<Id, RequestWrapper> requestWrapperMap = new Map<Id, RequestWrapper>();

        Enterprise_Training_Agreement__c eta = getETARecord();
        
        for(Training_Agreement_Class_Relationship__c tacr : TrainingUtil.getTrainingAgreementClassRelationForETA(new Set<Id> { eta.Id })) {
            courseClassMap.put(tacr.Class__r.Course__c, tacr.Class__c);
            classCourseMap.put(tacr.Class__c, tacr.Class__r.Course__c);
        }

        Map<Id, Class__c> classMap = new Map<Id, Class__c>([SELECT Id, Course__c,Course_Code__c, CreatedDate, Open_Seats__c, 
                                                                Format_Of_Class__c, Language__r.Language_Code__c, 
                                                                Language__r.Name, Language__r.Language_Display_Name__c, Total_Seats_Taken__c 
                                                            FROM Class__c 
                                                            WHERE Id IN :classCourseMap.keySet()
                                                            AND Status__c = :TrainingUtil.STATUS_ACTIVE]);
        Map<Id, Course__c> courseMap = new Map<Id, Course__c>([SELECT Id 
                                                                FROM Course__c 
                                                                WHERE Id IN :courseClassMap.keySet()]);
        Map<Id, Course_Language__c> courseLanguageMap = new Map<Id, Course_Language__c>();

        for(Course_Language__c courseLanguage : [SELECT Id, Localized_Course_Name__c, Localized_Short_Description__c,
                                                    Localized_Pre_Requisite__c, Course__c, 
                                                    Course_Language__r.Name, Course_Language__r.SF_ISO_Code__c,
                                                    Course_Language__r.Language_Display_Name__c
                                                FROM Course_Language__c 
                                                WHERE Course__c IN :courseClassMap.keySet() 
                                                AND Course_Language__r.SF_ISO_Code__c = 'en_US']) {
            courseLanguageMap.put(courseLanguage.Course__c, courseLanguage);
        }

        for(Id classId : classMap.keySet()) {
            Class__c etaclass = classMap.get(classId);
            Course__c course = courseMap.get(etaclass.Course__c);
            Course_Language__c courseLanguage = courseLanguageMap.get(course.Id);

            RequestWrapper rw = new RequestWrapper();
            rw.isNewEnrollment = false;
            rw.etaclass = etaclass;
            rw.course = course;
            rw.courseLanguage = courseLanguage;

            requestWrapperMap.put(etaclass.Id, rw);
        }

        Logger.pop();

        return requestWrapperMap;
    }

    public void loadAvailableAndEnrolledClasses(Map<Id, RequestWrapper> allClassesMap) {
        Logger.push('EnrollmentPageController' , 'loadAvailableAndEnrolledClasses');

        Enterprise_Training_Agreement__c eta = getETARecord();
        Contact contact = getContactRecord();

        Map<Id, List<Enrollment__c>> etaEnrollmentMap = TrainingUtil.getEnrollmentsForETA(new Set<Id> { eta.Id }, 
                                                                                            new Set<String> { contact.Email },
                                                                                            'Registered');
        
        if(etaEnrollmentMap.size() > 0 && etaEnrollmentMap.containsKey(eta.Id)) {
            Map<Id, Id> classCourseMap = new Map<Id, Id>();
            Map<Id, Id> courseClassMap = new Map<Id, Id>();
            Map<Id, Enrollment__c> enrollmentMap = new Map<Id, Enrollment__c>();

            for(Enrollment__c enrollment : etaEnrollmentMap.get(eta.Id)) {
                courseClassMap.put(enrollment.Class__r.Course__c, enrollment.Class__c);
                classCourseMap.put(enrollment.Class__c, enrollment.Class__r.Course__c);
                enrollmentMap.put(enrollment.Class__c, enrollment);
            }

            Map<Id, Class__c> classMap = new Map<Id, Class__c>([SELECT Id, Course__c, Course_Code__c,Open_Seats__c, 
                                                                    Format_Of_Class__c, Language__r.Name, Language__r.Language_Code__c, 
                                                                    Language__r.Language_Display_Name__c, Total_Seats_Taken__c 
                                                                FROM Class__c 
                                                                WHERE Id IN :classCourseMap.keySet()
                                                                AND Status__c = :TrainingUtil.STATUS_ACTIVE]);
            Map<Id, Course__c> courseMap = new Map<Id, Course__c>([SELECT Id 
                                                                    FROM Course__c 
                                                                    WHERE Id IN :courseClassMap.keySet()]);
            Map<Id, Course_Language__c> courseLanguageMap = new Map<Id, Course_Language__c>();

            for(Course_Language__c courseLanguage : [SELECT Id, Localized_Course_Name__c, Localized_Short_Description__c,
                                                        Course_Language__r.Language_Display_Name__c,
                                                        Localized_Pre_Requisite__c, Course__c, Course_Language__r.Name 
                                                    FROM Course_Language__c 
                                                    WHERE Course__c IN :courseClassMap.keySet() 
                                                    AND Course_Language__r.SF_ISO_Code__c = 'en_US']) {
                courseLanguageMap.put(courseLanguage.Course__c, courseLanguage);
            }

            for(Id classId : classMap.keySet()) {
                Class__c etaclass = classMap.get(classId);
                Course__c course = courseMap.get(etaclass.Course__c);
                Course_Language__c courseLanguage = courseLanguageMap.get(course.Id);

                RequestWrapper rw = new RequestWrapper();
                rw.isNewEnrollment = false;
                rw.etaclass = etaclass;
                rw.course = course;
                rw.courseLanguage = courseLanguage;
                rw.enrollment = enrollmentMap.get(classId);

                enrolledClassesMap.put(etaclass.Id, rw);
            }
        }

        // Get a map of <ETA, <Class, Enrollmentcount>>
        Map<Id, Map<Id, Integer>> etaClassCountMap = TrainingUtil.getConsumedSeatCountForETA(new Set<Id> { eta.Id }, 
                                                                                             allClassesMap.keySet());

        // Get ETA record type ids for Seat Based and Unlimited ETA
        Id seatBasedEtaRtId = Schema.SObjectType.Enterprise_Training_Agreement__c.getRecordTypeInfosByName().get('Seat-Based').getRecordTypeId();
        Id unlimitedEtaRtId = Schema.SObjectType.Enterprise_Training_Agreement__c.getRecordTypeInfosByName().get('Unlimited').getRecordTypeId();

        for(Id classId : allClassesMap.keySet()) {
            if(!enrolledClassesMap.containsKey(classId)) {
                RequestWrapper rw = allClassesMap.get(classId);
                // Process the class if we have a seat based ETA
                if(seatBasedEtaRtId == eta.RecordTypeId) {
                    Integer seatsTaken = 0;

                    if(etaClassCountMap.get(eta.Id) != null) {
                        seatsTaken = etaClassCountMap.get(eta.Id).get(classId);
                        seatsTaken = (seatsTaken == null ? 0 : seatsTaken);
                    }

                    // add to available class only if the total enrollments for this class < max seats on eta
                    if(seatsTaken == 0 || seatsTaken < eta.Max_Seats__c) {
                        availableClassesMap.put(classId, allClassesMap.get(classId));
                    }
                } else if(unlimitedEtaRtId == eta.RecordTypeId) {
                    // Process the class if we have a unlimited ETA
                    availableClassesMap.put(classId, allClassesMap.get(classId));
                }                
            }
        }

        Logger.pop();
    }

    public List<RequestWrapper> getAvailableClasses() {
        Logger.push('EnrollmentPageController', 'getAvailableClasses');

        List<RequestWrapper> rwList = new List<RequestWrapper>();
        if(!availableClassesMap.isEmpty()) {
            rwList = availableClassesMap.values();
            rwList.sort();
        }

        Logger.pop();

        return rwList;
    }

    private Enterprise_Training_Agreement__c getETARecord() {
        Logger.push('EnrollmentPageController', 'getETARecord');

        Enterprise_Training_Agreement__c eta = null;
        if(enrollmentRequest.Enterprise_Training_Agreement__c != null) {
            eta = [SELECT Max_Seats__c, RecordTypeId, Account_Name__r.Name 
                    FROM Enterprise_Training_Agreement__c
                    WHERE Id = :enrollmentRequest.Enterprise_Training_Agreement__c Limit 1];
        }

        Logger.pop();

        return eta;
    }

    private Contact getContactRecord() {
        Logger.push('EnrollmentPageController', 'getContactRecord');

        Contact contact = null;
        if(enrollmentRequest.Contact__c != null) {
            contact = [SELECT FirstName, LastName, Email FROM Contact WHERE Id = :enrollmentRequest.Contact__c LIMIT 1];
        }

        Logger.pop();

        return contact;
    }

    private Boolean isEnrolleBlacklisted() {
        Logger.push('EnrollmentPageController', 'isEnrolleBlacklisted');
        Contact contact = getContactRecord();
        Logger.pop();
        return TrainingUtil.isEnrolleeBlacklisted(enrollmentRequest.Enterprise_Training_Agreement__c, contact.Email);
    }

    private Boolean isEnrolleFromAllowedDomain() {
        Logger.push('EnrollmentPageController', 'isEnrolleFromAllowedDomain');

        Boolean isAllowed = true;

        Map<Id,String> etaToEnrolleeEmailMap = new Map<Id,String>();

        Map<id,Map<string,Boolean>> etaToEmailToIsAllowedMap = new Map<id,Map<string,Boolean>>();

        Contact contact = getContactRecord();

        if(enrollmentRequest.Enterprise_Training_Agreement__c != null){
            etaToEnrolleeEmailMap.put(enrollmentRequest.Enterprise_Training_Agreement__c, contact.Email);
            etaToEmailToIsAllowedMap = TrainingUtil.areEnrolleeFromAllowedDomain(etaToEnrolleeEmailMap);

            if(!etaToEmailToIsAllowedMap.containsKey(enrollmentRequest.Enterprise_Training_Agreement__c)){
                isAllowed = false;
            }
        }

        Logger.pop();

        return isAllowed;
    }
}