objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Mark for Deletion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Enterprise_Training_Agreement__c.object
<CustomObject>
    <label>Enterprise Training Agreement</label>
    <nameField>
        <label>Enterprise Training Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enterprise Training Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Training_Agreement_Class_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Class__c.Format_Of_Class__c</field>
                <operation>equals</operation>
                <value>Self-Paced</value>
            </filterItems>
            <filterItems>
                <field>Class__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enterprise Agreement</relationshipLabel>
        <relationshipName>Training_Agreement_Class</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Training_Agreement_Class_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Agreement Class Relationship</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Training Agreement Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Agreement Class Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ETAgreementDml.cls
/**
 *@author Original: Sagar Talele - Cloud Sherpas/Mathworks, Last Modified: Sagar Talele - Cloud Sherpas/Mathworks
 *@date Original:   29 July 2015, Last Modified: 29 July 2015
 *@description:     This is a Dml class for Enterprise_Training_Agreement__c Object.
 */
public class ETAgreementDml {
    
    /**
     *@author Original: Sagar Talele - Cloud Sherpas/Mathworks, Last Modified: Sagar Talele - Cloud Sherpas/Mathworks
     *@date Original: 29 July 2015, Last Modified: 29 July 2015
     *@description: Method that handles Dml events for Enterprise_Training_Agreement__c object.
     */
    public void insertTAgreementClassRelationship(List<Enterprise_Training_Agreement__c>ETAgreemetLst){
    
        Logger.push('insertTAgreementClassRelationship','ETAgreementDml ');
        
        //instantiating the List which contains list of Class__c records for status Active and record Type Self-paced
        List<Class__c> classlist = new List<Class__c> ();
        classlist = [Select Id,Name,Status__c,RecordType.Name From Class__c Where Status__c = 'Active' And RecordType.Name = 'Self-Paced'];
        //instantiating the List which contains list of Training_Agreement_Class_Relationship__c records
        List<Training_Agreement_Class_Relationship__c> TAgreementClassRelList = new List<Training_Agreement_Class_Relationship__c>();
        
        for(Enterprise_Training_Agreement__c ETAgreementObj : ETAgreemetLst){
            for(Class__c classObj : classlist){
                Training_Agreement_Class_Relationship__c TAgreementClassRelObj = new Training_Agreement_Class_Relationship__c();
                TAgreementClassRelObj.Class__c = classObj.Id;
                TAgreementClassRelObj.Enterprise_Training_Agreement__c = ETAgreementObj.Id;
                TAgreementClassRelList.add(TAgreementClassRelObj);
            }
        }
        
        //check list is not empty
        if(!TAgreementClassRelList.isEmpty()){
            try{
            insert TAgreementClassRelList;
            }
            catch(DMLException ex){
                for (Integer i = 0; i < ex.getNumDml(); i++) {
                 //Process exception here
                Logger.debugException('Error in inserting Training Agreement Class Relationship Record Object:'+ex.getDmlMessage(i)+ 'for ID:'+ex.getDmlId(i));
                }
            }
        }
        
        Logger.pop();
    }
}