objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Mark for Deletion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Enrollment__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>Class_Enrollees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Enrollment_Code__c</fullName>
        <label>Enrollment Code</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bulk Enrollment</fullName>
                </value>
                <value>
                    <fullName>Manual Enrollment</fullName>
                </value>
                <value>
                    <fullName>Self-Enrollment Portal</fullName>
                </value>
                <value>
                    <fullName>Commerce Enrollment</fullName>
                </value>
                <value>
                    <fullName>External Enrollment</fullName>
                </value>
                <value>
                    <fullName>Migration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Enrollment_Code__c.object
<CustomObject>
    <description>This object represents the code associated with an Enterprise Training Agreement and holds the status the enrollment code is in.</description>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <description>Enterprise Training Agreement the Enrollment Code is associated with.</description>
        <inlineHelpText>Enterprise Training Agreement the Enrollment Code is associated with.</inlineHelpText>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Enrollment Codes</relationshipLabel>
        <relationshipName>Enrollment_Codes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Code</label>
    <nameField>
        <displayFormat>EC-{0000}</displayFormat>
        <label>Enrollment Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Enrollment_Request__c.object
<CustomObject>
    <description>Staging object to ingest requests for class enrollment under Enterprise Training Agreements from multiple sources including manual internal enrollments, self-enrollments via a portal and bulk enrollments via a file load. Records that are processed through this object will ultimately result in records being created in the Enrollment object.</description>
    <fields>
        <fullName>Batch_ID__c</fullName>
        <inlineHelpText>Identifier used to group enrollment requests together for purposes of creating summary email notifications once all requests have been processed</inlineHelpText>
        <label>Batch ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Class to enroll Contact in</inlineHelpText>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enrollment Requests</relationshipLabel>
        <relationshipName>Enrollment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Contact to be enrolled</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Enrollment Requests</relationshipLabel>
        <relationshipName>Enrollment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enrollment_Code__c</fullName>
        <description>This is not a direct lookup to the Enrollment Code object so it can support querying for records by the Code itself rather than requiring the Salesforce ID of the Code.</description>
        <inlineHelpText>Code used to identify the Enterprise Training Agreement the Enrollment Request should be made for</inlineHelpText>
        <label>Enrollment Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Resulting Enrollment record from this Enrollment Request - should be set after email notification is sent</inlineHelpText>
        <label>Enrollment</label>
        <referenceTo>Enrollment__c</referenceTo>
        <relationshipLabel>Enrollment Requests</relationshipLabel>
        <relationshipName>Enrollment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Training agreement the Enrollment should be created under</inlineHelpText>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Enrollment Requests</relationshipLabel>
        <relationshipName>Enrollment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exception_Reason__c</fullName>
        <inlineHelpText>Details if an exception occurred during processing</inlineHelpText>
        <label>Exception Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <inlineHelpText>How did this Enrollment Request get added to the queue?</inlineHelpText>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bulk Enrollment</fullName>
                </value>
                <value>
                    <fullName>Manual Enrollment</fullName>
                </value>
                <value>
                    <fullName>Self-Enrollment Portal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Pending Notification</fullName>
                </value>
                <value>
                    <fullName>Process Manually</fullName>
                </value>
                <value>
                    <fullName>No Action Planned</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Exception</fullName>
                </value>
                <value>
                    <fullName>Reprocess</fullName>
                </value>
                <value>
                    <fullName>Pending CDS Lookup</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Request</label>
    <nameField>
        <displayFormat>ER-{0}</displayFormat>
        <label>Enrollment Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Enterprise_Training_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Term_End_Date__c</fullName>
        <description>Agreement expiration date</description>
        <label>Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Term_Start_Date__c</fullName>
        <description>The date the agreement becomes effective</description>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <label>Enterprise Training Agreement</label>
    <nameField>
        <label>Enterprise Training Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enterprise Training Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EnrollmentRequestToEnrollmentBatch.cls
/**
* @author           Pranav Raulkar
* @date             5-May-2016
* @description      This batch processes all the enrollment request records that are fully populated with
*                   a valid contact, class and enterprise training agreement with no exceptions encountered
*                   and creates enrollments for each enrollment request.
* @revision         1.0 - Initial version
                    Archana Suryawanshi - Changed Implemented Interface from Batchable to Queueable and did related changes
                                          in other methods.
*/
global class EnrollmentRequestToEnrollmentBatch implements Queueable {
//global class EnrollmentRequestToEnrollmentBatch implements Queueable,Schedulable {
    // Query to run on start of the batch
    private String query;
    private Set<Id> enrolReqIds;

    /**
    * @author           Pranav Raulkar
    * @modified by      Archana Suryawanshi
    * @date             5-May-2016
    * @modified date    9-May-2016
    * @description      Constructor
    */
    public EnrollmentRequestToEnrollmentBatch(Set<Id> enrolReqIdSet) {
        Logger.push('EnrollmentRequestToEnrollmentBatch', 'EnrollmentRequestToEnrollmentBatch');
        
        enrolReqIds = enrolReqIdSet;
        
        Logger.pop();
    }
    
   

    /**
    * @author           Pranav Raulkar
    * @modified by      Archana Suryawanshi
    * @date             5-May-2016
    * @modified date    11-May-2016
    * @description      Execute method processes all the records from enrolReqIds and calls the utility method which creates  
    *                   enrollment for each enrollment request. The returned enrollments are inserted and any errors encountered
    *                   during the insert are logged against the enrollment request as well as in the debugs
    *                   (only for failed records, all the other requests continue processing).
    * @param            qContext - The Queueable Context
    */
    global void execute(QueueableContext qContext) {
        Logger.push('EnrollmentRequestToEnrollmentBatch', 'execute');
        
        List<Enrollment_Request__c> enrollmentLst = [SELECT Id, Batch_ID__c, Class__c, Contact__c, Enrollment_Code__c,
                                                     Enterprise_Training_Agreement__c, Enterprise_Training_Agreement__r.Term_Start_Date__c, 
                                                     Enterprise_Training_Agreement__r.Term_End_Date__c, Enterprise_Training_Agreement__r.CurrencyIsoCode,
                                                     Enterprise_Training_Agreement__r.Order_Number__c, Source__c, Status__c  
                                                     FROM Enrollment_Request__c WHERE Id IN :enrolReqIds];

        //Call the createEnrollmentFromEnrollmentRequest Method to create the Enrollment.
        List<Enrollment__c> enrollmentsToInsert = TrainingUtil.createEnrollmentFromEnrollmentRequest(enrollmentLst);

        // Partial insert the enrollments
        List<Database.SaveResult> srList = Database.insert(enrollmentsToInsert, false);

        // List to hold any enrollment requests to be updated with status and error messages
        List<Enrollment_Request__c> erToUpdate = new List<Enrollment_Request__c>();

        for(Integer i = 0; i < srList.size(); i++) {
            Database.SaveResult sr = srList[i];
            
           
            
            // Check if we have any failures. We need to update the status and error message
            // on the original enrollment request.
            if(!sr.isSuccess()) {
                Database.Error dbErr = sr.getErrors()[0];
                Enrollment_Request__c er = enrollmentLst[i];
                er.Status__c = 'Exception';
                er.Exception_Reason__c = dbErr.getMessage();
                erToUpdate.add(er);
            }
            else{
                Enrollment_Request__c er = enrollmentLst[i];
                er.Status__c = 'Pending Notification';
                er.Exception_Reason__c ='';
                er.Enrollment__c = sr.getId();
                erToUpdate.add(er);                
            }
        }

        // Update the enrollment requests with exception status and exeption message
        if(!erToUpdate.isEmpty()) {
            try {
                update erToUpdate;
            } catch(Exception ex) {
                Logger.debugException(ex);
            }       
        }
        //call batch
        if(!enrolReqIds.isEmpty() && !Test.isRunningTest()){
            System.enqueueJob(new EmailToEnrolleesBatch (enrolReqIds));
        }
         
        Logger.pop();
    }
    
   /* global void execute(SchedulableContext ctx) {
    }
*/
    
    
}