objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>ClassCriteriaBE__c</fullName>
        <formula>Course__r.Course_Code__c+Format_Of_Class__c+Language__r.Language_Code__c</formula>
        <label>ClassCriteriaBE</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class_Format__c</fullName>
        <label>Class Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Instructor Led Classroom</fullName>
                </value>
                <value>
                    <fullName>Instructor Led Online</fullName>
                </value>
                <value>
                    <fullName>Self-Paced Online</fullName>
                </value>
                <value>
                    <fullName>Certification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <label>Part Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Mark for Deletion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>MathWorks_Account_ID__c</fullName>
        <label>MathWorks Account ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Course_Code__c</fullName>
        <label>Part Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <default>true</default>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <recordTypes>
        <fullName>Training</fullName>
        <active>true</active>
        <description>Record type to create non certification course</description>
        <label>Training</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Enrollment_Code__c.object
<CustomObject>
    <description>This object represents the code associated with an Enterprise Training Agreement and holds the status the enrollment code is in.</description>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <description>Enterprise Training Agreement the Enrollment Code is associated with.</description>
        <inlineHelpText>Enterprise Training Agreement the Enrollment Code is associated with.</inlineHelpText>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Enrollment Codes</relationshipLabel>
        <relationshipName>Enrollment_Codes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Code</label>
    <nameField>
        <displayFormat>EC-{0000}</displayFormat>
        <label>Enrollment Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Enrollment_Request__c.object
<CustomObject>
    <description>Staging object to ingest requests for class enrollment under Enterprise Training Agreements from multiple sources including manual internal enrollments, self-enrollments via a portal and bulk enrollments via a file load. Records that are processed through this object will ultimately result in records being created in the Enrollment object.</description>
    <fields>
        <fullName>Class_Format__c</fullName>
        <description>Current use case is Self-Paced only but adding additional options for future expansion</description>
        <inlineHelpText>Format of the Class this Enrollment Request is for -  combined with the Course Code and Language to identify the specific Class to enroll in</inlineHelpText>
        <label>Class Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Self-Paced</fullName>
                </value>
                <value>
                    <fullName>Distance Learning</fullName>
                </value>
                <value>
                    <fullName>Instructor Led</fullName>
                </value>
                <value>
                    <fullName>Exam</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Class to enroll Contact in</inlineHelpText>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enrollment Requests</relationshipLabel>
        <relationshipName>Enrollment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Contact to be enrolled</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Enrollment Requests</relationshipLabel>
        <relationshipName>Enrollment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>Not a direct lookup to Course object so requests can be made via the Code rather than requiring the Salesforce ID of the Course</description>
        <inlineHelpText>Code used to identify the Course the Enrollment Code is being made for - this code plus the Language and Format will identify the specific Class to enroll in</inlineHelpText>
        <label>Course Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <inlineHelpText>Email Address of the Enrollee - used to find the Contact in Salesforce or CDS if the Contact is not identified explicitly</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Enrollment_Code__c</fullName>
        <description>This is not a direct lookup to the Enrollment Code object so it can support querying for records by the Code itself rather than requiring the Salesforce ID of the Code.</description>
        <inlineHelpText>Code used to identify the Enterprise Training Agreement the Enrollment Request should be made for</inlineHelpText>
        <label>Enrollment Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Training agreement the Enrollment should be created under</inlineHelpText>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Enrollment Requests</relationshipLabel>
        <relationshipName>Enrollment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exception_Reason__c</fullName>
        <inlineHelpText>Details if an exception occurred during processing</inlineHelpText>
        <label>Exception Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language_Code__c</fullName>
        <inlineHelpText>ISO Code of the Language the Enrollment Request is for - used to identify the correct Class when combined with the Course Code and Format</inlineHelpText>
        <label>Language Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Pending Notification</fullName>
                </value>
                <value>
                    <fullName>Process Manually</fullName>
                </value>
                <value>
                    <fullName>No Action Planned</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Exception</fullName>
                </value>
                <value>
                    <fullName>Reprocess</fullName>
                </value>
                <value>
                    <fullName>Pending CDS Lookup</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Request</label>
    <nameField>
        <displayFormat>ER-{0}</displayFormat>
        <label>Enrollment Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Enterprise_Training_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <description>Check if the Agreement is Active or not. It is based on start date and end date.</description>
        <formula>(TODAY() &gt;=  Term_Start_Date__c ) &amp;&amp; ( TODAY() &lt;=  Term_End_Date__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Enterprise Training Agreement</label>
    <nameField>
        <label>Enterprise Training Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enterprise Training Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Language__c.object
<CustomObject>
    <fields>
        <fullName>Language_Code__c</fullName>
        <label>Language Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Language</label>
    <nameField>
        <label>Language</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Training_Agreement_Class_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>ClassCriteriaBE__c</fullName>
        <formula>Class__r.Course__r.Course_Code__c+Class__r.Format_Of_Class__c+Class__r.Language__r.Language_Code__c+CASESAFEID(Enterprise_Training_Agreement__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ClassCriteriaBE</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Class__c.Format_Of_Class__c</field>
                <operation>equals</operation>
                <value>Self-Paced</value>
            </filterItems>
            <filterItems>
                <field>Class__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enterprise Agreement</relationshipLabel>
        <relationshipName>Training_Agreement_Class</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>Part Number</description>
        <formula>Class__r.Course__r.Course_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Part Number</inlineHelpText>
        <label>Course Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Training_Agreement_Class_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Agreement Class Relationship</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Training Agreement Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Agreement Class Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EnrollmentRequestDml.cls
/** 
 *@author Original: Archana Suryawanshi - Cloud Sherpas/Mathworks, Last Modified: Archana Suryawanshi  - Cloud Sherpas/Mathworks
 *@date Original: 4 April 2015, Last Modified:  25 April 2016
 *@description This  is Dml class for 'EnrollmentRequestMasterTrigger'. 
 */ 
public class EnrollmentRequestDml {
  
   /**
    * @author Original: Archana Suryawanshi - Cloud Sherpas/Mathworks
    * @date Original: 25 April 2016, Last Modified: 25 April 2016
    * @description: Method to validate Enterprise Training Agreement on Enrollment Request
    * @param : reqList collection of Enrollment Request records 
    **/
    public list<Enrollment_Request__c> validateETAOnEnrollmentReq(list<Enrollment_Request__c> reqList){
        Logger.push('validateETAOnEnrollmentReq', 'EnrollmentRequestDml');
        
        List<Enrollment_Request__c> eReqListwithETA = new List<Enrollment_Request__c>();
        List<Enrollment_Request__c> eReqListwithoutETA = new List<Enrollment_Request__c>();
        List<String> etaCodesLst = new List<String>();
        Set<Enrollment_Code__c> enCodeObjSet = new Set<Enrollment_Code__c>();
        Map<String,Enrollment_Code__c> eCodeToECodeObjMap = new Map<String,Enrollment_Code__c>();
        Map<id,TrainingUtil.ValidationStatus> codeToStatusMap = new  Map<id,TrainingUtil.ValidationStatus>();
        
        //Get list of Enrollment_Request__c not having Enterprise_Training_Agreement__c 
        //and also when the status on the enrollment request is reprocess, so that validations can be run again          
        for(Enrollment_Request__c reqObj:reqList){
            if(reqObj.Enterprise_Training_Agreement__c!=null && reqObj.Status__c != 'Reprocess'){
                eReqListwithETA.add(reqObj);                
            }
            else{
                eReqListwithoutETA.add(reqObj); 
                etaCodesLst.add(reqObj.Enrollment_Code__c);
            }            
        }
        
        //Query Enrollment_Code__c
        enCodeObjSet = new Set<Enrollment_Code__c>([select id,Enterprise_Training_Agreement__c,Code__c,Enterprise_Training_Agreement__r.Is_Active__c,Status__c 
                                                    from Enrollment_Code__c where Code__c in:etaCodesLst]);
        
        //Get Map of Enrollment code to its Status
        codeToStatusMap = TrainingUtil.validateEnrollmentCodes(enCodeObjSet);
        
        //Get eCodeToECodeObjMap
        for(Enrollment_Code__c codeObj:enCodeObjSet){   
            eCodeToECodeObjMap.put(codeObj.Code__c,codeObj);        
        }
        
        //validate Enterprise_Training_Agreement__c
        for(Enrollment_Request__c reqObj:eReqListwithoutETA){
            if(eCodeToECodeObjMap.get(reqObj.Enrollment_Code__c)!=null) {
                //Check if status is REVOKED
                if(codeToStatusMap.get(eCodeToECodeObjMap.get(reqObj.Enrollment_Code__c).id)!=TrainingUtil.ValidationStatus.REVOKED){
                    //Check if status is INACTIVE_ETA_CODE
                    if(codeToStatusMap.get(eCodeToECodeObjMap.get(reqObj.Enrollment_Code__c).id)!=TrainingUtil.ValidationStatus.INACTIVE_ETA_CODE){
                        //Check if status is VALID
                        if(codeToStatusMap.get(eCodeToECodeObjMap.get(reqObj.Enrollment_Code__c).id)==TrainingUtil.ValidationStatus.VALID){
                            reqObj.Enterprise_Training_Agreement__c = eCodeToECodeObjMap.get(reqObj.Enrollment_Code__c).Enterprise_Training_Agreement__c;    
                            eReqListwithETA.add(reqObj);
                        }
                    } 
                    else{
                        reqObj.Enterprise_Training_Agreement__c = eCodeToECodeObjMap.get(reqObj.Enrollment_Code__c).Enterprise_Training_Agreement__c;
                        reqObj.Status__c = 'Exception'; 
                        reqObj.Exception_Reason__c = 'Inactive Agreement';       
                    }
                }
                else{
                    reqObj.Enterprise_Training_Agreement__c = eCodeToECodeObjMap.get(reqObj.Enrollment_Code__c).Enterprise_Training_Agreement__c;
                    reqObj.Status__c = 'Exception'; 
                    reqObj.Exception_Reason__c = 'Enrollment Code Revoked';   
                }
            }
            else{
                reqObj.Status__c = 'Exception'; 
                reqObj.Exception_Reason__c = 'Invalid Enrollment Code';   
            }
        }
        
        Logger.pop();
        return eReqListwithETA;            
    }
    
    /**
    * @author Original: Archana Suryawanshi - Cloud Sherpas/Mathworks
    * @date Original: 22 April 2016, Last Modified: 22 April 2016
    * @description: Method to validate Contact on Enrollment Request
    * @param : reqList collection of Enrollment Request records 
    **/
    public list<Enrollment_Request__c>  validateContactOnEnrollmentReq(list <Enrollment_Request__c> reqList){
        Logger.push('validateContactOnEnrollmentReq', 'EnrollmentRequestDml');
        
        List<Enrollment_Request__c> eReqListwithCon = new List<Enrollment_Request__c>();
        List<Enrollment_Request__c> eReqListwithoutCon = new List<Enrollment_Request__c>();
        List<Enrollment_Request__c> eReqListToDoCDSLookup = new List<Enrollment_Request__c>();
        Set<String> etaIdSet = new Set<String>();
        List<String> emailLst = new List<String>();
        Map<String,contact> emailToConMap = new Map<String,contact>();
        Map<id,Map<string,Boolean>> enrolleeBlacklistMap = new Map<id,Map<string,Boolean>>();
        Map<id,Map<string,Boolean>> enrolleeAllowedDomainMap = new Map<id,Map<string,Boolean>>();
        Map<Id,String> etaIdToEnrolleeEmailMap = new Map<Id,String>();
        
        //Check if Contact__c is already Populated
        for(Enrollment_Request__c reqObj:reqList){
        
            if(reqObj.Contact__c!=null && reqObj.Status__c != 'Reprocess'){
                reqObj.Exception_Reason__c = '';
                reqObj.Status__c = 'Processing';
                eReqListwithCon.add(reqObj);                
            }
            else{
                
                eReqListwithoutCon.add(reqObj); 
                emailLst.add(reqObj.Email__c);
                etaIdSet.add(reqObj.Enterprise_Training_Agreement__c);
                etaIdToEnrolleeEmailMap.put(reqObj.Enterprise_Training_Agreement__c,reqObj.Email__c);
            }            
        }
           
        //Query for contacts having email address in list emailLst
        for(Contact conObj:[select id,Email,MathWorks_Account_ID__c from Contact where email in:emailLst]){
            emailToConMap.put(conObj.Email,conObj);            
        }
        
        //Get Map of Blacklisted Enrollee from TrainingUtil
        enrolleeBlacklistMap = TrainingUtil.areEnrolleeBlacklisted(etaIdSet, emailToConMap.keyset());
        
        //Get Map of Allowed domain Enrollee from TrainingUtil
        enrolleeAllowedDomainMap = TrainingUtil.areEnrolleeFromAllowedDomain(etaIdToEnrolleeEmailMap);
       
        for(Enrollment_Request__c reqObj:eReqListWithoutCon){
            //Check if emailToConMap contains email address 
            if(emailToConMap.get(reqObj.Email__c)!=null){
                
                //Check if contact's MathWorks_Account_ID__c is not null
                if((emailToConMap.get(reqObj.Email__c).MathWorks_Account_ID__c)!=null){ 
                   
                    //Check for Enrollee Blacklist for the related Training Agreement
                    if(!enrolleeBlacklistMap.containsKey(reqObj.Enterprise_Training_Agreement__c) || !enrolleeBlacklistMap.get(reqObj.Enterprise_Training_Agreement__c).containsKey(reqObj.Email__c)){
                        
                        //Check Contact's email address domain does not exist in the Allowed Domains list for the related Training Agreement
                        if(enrolleeAllowedDomainMap.containsKey(reqObj.Enterprise_Training_Agreement__c) && enrolleeAllowedDomainMap.get(reqObj.Enterprise_Training_Agreement__c).containsKey(reqObj.Email__c)){
                            reqObj.Contact__c = emailToConMap.get(reqObj.Email__c).id;
                            reqObj.Exception_Reason__c = '';
                            reqObj.Status__c = 'Processing';                           
                            eReqListwithCon.add(reqObj);      
                        }
                        else{
                            reqObj.Contact__c = emailToConMap.get(reqObj.Email__c).id;
                            reqObj.Status__c = 'Exception'; 
                            reqObj.Exception_Reason__c = 'Invalid Email Domain';        
                        }
                    }
                    else{
                        reqObj.Contact__c = emailToConMap.get(reqObj.Email__c).id;
                        reqObj.Status__c = 'Exception'; 
                        reqObj.Exception_Reason__c = 'Contact Blacklisted';    
                    }
                } 
                else{
                    reqObj.Contact__c = emailToConMap.get(reqObj.Email__c).id;
                    reqObj.Status__c = 'Exception'; 
                    reqObj.Exception_Reason__c = 'No MW Profile';
                }
            }
            else{
                reqObj.Status__c = 'Exception'; 
                reqObj.Exception_Reason__c = 'Contact not found with the email';
                eReqListToDoCDSLookup.add(reqObj);
            }
        }       
        Logger.pop();
        return eReqListwithCon;
          
    }
    
    /**
    * @author Original: Archana Suryawanshi - Cloud Sherpas/Mathworks
    * @date Original: 22 April 2016, Last Modified: 22 April 2016
    * @description: Method to validate Class on Enrollment Request
    * @param : reqList collection of Enrollment Request records 
    **/
    public list<Enrollment_Request__c>  validateClassOnEnrollmentReq(list <Enrollment_Request__c> reqList){
        Logger.push('validateClassOnEnrollmentReq', 'EnrollmentRequestDml');
        
        List<Enrollment_Request__c> eReqListwithClass = new List<Enrollment_Request__c>();
        List<Enrollment_Request__c> eReqListwithoutClass = new List<Enrollment_Request__c>();
        List<Class__c> classLst= new List<Class__c>();
        Set<Id> classObjLst= new Set<Id>();
        List<Training_Agreement_Class_Relationship__c> tacrObjlst = new List<Training_Agreement_Class_Relationship__c>();
        Set<Id> etaIdSet = new Set<Id>();
        //Map to contain Id of Class Object with Enterprise Training Agreement Object with List of Enrollment.
        Map<Id,Map<Id, Integer>> clsEtaEnrolMap = new Map<Id,Map<Id, Integer>>();
        
        Map<String,Training_Agreement_Class_Relationship__c> tacrMap = new  Map<String,Training_Agreement_Class_Relationship__c>();
        Map<String,class__c> classMap = new  Map<String,class__c>();
        
        Set<String> criteriaToCompare = new Set<String>();
        Set<String> criteriaToCompareInEtar = new Set<String>();
        
        //Enrollment Seat-Based Record Type Id.
        Id eTARecTypeId;
         
        //Quering the RecordType Id of Seat-Based Enterprise Training Agreement Object
        eTARecTypeId = Schema.SObjectType.Enterprise_Training_Agreement__c.getRecordTypeInfosByName().get('Seat-Based').getRecordTypeId();
         
        
        //Check if class__c is already Populated
        for(Enrollment_Request__c reqObj:reqList){
            if(reqObj.class__c!=null && reqObj.Status__c != 'Reprocess'){
                eReqListwithClass.add(reqObj);                
            }
            else{
                eReqListwithoutClass.add(reqObj);
                etaIdSet.add(reqObj.Enterprise_Training_Agreement__c);
                criteriaToCompare.add(reqObj.Course_Code__c+reqObj.Class_Format__c+reqObj.Language_Code__c);
                criteriaToCompareInEtar.add(reqObj.Course_Code__c+reqObj.Class_Format__c+reqObj.Language_Code__c+reqObj.Enterprise_Training_Agreement__c);
            }
        }
        
        system.debug(eReqListwithClass);
         system.debug(eReqListwithoutClass);
        
        //Find matching class by criteriaToCompare
        for(class__C classObj:[SELECT ClassCriteriaBE__c
                               FROM class__c
                               WHERE ClassCriteriaBE__c in :criteriaToCompare]){
            classMap.put((classObj.ClassCriteriaBE__c).tolowercase(),classObj);
        }
        
        //Find matching class by criteriaToCompareInEtar
        for(Training_Agreement_Class_Relationship__c tacrObj:[SELECT Class__r.Course__c,Class__c,Class__r.Course__r.Course_Code__c,class__r.Enrollee_Seats_Taken__c,
                                                              Class__r.Format_Of_Class__c,Class__r.Language__r.Language_Code__c,Class__r.status__c,
                                                              Enterprise_Training_Agreement__r.Max_Seats__c ,Enterprise_Training_Agreement__c,ClassCriteriaBE__c,
                                                              Enterprise_Training_Agreement__r.RecordType.Name
                                                              FROM Training_Agreement_Class_Relationship__c
                                                              WHERE ClassCriteriaBE__c in :criteriaToCompareInEtar]){
            tacrMap.put((tacrObj.ClassCriteriaBE__c).tolowercase(),tacrObj);
            classObjLst.add(tacrObj.Class__c);
        }
        
        system.debug('classObjLst'+classObjLst);
        system.debug('etaIdSet'+etaIdSet);
        clsEtaEnrolMap=TrainingUtil.getConsumedSeatCountForETA(etaIdSet,classObjLst);
        
        system.debug('clsEtaEnrolMap'+clsEtaEnrolMap);
        
        for(Enrollment_Request__c reqObj:eReqListwithoutClass){
        
           string keyCriteria = (reqObj.Course_Code__c+reqObj.Class_Format__c+reqObj.Language_Code__c).tolowercase();
           string keyEtaCriteria = (reqObj.Course_Code__c+reqObj.Class_Format__c+reqObj.Language_Code__c+reqObj.Enterprise_Training_Agreement__c).tolowercase();
          
           //Check if class Exist in org
           if(classMap.containsKey(keyCriteria)){
               
               //Check if Class is not listed in the Training Agreement Class Relationship object for the Agreement,
                if(tacrMap.containsKey(keyEtaCriteria)){
                    
                    //Check if the Class is inactive    
                    if(tacrMap.get(keyEtaCriteria).class__r.status__c == 'Active'){ 
                        
                           
                            //Check if the Class is found but the Enterprise Training Agreement is Seat-Based and the number of seats would be go beyond the threshold
                            if(!clsEtaEnrolMap.containsKey(tacrMap.get(keyEtaCriteria).Enterprise_Training_Agreement__c)){
                                reqObj.Class__c = tacrMap.get(keyEtaCriteria).class__c;
                                eReqListwithClass.add(reqObj);
                            }
                            else{
                            
                                if(((clsEtaEnrolMap.get(tacrMap.get(keyEtaCriteria).Enterprise_Training_Agreement__c).get(tacrMap.get(keyEtaCriteria).class__c))<(tacrMap.get(keyEtaCriteria).Enterprise_Training_Agreement__r.Max_Seats__c))){
                                    reqObj.Class__c = tacrMap.get(keyEtaCriteria).class__c;
                                    eReqListwithClass.add(reqObj);
                                }
                                else{
                                     reqObj.Status__c = 'Exception'; 
                                     reqObj.Exception_Reason__c = 'Seat-Based Class Is Full'; 
                                     reqObj.Class__c = tacrMap.get(keyEtaCriteria).class__c;
                                    
                                }
                            
                            }
                        }
                        else{
                            reqObj.Status__c = 'Exception'; 
                            reqObj.Exception_Reason__c = 'InActive Class';      
                        }
                    }
                else{
                        reqObj.Status__c = 'Exception'; 
                        reqObj.Exception_Reason__c = 'Class Not Part of Training Agreement';     
                }
            }      
            else{
                reqObj.Status__c = 'Exception'; 
                reqObj.Exception_Reason__c = 'InValid Class'; 
            }              
        }
        Logger.pop();   
        return eReqListwithClass;
    }
    
    /**
    * @author       Pranav Raulkar
    * @date         5-May-2016
    * @description  Sets the GUID on the enrollment requests created. 
    *               The same GUID is stamped on all the enrollment requests created in a context.   
    * @param        enrollmentRequestList - List of Enrollment_Request__c created
    */
    public void setGUIDOnEnrollmentRequests(List<Enrollment_Request__c> enrollmentRequestList) {
        Logger.push('EnrollmentRequestDml', 'setGUIDOnEnrollmentRequests');

        if(enrollmentRequestList != null && enrollmentRequestList.size() > 0) {
            String guid = TrainingUtil.generateGUID();
            for(Enrollment_Request__c er : enrollmentRequestList) {
                er.Batch_Id__c = guid;
            }
        }

        Logger.pop();
    }
}