objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Class_Format__c</fullName>
        <label>Class Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Instructor Led Classroom</fullName>
                </value>
                <value>
                    <fullName>Instructor Led Online</fullName>
                </value>
                <value>
                    <fullName>Self-Paced Online</fullName>
                </value>
                <value>
                    <fullName>Certification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Instructor_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instructor User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Classes_Instructor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Instructor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Instructor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>PrimInstClasses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publish_To_Web__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Publish To Web</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sponsor_Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sponsor Office</label>
        <referenceTo>Sponsor_Office__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Mark for Deletion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Time_Zone_Canonical__c</fullName>
        <label>Time Zone Canonical</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <label>Time Zone</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Training_Time_Zone</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Training_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training Location</label>
        <referenceTo>Training_Location__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Publish_to_Web__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Publish to Web</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <default>true</default>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <recordTypes>
        <fullName>Training</fullName>
        <active>true</active>
        <description>Record type to create non certification course</description>
        <label>Training</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Course_Language__c.object
<CustomObject>
    <fields>
        <fullName>Course_Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Course Languages</relationshipLabel>
        <relationshipName>Course_Languages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Languages</relationshipLabel>
        <relationshipName>Course_Languages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Localized_Course_Name__c</fullName>
        <inlineHelpText>Translated version of the English Course Name into the Language this record represents</inlineHelpText>
        <label>Localized Course Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UniqueCourseLanguage__c</fullName>
        <formula>CASESAFEID(Course__c) +&apos;&apos;+ CASESAFEID(Course_Language__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UniqueCourseLanguage</label>
        <type>Text</type>
    </fields>
    <label>Course Language</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Course Language Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Enrollment__c.object
<CustomObject>
    <fields>
        <fullName>Class_Format__c</fullName>
        <formula>TEXT(Class__r.Class_Format__c)</formula>
        <label>Class Format</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>Class_Enrollees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Language__c.object
<CustomObject>
    <label>Language</label>
    <nameField>
        <label>Language</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sponsor_Office__c.object
<CustomObject>
    <fields>
        <fullName>Class_Default_End_Time__c</fullName>
        <defaultValue>&apos;5:00 PM&apos;</defaultValue>
        <inlineHelpText>Enter the time in this format (HH:MM AM)</inlineHelpText>
        <label>Class Default End Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class_Default_Start_Time__c</fullName>
        <defaultValue>&apos;9:00 AM&apos;</defaultValue>
        <inlineHelpText>Enter the time in this format (HH:MM AM)</inlineHelpText>
        <label>Class Default Start Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class_Default_Time_Zone__c</fullName>
        <label>Class Default Time Zone</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Training_Time_Zone</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Default_Class_Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Default Class Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Sponsor Offices</relationshipLabel>
        <relationshipName>Sponsor_Office_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sponsor Office</label>
    <nameField>
        <label>Sponsor Office</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sponsor Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Training_Agreement_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings related to Enterprise Training Agreements for Customer Training</description>
    <fields>
        <fullName>Auto_Create_Class_Association__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This check box value decides whether we have to create Training_Agreement_Class_Relationship__c records or not</description>
        <label>Auto Create Class Association</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Class_Prevent_Defaults__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be used for data migration to prevent setting defaults on the class from sponsor office and course language.
If the value is checked, then the defaults will not be set.</description>
        <label>Class Prevent Defaults</label>
        <type>Checkbox</type>
    </fields>
    <label>Training Agreement Settings</label>
</CustomObject>

objects/Training_Location__c.object
<CustomObject>
    <fields>
        <fullName>Publish_To_Web__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Publish To Web</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                    <default>true</default>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Mark for Deletion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <label>Time Zone</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Training_Time_Zone</valueSetName>
        </valueSet>
    </fields>
    <label>Training Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Training_Time_Zone.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Australia Adelaide</fullName>
    </customValue>
    <customValue>
        <fullName>Australia Brisbane</fullName>
    </customValue>
    <customValue>
        <fullName>Australia Hobart</fullName>
    </customValue>
    <customValue>
        <fullName>Australia Melbourne</fullName>
    </customValue>
    <customValue>
        <fullName>Australia Perth</fullName>
    </customValue>
    <customValue>
        <fullName>Australia Sydney</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Canada Atlantic</fullName>
    </customValue>
    <customValue>
        <fullName>Canada Central</fullName>
    </customValue>
    <customValue>
        <fullName>Canada Eastern</fullName>
    </customValue>
    <customValue>
        <fullName>Canada Mountain</fullName>
    </customValue>
    <customValue>
        <fullName>Canada Pacific</fullName>
    </customValue>
    <customValue>
        <fullName>Chile</fullName>
    </customValue>
    <customValue>
        <fullName>China</fullName>
    </customValue>
    <customValue>
        <fullName>Colombia</fullName>
    </customValue>
    <customValue>
        <fullName>Costa Rica</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Iceland</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <customValue>
        <fullName>Korea</fullName>
    </customValue>
    <customValue>
        <fullName>Luxembourg</fullName>
    </customValue>
    <customValue>
        <fullName>Mexico Central</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
    </customValue>
    <description>Time Zone for training classes</description>
    <masterLabel>Training Time Zone</masterLabel>
</GlobalValueSet>

classes/ClassTriggerHandler.cls
/**
 *@author Original: Sagar Talele - Cloud Sherpas/Mathworks, Last Modified: Andy Ognenoff - Cloud Sherpas/Mathworks
 *@date Original:   26 June 2015, Last Modified: 24 March 2017
 *@description:     This is a Handler class for Class Object.
 */
public class ClassTriggerHandler {
    
    ClassDml classDmlObj = new ClassDml();
    //get training Agreement Settings instance
    Training_Agreement_Settings__c settings = Training_Agreement_Settings__c.getInstance();
    /**
     *@author Original: Sagar Talele - Cloud Sherpas/Mathworks, Last Modified: Andy Ognenoff - Cloud Sherpas/Mathworks
     *@date Original: 29 June 2015, Last Modified: 07 July 2015
     *@description: Method that handles Before Delete trigger event on the Class__c object.
     */
    public void onBeforeDelete(List<Class__c>clssLst){
        Logger.push('onBeforeDelete','ClassTriggerHandler');
        //instantiating the Set of class id 
        Set<Id> classId = new Set<Id>();
        //instantiating the List which contains list of class records
        List<Class__c> classList = new List<Class__c>();
        for(Class__c classObj : clssLst){
            classId.add(classObj.Id);
        }
        //query the Class records with the related enrollments
        classList = [Select Id,Name, Publish_To_Web__c, (Select Id,Class__c From Class_Enrollees__r) From Class__c Where Id IN :classId];
        //check list is not empty
        if(!classList.isEmpty()){
            //send class list and enrollment list      
            classDmlObj.preventDelClassesWithEnrollments(classList);
        }
        Logger.pop();
      
    }
    /**
     *@author Original: Sagar Talele - Cloud Sherpas/Mathworks, Last Modified: Sagar Talele - Cloud Sherpas/Mathworks
     *@date Original: 29 June 2015, Last Modified: 24 March 2017
     *@description: Method that handles Before insert trigger event on the Class__c object.
     */
    public void onBeforInsert(List<Class__c>clssLst){
        Logger.push('onBeforInsert','ClassTriggerHandler');
        set<Id> spOfficeId = new set<Id> ();      
        List<Sponsor_Office__c> spOfficeList = new List<Sponsor_Office__c>();       
        Map<Id,Sponsor_Office__c> spOfficeMap = new Map<Id,Sponsor_Office__c>();       
        set<String> courselangId= new set<String> ();       
        List<Course_Language__c> courselangList = new List<Course_Language__c>();      
        Map<String,Course_Language__c > courseLangMap = new Map<String,Course_Language__c >();
        List<Class__c> primInstClasslst = new List<Class__c>();

        ClassDMLObj.classTimeZone(clssLst);
        
        //SS 3/24/2017 Populate Primary Instructor User Id which will be used for survey record ownership
         for(Class__c classObj : clssLst){
        	if(classObj.Primary_Instructor__c !=null){
                primInstClasslst.add(classObj);
            }
        }
        
        ClassDMLObj.classsetInstructorUser(primInstClasslst); //SS 3/24/2017
       
        if (!settings.Class_Prevent_Defaults__c){
                   
        ClassDMLObj.classclone(clssLst);

          //iterate over the class list
        for(Class__c classObj : clssLst){
            if(classObj.Sponsor_Office__c !=null){
                spOfficeId.add(classObj.Sponsor_Office__c);
            }
        }
              
        if(!spOfficeId.isEmpty()){
            //query for getting Sponsor list which belongs to trigger context.
            spOfficeList = [Select Id,Class_Default_End_Time__c,Class_Default_Start_Time__c,Default_Class_Language__c,Class_Default_Time_Zone__c, CurrencyIsoCode From Sponsor_Office__c where Id IN :spOfficeId];
            //iterate over sponsor list to populate the map of sponsor office
            for(Sponsor_Office__c  spObj : spOfficeList ){
                if(!spOfficeMap.containsKey(spObj.Id)){
                    spOfficeMap.put(spObj.Id,spObj);
                }
            }
            //iterate over the class list so we can set language,start time,end time.
            for(Class__c clsObj : clssLst){
                if (!clsObj.isClone()){
                clsObj.Language__c = spOfficeMap.get(clsObj.Sponsor_Office__c).Default_Class_Language__c;
                clsObj.CurrencyIsoCode = spOfficeMap.get(clsObj.Sponsor_Office__c).CurrencyIsoCode;
                if (clsObj.Class_Format__c != 'Self-Paced Online')
                {
                    clsObj.Start_Time__c = spOfficeMap.get(clsObj.Sponsor_Office__c).Class_Default_Start_Time__c;
                	clsObj.End_Time__c = spOfficeMap.get(clsObj.Sponsor_Office__c).Class_Default_End_Time__c;  
                }
            }
            }           
        }
        
        
        
        //logic for inserting class name automatically from course language
        for(Class__c classObj : clssLst){
            if(classObj.Course__c != null && classObj.Language__c != null){
                courselangId.add(classObj.Course__c +''+ classObj.Language__c);
            }
         }
         
        if(!courselangId.isEmpty()){
            //query  for getting course language records
            courselangList = [Select Id,Course__c,Course_Language__c,Localized_Course_Name__c,UniqueCourseLanguage__c From Course_Language__c Where UniqueCourseLanguage__c In :courselangId];
        }
        if(!courselangList.isEmpty()){
            //iterate over the course language for getting the UniqueCourseLanguage__c 
            //which is a unique key for identification of course and respective language
            for(Course_Language__c  courslangObj : courselangList ){
                //fill the map with UniqueCourseLanguage__c as key
                if(!courseLangMap.containsKey(courslangObj.UniqueCourseLanguage__c )){
                    courseLangMap.put(courslangObj.UniqueCourseLanguage__c,courslangObj);
                }
            }
        }
        //iterate over the class list so we can set Class name.
        for(Class__c clsObj : clssLst){
            if (!clsObj.isClone()){
                String uniqueCourseLang = clsObj.Course__c +''+ clsObj.Language__c;
                if(!courseLangMap.isEmpty()){
                    clsObj.Name= courseLangMap.get(uniqueCourseLang).Localized_Course_Name__c;
                }
        }     
        }
        }
       Logger.pop();
    }
    
    /**
     *@author Original: Abhay Verma - Cloud Sherpas/Mathworks, Last Modified: Sagar Talele - Cloud Sherpas/Mathworks
     *@date Original: 29 July 2015, Last Modified: 
     *@description: Method that handles After insert trigger event on the Class__c object.
     */
    
    public void onAfterInsert(List<Class__c> clssLst){
        Set<Id> activeClsSet = new Set<Id>();
        List<Class__c> activeClsLst = new List<Class__C>();
        List<Class__c> newClsLst = new List<Class__c>();
        
        if(!clssLst.IsEmpty()){   
          
            for(Class__c clsObj : clssLst){
                activeClsSet.add(clsObj.Id);
            }   
            //Quering the Triggered Class Record     
            newClsLst = [SELECT Name, Id, Status__c, RecordType.Name FROM Class__c WHERE Id IN: activeClsSet];
            
            for(Class__c clssObj : newClsLst){
                //If the Class Status Is Active and it Record Type is Self-Paced.
                if(clssObj.Status__c == 'Active' && clssObj.RecordType.Name == 'Self-Paced'){
                    activeClsLst.add(clssObj);
                }
            }
        }
        //added switch for Auto create Auto create class assoiciation records
        if(settings.Auto_Create_Class_Association__c){
            classDmlObj.insertTrainingAgreementClassRelationship(activeClsLst);
        }
        
    }
  
    /**
     *@author Original: Shweta Shanbhag
     *@date Original: February 1 2017
     *@description: Method that handles before update trigger event on the Class__c object.
     */
    public void onBeforeUpdate(Map<Id, Class__c> clssNewMap, Map<Id, Class__c> clssOldMap){
        Logger.push('onBeforeUpdate','ClassTriggerHandler');
        List<Class__c> classupdlst = new List<Class__C>();
        List<Class__c> classinstUserlst = new List<Class__C>();
        
        for (Class__c clss:clssNewMap.values()){
            if (clssOldMap.get(clss.Id).Training_Location__c != clss.Training_Location__c)
            {              
              classupdlst.add(clss);
            }
            else if (clssOldMap.get(clss.Id).Time_Zone__c != clss.Time_Zone__c)
            {
               clss.Time_Zone_Canonical__c = classDmlObj.calctimezoneCanonical(clss.Time_Zone__c);
            }
        }
        
        for (Class__c clss:clssNewMap.values()){
            if (clssOldMap.get(clss.Id).Primary_Instructor__c != clss.Primary_Instructor__c)             
            {  
                if (clss.Primary_Instructor__c != null)
                {	classinstUserlst.add(clss); }
                else
                { clss.Instructor_User__c = null;}   
            }
        }
        classDmlObj.classTimeZone(classupdlst); 
        classDmlObj.classsetInstructorUser(classinstUserlst); //SS 3/24/2017 Populate Primary Instructor User Id 
    }
    /**
     *@author Original: Abhay Verma - Cloud Sherpas/Mathworks, Last Modified: Sagar Talele - Cloud Sherpas/Mathworks
     *@date Original: 29 July 2015, Last Modified: 
     *@description: Method that handles After update trigger event on the Class__c object.
     */
    
    public void onAfterUpdate(List<Class__c> clssLst, Map<id,Class__c> clssMap){
        List<Class__c> activeClsLst = new List<Class__C>();
        List<Class__c> classlocupdList = new List<Class__c>();
        List<Class__c> classtzupdList = new List<Class__c>();
        List<Class__c> newClsLst = new List<Class__c>();
        Set<Id> activeClsSet = new Set<Id>();
        
        //Check if the List is Empty or not.
        if(!clssLst.IsEmpty()){   
            for(Class__c clsObj : clssLst){
                activeClsSet.add(clsObj.Id);    
            }   
            
            //Quering the Triggered Class Record     
            newClsLst = [SELECT Name, Id, Status__c, Training_Location__c, RecordType.Name FROM Class__c WHERE Id IN: activeClsSet];
            
            for(Class__c clsObj : newClsLst){          
                Class__c clsOldObj = clssMap.get(clsObj.Id);            
                if(clsOldObj.Status__c == 'Inactive' && clsObj.Status__c == 'Active'){                
                    if(clsOldObj.Status__c != clsObj.Status__c && clsObj.RecordType.Name == 'Self-Paced'){
                            activeClsLst.add(clsObj);
                    }//End of if.
                }//End of Active and Inactive If.   
                if(clsOldObj.Training_Location__c != clsObj.Training_Location__c ){
                    classlocupdList.add(clsObj);
                }
                
            }//End of For Loop
        }//End of List Check "If"
       
        if(settings.Auto_Create_Class_Association__c){
            classDmlObj.insertTrainingAgreementClassRelationship(activeClsLst);
        }
     	
        if (!classlocupdList.isEmpty()){
       //    classDmlObj.classTimeZone(classlocupdList);
        }
            
        
    }
    
    
}