objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_Email__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Send Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sponsor_Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sponsor Office</label>
        <referenceTo>Sponsor_Office__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Mark for Deletion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <description>Contact Preferred Language</description>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Swedish</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Portuguese</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Enrollment_Request__c.object
<CustomObject>
    <description>Staging object to ingest requests for class enrollment under Enterprise Training Agreements from multiple sources including manual internal enrollments, self-enrollments via a portal and bulk enrollments via a file load. Records that are processed through this object will ultimately result in records being created in the Enrollment object.</description>
    <fields>
        <fullName>Batch_ID__c</fullName>
        <inlineHelpText>Identifier used to group enrollment requests together for purposes of creating summary email notifications once all requests have been processed</inlineHelpText>
        <label>Batch ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Class to enroll Contact in</inlineHelpText>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enrollment Requests</relationshipLabel>
        <relationshipName>Enrollment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Contact to be enrolled</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Enrollment Requests</relationshipLabel>
        <relationshipName>Enrollment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <inlineHelpText>Email Address of the Enrollee - used to find the Contact in Salesforce or CDS if the Contact is not identified explicitly</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Training agreement the Enrollment should be created under</inlineHelpText>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Enrollment Requests</relationshipLabel>
        <relationshipName>Enrollment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exception_Reason__c</fullName>
        <inlineHelpText>Details if an exception occurred during processing</inlineHelpText>
        <label>Exception Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Pending Notification</fullName>
                </value>
                <value>
                    <fullName>Process Manually</fullName>
                </value>
                <value>
                    <fullName>No Action Planned</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Exception</fullName>
                </value>
                <value>
                    <fullName>Reprocess</fullName>
                </value>
                <value>
                    <fullName>Pending CDS Lookup</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Request</label>
    <nameField>
        <displayFormat>ER-{0}</displayFormat>
        <label>Enrollment Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Enterprise_Training_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Language to display content in on self-enrollment portal</inlineHelpText>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Enterprise Training Agreements</relationshipLabel>
        <relationshipName>Enterprise_Training_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sponsor_Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sponsor Office</label>
        <referenceTo>Sponsor_Office__c</referenceTo>
        <relationshipLabel>Enterprise Training Agreements</relationshipLabel>
        <relationshipName>Enterprise_Training_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enterprise Training Agreement</label>
    <nameField>
        <label>Enterprise Training Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enterprise Training Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Language__c.object
<CustomObject>
    <fields>
        <fullName>SF_ISO_Code__c</fullName>
        <description>The universal ISO language code.</description>
        <inlineHelpText>The universal ISO language code.</inlineHelpText>
        <label>Salesforce ISO Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Language</label>
    <nameField>
        <label>Language</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sponsor_Office__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Sponsor Office</label>
    <nameField>
        <label>Sponsor Office</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sponsor Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Training_Agreement_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings related to Enterprise Training Agreements for Customer Training</description>
    <fields>
        <fullName>OrgWideEmailAddress__c</fullName>
        <label>OrgWideEmailAddress</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This value decide the email notification</description>
        <label>Send Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Task_Owner__c</fullName>
        <description>after sending the message task should be created and task owner is the stored value in this field</description>
        <label>Task Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VF_Email_Template_Name__c</fullName>
        <description>This Visual Force Email Template name is used to set template Id for automatically email triggered upon Enrollment Confirmation</description>
        <label>VF Email Template Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Training Agreement Settings</label>
</CustomObject>

classes/EmailToEnrolleesBatch.cls
/**
  * @author Original: Sagar Talele - Accenture/Mathworks Last Modified: Sagar talele
  * @date Original: 20 May 2016, Last Modified: 20 May 2016
  * @description: This batch will send a mail to enrollee which includes all the details 
  *               of courses that enrollee enrolled.This batch will also update status of
  *               Enrollment request 
  **/
global class EmailToEnrolleesBatch implements Queueable {
    Set<Id> enrollReqIdSet = new Set<Id>();
    /**
      * @author Original: Sagar Talele - Accenture/Mathworks Last Modified: Sagar talele
      * @date Original: 20 May 2016, Last Modified: 20 May 2016
      * @description: This is execute method to build a logic for sending mails
      **/
    public EmailToEnrolleesBatch(Set<Id> enrollReqIds){
        Logger.push('EmailToEnrolleesBatch', 'EmailToEnrolleesBatch');
        enrollReqIdSet = enrollReqIds;
        Logger.pop();
    }
    /**
      * @author Original: Sagar Talele - Accenture/Mathworks Last Modified: Sagar talele
      * @date Original: 20 May 2016, Last Modified: 20 May 2016
      * @description: This is execute method to build a logic for sending mails
      **/
    global void execute(QueueableContext context) {
        Logger.push('EmailToEnrolleesBatch', 'execute');
        
        List<AggregateResult>enrollrequestAggrList = new List<AggregateResult>();
        Set<String> batchIdSet = new Set<String> ();
        Set<Id> contactIdSet = new Set<Id>();
        List<Enrollment_Request__c> enrollrequestList = new List<Enrollment_Request__c>();
        //instantiating a list of org emails
        List<OrgWideEmailAddress> orgEmailList = new List<OrgWideEmailAddress>();
        //get value from custom setting for Template Name
        Training_Agreement_Settings__c setting = Training_Agreement_Settings__c.getInstance();
        //instantiating Messaging.SingleEmailMesage List
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
        //Map of Contact Id as a key and value as a list of Enrollment Request
        Map<Id,List<Enrollment_Request__c>> conIdToEnrollReqMap = new Map<Id,List<Enrollment_Request__c>>();
        //Map of Contact id as a key and value as a boolean which decide the mail is required to send or not.
        Map<Id,Boolean> conIdToIsSendMailMap = new Map<Id,Boolean>();
        //instantiating a list of Enrollment Request
        List<Enrollment_Request__c> enrollReqLst = new List<Enrollment_Request__c>();
        //Contact Id set
        Set<Id> conIdSet = new Set<Id>();
        //Map of Contact Id as key and Messaging.sendEmailResult as a value
        Map<Id,Messaging.SendEmailResult> contactIdToEmailResultMap = new Map<Id,Messaging.SendEmailResult>();
        //instantiating a list of Messaging.SendEmailResult
        List<Messaging.SendEmailResult> results ;
        String templateApiName;
        Id templateId;
        Integer i=0;
        Integer j=0;
        List<Task> taskList = new List<Task>();
        Map<Id,String> conIdToHtmlBodyMap = new Map<Id,String>();
        Set<Id> conIdForTaskSet = new Set<Id>();
        Map<Id,String> conIdToEmailSubjectMap = new Map<Id,String>();
        
        enrollrequestAggrList = [Select count(id) ,Contact__c,Batch_ID__c From Enrollment_Request__c Where Status__c != 'Completed' group by Contact__c,Batch_ID__c];
        System.debug('**enrollrequestAggrList**'+enrollrequestAggrList);
        
        for(AggregateResult agr: enrollrequestAggrList){
            batchIdSet.add(String.valueOf(agr.get('Batch_ID__c')));
            contactIdSet.add((Id)agr.get('Contact__c'));
            //batchIdSet.add('0ea0c549-c46d-2980-7878-8f532704575a');
            //contactIdSet.add('003e000000Xdee8');
        }
        
        enrollrequestList = [Select Id,
                                    Contact__r.Email,Batch_ID__c,
                                    Contact__c,Class__c,
                                    Enterprise_Training_Agreement__c,
                                    Enterprise_Training_Agreement__r.Sponsor_Office__r.Email__c,
                                    Status__c,
                                    Enterprise_Training_Agreement__r.Language__r.SF_ISO_Code__c
                                        From Enrollment_Request__c
                                        Where Batch_ID__c IN : batchIdSet 
                                            And Contact__c IN : contactIdSet
                                                And Id IN :enrollReqIdSet ];
        System.debug('**enrollrequestList**'+enrollrequestList);
        
        if(setting.Send_Email__c){
            //Set TemplateId
            templateApiName = setting.VF_Email_Template_Name__c;//'Mathworks_Training_Enroll_Confirmation';
            templateId = [select id, name from EmailTemplate where developername = : templateApiName].id;
            System.debug('**templateId**'+templateId);
            //set setOrgWideEmailAddressId from eta sponsor office email
            //query for Org Email ids
            orgEmailList = [SELECT Id,Address,DisplayName  FROM OrgWideEmailAddress where Address =:setting.OrgWideEmailAddress__c];
            System.debug('**orgEmailList**'+orgEmailList);
           
            
            //sendEmail to for enrollment request
            for(Enrollment_Request__c enrollReq : enrollrequestList){
            
                if(!conIdToEnrollReqMap.containsKey(enrollReq.Contact__c)){
                    conIdToEnrollReqMap.put(enrollReq.Contact__c,new List<Enrollment_Request__c>{enrollReq});
                }else{
                    conIdToEnrollReqMap.get(enrollReq.Contact__c).add(enrollReq);
                }
                
                if(conIdToEnrollReqMap.ContainsKey(enrollReq.Contact__c) && enrollReq.Status__c == 'Pending Notification'){
                    if(!conIdToIsSendMailMap.containsKey(enrollReq.Contact__c)){
                        conIdToIsSendMailMap.put(enrollReq.Contact__c,true);
                    }
                }else{
                        conIdToIsSendMailMap.put(enrollReq.Contact__c,false);
                }
            }
            
            //sendEmail to for enrollment request
            for(Enrollment_Request__c enrollReq : enrollrequestList){
                if(conIdToIsSendMailMap.containsKey(enrollReq.Contact__c) && conIdToIsSendMailMap.get(enrollReq.Contact__c) && !conIdSet.contains(enrollReq.Contact__c)){
                        System.debug('**enrollReq**'+enrollReq);
                        String[] toAddresses = new String[] {enrollReq.Contact__r.email};
                        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                        email.setToAddresses(toAddresses);
                        email.setTargetObjectId(enrollReq.Contact__c);
                        email.setTreatTargetObjectAsRecipient(true);
                        email.setWhatId(enrollReq.Id);
                        email.setTemplateId(templateId);
                        email.setSaveAsActivity(false);
                        email.setReplyTo(setting.OrgWideEmailAddress__c);
                        if(!orgEmailList.isEmpty()){
                           email.setOrgWideEmailAddressId(orgEmailList[0].Id);
                        }
                        
                        emailList.add(email);
                        conIdSet.add(enrollReq.Contact__c);
                }  
            }
            
            // send email to get result for enrollent request update
            try{
                    System.debug('**emailList**'+emailList);
                    //send all emails from the transaction
                    results = Messaging.sendEmail(emailList,false);
            }catch(System.EmailException ex){
                    System.debug('**THERE WAS AN ISSUE TO SEND MAIL TO THE DESTINATION :**'+ex.getMessage());
                    Logger.debugException('THERE WAS AN ISSUE TO SEND MAIL TO THE DESTINATION : '+ex.getMessage());
            }
            
             
            for( Messaging.SendEmailResult emailResult: results){
                if(emailList.get(i).getTargetObjectId()!= null){
                    contactIdToEmailResultMap.put(emailList.get(i).getTargetObjectId(),emailResult);
                }
               i++;
            }
            System.debug('**contactIdToEmailResultMap**'+contactIdToEmailResultMap);
        }   
        
        //list to add Enrollment_Request__c success records
        List<Enrollment_Request__c> enrollReqUpdateList = new List<Enrollment_Request__c>();
        //For Task 
        List<Enrollment_Request__c> enrollReqTaskList = new List<Enrollment_Request__c>();
        for(Enrollment_Request__c enrollReq : enrollrequestList){
            if((contactIdToEmailResultMap.containsKey(enrollReq.Contact__c)
                && contactIdToEmailResultMap.get(enrollReq.Contact__c).isSuccess()) || !setting.Send_Email__c){
                enrollReq.Status__c = 'Completed';
                enrollReqUpdateList.add(enrollReq);
                enrollReqTaskList.add(enrollReq);
                if(!Test.isRunningTest()){
                    Messaging.SingleEmailMessage emailObj = Messaging.renderStoredEmailTemplate(templateId, enrollReq.Contact__c,enrollReq.Id);
                    if(!conIdToHtmlBodyMap.containsKey(enrollReq.Contact__c)){
                        conIdToHtmlBodyMap.put(enrollReq.Contact__c,emailObj.getHtmlBody().stripHtmlTags());
                        conIdToEmailSubjectMap.put(enrollReq.Contact__c,emailObj.getSubject());
                    }
                    system.debug('Talele Rocks : '+emailObj.getSubject());
                }
                
            }else{
                if(contactIdToEmailResultMap.containsKey(enrollReq.Contact__c)){
                enrollReq.Status__c = 'Exception';
                enrollReq.Exception_Reason__c = 'Email Notification Failure:'+contactIdToEmailResultMap.get(enrollReq.Contact__c).getErrors()[0].getMessage();
                enrollReqUpdateList.add(enrollReq);
                }
            }
            j++;
        }
        System.debug('**enrollReqUpdateList**'+enrollReqUpdateList);
        
        User u = [Select Id,Name,alias From User Where alias =: setting.Task_Owner__c];
        if(!enrollReqTaskList.isEmpty()){
            for(Enrollment_Request__c enrollReqObj : enrollReqTaskList){
                if(!conIdForTaskSet.contains(enrollReqObj.Contact__c)){
                    Task tsk = new Task();
                    tsk.Subject = conIdToEmailSubjectMap.get(enrollReqObj.Contact__c);//System.Label.Cp_EnrollTemplateSubject;
                    tsk.Description = conIdToHtmlBodyMap.get(enrollReqObj.Contact__c);
                    tsk.Priority = 'Medium';
                    tsk.whoid = enrollReqObj.Contact__c;
                    tsk.whatId = enrollReqObj.Enterprise_Training_Agreement__c;
                    tsk.status = 'Completed';
                    tsk.OwnerId = u.ID;
                    taskList.add(tsk);
                    conIdForTaskSet.add(enrollReqObj.Contact__c);
                }
            }
            Try{
                insert taskList;
            }catch(Exception ex){
                    Logger.debugException('THERE WAS AN ISSUE TO Creat the Task for Enrollment Request Record : '+ex.getMessage());
            }   
        }
                
        //udpate the Enrollment Request 
        Try{
            if(!enrollReqUpdateList.isEmpty()){
                Update enrollReqUpdateList;
            }
        }catch(Exception ex){
                    Logger.debugException('THERE WAS AN ISSUE TO Update the Enrollment Request Record : '+ex.getMessage());
        }
        
        Logger.pop();
                
    }
    /**
      * @author Original: Sagar Talele - Accenture/Mathworks Last Modified: Sagar talele
      * @date Original: 20 May 2016, Last Modified: 20 May 2016
      * @description: This is execute method Schedule the class
      **/
    global void execute(SchedulableContext ctx) {
    }
}