objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <formula>Training_Location__r.City__c</formula>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>Training_Location__r.Country__c</formula>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <label>Part Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <formula>TEXT(Training_Location__r.Location_Type__c)</formula>
        <label>Location Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <label>Max Seats</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Publish_To_Web__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Publish To Web</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>Training_Location__r.State__c</formula>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Mark for Deletion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Training_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training Location</label>
        <referenceTo>Training_Location__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Course_Code__c</fullName>
        <label>Part Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Publish_to_Web__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Publish to Web</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <default>true</default>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <recordTypes>
        <fullName>Training</fullName>
        <active>true</active>
        <description>Record type to create non certification course</description>
        <label>Training</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Language__c.object
<CustomObject>
    <fields>
        <fullName>SF_ISO_Code__c</fullName>
        <description>The universal ISO language code.</description>
        <inlineHelpText>The universal ISO language code.</inlineHelpText>
        <label>Salesforce ISO Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Language</label>
    <nameField>
        <label>Language</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Training_Location__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Training Locations</relationshipLabel>
        <relationshipName>Training_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <label>Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Admin_Contact__c</fullName>
        <inlineHelpText>Admin Contact, Phone number and Email Address</inlineHelpText>
        <label>Admin Contact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cancellation_Lead_Time__c</fullName>
        <inlineHelpText>Number of days before event that venue must be cancelled</inlineHelpText>
        <label>Cancellation Lead Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Code_State_Code__c</fullName>
        <description>Store the state code and country code.</description>
        <label>Country Code -  State Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <description>Store the country Code.</description>
        <label>Country Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Directions__c</fullName>
        <label>Directions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Location_Email__c</fullName>
        <label>Location Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Location_Fax__c</fullName>
        <label>Location Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Location_Name_Latin__c</fullName>
        <label>Location Name (Latin)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Phone__c</fullName>
        <label>Location Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>On Site</fullName>
                </value>
                <value>
                    <fullName>3rd Party Training Center</fullName>
                </value>
                <value>
                    <fullName>Corporate Training Center</fullName>
                </value>
                <value>
                    <fullName>Conference Center</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location_URL__c</fullName>
        <inlineHelpText>Location URL Link to description of the course</inlineHelpText>
        <label>Location URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publish_To_Web__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Publish To Web</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMER</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State_Code__c</fullName>
        <description>Store the state code.</description>
        <label>State Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                    <default>true</default>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Mark for Deletion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Technical_Contact__c</fullName>
        <inlineHelpText>Technical Contact Name, Phone Number and Email</inlineHelpText>
        <label>Technical Contact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Training Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Country_Code__c</fullName>
        <description>Customer Portal Field</description>
        <label>Country Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TrainingLocationPageXCTest.cls
/**
 *@author Original: Abhay Verma - Accenture/Mathworks, Last Modified: 
 *@date Original: 1 July 2016, Last Modified: 
 *@description This  is test class for 'TrainingLocationPage Extension' . 
 *@Revision:
 */
@isTest
public class TrainingLocationPageXCTest{
    
    //re-create custom setting test records when running the test class
    static CustomSettingsBuilder custsettbuild = new CustomSettingsBuilder();
    private static User usr; 
    
    /**
     *@author Original: Abhay Verma - Accenture/Mathworks, Last Modified: 
     *@date Original: 4 July 2016, Last Modified: 
     *@description: This method contain the test data use for different test method. 
     *@param: 
     *@Revision:
    */
    
    static void insertTestData() {
    
        //Inserting Bypass trigger custom setting
        custsettbuild.buildBypassTriggerSettings();
        
        usr = TestDataBuilder.buildTestUser(1);
        insert usr;
        
        System.runAs(usr){
                   
            //Create Training Location Test data.
            Training_Location__c trainLocObj = CTrainingTestDataBuilder.buildTestTrainingLoc(1);
            trainLocObj.State__c = 'Florida';
            insert trainLocObj;
        }//End of RunAs
    }//End of Method
    
    /**
     *@author Original: Abhay Verma - Accenture/Mathworks, Last Modified: 
     *@date Original: 4 July 2016, Last Modified: 
     *@description: Method to test the functionality to insert country as none of the training location Object. 
     *@param: 
     *@Revision:
    */
    
    private static testMethod void insertNoneTrainingLocationTest(){
        
        TrainingLocationPageXCTest.insertTestData();
        //Inserting Bypass trigger custom setting
        custsettbuild.buildBypassTriggerSettings();
        usr = [SELECT Id FROM User WHERE Id =: usr.Id];
        
        System.runAs(usr){                                  
            
            Training_Location__c traingLocObj = new Training_Location__c();
            
            traingLocObj = CTrainingTestDataBuilder.buildTestTrainingLoc(1);
            traingLocObj.Publish_To_Web__c = False;
                       
            
            //Start Test
            test.startTest();
            
            PageReference pageRef = Page.TrainingLocationPage;
            Test.setCurrentPage(pageRef);
            
            ApexPages.StandardController standardCtrlCon = new ApexPages.StandardController(traingLocObj);
            TrainingLocationPageXC controller = new TrainingLocationPageXC(standardCtrlCon);
            
            controller.trainingLocationObj = traingLocObj;
            //Assigning value to the component. 
            controller.compDataObj.countryCode = '--None--';
            controller.compDataObj.countryName = null;
            controller.compDataObj.StateName = null;
            controller.compDataObj.StateCode = null;
            controller.save();
            
            //Querying the Training Location.
            List<Training_Location__c> updatedTrainingLocObj = [SELECT Country__c, Country_Code__c,State__c, State_Code__c, Country_Code_State_Code__c 
                                                         FROM Training_Location__c];
            //Asserting the Training Location Country has the value as in the component.
            System.assertEquals(updatedTrainingLocObj[1].Country__c, null);
            System.assertEquals(updatedTrainingLocObj[1].Country_Code__c, null);
            System.assertEquals(updatedTrainingLocObj[1].State__c, null);
            System.assertEquals(updatedTrainingLocObj[1].State_Code__c, null);
            System.assertEquals(updatedTrainingLocObj[1].Country_Code_State_Code__c, null);
            
            
            //Stop Test
            test.stopTest();
        }//End of RunAs
    }//End of Method
    
    /**
     *@author Original: Abhay Verma - Accenture/Mathworks, Last Modified: 
     *@date Original: 4 July 2016, Last Modified: 
     *@description: Method to test the functionality to update the training location Object. 
     *@param: 
     *@Revision:
    */
 /*  SS - 1951614 - 2/23/17 - State should not be required when creating or editing locations 
    private static testMethod void checkStateRequireTest(){
        
        TrainingLocationPageXCTest.insertTestData();
        //Inserting Bypass trigger custom setting
        custsettbuild.buildBypassTriggerSettings();
        usr = [SELECT Id FROM User WHERE Id =: usr.Id];
        
        System.runAs(usr){
            //Querying the Training Location User.
            Training_Location__c trainingLocObj = [SELECT Id, Name, Location_Name_Latin__c, Region__c, Location_Type__c, 
                                    Status__c, Publish_To_Web__c, Account__c, Cancellation_Lead_Time__c,Address_Line_1__c,
                                    Address_Line_2__c, City__c, Country__c, Postal_Code__c, State__c, Admin_Contact__c, 
                                    Technical_Contact__c, Location_Email__c, Location_Fax__c, Location_Phone__c, Location_URL__c, Notes__c,
                                    Country_Code__c, State_Code__c, Country_Code_State_Code__c, Directions__c FROM Training_Location__c];
                                    
            //Start Test
            test.startTest();
            
            PageReference pageRef = Page.TrainingLocationPage;
            Test.setCurrentPage(pageRef);
            
            ApexPages.StandardController standardCtrlCon = new ApexPages.StandardController(trainingLocObj);
            TrainingLocationPageXC controller = new TrainingLocationPageXC(standardCtrlCon);
            
            controller.trainingLocationObj = trainingLocObj;
            //Assigning value to the component. 
            controller.compDataObj.countryCode = 'IN';
            controller.compDataObj.stateCode = null;
            controller.compDataObj.stateName = null;
            controller.compDataObj.countryName = 'India';
            controller.save();
            
            PageReference trainingLocPageRef = controller.save();
            
            //Querying the Training Location.
            List<Training_Location__c> updatedTrainingLocObj = [SELECT Country__c, Country_Code__c,State__c, State_Code__c, Country_Code_State_Code__c 
                                                         FROM Training_Location__c];
            
            //Asserting the Training Location Country has the value as in the component.
            System.assertNotEquals(updatedTrainingLocObj[0].Country__c, 'India');
            System.assertNotEquals(updatedTrainingLocObj[0].Country_Code__c, 'IN');
            System.assertNotEquals(updatedTrainingLocObj[0].State__c, null);
            System.assertEquals(updatedTrainingLocObj[0].State_Code__c, null);
            System.assertEquals(updatedTrainingLocObj[0].Country_Code_State_Code__c, null);
            
            
            //Stop Test
            test.stopTest();
        }//End of RunAs
    }//End of Method
  */  
    
    /**
     *@author Original: Abhay Verma - Accenture/Mathworks, Last Modified: 
     *@date Original: 4 July 2016, Last Modified: 
     *@description: Method to test the functionality for insertion of Training Location Object.. 
     *@param: 
     *@Revision:
    */
    
    private static testMethod void insertTrainingLocationTest(){
        
        TrainingLocationPageXCTest.insertTestData();
        //Inserting Bypass trigger custom setting
        custsettbuild.buildBypassTriggerSettings();
        
        usr = [SELECT Id FROM User WHERE Id =: usr.Id];
        
        System.runAs(usr){
           
            Training_Location__c traingLocObj = new Training_Location__c();
            
            traingLocObj = CTrainingTestDataBuilder.buildTestTrainingLoc(1);
            
            
            //Start Test
            test.startTest();
            PageReference pageRef = Page.TrainingLocationPage;
            Test.setCurrentPage(pageRef);
            
            ApexPages.StandardController standardCtrlCon = new ApexPages.StandardController(traingLocObj);
            TrainingLocationPageXC controller = new TrainingLocationPageXC(standardCtrlCon);
            
            //Creating the value for the page.
            controller.trainingLocationObj = traingLocObj;
            controller.compDataObj.countryCode = 'IN';
            controller.compDataObj.stateCode = 'IN-MH';
            controller.compDataObj.stateName = 'Maharashtra';
            controller.compDataObj.countryName = 'India';
            controller.save();
            
            //Querying the Training Location Object.
            List<Training_Location__c> trainingLocRec =[SELECT Id,  Country__c, State__c, State_Code__c, Country_Code_State_Code__c
                                                        FROM Training_Location__c];   
            //Assert if the Record is created or not.
            System.assertNotEquals(trainingLocRec[1].Id, null);
            System.assertEquals(trainingLocRec[1].Country__c, 'India');
            System.assertEquals(trainingLocRec[1].State__c, 'Maharashtra');
            System.assertEquals(trainingLocRec[1].State_Code__c, 'MH');
            System.assertEquals(trainingLocRec[1].Country_Code_State_Code__c, 'IN-MH');
            
            //Stop Test
            test.stopTest();
        }//End of RunAs
    }//End of Method
    
    //Test case: Change status to 'Mark for Deletion' while publish to web is true.
    private static testMethod void SetStatusMarkForDeletion_1(){
        
        TrainingLocationPageXCTest.insertTestData();
        //Inserting Bypass trigger custom setting
        custsettbuild.buildBypassTriggerSettings();
        
        usr = [SELECT Id FROM User WHERE Id =: usr.Id];
        
        System.runAs(usr){

            Training_Location__c traingLocObj = new Training_Location__c();
            
            traingLocObj = CTrainingTestDataBuilder.buildTestTrainingLoc(1);          
            traingLocObj.Status__c = 'Mark for Deletion';
            traingLocObj.publish_to_web__c = true;
            
            //Start Test
            test.startTest();
            PageReference pageRef = Page.TrainingLocationPage;
            Test.setCurrentPage(pageRef);
            
            ApexPages.StandardController standardCtrlCon = new ApexPages.StandardController(traingLocObj);
            TrainingLocationPageXC controller = new TrainingLocationPageXC(standardCtrlCon);
            
            //Creating the value for the page.
            controller.trainingLocationObj = traingLocObj;
            controller.compDataObj.countryCode = 'IN';
            controller.compDataObj.stateCode = 'IN-MH';
            controller.compDataObj.stateName = 'Maharashtra';
            controller.compDataObj.countryName = 'India';
            controller.save();
            
            test.stopTest();
        }//End of RunAs
        
		List<Apexpages.Message> msgs = ApexPages.getMessages();
		boolean b = false;
		for(Apexpages.Message msg:msgs){
		    if (msg.getDetail().contains(System.Label.Training_location_before_update_2)) b = true;
		}
		system.assert(b);
    }//End of Method
    
    //Test case: Change status to 'Mark for Deletion' while there is a class associated to the location.
    private static testMethod void SetStatusMarkForDeletion_2(){
        
        TrainingLocationPageXCTest.insertTestData();
        //Inserting Bypass trigger custom setting
        custsettbuild.buildBypassTriggerSettings();
        
        usr = [SELECT Id FROM User WHERE Id =: usr.Id];
        
        System.runAs(usr){
            
            Training_Location__c traingLocObj = new Training_Location__c();

            //Creating the Class__c test data.
            Language__c langObj = CTrainingTestDataBuilder.buildTestLanguage(0);
            langObj.SF_ISO_Code__c = 'en_US';
            insert langObj;

            Id courserecTypeId = Schema.SObjectType.Course__c.getRecordTypeInfosByName().get('Training').getRecordTypeId();
            Course__c courseObj = CTrainingTestDataBuilder.buildTestCourse(0);
            courseObj.recordTypeId = courserecTypeId;
            courseObj.Course_Code__c = 'TESTCODE';
            insert courseObj;

            traingLocObj = CTrainingTestDataBuilder.buildTestTrainingLoc(1);
            traingLocObj.Status__c = 'Active';
            traingLocObj.Publish_To_Web__c = False;
            insert traingLocObj;
            
            Id classrecTypeId = Schema.SObjectType.Class__c.getRecordTypeInfosByName().get('Instructor Led').getRecordTypeId();    
            Class__c clssObj = CTrainingTestDataBuilder.buildTestClass(0, courseObj.Id, langObj.Id);
            clssObj.Max_Seats__c  = 500;
            clssObj.recordTypeId = classrecTypeId;
            clssObj.Status__c='Active';
            clssObj.Training_Location__c = traingLocObj.id;
            insert clssObj;           
		
		
            
            //Start Test
            test.startTest();
            PageReference pageRef = Page.TrainingLocationPage;
            Test.setCurrentPage(pageRef);
            
            ApexPages.StandardController standardCtrlCon = new ApexPages.StandardController(traingLocObj);
            TrainingLocationPageXC controller = new TrainingLocationPageXC(standardCtrlCon);
            
            //Creating the value for the page.
            controller.trainingLocationObj = traingLocObj;
            controller.compDataObj.countryCode = 'IN';
            controller.compDataObj.stateCode = 'IN-MH';
            controller.compDataObj.stateName = 'Maharashtra';
            controller.compDataObj.countryName = 'India';
            controller.trainingLocationObj.Status__c = 'Mark for Deletion';
            controller.save();
            
            test.stopTest();
        }//End of RunAs
        
		List<Apexpages.Message> msgs = ApexPages.getMessages();
		boolean b = false;
		for(Apexpages.Message msg:msgs){
		    if (msg.getDetail().contains(System.Label.Training_location_before_update_2)) b = true;
		}
		system.assert(b);
    }//End of Method
    
}