objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Course__c.object
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Course_Language__c.object
<CustomObject>
    <fields>
        <fullName>Course_Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Course Languages</relationshipLabel>
        <relationshipName>Course_Languages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Languages</relationshipLabel>
        <relationshipName>Course_Languages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course Language</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Course Language Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Enrollment__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>Class_Enrollees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Enrollee_Name__c</fullName>
        <label>Enrollee Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Class Enrollments</relationshipLabel>
        <relationshipName>Class_Enrollees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Enrollment_Code__c</fullName>
        <label>Enrollment Code</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enrollment_Status__c</fullName>
        <label>Enrollment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Awaiting Payment</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Class Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
                <value>
                    <fullName>No Show-Bill</fullName>
                </value>
                <value>
                    <fullName>Registered - Awaiting Payment</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>!!! CHECK ME !!! -</fullName>
                </value>
                <value>
                    <fullName>!!! CHECK ME !!! -*** Unselected ***</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Enrollment_Code__c.object
<CustomObject>
    <description>This object represents the code associated with an Enterprise Training Agreement and holds the status the enrollment code is in.</description>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <description>Enterprise Training Agreement the Enrollment Code is associated with.</description>
        <inlineHelpText>Enterprise Training Agreement the Enrollment Code is associated with.</inlineHelpText>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Enrollment Codes</relationshipLabel>
        <relationshipName>Enrollment_Codes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Enrollment Code</label>
    <nameField>
        <displayFormat>EC-{0000}</displayFormat>
        <label>Enrollment Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Enterprise_Training_Agreement__c.object
<CustomObject>
    <label>Enterprise Training Agreement</label>
    <nameField>
        <label>Enterprise Training Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enterprise Training Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Training_Agreement_Class_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Class__c.Format_Of_Class__c</field>
                <operation>equals</operation>
                <value>Self-Paced</value>
            </filterItems>
            <filterItems>
                <field>Class__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enterprise Agreement</relationshipLabel>
        <relationshipName>Training_Agreement_Class</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Training_Agreement_Class_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Agreement Class Relationship</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Training Agreement Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Agreement Class Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EcodeTracker.cls
/*
 *Name: ECodeTracker
 *Author: Neha Mahajan
 *Description: For the registered and available section of classes. 
*/

public class EcodeTracker{
	
    public static void main(){

        Set<id> ETAset= new Set<id>();
        Set<id> EnObj= new Set<id>(); 
        Set<id> ClObj=new Set<id>();
        
        // User record to get the contactid
        User userObj= new User();
        userObj=[Select Id, Contactid, username from User where Id = :UserInfo.getUserId()];
        // Enrollment code and its associated ETA 
        list<Enrollment_Code__c> CodeObj=new list<Enrollment_Code__c>();
        CodeObj=[Select id, Enterprise_Training_Agreement__c from Enrollment_Code__c];
    	System.debug('****'+CodeObj);
    
        for(Enrollment_Code__c ecodeObj:CodeObj){
            ETAset.add(ecodeObj.Enterprise_Training_Agreement__c);
        }
            
        Map<id,list<Enrollment__c>> ClassMap= new Map<id,list<Enrollment__c>>();
        // Enrollment record which stores the classes and enrollments with status registered.
        list<Enrollment__c> EnrollObj= new list<Enrollment__c>();
        
        
        EnrollObj=[select id,Enterprise_Training_Agreement__c, Class__c,Class__r.Course__c,Class__r.name from Enrollment__c where Enterprise_Training_Agreement__c in :ETAset And Enrollment_Status__c='Registered' and Enrollee_Name__c=:userObj.Contactid];
        System.debug('**Classes Registered**'+EnrollObj);
            for(Enrollment__c EnrolObj:EnrollObj){
                        
           if(ClassMap.containsKey(EnrolObj.id)){
                ClassMap.get(EnrolObj.id).add(EnrolObj);
            }
            else{
                ClassMap.put(EnrolObj.id,new List<Enrollment__c>{EnrolObj});
            }    
            }
            
    for(Enrollment__c EnrolObj:EnrollObj){
       EnObj.add(EnrolObj.Class__c);
       ClObj.add(EnrolObj.Class__r.Course__c);
       
    }
   
    list<Course_Language__c> Clang= new list<Course_Language__c>();
    Clang=[Select Course__c, Course_Language__c,id, name from Course_Language__c where Course__c in :ClObj];
    System.debug('****'+Clang);  
        
    // Map to store available classes for an ETA.    
    Map<id,list<Training_Agreement_Class_Relationship__c>> TACObjMap= new Map<id,list<Training_Agreement_Class_Relationship__c>>();
    list<Training_Agreement_Class_Relationship__c> etaObj=new list<Training_Agreement_Class_Relationship__c>();
    etaObj=[select id, Class__r.Name,Enterprise_Training_Agreement__c from Training_Agreement_Class_Relationship__c where Enterprise_Training_Agreement__c in :ETAset];
        if(!TACObjMap.keySet().isEmpty() && TACObjMap.keySet() != null){
        for(Training_Agreement_Class_Relationship__c TAClass:etaObj){
            if(TACObjMap.containsKey(TAClass.id)){
               TACObjMap.get(TAClass.id).add(TAClass);
               }
            else
            {
              TACObjMap.put(TAClass.id, new List<Training_Agreement_Class_Relationship__c>{TAClass});
            }
        } 
      }
	}
         
}