objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Course_Code__c</fullName>
        <label>Part Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <label>Max Seats</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Mark for Deletion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <description>Contact Preferred Language</description>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Swedish</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Portuguese</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Course_Code__c</fullName>
        <label>Part Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <default>true</default>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <recordTypes>
        <fullName>Training</fullName>
        <active>true</active>
        <description>Record type to create non certification course</description>
        <label>Training</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Enrollment__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>Class_Enrollees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <formula>Class__r.Course_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Course Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Enrollment_Request__c.object
<CustomObject>
    <description>Staging object to ingest requests for class enrollment under Enterprise Training Agreements from multiple sources including manual internal enrollments, self-enrollments via a portal and bulk enrollments via a file load. Records that are processed through this object will ultimately result in records being created in the Enrollment object.</description>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Class to enroll Contact in</inlineHelpText>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enrollment Requests</relationshipLabel>
        <relationshipName>Enrollment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>Not a direct lookup to Course object so requests can be made via the Code rather than requiring the Salesforce ID of the Course</description>
        <inlineHelpText>Code used to identify the Course the Enrollment Code is being made for - this code plus the Language and Format will identify the specific Class to enroll in</inlineHelpText>
        <label>Course Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Training agreement the Enrollment should be created under</inlineHelpText>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Enrollment Requests</relationshipLabel>
        <relationshipName>Enrollment_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Language_Code__c</fullName>
        <inlineHelpText>ISO Code of the Language the Enrollment Request is for - used to identify the correct Class when combined with the Course Code and Format</inlineHelpText>
        <label>Language Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Pending Notification</fullName>
                </value>
                <value>
                    <fullName>Process Manually</fullName>
                </value>
                <value>
                    <fullName>No Action Planned</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Exception</fullName>
                </value>
                <value>
                    <fullName>Reprocess</fullName>
                </value>
                <value>
                    <fullName>Pending CDS Lookup</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Request</label>
    <nameField>
        <displayFormat>ER-{0}</displayFormat>
        <label>Enrollment Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Enterprise_Training_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Language to display content in on self-enrollment portal</inlineHelpText>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Enterprise Training Agreements</relationshipLabel>
        <relationshipName>Enterprise_Training_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <label>Max Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Enterprise Training Agreement</label>
    <nameField>
        <label>Enterprise Training Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enterprise Training Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Language__c.object
<CustomObject>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <label>ISO Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language_Code__c</fullName>
        <label>Language Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language_Display_Name__c</fullName>
        <inlineHelpText>Name that should be displayed to external users when viewing the Language of a Course/Class</inlineHelpText>
        <label>Language Display Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_ISO_Code__c</fullName>
        <description>The universal ISO language code.</description>
        <inlineHelpText>The universal ISO language code.</inlineHelpText>
        <label>Salesforce ISO Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Language</label>
    <nameField>
        <label>Language</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Language_Display_Name__c.object
<CustomObject>
    <description>Contains the display names</description>
    <fields>
        <fullName>Display_Name__c</fullName>
        <label>Display Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Language Display Names</relationshipLabel>
        <relationshipName>Language_Display_Names</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Language_code__c</fullName>
        <label>Language_code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Language Display Name</label>
    <nameField>
        <label>Language Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Language Display Names</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Training_Agreement_Class_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Class__c.Format_Of_Class__c</field>
                <operation>equals</operation>
                <value>Self-Paced</value>
            </filterItems>
            <filterItems>
                <field>Class__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enterprise Agreement</relationshipLabel>
        <relationshipName>Training_Agreement_Class</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>Part Number</description>
        <formula>Class__r.Course__r.Course_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Part Number</inlineHelpText>
        <label>Course Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Training_Agreement_Class_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Agreement Class Relationship</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Training Agreement Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Agreement Class Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EmailToEnrolleesBatchTest.cls
/**
 *@author Original: Sagar Talele - Accenture/Mathworks, Last Modified: 
 *@date Original:   1 June 2016, Last Modified: 
 *@description:     Test class to testing the functionality of the EmailToEnrolleesBatch.
 */
 
@isTest 
private class EmailToEnrolleesBatchTest{
    
    //re-create custom setting test records when running the test class
    static CustomSettingsBuilder custsettbuild = new CustomSettingsBuilder();
    private static final Integer ETAREEMENT_COUNT = 10;
    private static final Integer CLASS_COUNT = 10;
    private static final Integer LANG_COUNT = 2;
    private static final Integer COURSE_COUNT = 10;
    private static final Integer ETAREL_COUNT = 10;
    private static final Integer ENROL_REQ_COUNT = 10;
    private static final Integer CONTACT_COUNT = 10;
    static CTrainingCustomSettingBuilder CTcustsettbuild = new CTrainingCustomSettingBuilder();
      /*
    @ name    setupTestData
    @ date    5 May 2016
    @ author  Abhay Verma
    @ param   none.
    @ return  Void. 
    @ description :Create the setup data for the EnrollmentRequestToEnrollmentBatch. 
     */
    private static User usr;
    private static void setupTestData(){
        CTcustsettbuild.buildEnrollmentCodeConfiguration();
        //Inserting Bypass trigger custom setting
        custsettbuild.buildBypassTriggerSettings();
        usr = TestDataBuilder.buildTestUser(1);
        insert usr;
        
        System.runAs(usr){
         
          List<Language__c> langLst = new List<Language__c>();
            //create Language__c record from CTrainingTestDataBuilder.
            for(Integer i=0; i<LANG_COUNT; i++){
                Language__c langObj = CTrainingTestDataBuilder.buildTestLanguage(i);
                langObj.SF_ISO_Code__c = (i==0 ? 'en_US' : 'ja');
                langObj.Language_Code__c=(i==0 ? 'en' : 'ja');
                langObj.ISO_Code__c =(i==0 ? 'en' : 'ja');
                langLst.add(langObj);
            }
            insert langLst;
            
            //Create display language test data
            List<Language_Display_Name__c> dispLangLst = new List<Language_Display_Name__c>();
            
            Language_Display_Name__c dispLangObj = new Language_Display_Name__c();
            dispLangObj.Name = 'en';
            dispLangObj.Language__c = langLst[0].Id;
            dispLangObj.Display_name__c = 'English';
            dispLangObj.language_Code__c = 'en';
            
            dispLangLst.add(dispLangObj);
            
            Language_Display_Name__c dispLangObj1 = new Language_Display_Name__c();
            dispLangObj1.Name = 'ja';
            dispLangObj1.Language__c = langLst[0].id;
            dispLangObj1.Display_name__c = 'Japanese';
            dispLangObj1.language_Code__c = 'ja';
            
            dispLangLst.add(dispLangObj1); 
            
            insert dispLangLst;
            
            //Creating the Enterprise_Training_Agreement__c test data.
            List<Enterprise_Training_Agreement__c> ETagreeemntLst = new List<Enterprise_Training_Agreement__c>();
            for(Integer i=0;i<ETAREEMENT_COUNT;i++){
                //Create Test Data for Enterprise Training Agreement
                Enterprise_Training_Agreement__c eTAgreementObj = CTrainingTestDataBuilder.buildTestETAgreement(i);
                Id etraAgrerecTypeId = Schema.SObjectType.Enterprise_Training_Agreement__c.getRecordTypeInfosByName().get('Seat-Based').getRecordTypeId();
                ETAgreementObj.recordTypeId = etraAgrerecTypeId;
                ETAgreementObj.Language__c = langLst[0].Id;
                if(i < 2){
                    ETAgreementObj.Max_Seats__c = 10;
                }
                else{
                    ETAgreementObj.Max_Seats__c = 10;
                }
                ETagreeemntLst.add(ETAgreementObj);
            }
            insert ETagreeemntLst;
            
            //Creating the Course__c test data.
            Id courserecTypeId = Schema.SObjectType.Course__c.getRecordTypeInfosByName().get('Training').getRecordTypeId();
            List<Course__c> courseLst = new List<Course__c>();
            for(Integer i=0; i<COURSE_COUNT; i++){
                Course__c courseObj = CTrainingTestDataBuilder.buildTestCourse(i);
                courseObj.recordTypeId = courserecTypeId;
                courseObj.Course_Code__c = 'TESTCODE'+i;
                courseLst.add(courseObj);
            }
            insert courseLst;
            
             //Creating the Class__c test data.
            List<Class__c> clssLst = new List<Class__c>();    
            Id classrecTypeId = Schema.SObjectType.Class__c.getRecordTypeInfosByName().get('Self-Paced').getRecordTypeId();    
            //Creating the test data for Class Object. 
            for(Integer i=0;i<CLASS_COUNT;i++){            
                Class__c clssObj = CTrainingTestDataBuilder.buildTestClass(i, courseLst[i].Id, langLst[0].Id);
                clssObj.Max_Seats__c  = 500;
                clssObj.recordTypeId = classrecTypeId;
                clssObj.Status__c='Active';
                clssLst.add(clssObj);
            }
            insert clssLst;
            
             //Creating the Training_Agreement_Class_Relationship__c test data.
            List<Enterprise_Training_Agreement__c> etaLst = [SELECT Id, Is_Active__c FROM Enterprise_Training_Agreement__c];
            List<Training_Agreement_Class_Relationship__c> TACRelLst = new List<Training_Agreement_Class_Relationship__c>(); 
            for(Integer i=0;i<ETAREL_COUNT;i++){
                Training_Agreement_Class_Relationship__c TACRelObj;
                TACRelObj = CTrainingTestDataBuilder.buildTestTAClassRelationship(clssLst[i].Id, ETagreeemntLst[i].Id);
                TACRelLst.add(TACRelObj);
            }
            insert TACRelLst;  
            
            
            Account acc = TestDataBuilder.buildTestAccount(1, usr.Id);
            insert acc;
                    
            List<Contact> conList = new List<Contact>();
            for(Integer i=0; i<CONTACT_COUNT; i++){  
                Contact con = TestDataBuilder.buildTestContact(i, usr.Id, acc.Id); 
                con.email = 'test'+i+'@test.com';
                conList.add(con);
            }
            insert conList;
         
        }//End of RunAs
    }//End of Method
             
            
            
    /*
    @ name    EnrollmentRequestUpdateTest
    @ date    1 June 2016
    @ author  Sagar Talele
    @ param   none.
    @ return  Void. 
    @ description : . 
     */
    
    private static testMethod void EnrollmentRequestUpdateTest(){
        EmailToEnrolleesBatchTest.setupTestData();
        System.RunAs(usr){
            List<Contact> conLst = [SELECT Id FROM Contact];
            List<Training_Agreement_Class_Relationship__c> etarList = [SELECT Id, Enterprise_Training_Agreement__c, Class__c, class__r.Format_Of_Class__c, 
                                                                      class__r.Course_Code__c FROM Training_Agreement_Class_Relationship__c order by Enterprise_Training_Agreement__c];
            
            
            
            System.assertEquals(conLst.size(), 10);
            System.assertEquals(etarList.size(), 10);
            
            Test.startTest();
            
            List<Enrollment_Request__c> enrolReqLst = new List<Enrollment_Request__c>();
            for(Integer i=0;i<ENROL_REQ_COUNT;i++){
                Enrollment_Request__c enrolReqObj = new Enrollment_Request__c();
                enrolReqObj.Enterprise_Training_Agreement__c = etarList[i].Enterprise_Training_Agreement__c;
                enrolReqObj.Contact__c = conLst[i].Id;
                enrolReqObj.Class__c = etarList[i].class__c;
                enrolReqObj.Status__c = 'Processing';
                enrolReqLst.add(enrolReqObj);
            }
            insert enrolReqLst;
            List<Enrollment_Request__c> insertedEnrolReqLst = [SELECT Id FROM Enrollment_Request__c];
            System.assertEquals(insertedEnrolReqLst.size(), 10);
            
           
           // List<Enrollment__c> enrolList = [SELECT Id, Enterprise_Training_Agreement__c FROM Enrollment__c];
           //h System.assertEquals(enrolList.size(), 10);
            
            List<Enrollment_Request__c> updatedEnrolReqLstSuccess = [SELECT Id, Exception_Reason__c,status__c,Enrollment__c FROM Enrollment_Request__c 
                                                              WHERE Status__c != 'Exception'];
            Set<Id> enrollIdSet = new Set<Id>();
            for(Enrollment_Request__c EnrolReqObj : updatedEnrolReqLstSuccess){
                //System.assertEquals(EnrolReqObj.status__c,'Pending Notification');
                //System.assert(EnrolReqObj.Enrollment__c!=null);
                enrollIdSet.add(EnrolReqObj.Id);
            }
            
            List<Enrollment_Request__c> updatedEnrolReqLst = [SELECT Id, Exception_Reason__c FROM Enrollment_Request__c 
                                                              WHERE Status__c = 'Exception'];
            System.assertEquals(updatedEnrolReqLst.size(), 0);
            for(Enrollment_Request__c errorEnrolReqObj : updatedEnrolReqLst){
               // System.assertEquals(errorEnrolReqObj.Exception_Reason__c, System.Label.Max_Enrollment_Error_Message);
            }
            System.enqueueJob(new EmailToEnrolleesBatch(enrollIdSet));
             Test.stopTest();
            List<Enrollment_Request__c> enrollReqLst = new List<Enrollment_Request__c>();
            enrollReqLst = [Select Id,status__c From Enrollment_Request__c where Id In :enrollIdSet];
            for(Enrollment_Request__c enrollObj : enrollReqLst){
                System.assertEquals(enrollObj.status__c,'Completed');
            }
            
        }//End of RunAs
    }
     /*
    @ name    createTaskTest
    @ date    18 June 2016
    @ author  Sagar Talele
    @ param   none.
    @ return  Void. 
    @ description : . 
    */
    
    private static testMethod void createTaskTest(){
        EmailToEnrolleesBatchTest.setupTestData();
        System.RunAs(usr){
            List<Contact> conLst = [SELECT Id FROM Contact];
            List<Training_Agreement_Class_Relationship__c> etarList = [SELECT Id, Enterprise_Training_Agreement__c, Class__c, class__r.Format_Of_Class__c, 
                                                                      class__r.Course_Code__c FROM Training_Agreement_Class_Relationship__c order by Enterprise_Training_Agreement__c];
            
            
            
            System.assertEquals(conLst.size(), 10);
            System.assertEquals(etarList.size(), 10);
            
            Test.startTest();
            
            List<Enrollment_Request__c> enrolReqLst = new List<Enrollment_Request__c>();
            for(Integer i=0;i<ENROL_REQ_COUNT;i++){
                Enrollment_Request__c enrolReqObj = new Enrollment_Request__c();
                enrolReqObj.Enterprise_Training_Agreement__c = etarList[i].Enterprise_Training_Agreement__c;
                enrolReqObj.Contact__c = conLst[i].Id;
                enrolReqObj.Class__c = etarList[i].class__c;
                enrolReqObj.Status__c = 'Processing';
                enrolReqLst.add(enrolReqObj);
            }
            insert enrolReqLst;
            List<Enrollment_Request__c> insertedEnrolReqLst = [SELECT Id FROM Enrollment_Request__c];
            System.assertEquals(insertedEnrolReqLst.size(), 10);
            
           
           // List<Enrollment__c> enrolList = [SELECT Id, Enterprise_Training_Agreement__c FROM Enrollment__c];
           //h System.assertEquals(enrolList.size(), 10);
            
            List<Enrollment_Request__c> updatedEnrolReqLstSuccess = [SELECT Id, Exception_Reason__c,status__c,Enrollment__c FROM Enrollment_Request__c 
                                                              WHERE Status__c != 'Exception'];
            Set<Id> enrollIdSet = new Set<Id>();
            for(Enrollment_Request__c EnrolReqObj : updatedEnrolReqLstSuccess){
                //System.assertEquals(EnrolReqObj.status__c,'Pending Notification');
                //System.assert(EnrolReqObj.Enrollment__c!=null);
                enrollIdSet.add(EnrolReqObj.Id);
            }
            
            List<Enrollment_Request__c> updatedEnrolReqLst = [SELECT Id, Exception_Reason__c FROM Enrollment_Request__c 
                                                              WHERE Status__c = 'Exception'];
            System.assertEquals(updatedEnrolReqLst.size(), 0);
            for(Enrollment_Request__c errorEnrolReqObj : updatedEnrolReqLst){
               // System.assertEquals(errorEnrolReqObj.Exception_Reason__c, System.Label.Max_Enrollment_Error_Message);
            }
            System.enqueueJob(new EmailToEnrolleesBatch(enrollIdSet));
             Test.stopTest();
            List<Enrollment_Request__c> enrollReqLst = new List<Enrollment_Request__c>();
            enrollReqLst = [Select Id,status__c From Enrollment_Request__c where Id In :enrollIdSet];
            for(Enrollment_Request__c enrollObj : enrollReqLst){
                System.assertEquals(enrollObj.status__c,'Completed');
            }
            List<Task> taskList = new List<Task>();
            taskList =[Select Id From Task where Status = 'Completed'];
            System.assertEquals(taskList.size(),10);
        }//End of RunAs
    }
    
}