objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publish_To_Web__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Publish To Web</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Seat_Price__c</fullName>
        <label>Seat Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Training_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training Location</label>
        <referenceTo>Training_Location__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Publish_to_Web__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Publish to Web</label>
        <type>Checkbox</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <recordTypes>
        <fullName>Training</fullName>
        <active>true</active>
        <description>Record type to create non certification course</description>
        <label>Training</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Language__c.object
<CustomObject>
    <label>Language</label>
    <nameField>
        <label>Language</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Training_Location__c.object
<CustomObject>
    <fields>
        <fullName>Country_Code__c</fullName>
        <description>Store the country Code.</description>
        <label>Country Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publish_To_Web__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Publish To Web</label>
        <type>Checkbox</type>
    </fields>
    <label>Training Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Training_Validation_Rule__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Training validation rules</description>
    <fields>
        <fullName>prevent_unpublish_location__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Prevent publishing a location if the location has associated classes published.</description>
        <label>prevent unpublish a location</label>
        <type>Checkbox</type>
    </fields>
    <label>Training Validation Rule</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <description>Used to define the area that a user works in. If a user works in more then 1 area, their primary area should be defined by this value. This is used as part of a trigger on Case to default the area when creating a new case based on the user.</description>
        <label>Area</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>APAC - Application Engineering</fullName>
                </value>
                <value>
                    <fullName>APAC - Pilot Engineering</fullName>
                </value>
                <value>
                    <fullName>APAC - Technical Evangelist</fullName>
                </value>
                <value>
                    <fullName>AU - Application Engineering</fullName>
                </value>
                <value>
                    <fullName>AU - Customer Support</fullName>
                </value>
                <value>
                    <fullName>AU - Install</fullName>
                </value>
                <value>
                    <fullName>AU - Pilot Engineering</fullName>
                </value>
                <value>
                    <fullName>AU - Revenue Accounting and Controls</fullName>
                </value>
                <value>
                    <fullName>AU - Sales</fullName>
                </value>
                <value>
                    <fullName>AU - Technical Support</fullName>
                </value>
                <value>
                    <fullName>BNL - Application Engineering</fullName>
                </value>
                <value>
                    <fullName>BNL - Customer Support</fullName>
                </value>
                <value>
                    <fullName>BNL - Install</fullName>
                </value>
                <value>
                    <fullName>BNL - Pilot Engineering</fullName>
                </value>
                <value>
                    <fullName>BNL - Revenue Accounting and Controls</fullName>
                </value>
                <value>
                    <fullName>BNL - Sales</fullName>
                </value>
                <value>
                    <fullName>BNL - Technical Support</fullName>
                </value>
                <value>
                    <fullName>Business Applications</fullName>
                </value>
                <value>
                    <fullName>CH - Application Engineering</fullName>
                </value>
                <value>
                    <fullName>CH - Customer Support</fullName>
                </value>
                <value>
                    <fullName>CH - Install</fullName>
                </value>
                <value>
                    <fullName>CH - Pilot Engineering</fullName>
                </value>
                <value>
                    <fullName>CH - Revenue Accounting and Controls</fullName>
                </value>
                <value>
                    <fullName>CH - Sales</fullName>
                </value>
                <value>
                    <fullName>CH - Technical Support</fullName>
                </value>
                <value>
                    <fullName>CN - Application Engineering</fullName>
                </value>
                <value>
                    <fullName>CN - Customer Support</fullName>
                </value>
                <value>
                    <fullName>CN - Install</fullName>
                </value>
                <value>
                    <fullName>CN - Pilot Engineering</fullName>
                </value>
                <value>
                    <fullName>CN - Revenue Accounting and Controls</fullName>
                </value>
                <value>
                    <fullName>ES - Customer Support</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <description>Customer Portal Field</description>
        <label>Country Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Test_User__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field will be set on the user records created from the Test classes. Also will be used in the process builder to opt out  user records with checked flag.</description>
        <label>Is Test User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Portal_User_Status__c</fullName>
        <label>Portal User Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Customer Portal Field</description>
        <label>Student</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TrainingLocTriggerHandlerTest.cls
/**
 *@author Original: Krishna Bhaskarla,Mathworks
 *@date Original:    Aug 19, 2015
 *@description:     This is a test class for TrainingLocTriggerHandler 
 */
@isTest
public class TrainingLocTriggerHandlerTest {
    static CustomSettingsBuilder custsettbuild = new CustomSettingsBuilder();
    private static testMethod void beforeUpdateTest(){
        //Inserting Bypass trigger custom setting
         custsettbuild.buildBypassTriggerSettings();
         //Create test user
        // User usr = TestDataBuilder.buildTrainingAdminTestUser(1);
        Profile p = [select pf.id from profile pf WHERE pf.name= 'MW Training Admin' limit 1];
        User usr = new User();
        usr.emailencodingkey    = 'UTF-8';
        usr.languagelocalekey   = 'en_US';
        usr.localesidkey        = 'en_US';
        usr.timezonesidkey      = 'America/Los_Angeles'; 
        usr.ProfileId = p.Id;
        usr.alias           = 'TUser1';
        usr.email           = 'TUser1@mathworks.com';
        usr.lastname        = 'TUser1';
        usr.username        = 'TUser1@mathworks.com';
        usr.Area__c         = 'ES - Customer Support';
        usr.Portal_User_Status__c = 'Student';
        usr.Student__c = false;
        usr.Country_Code__c = 'ph';
        usr.Is_Test_User__c = true;
         insert usr;
         System.runAs(usr){
             List<Training_Location__c> trainLocList = new List<Training_Location__c>();
             Training_Location__c trainLocObj = CTrainingTestDataBuilder.buildTestTrainingLoc(1);
             trainLocObj.Publish_To_Web__c = true;
             insert trainLocObj;
             Training_Location__c trainLocInt = [Select Id, Name From Training_Location__c where id =: trainLocObj.Id];
             System.assert(trainLocInt != null);
             //create Course__c record from CTrainingTestDataBuilder.
             Course__c courseObj = CTrainingTestDataBuilder.buildTestCourse(0);
             insert courseObj;
             Course__c courseInt = [Select Id, Name From Course__c where id =: courseObj.Id];
             System.assert(courseInt != null);
                      
             //create Language__c record from CTrainingTestDataBuilder.
             Language__c langObj = CTrainingTestDataBuilder.buildTestLanguage(1);
             insert langObj;
             Language__c langInt = [Select Id from Language__c where id =:langObj.Id];
             System.assert(langInt != null);
             // create class
             Class__c classObj =CTrainingTestDataBuilder.buildTestClass(1,courseObj.Id,langObj.Id);
             classObj.Training_Location__c = trainLocInt.Id;
             classObj.Publish_To_Web__c = true;
             classObj.Seat_Price__c = 10;
             insert classObj;
             trainLocList.add(trainLocInt);
             String errorMsg = system.label.Training_location_before_update;
             try{
                 Training_Location__c updateObj = trainLocList.get(0);
                 updateObj.Publish_To_Web__c = false;
                 Update updateObj;
             } catch(Exception e){
                 System.assert(e.getMessage().contains(errorMsg));
             }
            
         }
    }
    private static testMethod void beforeDeleteTest(){
         //Inserting Bypass trigger custom setting
         custsettbuild.buildBypassTriggerSettings();
         //Create test user
         User usr = TestDataBuilder.buildTestUser(1);
         insert usr;
         System.runAs(usr){
             List<Training_Location__c> trainLocList = new List<Training_Location__c>();
             Training_Location__c trainLocObj = CTrainingTestDataBuilder.buildTestTrainingLoc(1);
             insert trainLocObj;
             Training_Location__c trainLoc=[select Id,Name from Training_Location__c where Id =:trainLocObj.id];
             system.assert(trainLoc !=null);
             trainLocList.add(trainLoc);
             String errorMsg = system.label.Training_location_before_delete;
             try{
                 Delete trainLocList[0];
             } catch(Exception e){
                 System.assert(e.getMessage().contains(errorMsg));
             }
         }
    }

    private static testMethod void beforeUpdateTest2(){
         //Inserting Bypass trigger custom setting
         custsettbuild.buildBypassTriggerSettings();
         
         Training_Validation_Rule__c rule = new Training_Validation_Rule__c();
         rule.prevent_unpublish_location__c = true;
         insert rule;

         List<Training_Location__c> trainLocList = new List<Training_Location__c>();
         Training_Location__c trainLocObj = CTrainingTestDataBuilder.buildTestTrainingLoc(1);
         insert trainLocObj;

         Training_Location__c trainLoc=[select Id,Name from Training_Location__c where Id =:trainLocObj.id];
         system.assert(trainLoc !=null);
         trainLocList.add(trainLoc);
         String errorMsg = system.label.Training_location_before_delete;
         try{
            trainLocList[0].Publish_To_Web__c = false;
            update trainLocList[0];
         } catch(Exception e){
             System.assert(e.getMessage().contains(errorMsg));
         }
    }

    private static testMethod void beforeUpdateTest3() {
        //Inserting Bypass trigger custom setting
         custsettbuild.buildBypassTriggerSettings();

         Training_Validation_Rule__c rule = new Training_Validation_Rule__c();
         rule.prevent_unpublish_location__c = true;
         insert rule;
         
         List<Training_Location__c> trainLocList = new List<Training_Location__c>();
         Training_Location__c trainLocObj1 = CTrainingTestDataBuilder.buildTestTrainingLoc(1);
         Training_Location__c trainLocObj2 = CTrainingTestDataBuilder.buildTestTrainingLoc(2);

         trainLocObj1.Publish_To_Web__c = true;

         trainLocList.add(trainLocObj1);
         trainLocList.add(trainLocObj2);

         insert trainLocList;

         Course__c courseObj = CTrainingTestDataBuilder.buildTestCourse(0);
         insert courseObj;
        
         Language__c langObj = CTrainingTestDataBuilder.buildTestLanguage(1);
         insert langObj;

         Class__c classObj =CTrainingTestDataBuilder.buildTestClass(1, courseObj.Id, langObj.Id);
         classObj.Training_Location__c = trainLocList[0].Id;
         classObj.Publish_To_Web__c = true;
         classObj.Seat_Price__c = 10;
         insert classObj;

         try {
            trainLocList[0].Publish_To_Web__c = false;
            update trainLocList;
         } catch(DmlException dmlEx) {
            System.assert(true);
         }
    }
}