objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Course_Code__c</fullName>
        <label>Part Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sponsor_Office_Email__c</fullName>
        <description>Sponsor Office Email to be used for Enrollment Email Notifications. (The related object Sponsor Office cannot be accessed from the email Template).</description>
        <formula>Sponsor_Office__r.Email__c</formula>
        <inlineHelpText>Sponsor Office Email to be used for Enrollment Email Notifications.</inlineHelpText>
        <label>Sponsor Office Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sponsor_Office_Phone__c</fullName>
        <description>Sponsor Office Name to be used for Enrollment Email Notifications. (The related object Sponsor Office cannot be accessed from the email Template).</description>
        <formula>Sponsor_Office__r.Phone__c</formula>
        <inlineHelpText>Sponsor Office Phone to be used for Enrollment Email Notifications.</inlineHelpText>
        <label>Sponsor Office Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sponsor_Office_Signature__c</fullName>
        <description>Sponsor Office Signature to be used for Enrollment Email Notifications. (The related object Sponsor Office cannot be accessed from the email Template).</description>
        <formula>SUBSTITUTE(Sponsor_Office__r.Signature__c, &apos;&lt;br/&gt;&apos;, &apos;&apos;)</formula>
        <inlineHelpText>Sponsor Office Signature to be used for Enrollment Email Notifications.</inlineHelpText>
        <label>Sponsor Office Signature</label>
        <type>Text</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <description>Contact Preferred Language</description>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Swedish</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Portuguese</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Course_Code__c</fullName>
        <label>Part Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Course_Language__c.object
<CustomObject>
    <fields>
        <fullName>Course_Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Course Languages</relationshipLabel>
        <relationshipName>Course_Languages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Languages</relationshipLabel>
        <relationshipName>Course_Languages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Localized_Course_Name__c</fullName>
        <inlineHelpText>Translated version of the English Course Name into the Language this record represents</inlineHelpText>
        <label>Localized Course Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Course Language</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Course Language Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Enterprise_Training_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Enterprise Training Agreements</relationshipLabel>
        <relationshipName>Enterprise_Training_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active_Self_Enrollment_URL__c</fullName>
        <label>Active Self-Enrollment URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Language to display content in on self-enrollment portal</inlineHelpText>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Enterprise Training Agreements</relationshipLabel>
        <relationshipName>Enterprise_Training_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Enterprise Training Agreements</relationshipLabel>
        <relationshipName>Enterprise_Training_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sponsor_Office_Email__c</fullName>
        <formula>Sponsor_Office__r.Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sponsor Office Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sponsor_Office_Phone__c</fullName>
        <formula>Sponsor_Office__r.Phone__c</formula>
        <label>Sponsor Office Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sponsor_Office_Signature__c</fullName>
        <formula>Sponsor_Office__r.Signature__c</formula>
        <label>Sponsor Office Signature</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Term_End_Date__c</fullName>
        <description>Agreement expiration date</description>
        <label>Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Term_Start_Date__c</fullName>
        <description>The date the agreement becomes effective</description>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <label>Enterprise Training Agreement</label>
    <nameField>
        <label>Enterprise Training Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enterprise Training Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Language__c.object
<CustomObject>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <label>ISO Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language_Code__c</fullName>
        <label>Language Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language_Display_Name__c</fullName>
        <inlineHelpText>Name that should be displayed to external users when viewing the Language of a Course/Class</inlineHelpText>
        <label>Language Display Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_ISO_Code__c</fullName>
        <description>The universal ISO language code.</description>
        <inlineHelpText>The universal ISO language code.</inlineHelpText>
        <label>Salesforce ISO Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Language</label>
    <nameField>
        <label>Language</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Language_Display_Name__c.object
<CustomObject>
    <description>Contains the display names</description>
    <fields>
        <fullName>Display_Name__c</fullName>
        <label>Display Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Language Display Names</relationshipLabel>
        <relationshipName>Language_Display_Names</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Language_code__c</fullName>
        <label>Language_code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Language Display Name</label>
    <nameField>
        <label>Language Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Language Display Names</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Training_Agreement_Class_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Class__c.Format_Of_Class__c</field>
                <operation>equals</operation>
                <value>Self-Paced</value>
            </filterItems>
            <filterItems>
                <field>Class__c.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enterprise Agreement</relationshipLabel>
        <relationshipName>Training_Agreement_Class</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <description>Part Number</description>
        <formula>Class__r.Course__r.Course_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Part Number</inlineHelpText>
        <label>Course Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Training_Agreement_Class_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Agreement Class Relationship</label>
    <nameField>
        <displayFormat>AC-{0000}</displayFormat>
        <label>Training Agreement Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Agreement Class Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TCNotificationController.cls
/**
 *@author Original: Sagar Talele - Cloud Sherpas/Mathworks, Last Modified: Shweta Shanbhag - Mathworks
 *@date Original: 13 May 2016, Last Modified: 15 December 2016
 *@description: This Class getting the value of Eta related values
 */
public Class TCNotificationController{
    public Enterprise_Training_Agreement__c etaObj {get;set;}
    public String etaId {get;set;}
     public String lang {get;set;}
    /**
    *    @author         Sagar Talele
    *    @date           7 July 2016
    *    @description    get the language code which is used on Visualforce page to set the language of the page
    */
    public String  language { 
        get{
            If(lang!= null || !String.isEmpty(lang)){
                language = lang;
                if(!String.isEmpty(language) && !TrainingUtil.doesLanguageExist(language)) {
                    // If there is no language code from URL or ETA, set default to English
                    language = TrainingUtil.DEFAULT_LANGUAGE_CODE;
                }
            }else{
                language = TrainingUtil.DEFAULT_LANGUAGE_CODE;
            }
            return language;
        }
        set{
           
        }
    }
    /**
     *@author Original: Sagar Talele - Cloud Sherpas/Mathworks, Last Modified: Sagar Talele - Cloud Sherpas/Mathworks
     *@date Original: 5 July 2016, Last Modified: 5 July 2016
     *@description: This method is for getting the value of ETA Record
     */
    public String getEnrollName() {
    String enrolleeName='';
        etaObj = [Select Id,Primary_Contact__r.Name,
                    Primary_Contact__r.LastName,
                    Primary_Contact__r.FirstName,
                    Account_Name__r.Name,
                    Account_Name__c,
                    Sponsor_Office_Phone__c,
                    Sponsor_Office_Email__c,
                    Sponsor_Office_Signature__c,
                    Term_End_Date__c,
                  	Term_Start_Date__c,
                    Language__r.SF_ISO_Code__c,
                    Active_Self_Enrollment_URL__c
                    From Enterprise_Training_Agreement__c
                    where Id =:etaId ];
        if(etaObj !=null){
            if(etaObj.Language__r.SF_ISO_Code__c == 'ja'){
                enrolleeName = etaObj.Primary_Contact__r.LastName + ' '+etaObj.Primary_Contact__r.FirstName;
            }
            else{
                enrolleeName = etaObj.Primary_Contact__r.Name;
            }             
        }
        System.debug('**etaEnrollName**'+etaObj);
        return enrolleeName;
    }
    /**
     *@author Original: Sagar Talele - Cloud Sherpas/Mathworks, Last Modified: Shweta Shanbhag
     *@date Original: 5 July 2016, Last Modified: 15 December 2016,
     *@description: This method is for getting the value of TAH AGREEMENT EXPIRY; SS - changed for Story:1837839
     */
    public String getEtaExpiryDate() {
       String returnDate = '';
       date expiryDate = etaObj.Term_End_Date__c;
         returnDate = DateTime.newInstance(expiryDate.year(), expiryDate.month(), expiryDate.day()).format('dd-MMM-yyyy');
        return returnDate ;
    } 
    
     /**
     *@author Original: Shweta Shanbhag - Mathworks, Last Modified: Shweta Shanbhag - Mathworks
     *@date Original: 12 Sep 2016, Last Modified: 12 Sep 2016
     *@description: This method is for getting the value of ETA Start Date;SS - changed for Story:1837839
     */
    public String getEtaStartDate() {
       String returnStDate = '';
       date StartDate = etaObj.Term_Start_Date__c;
       returnStDate = DateTime.newInstance(StartDate.year(), StartDate.month(), StartDate.day()).format('dd-MMM-yyyy');
       return returnStDate ;
    } 
    /**
     *@author Original: Sagar Talele - Cloud Sherpas/Mathworks, Last Modified: Shweta Shanbhag - MathWorks
     *@date Original: 5 July 2016, Last Modified: 25 August 2016
     *@description: This method is for getting the value of courses for the related to the eta
     */
    public String getRelatedEtaCourses(){
       List<Training_Agreement_Class_Relationship__c> trainAgrRelList = new List<Training_Agreement_Class_Relationship__c>();
       Map<Id, Id> courseClassMap = new Map<Id, Id>();
       Map<Id, Id> classCourseMap = new Map<Id, Id>();    
       Language_Display_Name__c langDisplayName = new Language_Display_Name__c();
       List<Course_Language__c> courseLangList = new List<Course_Language__c>();
       Map<Id, Course_Language__c> courseLanguageMap = new Map<Id, Course_Language__c>();
       Map<String,List<Language_Display_Name__c>> langCodeTolangDisplayNameMap = new Map<String,List<Language_Display_Name__c>>(); 
       String courseStr = '';
       
        trainAgrRelList = [Select Class__r.Course__r.Name 
                        From Training_Agreement_Class_Relationship__c 
                            Where Enterprise_Training_Agreement__c =:etaId];
        
        
        
        for(Training_Agreement_Class_Relationship__c trainAgrObj : trainAgrRelList){
            courseClassMap.put(trainAgrObj.Class__r.Course__c, trainAgrObj.Class__c);
            classCourseMap.put(trainAgrObj.Class__c, trainAgrObj.Class__r.Course__c);          
        }
        
         Map<Id, Course__c> courseMap = new Map<Id, Course__c>([SELECT Id 
                                                                FROM Course__c 
                                                                WHERE Id IN :courseClassMap.keySet()]);
        
         Map<Id, Class__c> classMap = new Map<Id, Class__c>([SELECT Id, Course__c, Course_Code__c, Language__r.Name,
                                                              Language__r.Language_Code__c, 
                                                              Language__r.Language_Display_Name__c,
                                                              Language__r.ISO_Code__c
                                                              FROM Class__c 
                                                              WHERE Id IN :classCourseMap.keySet()]);
        
        courseLangList = [Select Id,Localized_Course_Name__c, Course__c, Course_Language__c, 
                          Course_Language__r.SF_ISO_Code__c,Course_Language__r.ISO_Code__c, Course_Language__r.Language_Display_Name__c
                          From Course_Language__c 
                          where Course__c IN: courseClassMap.keySet()  
                          And Course_Language__r.SF_ISO_Code__c =:etaObj.Language__r.SF_ISO_Code__c];
        
        
		for(Course_Language__c courseLanObj : courseLangList){
        	courseLanguageMap.put(courseLanObj.Course__c, courseLanObj);	
        }
        system.debug('***ETA Language***'+etaObj.Language__r.SF_ISO_Code__c );
        
         for(Language_Display_Name__c langObj : [Select Id, Display_Name__c,Language__c,Language_code__c,
                                                Language__r.SF_ISO_Code__c,Language__r.ISO_Code__c
                                                From Language_Display_Name__c 
                                                where Language__r.SF_ISO_Code__c =: etaObj.Language__r.SF_ISO_Code__c])
        		{
                if(!langCodeTolangDisplayNameMap.ContainsKey(langObj.Language__r.ISO_Code__c) ){
                    langCodeTolangDisplayNameMap.put(langObj.Language__r.ISO_Code__c,new List<Language_Display_Name__c>{langObj});
                }else{
                    langCodeTolangDisplayNameMap.get(langObj.Language__r.ISO_Code__c).add(langObj);
                }
           
              }
        
         if(langCodeTolangDisplayNameMap!= null && langCodeTolangDisplayNameMap.size() == 0){
                
                for(Language_Display_Name__c langObj : [Select Id, Display_Name__c,Language__c,Language_code__c,Language__r.SF_ISO_Code__c,
                                                    Language__r.ISO_Code__c
                                                    From Language_Display_Name__c where Language__r.SF_ISO_Code__c =:TrainingUtil.DEFAULT_LANGUAGE_CODE]){
                    if(!langCodeTolangDisplayNameMap.ContainsKey(langObj.Language__r.ISO_Code__c) ){
                        langCodeTolangDisplayNameMap.put(langObj.Language__r.ISO_Code__c,new List<Language_Display_Name__c>{langObj});
                    }else{
                        langCodeTolangDisplayNameMap.get(langObj.Language__r.ISO_Code__c).add(langObj);
                    }
                 
                }
            }
        
        for(Id classId : classMap.keySet()) {
                Class__c etaclass = classMap.get(classId);
                Course__c course = courseMap.get(etaclass.Course__c);
                Course_Language__c courseLanguage = courseLanguageMap.get(course.Id);
                List<Language_Display_Name__c> langDisplayNameList = NULL;
                langDisplayNameList = langCodeTolangDisplayNameMap.get(courseLanguage.Course_Language__r.ISO_Code__c);
                
                if(langDisplayNameList == NULL ){
                    langDisplayNameList = langCodeTolangDisplayNameMap.get(TrainingUtil.DEFAULT_LANGUAGE_ISOCODE);
                }
                for(Language_Display_Name__c obj: langDisplayNameList){
                      if(obj.Language_code__c == etaclass.Language__r.ISO_Code__c && (obj.Language__r.SF_ISO_Code__c == etaObj.Language__r.SF_ISO_Code__c || obj.Language__r.SF_ISO_Code__c ==TrainingUtil.DEFAULT_LANGUAGE_CODE)){
                        langDisplayName = obj;
                    }
                
                }
             courseStr = courseStr + courseLanguage.Localized_Course_Name__c + ' ('+ langDisplayName.Display_Name__c + ')' + '<br/>';
         }
        
        return courseStr;
    }
}