objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Course_Code__c</fullName>
        <label>Part Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <label>Max Seats</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Mark for Deletion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <description>Contact Preferred Language</description>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Swedish</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Portuguese</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Course_Code__c</fullName>
        <label>Part Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <default>true</default>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <recordTypes>
        <fullName>Training</fullName>
        <active>true</active>
        <description>Record type to create non certification course</description>
        <label>Training</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Enrollment__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>Class_Enrollees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Course_Code__c</fullName>
        <formula>Class__r.Course_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Course Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enrollment_Status__c</fullName>
        <label>Enrollment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Awaiting Payment</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Class Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
                <value>
                    <fullName>No Show-Bill</fullName>
                </value>
                <value>
                    <fullName>Registered - Awaiting Payment</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>!!! CHECK ME !!! -</fullName>
                </value>
                <value>
                    <fullName>!!! CHECK ME !!! -*** Unselected ***</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Language__c.object
<CustomObject>
    <fields>
        <fullName>SF_ISO_Code__c</fullName>
        <description>The universal ISO language code.</description>
        <inlineHelpText>The universal ISO language code.</inlineHelpText>
        <label>Salesforce ISO Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Language</label>
    <nameField>
        <label>Language</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EnrollmentServicev1Test.cls
/**
 * @author Original: Haigang Wu - Mathworks
 * @date Original: Jan 24 2017
 * @description: Enrollment REST service test.
 * @revision: 
 */ 


@isTest
private class EnrollmentServicev1Test {
    //re-create custom setting test records when running the test class
    static CustomSettingsBuilder custsettbuild = new CustomSettingsBuilder();
    static CTrainingCustomSettingBuilder cTrainSettingBuilder = new CTrainingCustomSettingBuilder();

    private static final Integer RECORD_COUNT = 5;
    private static User usr;
    private static string enrollId;
    private static string classId;
    private static string contactEmail;
    
    static void dummyData(){
        
        //Inserting Bypass trigger custom setting
        custsettbuild.buildBypassTriggerSettings();
        //re-create the Enrollment Code Configuration Setting
        cTrainSettingBuilder.buildEnrollmentCodeConfiguration();
        
        //Create test user
        //usr = TestDataBuilder.buildTestUser(1);

        //insert usr;
        usr = [SELECT Id, Email FROM User WHERE Id =: UserInfo.getUserId()];
        System.runAs(usr){
        
             List<Language__c> langList = new List<Language__c>();
            //create Language__c record from CTrainingTestDataBuilder.
            for(Integer i=0; i<5; i++){
                Language__c langObj = CTrainingTestDataBuilder.buildTestLanguage(i);
                langObj.SF_ISO_Code__c = (Math.mod(i,2) == 0 ? 'en_US' : 'ko');
                langList.add(langObj);
            }
            insert langList;
            
            //Creating the Course__c test data.
            Id courserecTypeId = Schema.SObjectType.Course__c.getRecordTypeInfosByName().get('Training').getRecordTypeId();
            List<Course__c> courseLst = new List<Course__c>();
            for(Integer i=0; i<RECORD_COUNT; i++){
                Course__c courseObj = CTrainingTestDataBuilder.buildTestCourse(i);
                courseObj.recordTypeId = courserecTypeId;
                courseObj.Course_Code__c = 'TESTCODE'+i;
                courseLst.add(courseObj);
            }
            insert courseLst;
            
             //Creating the Class__c test data.
            List<Class__c> clssLst = new List<Class__c>();    
            Id classrecTypeId = Schema.SObjectType.Class__c.getRecordTypeInfosByName().get('Self-Paced').getRecordTypeId();    
            //Creating the test data for Class Object. 
            for(Integer i=0;i<RECORD_COUNT;i++){            
                Class__c clssObj = CTrainingTestDataBuilder.buildTestClass(i, courseLst[i].Id, langList[0].Id);
                clssObj.Max_Seats__c  = 500;
                clssObj.recordTypeId = classrecTypeId;
                clssObj.Status__c='Active';
                clssLst.add(clssObj);
            }
            insert clssLst;
            
            Account acc = TestDataBuilder.buildTestAccount(1, usr.Id);
            insert acc;
                
            List<Contact> conList = new List<Contact>();
            for(Integer i=0; i<RECORD_COUNT; i++){  
                Contact con = TestDataBuilder.buildTestContact(i, usr.Id, acc.Id); 
                conList.add(con);
            }
            insert conList;
            contactEmail = conList[0].Email;
            
            List<Enrollment__c> enrolmntLst = new List<Enrollment__c>();
            for(Integer i=0; i<RECORD_COUNT; i++){
                Enrollment__c enrolmntObj = CTrainingTestDataBuilder.buildTestEnrollment(conList[i].id, clssLst[0].id);
                enrolmntObj.Enrollment_Status__c = 'Registered';
                enrolmntLst.add(enrolmntObj);
            }
            
            insert enrolmntLst;
            enrollId = enrolmntLst[0].id;
            classId = clssLst[0].id;
            
        }//End of Run As User
    }
    

    static testMethod void getPingTest1() {
		RestRequest req = new RestRequest();
		RestResponse res = new RestResponse();

		req.requestURI = '/services/apexrest/training/v1/enrollments/ping';
		req.httpMethod = 'GET';
		RestContext.request = req;
		RestContext.response = res;
		
		Test.startTest();
		EnrollmentServicev1.getEnrollmentbyId();
		Test.stopTest();
		
		system.assertEquals(200, RestContext.response.statuscode);        
		Map<String, Object> m = (Map<String, Object>) JSON.deserializeUntyped(RestContext.response.responseBody.toString());
		system.assertEquals('Working', m.get('message'));        
    }

    static testMethod void getPingTest2() {
		RestRequest req = new RestRequest();
		RestResponse res = new RestResponse();

		req.requestURI = '/services/apexrest/training/v1/enrollments/';
		req.httpMethod = 'GET';
		RestContext.request = req;
		RestContext.response = res;
		
		Test.startTest();
		EnrollmentServicev1.getEnrollmentbyId();
		Test.stopTest();
		
		system.assertEquals(200, RestContext.response.statuscode);        
		Map<String, Object> m = (Map<String, Object>) JSON.deserializeUntyped(RestContext.response.responseBody.toString());
		system.assertEquals('Working', m.get('message'));        
    }

    static testMethod void getInvalidEnrollmentIdTest() {
		RestRequest req = new RestRequest();
		RestResponse res = new RestResponse();

		req.requestURI = '/services/apexrest/training/v1/enrollments/fakeid';
		req.httpMethod = 'GET';
		RestContext.request = req;
		RestContext.response = res;
		
		Test.startTest();
		EnrollmentServicev1.getEnrollmentbyId();
		Test.stopTest();
		
		system.assertEquals(400, RestContext.response.statuscode);        
		Map<String, Object> m = (Map<String, Object>) JSON.deserializeUntyped(RestContext.response.responseBody.toString());
		system.assertEquals(System.Label.Enrollment_not_found, m.get('message'));        
    }

    static testMethod void getValidEnrollmentIdTest() {
		dummyData();

		RestRequest req = new RestRequest();
		RestResponse res = new RestResponse();

		req.requestURI = '/services/apexrest/training/v1/enrollments/' + enrollId;
		req.httpMethod = 'GET';
		RestContext.request = req;
		RestContext.response = res;
		
		Test.startTest();
		EnrollmentServicev1.getEnrollmentbyId();
		Test.stopTest();
		
		system.assertEquals(200, RestContext.response.statuscode);        
		Map<String, Object> m = (Map<String, Object>) JSON.deserializeUntyped(RestContext.response.responseBody.toString());
		system.assertEquals(classId, m.get('classId'));        
    }

    static testMethod void postPingTest() {
		RestRequest req = new RestRequest();
		RestResponse res = new RestResponse();

		req.requestURI = '/services/apexrest/training/v1/enrollments/ping';
		req.httpMethod = 'POST';
		RestContext.request = req;
		RestContext.response = res;
		
		Test.startTest();
		EnrollmentServicev1.newenrollments('cybernetictoday@gmail.com.mwtest','a2f18000000Q5lE','Registered','Credit Terms,','59966','1234','C33211111','20','Manual Enrollment');
		Test.stopTest();
		
		system.assertEquals(200, RestContext.response.statuscode);        
		Map<String, Object> m = (Map<String, Object>) JSON.deserializeUntyped(RestContext.response.responseBody.toString());
		system.assertEquals('Working', m.get('message'));        
    }

    static testMethod void postBlankEmailTest() {
		RestRequest req = new RestRequest();
		RestResponse res = new RestResponse();

		req.requestURI = '/services/apexrest/training/v1/enrollments/';
		req.httpMethod = 'POST';
		RestContext.request = req;
		RestContext.response = res;
		
		Test.startTest();
		EnrollmentServicev1.newenrollments('','a2f18000000Q5lE','Registered','Credit Terms,','59966','1234','C33211111','20','Manual Enrollment');
		Test.stopTest();
		
		system.assertEquals(400, RestContext.response.statuscode);        
		Map<String, Object> m = (Map<String, Object>) JSON.deserializeUntyped(RestContext.response.responseBody.toString());
		system.assertEquals(System.Label.Enrollment_Required_Fields, m.get('message'));        
    }

    static testMethod void postGlobalContactSearchFailTest() {
		RestRequest req = new RestRequest();
		RestResponse res = new RestResponse();

		req.requestURI = '/services/apexrest/training/v1/enrollments/';
		req.httpMethod = 'POST';
		RestContext.request = req;
		RestContext.response = res;
		
		Test.startTest();
		EnrollmentServicev1.newenrollments('test@test.com','a2f18000000Q5lE','Registered','Credit Terms,','59966','1234','C33211111','20','Manual Enrollment');
		Test.stopTest();
		
		system.assertEquals(400, RestContext.response.statuscode);        
		Map<String, Object> m = (Map<String, Object>) JSON.deserializeUntyped(RestContext.response.responseBody.toString());
		system.assertEquals(System.Label.Enrollment_Contact_not_found, m.get('message'));        
    }

    static testMethod void postInsertEnrollmentTest() {
		dummyData();

		RestRequest req = new RestRequest();
		RestResponse res = new RestResponse();

		req.requestURI = '/services/apexrest/training/v1/enrollments/';
		req.httpMethod = 'POST';
		RestContext.request = req;
		RestContext.response = res;
		
		Test.startTest();
		EnrollmentServicev1.newenrollments(contactEmail,classId,'Registered','Credit Terms,','59966','1234','C33211111','20','Manual Enrollment');
		Test.stopTest();
		
		system.assertEquals(201, RestContext.response.statuscode);        
		Map<String, Object> m = (Map<String, Object>) JSON.deserializeUntyped(RestContext.response.responseBody.toString());
		system.assertEquals(contactEmail, m.get('enrolleeEmail'));        
    }

}