objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <label>Max Seats</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Send_Email__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Send Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sponsor_Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sponsor Office</label>
        <referenceTo>Sponsor_Office__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Start Date to be used on the Quick Action. Start Date/Time will be on the Layouts with the Time defaulted based on Sponsor Office.</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <description>Contact Preferred Language</description>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Swedish</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Portuguese</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Course__c.object
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Enrollment__c.object
<CustomObject>
    <fields>
        <fullName>Certification_Exam_Agreement__c</fullName>
        <label>Certification Exam Agreement</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accept</fullName>
                </value>
                <value>
                    <fullName>Decline</fullName>
                </value>
                <value>
                    <fullName>Awaiting Response</fullName>
                    <default>true</default>
                    <label>Awaiting Response</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>Class_Enrollees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Enrollment_Status__c</fullName>
        <label>Enrollment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Awaiting Payment</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Class Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
                <value>
                    <fullName>No Show-Bill</fullName>
                </value>
                <value>
                    <fullName>Registered - Awaiting Payment</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>!!! CHECK ME !!! -</fullName>
                </value>
                <value>
                    <fullName>!!! CHECK ME !!! -*** Unselected ***</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_Awaiting_Payment_Notification__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The flag will be set to True when the status of an enrollment is changed to Awaiting Payment. This flag will be used to determine the base template to be used for email.</description>
        <inlineHelpText>Resend Awaiting Payment email notification</inlineHelpText>
        <label>Send Awaiting Payment Notification</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Flag for whether automated email notifications should be sent related to this enrollment</inlineHelpText>
        <label>Send Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_Registered_AP_Notification__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The flag will be set to True when the status of an enrollment is changed to Registered - Awaiting Payment. This flag will be used to determine the base template to be used for email.</description>
        <inlineHelpText>Resend Registered - Awaiting Payment email notification</inlineHelpText>
        <label>Send Registered - AP Notification</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_Registered_Notification__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The flag will be set to True when the status of an enrollment is changed to Registered. This flag will be used to determine the base template to be used for email.</description>
        <inlineHelpText>Resend Registered email notification</inlineHelpText>
        <label>Send Registered Notification</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{00000000}</displayFormat>
        <label>Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Enterprise_Training_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Language to display content in on self-enrollment portal</inlineHelpText>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Enterprise Training Agreements</relationshipLabel>
        <relationshipName>Enterprise_Training_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <label>Max Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sponsor_Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sponsor Office</label>
        <referenceTo>Sponsor_Office__c</referenceTo>
        <relationshipLabel>Enterprise Training Agreements</relationshipLabel>
        <relationshipName>Enterprise_Training_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enterprise Training Agreement</label>
    <nameField>
        <label>Enterprise Training Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enterprise Training Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Language__c.object
<CustomObject>
    <label>Language</label>
    <nameField>
        <label>Language</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sponsor_Office__c.object
<CustomObject>
    <label>Sponsor Office</label>
    <nameField>
        <label>Sponsor Office</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sponsor Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpdateNotificationFlagOnEnrollmentTest.cls
/**
 *@author Original: Abhay Verma - Cloud Sherpas/Mathworks, Last Modified: 
 *@date Original:   9 Sep 2015, Last Modified: 
 *@description:     Test class to testing the functionality of the UpdateNotificationFlagOnEnrollment.
 */
 
@isTest
public class UpdateNotificationFlagOnEnrollmentTest{
	//re-create custom setting test records when running the test class
	static CustomSettingsBuilder custsettbuild = new CustomSettingsBuilder();
    
	/*
	@ name    noClassSelectedTest
	@ date    9 Sep 2015
	@ author  Abhay Verma
	@ param   none.
	@ return  Void. 
	@ description :Testing Method to test the UpdateNotificationFlagOnEnrollment Class. 
    */
    
    //DMA 	@testSetup method will persist data for future test methods within this class
    //		Scheduled batch apex will begin execution at Test.StopTest() but may not finish before statements immediately after Test.StopTest() (such as assertions)
    //		Placing it in this @testSetup method will ensure the batch apex finishes before this method returns
    //		Assertions can then be performed in a subsequent test method
    //		
	@testSetup static void UpdateNotificationFlagTestSetup() {    
		//Inserting Bypass trigger custom setting
		custsettbuild.buildBypassTriggerSettings();
		//Create test user
		User usr = TestDataBuilder.buildTestUser(1);
		insert usr;
        List<Enrollment__c> enrolLst = new List<Enrollment__c>();
     
		System.runAs(usr){
			//create Training_Entitlement__c record from CTrainingTestDataBuilder.
			List<Enterprise_Training_Agreement__c> eTALst = new List<Enterprise_Training_Agreement__c>();
			for(Integer i=0;i<=1;i++){
				Enterprise_Training_Agreement__c ETAgreementObj = CTrainingTestDataBuilder.buildTestETAgreement(0);
				ETAgreementObj.Max_Seats__c = 210;
				eTALst.add(ETAgreementObj);
			}
			insert eTALst;
            
			Enterprise_Training_Agreement__c  ETAgreement = [Select Id,Name From Enterprise_Training_Agreement__c WHERE id =: eTALst[0].Id];
			System.assert(ETAgreement != null);
         
			//create Course__c record from CTrainingTestDataBuilder.
			Course__c courseObj = CTrainingTestDataBuilder.buildTestCourse(0);
			insert courseObj;
			Course__c courseInt = [Select Id, Name From Course__c where id =: courseObj.Id];
			System.assert(courseInt != null);
             
			//create Language__c record from CTrainingTestDataBuilder.
			Language__c langObj = CTrainingTestDataBuilder.buildTestLanguage(1);
			insert langObj;
			Language__c langInt = [Select Id from Language__c where id =:langObj.Id];
			System.assert(langInt != null);
			Id RecTypeId = Schema.SObjectType.Class__c.getRecordTypeInfosByName().get('Distance Learning').getRecordTypeId();
            
			//Create Sponsor_Office__c 
			Sponsor_Office__c sponOfficeObj = CTrainingTestDataBuilder.buildTestSponsorOffice(0,langObj.Id);
			sponOfficeObj.Name = 'BNL';
			insert sponOfficeObj ;
			Sponsor_Office__c sponOfficeInt = [Select Id From Sponsor_Office__c Where Id =:sponOfficeObj.Id];
			System.assert(sponOfficeInt != null);
             
            
			//intialize class list to create multiple records for class.
			List<Class__c> classList = new List<Class__c>();
			for(Integer i=0;i<3;i++){
				Class__c classObj =CTrainingTestDataBuilder.buildTestClass(i,courseObj.Id,langObj.Id);
				classObj.Max_Seats__c  = 400; 
				classObj.Start_Date__c = Date.Today() + 10;
				classObj.RecordTypeId = RecTypeId;
				classObj.Sponsor_Office__c = sponOfficeObj.Id;
				classList.add(classObj);
			}
			insert classList;
			Class__c classInt = [Select Id,Name From Class__c Where Id =: classList[0].Id];
			System.assert(classInt != null);
             
			//create Account record from TestDataBuilder.
			Account accObj = TestDataBuilder.buildTestAccount(0,UserInfo.getUserId());
			insert accObj;
			Account accountInt = [select Id,Name from Account where Id =: accObj.Id];
			system.assert(accountInt != null);   
             
			//create Contact record from TestDataBuilder.
			Contact contL = TestDataBuilder.buildTestContact(0,UserInfo.getUserId(),accObj.id);
			insert contL;
			Contact conInt = [Select Id,Name From Contact Where Id =: contL.Id];
			system.assert(conInt != null); 
            
			Integer i;
			for(i=0;i<=199;i++){
				Enrollment__c enrolObj =  CTrainingTestDataBuilder.buildTestEnrollment(conInt.Id, classList[0].Id);
				enrolObj.Send_Email__c = True;
				enrolObj.Start_Date__c = Date.Today() + 1;
				enrolObj.Enterprise_Training_Agreement__c = eTALst[0].Id; 
				enrolObj.Enrollment_Status__c = Math.mod(i,2) == 0?'Registered - Awaiting Payment':'Awaiting Payment';
                
				if(i<50){                     
					enrolObj.Enrollment_Status__c = 'Registered';
					enrolObj.Certification_Exam_Agreement__c= 'Awaiting Response';
				}
                
				if(enrolObj.Enrollment_Status__c == 'Registered - Awaiting Payment'){
					enrolObj.Send_Registered_AP_Notification__c = False;
				}
				else if(enrolObj.Enrollment_Status__c == 'Awaiting Payment'){
					enrolObj.Send_Awaiting_Payment_Notification__c = False;
				}
				enrolLst.add(enrolObj);
			}
			insert enrolLst;
        }
		Test.startTest();
		CronTrigger cronTrigger;
		Id jobId;
		String scheduleExpression = '0 5 0 * * ?';
		jobId = System.Schedule('Test Schedule', scheduleExpression, new UpdateNotificationFlagOnEnrollment());
        Test.stopTest();
       	
        //Get the CronTrigger info
		cronTrigger = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE Id = :jobId];
		//Verify that the expressions are the same; Scheduled Job has been added on cronTrigger
		System.assertEquals(scheduleExpression, cronTrigger.CronExpression);
    }
	@isTest static void UpdateNotificationFlagTestAssertions() { 

		//Query the Updated Enrollment Records
		List<Enrollment__c> updatedEnrolLst = [SELECT Id,Send_Registered_Notification__c,Certification_Exam_Agreement__c, Enrollment_Status__c, Send_Registered_AP_Notification__c, Send_Awaiting_Payment_Notification__c FROM Enrollment__c];                                                                                                                                                                                                                                                                                                                                         
		System.debug('___ Enrollment count= '+updatedEnrolLst.size());
        System.debug('updatedEnrolLst **&& ' +updatedEnrolLst);
                         
		for(Enrollment__c enrolObj : updatedEnrolLst){
			if(enrolObj.Enrollment_Status__c == 'Registered - Awaiting Payment'){
				//Assert if the Send_Registered_AP_Notification__c Flag is set true or not.
				System.assert(enrolObj.Send_Registered_AP_Notification__c == True);
			}
			else if(enrolObj.Enrollment_Status__c == 'Awaiting Payment'){
			//Asserting if the Send_Awaiting_Payment_Notification__c Flag is set True or not.
			System.assert(enrolObj.Send_Awaiting_Payment_Notification__c == True);
			}
			else if(enrolObj.Enrollment_Status__c == 'Registered' && enrolObj.Certification_Exam_Agreement__c== 'Awaiting Response'){
				System.assert(enrolObj.Send_Registered_Notification__c== True);
			}
		}
	}
}