objects/Contact.object
<CustomObject>
    <fields>
        <fullName>County_Local__c</fullName>
        <label>County (Local)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MW_Project__c.object
<CustomObject>
    <description>This is the AEG Request and Project Object.</description>
    <fields>
        <fullName>Project_Status__c</fullName>
        <description>The Project Status</description>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>PE: Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requester__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will have to be populated with the Requester Name.</description>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P{000000}</displayFormat>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>AEG approved project</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Team_Member__c.object
<CustomObject>
    <description>This object is for AE / PE Resource Requests and Tracking (User Story: 317488)</description>
    <fields>
        <fullName>Requester__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Copied from the Project record to be used in Project Team Member Workflow Email Alerts</description>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Team Member</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Project Team ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Project_Time_Card__c.object
<CustomObject>
    <fields>
        <fullName>Project_Status__c</fullName>
        <description>Pulls the Project Status value from the related project, used in validation rules and time card entry behavior</description>
        <formula>TEXT(Project__r.Project_Status__c)</formula>
        <label>Project Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Week_Date__c</fullName>
        <description>User Will fill Time card for particular date of the week.</description>
        <label>Week Date</label>
        <type>Date</type>
    </fields>
    <label>Time Card</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Project Time Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Functional_Role__c</fullName>
        <inlineHelpText>Denotes what role a user plays on a Sales Territory Team.  Used for Oppty assignment and to support collaboration among team members.</inlineHelpText>
        <label>Functional Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inside Sales Rep</fullName>
                </value>
                <value>
                    <fullName>Inside Sales Rep non primary</fullName>
                </value>
                <value>
                    <fullName>National Account Sales Specialist</fullName>
                </value>
                <value>
                    <fullName>Product Overlay Sales Rep</fullName>
                </value>
                <value>
                    <fullName>Sales Development Rep</fullName>
                </value>
                <value>
                    <fullName>Sales Maintenance Rep</fullName>
                </value>
                <value>
                    <fullName>Sales Maintenance Rep non primary</fullName>
                </value>
                <value>
                    <fullName>Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Sales Rep</fullName>
                </value>
                <value>
                    <fullName>Sales Rep Primary</fullName>
                </value>
                <value>
                    <fullName>Sales Specialist</fullName>
                </value>
                <value>
                    <fullName>Sales Support Manager</fullName>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                </value>
                <value>
                    <fullName>Application Engineer</fullName>
                </value>
                <value>
                    <fullName>Pilot Engineer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TimecardTriggerHandlerTest.cls
/**
     * Author Original:Sagar Talele
     * Date Original: 29 September 2014
     * Description: This is Test class for TimecardTriggerHandler
     */
@isTest
private class TimecardTriggerHandlerTest {
    //Create new instance of CustomSettingsBuilder
    static CustomSettingsBuilder custsettbuild = new CustomSettingsBuilder();

    public static Account accObj;
    public static Contact conObj;
    /**
     * Author Original:Sagar Talele
     * Date Original: 29 September 2014
     * Description: This is Test Method  for onBeforeDelete
     */
    static testMethod void TestonBeforeDelete() {
        
        custsettbuild.buildBypassTriggerSettings();
        custsettbuild.buildGenSetting();
        custsettbuild.buildAddressLatinTranslation();
        custsettbuild.buildProjectValidationRuleSettings();
        String ApplicationEngineerFRole=System.Label.ProjectTeamMemeberFunctionalRole_ApplicationEngineer;
        
        List<MW_Project__c> projectList=new List<MW_Project__c>();
        List<MW_Project__c> projectListToUpdate=new List<MW_Project__c>();
        List<Project_Team_Member__c> projectTeamList=new List<Project_Team_Member__c>();
        List<Project_Time_Card__c> projectTimeCardList=new List<Project_Time_Card__c>();
        List<Account>accountList=new List<Account>();
        List<Contact>contList=new List<Contact>();
       
        //Create a user for TestDataBuilder
        User usrObj=TestDataBuilder.buildTestUser(2);
        insert usrObj;
        
        User teamMember=TestDataBuilder.buildTestUser(3);
        teamMember.Functional_Role__c=ApplicationEngineerFRole;
        insert teamMember;

        
        //Create A Acocunt records for TestBuilder
        for(Integer i =0; i<10;i++){
            accObj = TestDataBuilder.buildTestAccount(i,UserInfo.getUserId());
            accObj.BillingCountryCode = 'US';
            accObj.BillingCountry = 'United States';
            accObj.BillingStateCode = 'NY';
            accObj.BillingState = 'New York';
            accountList.add(accObj);
        }
        insert accountList;
        System.AssertEquals(accountList.size(),10);
        //Create a contact recoords for TestBuilder
        for(Integer i =0;i<10;i++){

            Contact contNL = TestDataBuilder.buildTestContact(i,UserInfo.getUserId(),accountList[i].id);
            contNL.MailingCity ='Ningbo';
            contNL.MailingCountry = 'China';
            contNL.MailingCountryCode = 'CN';
            contNL.MailingPostalCode ='400012';
            contNL.MailingState = '北京';
            contNL.MailingStateCode ='11';
            contNL.MailingStreet = '宮崎県';
            contNL.County_Local__c = 'xyz';
            contNL.email = 'bob@gmail.com';

            contList.add(contNL);

        }
        insert contList;
        System.AssertEquals(contList.size(),10);
System.runas(teamMember){
        //Create a Project for TestBuilder
        for( Integer i =0;i<10;i++ ){
           // MW_Project__c proObj=TestDataBuilder.buildTestProject(i, Schema.SObjectType.MW_Project__c.getRecordTypeInfosByName().get('Sales Request').getRecordTypeId(), contList[i].Id); 
          // MW_Project__c proObj=TestDataBuilder.buildTestProject(i, Schema.SObjectType.MW_Project__c.getRecordTypeInfosByName().get('Project').getRecordTypeId(), contList[i].Id);  
            MW_Project__c proObj=TestDataBuilder.buildTestProjectNonOppty(i, Schema.SObjectType.MW_Project__c.getRecordTypeInfosByName().get('Project').getRecordTypeId(), contList[i].Id);  
            proObj.requester__C=usrObj.id;
            proObj.Project_Status__c='In Progress';
            projectList.add(proObj);

        }
        Test.startTest();
        insert projectList;
        System.AssertEquals(projectList.size(),10);
        for(Integer i=0;i<10;i++){
            
               for(Integer j=0;j<2;j++){
                    //Create a Timecard for TestBuilder
                    Project_Time_Card__c proTimeCardObj=TestDataBuilder.buildTestProjectTimeCard(teamMember.id,projectList[i].id);
                    proTimecardObj.Week_Date__c = System.today();
                    projectTimeCardList.add(proTimeCardObj);
               }
        }
        
        //insert projectTimecardList
        insert projectTimeCardList;
       
       //update the status of timecard as Closed for test
        for(MW_Project__c proObj : projectList){
            
            proObj.Project_Status__c='Closed';
           
         }
    
       update   projectList;
       System.assertEquals(projectList[0].Project_Status__c,'Closed');    
            try{
            delete projectTimeCardList[0];
            }
            catch(Exception e){
                System.assert(e.getMessage().contains('Delete failed'));
            }
            Test.stopTest();
       }
    }
}