objects/Contact.object
<CustomObject>
    <fields>
        <fullName>County_Local__c</fullName>
        <label>County (Local)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MW_Project__c.object
<CustomObject>
    <description>This is the AEG Request and Project Object.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Used as a place holder so that the project can be created from Account.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used as a place holder so that the project can be created from Opty. Will use this field to set the project Id on the opportunity from which it is created.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>AEG_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <label>Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Purpose__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Conf Call/Email</fullName>
                </value>
                <value>
                    <fullName>Visit Customer</fullName>
                </value>
                <value>
                    <fullName>WebEx</fullName>
                </value>
                <value>
                    <fullName>Guided Evaluation</fullName>
                </value>
                <value>
                    <fullName>Deep Technical Engagement</fullName>
                </value>
                <value>
                    <fullName>Product Customization</fullName>
                </value>
                <value>
                    <fullName>Private Seminar</fullName>
                </value>
                <value>
                    <fullName>Workshop</fullName>
                </value>
                <value>
                    <fullName>Public Seminar</fullName>
                </value>
                <value>
                    <fullName>Customer Visits MW</fullName>
                </value>
                <value>
                    <fullName>Release &amp; Software Update</fullName>
                </value>
                <value>
                    <fullName>CME</fullName>
                </value>
                <value>
                    <fullName>Webinar</fullName>
                </value>
                <value>
                    <fullName>Conference/Trade Show</fullName>
                </value>
                <value>
                    <fullName>Web Event</fullName>
                </value>
                <value>
                    <fullName>Partner/Distributor Support</fullName>
                </value>
                <value>
                    <fullName>Other Physical Events</fullName>
                </value>
                <value>
                    <fullName>Departmental Support</fullName>
                </value>
                <value>
                    <fullName>Administrative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <label>Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Opportunity Support</fullName>
                </value>
                <value>
                    <fullName>Territory Support</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Other Dept Support</fullName>
                </value>
                <value>
                    <fullName>TE University Engagement</fullName>
                </value>
                <value>
                    <fullName>Administrative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requester__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will have to be populated with the Requester Name.</description>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P{000000}</displayFormat>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>AEG approved project</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity_Projects__c.object
<CustomObject>
    <description>This Object is the Junction Object between Opportunity and MW_Projects.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Opportunity_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>MW_Project__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunity_Projects</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Project Relationship</label>
    <nameField>
        <displayFormat>OP-{0000}</displayFormat>
        <label>Opportunity Projects Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Project Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OpportunityProjectDmlTest.cls
/**
*author Original: Sagar Talele - Cloud Sherpas/Mathworks, Modified by : Faina Gorelik
*date Original: 1 April 2015, Last Modified:25 January 2016, 03 March 2017
*description : This  is test class for 'OpportunityProjectTrigger'  , AtTask 1950895   - fix value on created opportunities due to the validation rules
*revision:
*/
@isTest
public class OpportunityProjectDmlTest {
 /**
    *author Original: Sagar Talele - Cloud Sherpas/Mathworks
    *date Original: 1 April 2015, Last Modified:
    *description : This  is test Method  to ensure the first opportunity is assigned to Project
    *revision:
    */
     //Create new instance of CustomSettingsBuilder
    static CustomSettingsBuilder custsettbuild = new CustomSettingsBuilder();
    public static Account accObj;
    public static Contact conObj;
    
    static testMethod void testupdateOpportunityOnProject(){
         custsettbuild.buildBypassTriggerSettings();
         custsettbuild.buildGenSetting();
         custsettbuild.buildAddressLatinTranslation();
         List<Account> accNLLst =new List<Account>();
         List<Contact> contNLLst =new List<Contact>();
         List<Opportunity> oppLst=new List<Opportunity>();
         List<Opportunity_Projects__c> oppProjectLst=new List<Opportunity_Projects__c>();
        for(Integer i=0;i<=50;i++){

            accObj = TestDataBuilder.buildTestAccount(i,UserInfo.getUserId());
            accObj.BillingCountryCode = 'US';
            accObj.BillingCountry = 'United States';
            accObj.BillingStateCode = 'NY';
            accObj.BillingState = 'New York';

            accNLLst.add(accObj);
        }

        insert accNLLst;
        //create Contact record from TestDataBuilder.
        for(Integer i=0;i<=50;i++){

            Contact contNL = TestDataBuilder.buildTestContact(i,UserInfo.getUserId(),accNLLst[i].id);
            
                contNL.MailingCity ='Ningbo';
                contNL.MailingCountry = 'India';
                contNL.MailingCountryCode = 'IN';
                contNL.MailingPostalCode ='400012';
                contNL.MailingState = 'Gujarat';
                contNL.MailingStateCode ='GJ';
                contNL.MailingStreet = 'dgfd';
                contNL.County_Local__c = 'xyz';
                contNL.email = 'bob@gmail.com';

            contNLLst.add(contNL);

        }

        insert contNLLst;
        List<MW_Project__c> recList = new List<MW_Project__c>();

        //Changing the Owner Of opportunity
        User usrObj=TestDataBuilder.buildTestUser(2);
        insert usrObj;

        for(Integer i = 0; i <=50; i++){

            //MW_Project__c rec = TestDataBuilder.buildTestProject(i, Schema.SObjectType.MW_Project__c.getRecordTypeInfosByName().get('Sales Request').getRecordTypeId(), contNLLst[i].Id);//AtTask 1950895
            MW_Project__c rec = TestDataBuilder.buildTestProject(i, Schema.SObjectType.MW_Project__c.getRecordTypeInfosByName().get('Project').getRecordTypeId(), contNLLst[i].Id);
           // rec.account__C = accNLLst[i].id; fg
            rec.Purpose__c='Opportunity Support';//Territory Support'; fg
            rec.outcome__c = 'Workshop';//Internal';fg
            rec.requester__C=usrObj.id;
            recList.add(rec);

        }
         //create Opportunity record from TestDataBuilder.
         for(integer i=0;i<50;i++){
             Opportunity oppObj=TestDataBuilder.buildTestOpportunity(i);
             oppObj.amount=20;
             oppObj.AccountId = accNLLst[i].id;
             oppObj.CurrencyIsoCode='INR';
             oppLst.add(oppObj);
         }
       
         Test.startTest();

        insert recList;
       
        insert oppLst;
        system.assert(recList.size()!=0);
        // create Opportunity Project record
         for(integer i=0;i<50;i++){
             Opportunity_Projects__c  oppProjectObj=TestDataBuilder.buildOpportunityProject(recList[i].Id,oppLst[i].id);
             oppProjectLst.add(oppProjectObj);
         }
        insert oppProjectLst;
        
        MW_Project__c projectObj = [Select Id,Opportunity__c From MW_Project__c where id =: recList[0].Id];
        System.assertEquals(projectObj.Opportunity__c,oppLst[0].Id);
        Test.stopTest();
       
    }
    // fg
     static testMethod void testdeleteOpportunityOnProject(){
         
          custsettbuild.buildBypassTriggerSettings();
         custsettbuild.buildGenSetting();
         custsettbuild.buildAddressLatinTranslation();
         List<Account> accNLLst =new List<Account>();
         List<Contact> contNLLst =new List<Contact>();
         List<Opportunity> oppLst=new List<Opportunity>();
         List<Opportunity_Projects__c> oppProjectLst=new List<Opportunity_Projects__c>();
        for(Integer i=0;i<=50;i++){

            accObj = TestDataBuilder.buildTestAccount(i,UserInfo.getUserId());
            accObj.BillingCountryCode = 'US';
            accObj.BillingCountry = 'United States';
            accObj.BillingStateCode = 'NY';
            accObj.BillingState = 'New York';

            accNLLst.add(accObj);
        }

        insert accNLLst;
        //create Contact record from TestDataBuilder.
        for(Integer i=0;i<=50;i++){

            Contact contNL = TestDataBuilder.buildTestContact(i,UserInfo.getUserId(),accNLLst[i].id);
            
                contNL.MailingCity ='Ningbo';
                contNL.MailingCountry = 'India';
                contNL.MailingCountryCode = 'IN';
                contNL.MailingPostalCode ='400012';
                contNL.MailingState = 'Gujarat';
                contNL.MailingStateCode ='GJ';
                contNL.MailingStreet = 'dgfd';
                contNL.County_Local__c = 'xyz';
                contNL.email = 'bob@gmail.com';

            contNLLst.add(contNL);

        }

        insert contNLLst;
        List<MW_Project__c> recList = new List<MW_Project__c>();

        //Changing the Owner Of opportunity
        User usrObj=TestDataBuilder.buildTestUser(2);
        insert usrObj;

        for(Integer i = 0; i <=50; i++){

           // MW_Project__c rec = TestDataBuilder.buildTestProject(i, Schema.SObjectType.MW_Project__c.getRecordTypeInfosByName().get('Sales Request').getRecordTypeId(), contNLLst[i].Id);//AtTask 1950895
           MW_Project__c rec = TestDataBuilder.buildTestProject(i, Schema.SObjectType.MW_Project__c.getRecordTypeInfosByName().get('Project').getRecordTypeId(), contNLLst[i].Id);
         //   rec.account__C = accNLLst[i].id; //
            //rec.Purpose__c='Territory Support';
            rec.Purpose__c ='Opportunity Support';
           // rec.outcome__c = 'Internal';
           	rec.Outcome__c = 'Workshop';
            rec.requester__C=usrObj.id;
            recList.add(rec);

        }
         //create Opportunity record from TestDataBuilder.
         for(integer i=0;i<50;i++){
             Opportunity oppObj=TestDataBuilder.buildTestOpportunity(i);
             oppObj.AccountId = accNLLst[i].id;
             oppObj.amount=20;
             oppObj.CurrencyIsoCode='INR';
             oppObj.Primary_Contact__c = contNLLst[i].Id;
             oppLst.add(oppObj);
         }
        insert recList;//Project List
        insert oppLst;// Opportunity List
         
       // create junction record to test the scenario where project associated with one opportunity or multiple opportunities

      List<Opportunity_Projects__c> OptyProj = new List<Opportunity_Projects__c>();
        Opportunity_Projects__c OptProj1 = new Opportunity_Projects__c(
        Project__c = recList[0].Id,
        Opportunity__c = oppLst[0].Id);
        OptyProj.add(OptProj1);
         
        Opportunity_Projects__c OptProj2 = new Opportunity_Projects__c(
        Project__c = recList[1].Id,
        Opportunity__c = oppLst[1].Id);
        OptyProj.add(OptProj2);
         
        Opportunity_Projects__c OptProj3 = new Opportunity_Projects__c(
        Project__c = recList[1].Id,
        Opportunity__c = oppLst[2].Id);
        OptyProj.add(OptProj3);
         
        Opportunity_Projects__c OptProj4 = new Opportunity_Projects__c(
        Project__c = recList[1].Id,
        Opportunity__c = oppLst[3].Id);
        OptyProj.add(OptProj4);
         
        insert OptyProj;
       
         
        Test.startTest();
        List<Opportunity_Projects__c> oppProjList = new List<Opportunity_Projects__c>();
        List<Opportunity_Projects__c> oppProjLst = new List<Opportunity_Projects__c>();
        oppProjList = [select id from Opportunity_Projects__c where Project__c = : recList[0].Id and Opportunity__c =: oppLst[0].Id];
        delete oppProjList;
        MW_Project__c mwProj = [select Opportunity__c from MW_Project__c where id = :recList[0].Id];
        //System.assertEquals(null, [select Opportunity__c from MW_Project__c where id = :recList[0].Id].Opportunity__c);
        System.assertEquals(null,mwProj.Opportunity__c);
        oppProjLst = [select id from Opportunity_Projects__c where Project__c = : recList[1].Id and Opportunity__c =: oppLst[1].Id];
        delete oppProjLst;
        MW_Project__c proj = [select Opportunity__c from MW_Project__c where id = :recList[1].Id];
        //System.assertEquals(oppLst[2].Id, [select Opportunity__c from MW_Project__c where id = :recList[1].Id].Opportunity__c);
        System.assertEquals(oppLst[2].Id,proj.Opportunity__c);
        Test.stopTest();
         
     }
   // fg end 
}