objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Pre_Requisite__c</fullName>
        <description>This is used for displaying on web pages. Not to control enrollments for classes. Display only.</description>
        <inlineHelpText>This is used for displaying on TAH web pages.</inlineHelpText>
        <label>Prerequisite</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prerequisite__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Only relevant for Exams and controls enrollment</description>
        <inlineHelpText>Exam that is required to pass before this exam can be attempted</inlineHelpText>
        <label>Prerequisite</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Prerequisites for:</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <description>This is used for displaying on web pages.</description>
        <inlineHelpText>This is used for displaying on web pages.</inlineHelpText>
        <label>Short Description</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <default>true</default>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <recordTypes>
        <fullName>Training</fullName>
        <active>true</active>
        <description>Record type to create non certification course</description>
        <label>Training</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Course_Language__c.object
<CustomObject>
    <fields>
        <fullName>Course_Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Course Languages</relationshipLabel>
        <relationshipName>Course_Languages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Languages</relationshipLabel>
        <relationshipName>Course_Languages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Localized_Pre_Requisite__c</fullName>
        <description>This is used for displaying on web pages.</description>
        <inlineHelpText>This is used for displaying on web pages.</inlineHelpText>
        <label>Localized Prerequisite</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Localized_Short_Description__c</fullName>
        <description>This is used for displaying on web pages.</description>
        <inlineHelpText>This is used for displaying on web pages.</inlineHelpText>
        <label>Localized Short Description</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Course Language</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Course Language Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Language__c.object
<CustomObject>
    <label>Language</label>
    <nameField>
        <label>Language</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CourseTriggerHandlerTest.cls
/**
 *@author Original: Sagar Talele - Cloud Sherpas/Mathworks, Last Modified: Krishna Bhaskarla, Mathworks story Ref No: 1093975
 *@date Original:    3 June 2015, Last Modified:  23 Sep 2015
 *@description:     This is a test class for CoursetriggerHandler 
 */
@isTest
public  with sharing class CourseTriggerHandlerTest{
    
    //re-create custom setting test records when running the test class
    static CustomSettingsBuilder custsettbuild = new CustomSettingsBuilder();
     /*
    @ name    contactRelatedLicenseAndProductTest
    @ date     25 June 2015
    @ author  Sagar Talele
    @ param   none.
    @ return  Void. 
    @ description :Expected that on insertion of course the course language records gets created  
                   and number of records depends on records in language object.
     */              
     private static testMethod void insertCourseLanguageTest(){
         
         //Inserting Bypass trigger custom setting
         custsettbuild.buildBypassTriggerSettings();
         //Create test user
         User usr = TestDataBuilder.buildTestUser(1);
            insert usr;
            List <Language__c> lanList = new List <Language__c> ();
         System.runAs(usr){
             
             for(Integer i=0;i<3;i++){
                 //create Language__c record from CTrainingTestDataBuilder.
                 Language__c langObj = CTrainingTestDataBuilder.buildTestLanguage(i);
                 lanList.add(langObj);
             }
             insert lanList;
             Language__c langInt = [Select Id,Name From Language__c where id =: lanList[0].Id];
             System.assert(langInt != null);
             
             //create Course__c record from CTrainingTestDataBuilder.
             Course__c courseObj = CTrainingTestDataBuilder.buildTestCourse(0);
             insert courseObj;
             Course__c courseInt = [Select Id, Name,Pre_Requisite__c,Short_Description__c,Prerequisite__c From Course__c where id =: courseObj.Id];
             System.assert(courseInt != null);
             
             //test  the businesss logic that 3 records created for course language after insert of course
             List<Course_Language__c> clangList = [Select Id,Course__c,Localized_Pre_Requisite__c,Localized_Short_Description__c From Course_Language__c where Course__c =: courseObj.Id];
             System.assertEquals(clangList.size (), 3);
             //assert to check for fields if they are same
             System.assertEquals(courseInt.Pre_Requisite__c!=null,true);
             System.assertEquals(clangList[0].Localized_Pre_Requisite__c!=null,true);
             System.assertEquals(courseInt.Pre_Requisite__c,clangList[0].Localized_Pre_Requisite__c);
             System.assertEquals(courseInt.Short_Description__c,clangList[0].Localized_Short_Description__c);
         }
     }
     /*
    @ name    contactRelatedLicenseAndProductTest
    @ date     3 June 2015
    @ author  Sagar Talele; last modified: Krishna B
    @ param   none.
    @ return  Void. 
    @ description :Expected that on insertion of course the Training Domain Connection records gets created  
                   and number of records depends on records in Training Domain records which has status equal to active.
        Removing this code. Please ref story(1093975) for details 
     */   
    
   /*  private static testMethod void insertTrainingDomainConTest(){
         //Inserting Bypass trigger custom setting
         custsettbuild.buildBypassTriggerSettings();
         //Create test user
         User usr = TestDataBuilder.buildTestUser(1);
            insert usr;
           List <Training_Domain__c> trainDomList = new List <Training_Domain__c> (); 
         System.runAs(usr){
             for(Integer i=0;i<3;i++){
                 //create Language__c record from CTrainingTestDataBuilder.
                 Training_Domain__c trainDomObj = CTrainingTestDataBuilder.buildTestTrainingDomain(i);
                 trainDomList.add(trainDomObj);
             }
             insert trainDomList;
             Training_Domain__c trainDonInt = [Select Id,Status__c From Training_Domain__c where Id =: trainDomList[0].Id];
             System.assert(trainDonInt != null);
             //create Course__c record from CTrainingTestDataBuilder.
             Course__c courseObj = CTrainingTestDataBuilder.buildTestCourse(0);
             insert courseObj;
             Course__c courseInt = [Select Id, Name From Course__c where id =: courseObj.Id];
             System.assert(courseInt != null);
             
             List<Training_Domain_Connections__c> trainDonConInt = [Select Id,Course__c,Training_Domain__c From Training_Domain_Connections__c where Course__c =: courseObj.Id];
             System.assertEquals(trainDonConInt.size (),trainDomList.size() );
         } 
     } */
}