objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Pre_Requisite__c</fullName>
        <description>This is used for displaying on web pages. Not to control enrollments for classes. Display only.</description>
        <inlineHelpText>This is used for displaying on TAH web pages.</inlineHelpText>
        <label>Prerequisite</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <description>This is used for displaying on web pages.</description>
        <inlineHelpText>This is used for displaying on web pages.</inlineHelpText>
        <label>Short Description</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <default>true</default>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <recordTypes>
        <fullName>Training</fullName>
        <active>true</active>
        <description>Record type to create non certification course</description>
        <label>Training</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Course_Language__c.object
<CustomObject>
    <fields>
        <fullName>Course_Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Course Languages</relationshipLabel>
        <relationshipName>Course_Languages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Languages</relationshipLabel>
        <relationshipName>Course_Languages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Localized_Course_Name__c</fullName>
        <inlineHelpText>Translated version of the English Course Name into the Language this record represents</inlineHelpText>
        <label>Localized Course Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Localized_Pre_Requisite__c</fullName>
        <description>This is used for displaying on web pages.</description>
        <inlineHelpText>This is used for displaying on web pages.</inlineHelpText>
        <label>Localized Prerequisite</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Localized_Short_Description__c</fullName>
        <description>This is used for displaying on web pages.</description>
        <inlineHelpText>This is used for displaying on web pages.</inlineHelpText>
        <label>Localized Short Description</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Course Language</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Course Language Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Language__c.object
<CustomObject>
    <fields>
        <fullName>ISO_Code__c</fullName>
        <label>ISO Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Language</label>
    <nameField>
        <label>Language</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CourseDml.cls
/**
 *@author Original: Sagar Talele - Cloud Sherpas/Mathworks, Last Modified: Sagar Talele - Cloud Sherpas/Mathworks
 *@date Original:   3 June 2015, Last Modified: 3 June 2015
 *@description:     Class to handle delegated DML operations for Course object.
 */
public class CourseDml{
    
    /**
     *@author Original: Sagar Talele - Cloud Sherpas/Mathworks, Last Modified: Sagar Talele - Cloud Sherpas/Mathworks
     *@date Original: 13 May 2015, Last Modified: 13 May 2015
     *@description: Method that handles insert records events for Course_Language__c object.
     */
    public void insertCourseLanguage(List<Course__c > courseList){
        Logger.push('insertCourseLanguage','CourseDml');
         //instantiating the List which contains list of Language__c records
        List<Language__c> langlist = new List<Language__c> ();
        //instantiating the List which contains list of Course_Language__c records
        List<Course_Language__c> clangList = new List<Course_Language__c>();
        //change for Localized_Pre_Requisite__c and Localized_Short_Description__c
        langlist = [Select Id,Name,ISO_Code__c From Language__c];
        for(Course__c cObj : courseList){
            //iterate over the langauge List 
            // addition of Localized_Pre_Requisite__c and Localized_Short_Description__c fields --- Neha Mahajan
            for(Language__c lObj : langlist){
                Course_Language__c cLangObj = new Course_Language__c ();
                cLangObj.Course__c = cObj.Id;
                cLangObj.Localized_Course_Name__c = cObj.Name;
                cLangObj.Course_Language__c = lObj.Id;
                cLangObj.Localized_Pre_Requisite__c=cObj.Pre_Requisite__c;
                cLangObj.Localized_Short_Description__c=cObj.Short_Description__c;
                clangList.add(cLangObj);
            }
    
        }
        try{            
            if(!clangList.isEmpty()){
                //insert list of Course language Object.
                 insert  clangList;
            }
        }
        catch (System.DmlException e) {
            // Capture Dml exception here
            Logger.debugException('DmlException:'+e);
        }
        Logger.pop();
    }
    /**
     *@author Original: Sagar Talele - Cloud Sherpas/Mathworks, Last Modified: Krishna BhaskarlaMathworks
     *@date Original: 25 June 2015, Last Modified: 25 June 2015
     *@description: Method that handles insert records events for Training_Domain_Connections__c object.
                    No longer need this code. Story Ref No: 1093975
     */
    /*public void insertTrainDomainCon(List<Course__c > courseList){
         Logger.push('insertTrainDoaminCon','CourseDml');
         //instantiating the List which contains list of Training_Domain__c records
         List<Training_Domain__c> tDomainlist = new List<Training_Domain__c> ();
         //instantiating the List which contains list of Training_Domain__c records
         List<Training_Domain_Connections__c> tDomainConlist = new List<Training_Domain_Connections__c> ();
         //logic for insertion of Training Domain Connection
        tDomainlist = [Select Id,Status__c From Training_Domain__c where Status__c = 'Active'];
         //iterate over the course List
         for(Course__c cObj : courseList){
             //iterate over the Training Domain List
            for(Training_Domain__c tdomainObj : tDomainlist ){
                Training_Domain_Connections__c trainDConObj = new Training_Domain_Connections__c ();
                trainDConObj.Course__c = cObj.Id;
                trainDConObj.Training_Domain__c = tdomainObj.Id;
                tDomainConlist.add(trainDConObj);
            }
         }
         try{            
             if(!tDomainConlist.isEmpty()){
                 //insert list of Training Domain Connection Object.
                 insert  tDomainConlist;
             }
         }
         catch (System.DmlException e) {
             // Capture Dml exception here
             Logger.debugException('DmlException:'+e);
         }
         Logger.pop();
    } */

}