objects/Email_Template_Selection_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is used to select the correct Customer Training notification email template based on the event</description>
    <fields>
        <fullName>Email_Template_Name__c</fullName>
        <description>This field stores the value of base email template with respect to field name</description>
        <inlineHelpText>The base email template name related to the event. Example API Name &quot;Test_Enrollment_Emails_Self_Paced_ENU_Natick&quot; - only &quot;Test_Enrollment_Emails&quot; would go in this field.  The rest is added dynamically.</inlineHelpText>
        <label>Email Template Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Name__c</fullName>
        <description>this field stores the value of events</description>
        <inlineHelpText>Friendly name of the event the notification will be sent for (ie: Enrollment Confirmation - Registered)</inlineHelpText>
        <label>Event Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldName__c</fullName>
        <description>This field stores the field name for respective Email template</description>
        <inlineHelpText>API Name of the checkbox field on the Enrollment object used to map to the template specified.</inlineHelpText>
        <label>FieldName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Email Template Selection Settings</label>
</CustomObject>

objects/EmailAddressForSponsorOffice__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom Setting stores the Email address for Sponsor Office for those not having Email address</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>stores the email Address for Sponsor office</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>EmailAddressForSponsorOffice</label>
</CustomObject>

objects/Training_Agreement_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings related to Enterprise Training Agreements for Customer Training</description>
    <fields>
        <fullName>Account_Academy_Login_Url_to_MATLAB_Acad__c</fullName>
        <description>stores the Account/Academy Login Url</description>
        <label>Account/Academy Login Url to MATLAB Acad</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Auto_Create_Class_Association__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This check box value decides whether we have to create Training_Agreement_Class_Relationship__c records or not</description>
        <label>Auto Create Class Association</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Character_Set__c</fullName>
        <description>Set of characters to be used (semicolon delimited) to generate the Enrollment Code for Enterprise Training Agreement.</description>
        <inlineHelpText>Set of characters to be used (semicolon delimited) to generate the Enrollment Code for Enterprise Training Agreement.</inlineHelpText>
        <label>Character Set</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Code_Length__c</fullName>
        <description>The desired length of the Enrollment Code. Defaults to 12. Advised to keep this greater than 8 to avoid collisions.</description>
        <inlineHelpText>The desired length of the Enrollment Code. Defaults to 12. Advised to keep this greater than 8 to avoid collisions.</inlineHelpText>
        <label>Code Length</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email_Template_Subject__c</fullName>
        <description>store the email template subject name</description>
        <label>Email Template Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FAQ_Page_Url__c</fullName>
        <label>FAQ Page Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Mw_Local_Training_Url_to_Default_Traini__c</fullName>
        <description>This stores the Mw Local Trainig Url</description>
        <label>Mw Local Training Url to  Default Traini</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>OrgWideEmailAddress__c</fullName>
        <label>OrgWideEmailAddress</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Self_Enrollment_Authenticated_URL__c</fullName>
        <description>Base URL (including param names) of the Authenticated page used to validate Enrollment Codes and present the list of classes for enrollment.</description>
        <inlineHelpText>Base URL (including param names) of the Authenticated page used to validate Enrollment Codes and present the list of classes for enrollment.</inlineHelpText>
        <label>Self Enrollment Authenticated URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Self_Enrollment_Unauthenticated_URL__c</fullName>
        <description>Base URL (including param names) of the Unauthenticated Force.com Site used to validate Enrollment Codes.</description>
        <inlineHelpText>Base URL (including param names) of the Unauthenticated Force.com Site used to validate Enrollment Codes.</inlineHelpText>
        <label>Self Enrollment Unauthenticated URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This value decide the email notification</description>
        <label>Send Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Task_Owner__c</fullName>
        <description>after sending the message task should be created and task owner is the stored value in this field</description>
        <label>Task Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Training_Coordinator_Email_Template_Name__c</fullName>
        <description>Enu TAH Training CoOrdinator Notification Email Template Name</description>
        <label>Training Coordinator Email Template Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Training_Coordinator_Renewal_Temp_Name__c</fullName>
        <description>Training Coordinator Renewal Template Name</description>
        <label>Training Coordinator Renewal Temp Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TrainopsEmails__c</fullName>
        <description>This email is used in sending an email to Training Coordinator to keep this email id as cc address</description>
        <label>TrainopsEmails</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VF_Email_Template_Name__c</fullName>
        <description>This Visual Force Email Template name is used to set template Id for automatically email triggered upon Enrollment Confirmation</description>
        <label>VF Email Template Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Training Agreement Settings</label>
</CustomObject>

classes/CTrainingCustomSettingBuilder.cls
/**
 * @author Original: Sagar Talele - Cloud Sherpas/Mathworks, Last Modified: Sagar Talele - Cloud Sherpas/Mathworks
 * @date Original: 18 Aug 2015, Last Modified: 18 Aug 2015
 * @description Global utility class that contains different record builders for unit testing.
 */
public  class CTrainingCustomSettingBuilder {  

    /**
    * @author Original: Sagar Talele - Cloud Sherpas/Mathworks, Last Modified by:Sagar Talele
    * @date Original: 17 Aug 2015, Last Modified:  17 Aug 2015
    * @description Helper method to re-create Email_Template_Selection_Settings__c.
    */
     public static void buildEmailTemplateSelectionSettings(){
         Email_Template_Selection_Settings__c emailTempObj = new Email_Template_Selection_Settings__c();
         emailTempObj.Name = 'TestEmailFunctionality';
         emailTempObj.Event_Name__c = 'TestEmailFunctionality';
         emailTempObj.Email_Template_Name__c = 'TestEmailFunctionality_Test';
         emailTempObj.FieldName__c = 'Test_Flags_1__c';
         insert emailTempObj;
     }
      /**
    * @author Original: Sagar Talele - Cloud Sherpas/Mathworks, Last Modified by:Sagar Talele
    * @date Original: 17 Aug 2015, Last Modified:  17 Aug 2015
    * @description Helper method to re-create Email_Template_Selection_Settings__c.
    */
    public static void buildEmailAddressForSponsorOfficeSettings(){
        EmailAddressForSponsorOffice__c emailAddressObj = new EmailAddressForSponsorOffice__c();
        emailAddressObj.Email__c = 'support@mathworks.com';
        emailAddressObj.name = 'test';
        insert emailAddressObj;
    }
    
    
    /**
    * @author Original: Abhay Verma - Accenture/Mathworks, Last Modified by:
    * @date Original: 5 April 2016, Last Modified:  
    * @description Helper method to re-create Training_Agreement_Settings__c .
    */
    
    public void buildEnrollmentCodeConfiguration(){
        Training_Agreement_Settings__c enrolCodeConfig = new Training_Agreement_Settings__c();
        enrolCodeConfig.SetupOwnerId = UserInfo.getOrganizationId();
        enrolCodeConfig.Character_Set__c = '0;1;2;3;4;5;6;7;8;9;A;B;C;D;E;F;G;H;I;J;K;L;M;N;O;P;Q;R;S;T;U;V;W;X;Y;Z';
        enrolCodeConfig.Code_Length__c = 12;
        enrolCodeConfig.Self_Enrollment_Authenticated_URL__c = 'https://traindev-mathworksservicerequest.cs15.force.com/enroll?code=';
        enrolCodeConfig.Self_Enrollment_Unauthenticated_URL__c = 'https://traindev-mathworksservicerequest.cs15.force.com/enroll?code=';       
        enrolCodeConfig.Account_Academy_Login_Url_to_MATLAB_Acad__c ='https://testAccountAcademy@loginUrltest.com';
        enrolCodeConfig.Send_Email__c = true;
        enrolCodeConfig.Mw_Local_Training_Url_to_Default_Traini__c = 'https://localTraining@urltest.com';
        enrolCodeConfig.VF_Email_Template_Name__c = 'Mathworks_Training_Enroll_Confirmation';
        enrolCodeConfig.Task_Owner__c = 'mwsadmin';
        enrolCodeConfig.Email_Template_Subject__c = 'MathWorks Online Training Enrollment Confirmation';
        enrolCodeConfig.OrgWideEmailAddress__c = 'abc@test.com';
        enrolCodeConfig.Training_Coordinator_Email_Template_Name__c = 'TAH_Training_Coordinator_Notification';
        enrolCodeConfig.TrainopsEmails__c = 'testTrainingOps@nmkTest.com';
        enrolCodeConfig.Training_Coordinator_Renewal_Temp_Name__c = 'TAH_TC_Renewal_Notification';
        enrolCodeConfig.FAQ_Page_Url__c = 'faqPageUrl@testLink.com';
        insert enrolCodeConfig;
    }
    /***************************************************************************************
     * @author Original: Sagar Talele Accenture/Mathworks, Last Modified by:
     * @date Original: 12 March 2016, Last Modified: 12 March 2016
     * @description : Helper method to re-create Training_Agreement_Settings__c.
     ****************************************************************************************/
    public void buildTrainingAgreementSettings(){
        Training_Agreement_Settings__c  trainigSettings = new Training_Agreement_Settings__c ();
        trainigSettings.Auto_Create_Class_Association__c = false;
        insert trainigSettings;
        
    } 
}