objects/Enrollment_Code__c.object
<CustomObject>
    <description>This object represents the code associated with an Enterprise Training Agreement and holds the status the enrollment code is in.</description>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <description>Enterprise Training Agreement the Enrollment Code is associated with.</description>
        <inlineHelpText>Enterprise Training Agreement the Enrollment Code is associated with.</inlineHelpText>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Enrollment Codes</relationshipLabel>
        <relationshipName>Enrollment_Codes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Code</label>
    <nameField>
        <displayFormat>EC-{0000}</displayFormat>
        <label>Enrollment Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Enterprise_Training_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Enterprise Training Agreements</relationshipLabel>
        <relationshipName>Enterprise_Training_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <description>Check if the Agreement is Active or not. It is based on start date and end date.</description>
        <formula>(TODAY() &gt;=  Term_Start_Date__c ) &amp;&amp; ( TODAY() &lt;=  Term_End_Date__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Self_Enrollment_Content__c</fullName>
        <description>The Self-Enrollment Content to show up on the Self Enrollment page (during enrollment code precheck) on the unauthenticated Force.com site.</description>
        <inlineHelpText>The Self-Enrollment Content to show up on the Self Enrollment page (during enrollment code precheck) on the unauthenticated Force.com site.</inlineHelpText>
        <label>Self-Enrollment Content</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Term_End_Date__c</fullName>
        <description>Agreement expiration date</description>
        <label>Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Term_Start_Date__c</fullName>
        <description>The date the agreement becomes effective</description>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <label>Enterprise Training Agreement</label>
    <nameField>
        <label>Enterprise Training Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enterprise Training Agreements</pluralLabel>
    <recordTypes>
        <fullName>Unlimited</fullName>
        <active>true</active>
        <description>Unlimited Seats</description>
        <label>Unlimited</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SelfEnrollmentControllerTest.cls
/***************************************************************************************
 * author Original: Sagar Talele - Cloud Sherpas/Mathworks, Last Modified:Sagar Talele
 * date Original: 28 March 2016, Last Modified: 28 March 2016
 * description : This is a test class for EnrollmentTriggerHandler
 ****************************************************************************************/
@isTest
public class SelfEnrollmentControllerTest{
    
    //re-create custom setting test records when running the test class
    static CustomSettingsBuilder custsettbuild = new CustomSettingsBuilder();
    static CTrainingCustomSettingBuilder cTcustsettbuild = new CTrainingCustomSettingBuilder();
    /***************************************************************************************
     * author Original: Sagar Talele - Cloud Sherpas/Mathworks, Last Modified:Sagar Talele
     * date Original: 28 March 2016, Last Modified: 28 March 2016
     * description : This is a test Method for SelfEnrollmentController 
     ****************************************************************************************/
     private static testMethod void validateEnrollmentCodeTest(){
         
        //Inserting Bypass trigger custom setting
        custsettbuild.buildBypassTriggerSettings();
        cTcustsettbuild.buildEnrollmentCodeConfiguration();
        Id etAgrrementRecTypeId = [Select ID, Name From RecordType Where sObjectType = 'Enterprise_Training_Agreement__c' AND RecordType.Name = 'Unlimited' limit 1].Id;
        //intialize class list to create multiple records for Enterprise Training Agreement.
        List<Enterprise_Training_Agreement__c> ETAgreementList = new List<Enterprise_Training_Agreement__c>();
        for(Integer i=0;i<3;i++){
            Enterprise_Training_Agreement__c ETAgreementObj = CTrainingTestDataBuilder.buildTestETAgreement(1);
            ETAgreementObj.RecordTypeId = etAgrrementRecTypeId ;
            ETAgreementObj.Self_Enrollment_Content__c = 'testRichText';
            ETAgreementList.add(ETAgreementObj);
        }
        insert ETAgreementList ;
        System.assertEquals(ETAgreementList.size(),3);
        Enterprise_Training_Agreement__c  etaObj = [Select Id,Is_Active__c,Account_Name__c From Enterprise_Training_Agreement__c  where Id =:ETAgreementList[0].Id ];
        system.assertEquals(etaObj.Is_Active__c ,true);
        //intialize class list to create multiple records for Enrollment_Code__c 
        List<Enrollment_Code__c> enrollCodeList = new List<Enrollment_Code__c>();
        for(Integer i=0;i<3;i++){
            Enrollment_Code__c enrollObj= CTrainingTestDataBuilder.buildTestEnrollmentCode(etaObj.Id);
            enrollCodeList.add(enrollObj);
        }
        insert enrollCodeList;
        Enrollment_Code__c enrollCode = [Select id,Code__c,Status__c, Enterprise_Training_Agreement__c, Enterprise_Training_Agreement__r.Is_Active__c From Enrollment_Code__c Where Id =:enrollCodeList[0].Id];
        system.assertEquals(enrollCode.Code__c != null,true);
        
        PageReference pageRef = Page.SelfEnrollment;
        Test.setCurrentPage(pageRef);
        SelfEnrollmentController SelfEnrollmentController = new SelfEnrollmentController();
        SelfEnrollmentController.enrollmentCode = enrollCode.Code__c;
        SelfEnrollmentController.navigateToAuthUrl();
        SelfEnrollmentController.checkEnrollmentCode();
        SelfEnrollmentController.navigateToAuthUrl();
        // Add parameters to page URL
        ApexPages.currentPage().getParameters().put(TrainingUtil.ECODE_URL_PARAM_KEY, enrollCode.Code__c);
        ApexPages.currentPage().getParameters().put('language', '');
        SelfEnrollmentController.validateEnrollmentCode(enrollCode);
        system.assertEquals(SelfEnrollmentController.isValidEnrollmentCode,true);
        //system.assertEquals(SelfEnrollmentController.isError,false);
        
     }
     /***************************************************************************************
     * author Original: Sagar Talele - Cloud Sherpas/Mathworks, Last Modified:Sagar Talele
     * date Original: 28 March 2016, Last Modified: 28 March 2016
     * description : This is a test Method for SelfEnrollmentController 
     ****************************************************************************************/
     private static testMethod void validateEnrollmentCodeNegativeTest(){
        //Senario 2 where Code__c  is null and Enterprise_Training_Agreement__c   isActive is false
         //intialize class list to create multiple records for Enterprise Training Agreement.
         //Inserting Bypass trigger custom setting
        custsettbuild.buildBypassTriggerSettings();
        cTcustsettbuild.buildEnrollmentCodeConfiguration();
        Id etAgrrementRecTypeId = [Select ID, Name From RecordType Where sObjectType = 'Enterprise_Training_Agreement__c' AND RecordType.Name = 'Unlimited' limit 1].Id;
        
        List<Enterprise_Training_Agreement__c> ETAgtList = new List<Enterprise_Training_Agreement__c>();
        for(Integer i=0;i<3;i++){
            Enterprise_Training_Agreement__c ETAgreementObj = CTrainingTestDataBuilder.buildTestETAgreement(1);
            ETAgreementObj.RecordTypeId = etAgrrementRecTypeId ;
            ETAgreementObj.Self_Enrollment_Content__c = null;
            ETAgreementObj.Term_Start_Date__c = System.Today().addDays(-2);
            ETAgreementObj.Term_End_Date__c = System.Today().addDays(-1);
            ETAgtList.add(ETAgreementObj);
        }
        insert ETAgtList ;
        System.assertEquals(ETAgtList.size(),3);
        Enterprise_Training_Agreement__c  etaObj1 = [Select Id,Is_Active__c,Account_Name__c From Enterprise_Training_Agreement__c  where Id =:ETAgtList[0].Id ];
        system.assertEquals(etaObj1.Is_Active__c ,false);
        //intialize class list to create multiple records for Enrollment_Code__c 
        List<Enrollment_Code__c> enrollCodeLst = new List<Enrollment_Code__c>();
        for(Integer i=0;i<3;i++){
            Enrollment_Code__c enrollObj= CTrainingTestDataBuilder.buildTestEnrollmentCode(etaObj1.Id);
            enrollCodeLst.add(enrollObj);
        }
        insert enrollCodeLst;
        Enrollment_Code__c enrollCodeObj = [Select id,Code__c From Enrollment_Code__c Where Id =:enrollCodeLst[0].Id];
        enrollCodeObj.Code__c =null;
        update enrollCodeObj;
        system.assertEquals(enrollCodeObj.Code__c == null,true);
        
        PageReference pageRef1 = Page.SelfEnrollment;
        Test.setCurrentPage(pageRef1);
        // Add parameters to page URL
       // ApexPages.currentPage().getParameters().put('code', '888888888888');
        ApexPages.currentPage().getParameters().put('code', '888888888888');
        ApexPages.currentPage().getParameters().put(TrainingUtil.ECODE_URL_PARAM_KEY, enrollCodeObj.Code__c);
        SelfEnrollmentController controller = new SelfEnrollmentController();
        controller.navigateToAuthUrl();
        system.assertEquals(controller.isValidEnrollmentCode,false);
    }
}