objects/Enrollment_Code__c.object
<CustomObject>
    <description>This object represents the code associated with an Enterprise Training Agreement and holds the status the enrollment code is in.</description>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Enrollment Code</label>
    <nameField>
        <displayFormat>EC-{0000}</displayFormat>
        <label>Enrollment Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EnrollmentCodeTriggerHandler.cls
/**
 * @author      Pranav Raulkar
 * @date        29/03/2016
 * @description   Trigger handler for EnrollmentCodeTrigger
 *           The trigger handler handles following events -
 *          1.  Before Insert
 * @revision    1.0 - Initial version
 */
public with sharing class EnrollmentCodeTriggerHandler {
  public void onBeforeInsert(List<Enrollment_Code__c> enrollmentCodeList) {
    if(Trigger.isExecuting) {
      if(enrollmentCodeList != null && enrollmentCodeList.size() > 0) {
        for(Enrollment_Code__c eCode : enrollmentCodeList) {
          eCode.Code__c = TrainingUtil.generateEnrollmentCode();
        }
      }
    }
  }
}