objects/Enrollment_Code__c.object
<CustomObject>
    <description>This object represents the code associated with an Enterprise Training Agreement and holds the status the enrollment code is in.</description>
    <fields>
        <fullName>Enterprise_Training_Agreement__c</fullName>
        <description>Enterprise Training Agreement the Enrollment Code is associated with.</description>
        <inlineHelpText>Enterprise Training Agreement the Enrollment Code is associated with.</inlineHelpText>
        <label>Enterprise Training Agreement</label>
        <referenceTo>Enterprise_Training_Agreement__c</referenceTo>
        <relationshipLabel>Enrollment Codes</relationshipLabel>
        <relationshipName>Enrollment_Codes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment Code</label>
    <nameField>
        <displayFormat>EC-{0000}</displayFormat>
        <label>Enrollment Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Enterprise_Training_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Language to display content in on self-enrollment portal</inlineHelpText>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Enterprise Training Agreements</relationshipLabel>
        <relationshipName>Enterprise_Training_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enterprise Training Agreement</label>
    <nameField>
        <label>Enterprise Training Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enterprise Training Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Language__c.object
<CustomObject>
    <label>Language</label>
    <nameField>
        <label>Language</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Training_Agreement_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings related to Enterprise Training Agreements for Customer Training</description>
    <fields>
        <fullName>Self_Enrollment_Authenticated_URL__c</fullName>
        <description>Base URL (including param names) of the Authenticated page used to validate Enrollment Codes and present the list of classes for enrollment.</description>
        <inlineHelpText>Base URL (including param names) of the Authenticated page used to validate Enrollment Codes and present the list of classes for enrollment.</inlineHelpText>
        <label>Self Enrollment Authenticated URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Training Agreement Settings</label>
</CustomObject>

classes/SelfEnrollmentController.cls
/**
 * @author          Pranav Raulkar
 * @date            26/03/2016
 * @description     This class houses utility methods for the Mathworks TAH module.
 *                  A valid enrollment code is one where - 
 *                  a.  Of same length as specified in enrollment code configuration setting
 *                  b.  Status__c = Active
 *                  c.  Associated with an ETA which is Active
 * @revision        1.0 - Initial version
 */
public without sharing class SelfEnrollmentController {
    /* Public variables section */
    public Enrollment_Code__c eCode                 { get; set; }

    public String letsGetStartedLink                { get; set; }
    public String language                          { get; set; }
    public String enrollmentCode                    { get; set; }

    public Boolean isNonExistentEnrollmentCode      { get; set; }
    public Boolean isInactiveEtaCode                { get; set; }
    public Boolean isEnrollmentCodeRevoked          { get; set; }
    public Boolean isValidEnrollmentCode            { get; set; }

    /*
        @author         Pranav Raulkar
        @date           26/03/2016
        @description    Constructor method. Initializes all the variables on page load and performs
                        a onload enrollment code validation if an enrollment code is embedded in the
                        page URL.
    */
    public SelfEnrollmentController() {
        initializeVars();
        readURLParams();
        fetchEnrollmentCodeRecord();
        setPageLanguage();
        validateEnrollmentCode(eCode);
    }

    /*
        @author         Pranav Raulkar
        @date           13/04/2016
        @description    Method to initialize the class variables
    */
    private void initializeVars() {
        Logger.push('SelfEnrollmentController', 'initializeVars');
        
        isNonExistentEnrollmentCode = false;
        isInactiveEtaCode = false;
        isEnrollmentCodeRevoked = false;
        isValidEnrollmentCode = false;
        
        Logger.pop();
    }

    /*
        @author         Pranav Raulkar
        @date           13/04/2016
        @description    Method to initialize the class variables
    */
    private void readURLParams() {
        Logger.push('SelfEnrollmentController', 'readURLParams');

        // Get the code from URL
        enrollmentCode = ApexPages.currentPage().getParameters().get(TrainingUtil.ECODE_URL_PARAM_KEY);

        // Get the language from URL
        language = ApexPages.currentPage().getParameters().get(TrainingUtil.LANGUAGE_URL_PARAM_KEY);

        Logger.pop();
    }

    /*
        @author         Pranav Raulkar
        @date           13/04/2016
        @description    Method to initialize the class variables
    */
    private void fetchEnrollmentCodeRecord() {
        Logger.push('SelfEnrollmentController', 'fetchEnrollmentCodeRecord');

        // Get the enrollment code from database
        eCode = TrainingUtil.getEnrollmentCode(enrollmentCode); 

        Logger.pop();
    }

    /*
        @author         Pranav Raulkar
        @date           13/04/2016
        @description    Deduce the language code that needs to be used for the page
    */
    private void setPageLanguage() {
        Logger.push('SelfEnrollmentController', 'setPageLanguage');

        if(String.isEmpty(language) && eCode != null) {
            // If the language from URL is empty and we have a enrollment code, get ETA language
            language = eCode.Enterprise_Training_Agreement__r.Language__r.SF_ISO_Code__c;

            if(String.isEmpty(language)) {
                // If there is no language code from URL or ETA, set default to English
                language = TrainingUtil.DEFAULT_LANGUAGE_CODE;
            }
        } else if(!String.isEmpty(language) && !TrainingUtil.doesLanguageExist(language)) {
            // If there is no language code from URL or ETA, set default to English
            language = TrainingUtil.DEFAULT_LANGUAGE_CODE;
        }

        Logger.pop();
    }

    /*
        @author         Pranav Raulkar
        @date           26/03/2016
        @description    The method performs the enrollment code validation as per following -
                        1.  Check if enrollment code exists.
                        2.  Check if the enrollment code is valid (code active)
                        3.  Check if enrollment code's ETA is active
                        4.  Check if enrollment code is revoked
    */
    public void validateEnrollmentCode(Enrollment_Code__c eCode) {
        Logger.push('SelfEnrollmentController', 'validateEnrollmentCode');

        TrainingUtil.ValidationStatus status = TrainingUtil.validateEnrollmentCode(eCode);
        
        if(status == TrainingUtil.ValidationStatus.NON_EXISTENT) {
            isNonExistentEnrollmentCode = true;
        } else if(status == TrainingUtil.ValidationStatus.VALID) {
            isValidEnrollmentCode = true;
        } else if(status == TrainingUtil.ValidationStatus.INACTIVE_ETA_CODE) {
            isInactiveEtaCode = true;
        } else if (status == TrainingUtil.ValidationStatus.REVOKED) {
            isEnrollmentCodeRevoked = true;
        }

        Logger.pop();
    }

    /*
        @author         Pranav Raulkar
        @date           26/03/2016
        @description    The method initializes the class variables and performs the enrollment code validation.
    */
    public PageReference checkEnrollmentCode() {
        Logger.push('SelfEnrollmentController', 'checkEnrollmentCode');

        initializeVars();
        fetchEnrollmentCodeRecord();
        setPageLanguage();
        validateEnrollmentCode(eCode);

        Logger.pop();

        return null;
    }

    /*
        @author         Pranav Raulkar
        @date           29/03/2016
        @description    Checks if the enrollment code is valid and prepares the link to 
                        naviagte to when the "Let's get started" button is clicked.
    */
    public PageReference navigateToAuthUrl() {
        PageReference letsGetStarted;
        if(isValidEnrollmentCode) {
            Training_Agreement_Settings__c ENROLL_CODE_CONFIG = Training_Agreement_Settings__c.getOrgDefaults();
            letsGetStarted = new PageReference(String.format(ENROLL_CODE_CONFIG.Self_Enrollment_Authenticated_URL__c, new List<String> { enrollmentCode }));
            letsGetStarted.setRedirect(true);            
        }
        return letsGetStarted;
    }   
}