objects/Enterprise_Training_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Classes__c</fullName>
        <description>Count of classes associated with the ETA</description>
        <inlineHelpText>Number of classes associated with ETA</inlineHelpText>
        <label>Classes</label>
        <summaryForeignKey>Training_Agreement_Class_Relationship__c.Enterprise_Training_Agreement__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>License_ID__c</fullName>
        <description>Used by Eloqua marketing program to identify LEUs</description>
        <inlineHelpText>License ID corresponding to the TAH/Unlimited license agreement to use for identifying Licensed End Users to notify of access to training under this agreement when the &quot;Enable LEU Campaigns&quot; box is checked</inlineHelpText>
        <label>License ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Submit_Batch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Trigger manually ETA records to Course Management System</description>
        <inlineHelpText>For system admin only to trigger manually ETAs records to Course Management System</inlineHelpText>
        <label>Submit Batch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Term_End_Date__c</fullName>
        <description>Agreement expiration date</description>
        <label>Term End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Term_Start_Date__c</fullName>
        <description>The date the agreement becomes effective</description>
        <label>Term Start Date</label>
        <type>Date</type>
    </fields>
    <label>Enterprise Training Agreement</label>
    <nameField>
        <label>Enterprise Training Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enterprise Training Agreements</pluralLabel>
    <recordTypes>
        <fullName>Unlimited</fullName>
        <active>true</active>
        <description>Unlimited Seats</description>
        <label>Unlimited</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ETrainingAgreementTriggerHandler.cls
/**
 *@author Original: Sagar Talele - Cloud Sherpas/Mathworks, Last Modified: Sagar Talele - Cloud Sherpas/Mathworks, Faina Gorelik MathWorks AtTask 2238455 /
 *@date Original:   29 July 2015, Last Modified: 29 July 2015, August 2017
 *@description:     This is a handler class for Enterprise Training Agreement 
 */
public class ETrainingAgreementTriggerHandler{
    
    /**
     *@author Original: Sagar Talele - Cloud Sherpas/Mathworks, Last Modified: Sagar Talele - Cloud Sherpas/Mathworks
     *@date Original: 29 July 2015, Last Modified: 29 July 2015
     *@description: Method that handles After insert trigger event on the Enterprise_Training_Agreement__cobject.
     */
    public void onAfterInsert(List<Enterprise_Training_Agreement__c>ETAgreementLst){
        
        Logger.push('onAfterInsert','ETrainingAgreementTriggerHandler');
        ETAgreementDml ETAgreemetDmlObj = new ETAgreementDml ();
        //instantiating the Set of course id 
        Set<Id> ETAgreementId= new Set<Id>();
        //instantiating the List which contains list of course records
        List<Enterprise_Training_Agreement__c> ETAgreementList = new List<Enterprise_Training_Agreement__c>();
        
        //TODO: Do we need a SOQL for this? Can't we use schema methods for this?
        Map<ID,RecordType> rt_Map = New Map<ID,RecordType>([Select ID, Name From RecordType Where sObjectType = 'Enterprise_Training_Agreement__c']);
        
        //iterate over the  Enterprise Training Agreement List 
        for(Enterprise_Training_Agreement__c EtAgreementObj : ETAgreementLst){
           
              if(rt_map.get(EtAgreementObj.recordTypeID).name.containsIgnoreCase('Unlimited')){
                  ETAgreementId.add(EtAgreementObj.Id);
              }
           // we might need to create a different list to pass to MAOTS to combine with seat based ETAs
       }
       
        //check set is not empty
       if(!ETAgreementId.isEmpty()){
             //query the Enterprise Training Agreement records which involved in trigger event 
            ETAgreementList = [Select Id,Name From Enterprise_Training_Agreement__c Where Id In :ETAgreementId];
        }
        
        //check list is not empty
        if(!ETAgreementList.isEmpty()){
            //send Enterprise Training Agreement list  to EEnterprise Training Agreement  Dml Class       
            ETAgreemetDmlObj.insertTAgreementClassRelationship(ETAgreementList);
      
        }
        
        Logger.pop();
    
    }
    
    public void onAfterUpdate(map<Id, Enterprise_Training_Agreement__c> oldmap, map<Id, Enterprise_Training_Agreement__c> newmap){
 
    /**
     *@author Original: Faina Gorelik - Mathworks
     *@date Original: 16 September 2017, Last Modified: 
     *@description: Method that handles After update  trigger event on the Enterprise_Training_Agreement__cobject.
     */
        Set <Id> Set_ETAId = new Set<id>(); // pass to future call to send to Training Authorization;
        for (Enterprise_Training_Agreement__c eta : newmap.values()){
            // filter only ETAs with the updated fields we pass to Training Authorization or if we need to trigger the existing record by setting Submit Batch flag to true
            if((oldmap.get(eta.id).Submit_Batch__c != eta.Submit_Batch__c && eta.Submit_Batch__c==true ) || (oldmap.get(eta.id).Classes__c  != eta.Classes__c) || (oldmap.get(eta.id).License_ID__c != eta.License_ID__c) || (oldmap.get(eta.id).Term_End_Date__c  != eta.Term_End_Date__c) ||(oldmap.get(eta.id).Term_Start_Date__c  != eta.Term_Start_Date__c)  ){
                Set_ETAId.add(eta.Id);                
            }
        }
        
        if (Set_ETAId.size()>0){
                TrainingAgreementClassDML.callMAOTS(Set_ETAId);
        }
    }
    

}