objects/Integration_Settings__c.object
<CustomObject>
    <description>Custom Object used on Integrations for retrieving default connection data</description>
    <fields>
        <fullName>CA_Cert__c</fullName>
        <description>CA Signed certificate used in Integration&apos;s connecting to MW like OnSupport, Articles service</description>
        <label>CA Cert</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caller_ID__c</fullName>
        <description>This contains the Math Works Caller Id Value</description>
        <label>Caller ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Clientname__c</fullName>
        <label>Clientname</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Endpoint__c</fullName>
        <label>Endpoint Base URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Locale__c</fullName>
        <description>This field contains the value of Locale</description>
        <label>Locale</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Retry_Attempts__c</fullName>
        <description>This specifies the number of Attempts for retry for service</description>
        <label>Retry Attempts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Timeout__c</fullName>
        <label>Timeout</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Integration Setting</label>
    <nameField>
        <label>Integration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LicenseIntegrationSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains integration setting related to the  license</description>
    <fields>
        <fullName>LicenseMWUrl__c</fullName>
        <description>Contains License Base Url for Mathworks</description>
        <label>LicenseMWUrl</label>
        <type>Url</type>
    </fields>
    <label>License Integration Setting</label>
</CustomObject>

classes/LicenseLookupControllerTest.cls
/**
 *@author Original: Sagar Talele - Cloud Sherpas/Mathworks, Last Modified: Sagar Talele - Cloud Sherpas/Mathworks
 *@date Original:   23 Feb 2015, Last Modified: 23 Feb 2015,
 *@description:     This is a test class for LicenseLookupController class
 */
@isTest
public with sharing class LicenseLookupControllerTest {

    //re-create custom setting test records when running the test class
    static CustomSettingsBuilder custsettbuild = new CustomSettingsBuilder();
     @testSetup static void setup() {

        //build integration settings
        String token;
        Integration_Settings__c intSett = new Integration_Settings__c();
        intSett.Name = 'MW Integrations';
        intSett.Username__c = 'Salesforce';
        intSett.Password__c = 'TestPassword123'; //do not use real passwords
        intSett.Clientname__c = 'Salesforce';
        intSett.Timeout__c = 60000;
        intSett.Endpoint__c = 'https://sf-ext-dev3.mathworks.com/';
        intSett.Locale__c = 'en_US';
        intSett.Retry_Attempts__c =3;
        intSett.Caller_ID__c ='SFDC';
        intSett.CA_Cert__c= 'SF_UAT2';
        insert intSett;


  }
    /*
    @ name    LicenseLookup
    @ date   23 Feb 2015,
    @ author  Sagar Talele
    @ param   none.
    @ return  Void. 
    @ description :Expected that it  will show  Liceneses and  related information.
     */
    private static testMethod void viewLicenseLookupTest() {
    
        custsettbuild.buildLicensesIntegrationSetting();
        LicenseIntegrationSetting__c getSetLicense = LicenseIntegrationSetting__c.getInstance();
       
        List<Contact> conLst =new List<Contact>();
        List<Account> accLst =new List<Account>();
    
        User usr = TestDataBuilder.buildTestUser(1);
        insert usr;
		 
       
        custsettbuild.buildIntegrationSetting();
        //re-create address latin conversion Custom Setting
        custsettbuild.buildAddressLatinTranslation();
        //Inserting Bypass trigger custom setting
       // custsettbuild.buildBypassTriggerSettings();

        System.runAs(usr){
            //set current page 
            PageReference licensePage= Page.LicenseLookupPage;
            Test.setCurrentPage(licensePage);
            
            Contact contL = new Contact();

            ApexPages.StandardController standardCtrlCon = new ApexPages.StandardController(contL);
            LicenseLookupController controller = new LicenseLookupController(standardCtrlCon);
			controller.licenseID = '149544';
            // Use MultiStaticResourceCalloutMock to
            // specify fake response for a certain endpoint and 
            // include response body in a static resource.    
            
            
            MultiStaticResourceCalloutMock multimockgetLicense= new MultiStaticResourceCalloutMock();
            multimockgetLicense.setStaticResource('https://sf-ext-dev3.mathworks.com/businessprocesstokenws/services/BusinessProcessTokenService','mockBusinessProcessTokenServiceResponse');
	        multimockgetLicense.setStaticResource(getSetLicense.LicenseMWUrl__c+'/'+controller.licenseID, 'MockResponseLicenseLookup');
            multimockgetLicense.setStatusCode(200);
            multimockgetLicense.setHeader('Content-Type', 'application/json');  
             
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, multimockgetLicense);
            controller.viewLicenses();
            controller.hideLicenseDetailSection();
            Test.stopTest();

        }    
    }
}