objects/Log__c.object
<CustomObject>
    <description>This is the log entity that stores information about system errors that may be encountered while the system is running.</description>
    <fields>
        <fullName>ExceptionType__c</fullName>
        <description>This is the exception code from the thrown excpetion</description>
        <label>ExceptionType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>This is the developer provided string in the debug or exception entry</description>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{000000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <recordTypes>
        <fullName>Debug</fullName>
        <active>true</active>
        <label>Debug</label>
    </recordTypes>
    <recordTypes>
        <fullName>Exception</fullName>
        <active>true</active>
        <label>Exception</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LogConfig__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings to manage the custom logging using Logger framework</description>
    <fields>
        <fullName>Debug_Record_Type__c</fullName>
        <description>This is the name of the record type which is used to present debug information on the log object.</description>
        <label>Debug Record Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Record_Type__c</fullName>
        <description>This is the name of the record type which is used to present exception information on the log object</description>
        <label>Exception Record Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exceptions_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is a flag to denote if exceptions should be logged to the database</description>
        <label>Exceptions Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Logging_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is a flag to denote if debuf information should be logged to the database</description>
        <label>Logging Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>LogConfig</label>
</CustomObject>

classes/LoggerTest.cls
/*******************************************************************************
* @author         Andre Calimlim
* @date           5.19.2014
* @return         
* @description    Test class for testing the class named 
*                 Logger
*******************************************************************************/
@isTest
public class LoggerTest {

/*******************************************************************************
* @author         Andre Calimlim
* @date           5.19.2014
* @return         
* @description    This test methods creates log exceptions intentionally to check
                  the logger methods of Logger class
* @Revision(s) 
*******************************************************************************/

    static testMethod void testLogger() {
        
        User usr = TestDataBuilder.buildTestUser(1); 
        insert usr;
        System.runAs(usr){
            
           	insert new LogConfig__c(Debug_Record_Type__c='Debug', Exception_Record_Type__c='Exception', Exceptions_Enabled__c=true, Logging_Enabled__c=true);
            
            Test.startTest(); 
            
            //test push method
            Logger.push('createAccount','AccountDML');     
       		Logger.debug('Test debug message');
            //generate exception
            try {
            	insert new Account();
            
            }   
            catch (System.DmlException ex) {
                
            	Logger.debugException(ex); 
                
          
            }
            
            //test pop method
            Logger.pop();
            
			List<Log__c> testLog = [Select ExceptionType__c, Message__c from Log__c];
			System.assertEquals('Test debug message', testLog[0].Message__c);
			System.assert(testLog[1].Message__c.indexOf('fail') > -1);
			
						
			
            Test.stopTest();
            
        }
     
   }
   
}