objects/MW_Project__c.object
<CustomObject>
    <description>This is the AEG Request and Project Object.</description>
    <fields>
        <fullName>First_Assigned_Date__c</fullName>
        <inlineHelpText>Date/Time the Project was first assigned to a team member</inlineHelpText>
        <label>First Assigned Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <label>Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Purpose__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Conf Call/Email</fullName>
                </value>
                <value>
                    <fullName>Visit Customer</fullName>
                </value>
                <value>
                    <fullName>WebEx</fullName>
                </value>
                <value>
                    <fullName>Guided Evaluation</fullName>
                </value>
                <value>
                    <fullName>Deep Technical Engagement</fullName>
                </value>
                <value>
                    <fullName>Product Customization</fullName>
                </value>
                <value>
                    <fullName>Private Seminar</fullName>
                </value>
                <value>
                    <fullName>Workshop</fullName>
                </value>
                <value>
                    <fullName>Public Seminar</fullName>
                </value>
                <value>
                    <fullName>Customer Visits MW</fullName>
                </value>
                <value>
                    <fullName>Release &amp; Software Update</fullName>
                </value>
                <value>
                    <fullName>CME</fullName>
                </value>
                <value>
                    <fullName>Webinar</fullName>
                </value>
                <value>
                    <fullName>Conference/Trade Show</fullName>
                </value>
                <value>
                    <fullName>Web Event</fullName>
                </value>
                <value>
                    <fullName>Partner/Distributor Support</fullName>
                </value>
                <value>
                    <fullName>Other Physical Events</fullName>
                </value>
                <value>
                    <fullName>Departmental Support</fullName>
                </value>
                <value>
                    <fullName>Administrative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Team_Members__c</fullName>
        <description>Field to hold a concatenated list of Project Team Member user IDs (populated via trigger on Project Team Member object) to be used for dynamically determining &quot;My Projects&quot;.</description>
        <label>Project Team Members</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <label>Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Opportunity Support</fullName>
                </value>
                <value>
                    <fullName>Territory Support</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Other Dept Support</fullName>
                </value>
                <value>
                    <fullName>TE University Engagement</fullName>
                </value>
                <value>
                    <fullName>Administrative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requester__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will have to be populated with the Requester Name.</description>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Selling_Priorities__c</fullName>
        <label>Selling Priorities</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Automated Driving</fullName>
                </value>
                <value>
                    <fullName>Computer Vision</fullName>
                </value>
                <value>
                    <fullName>HDL</fullName>
                </value>
                <value>
                    <fullName>Engineering Data Analytics</fullName>
                </value>
                <value>
                    <fullName>Robotics</fullName>
                </value>
                <value>
                    <fullName>Motor and Power Control</fullName>
                </value>
                <value>
                    <fullName>Internet of Things</fullName>
                </value>
                <value>
                    <fullName>MATLAB Platform</fullName>
                </value>
                <value>
                    <fullName>Physical Systems Modeling</fullName>
                </value>
                <value>
                    <fullName>Polyspace</fullName>
                </value>
                <value>
                    <fullName>Simulink Real-Time</fullName>
                </value>
                <value>
                    <fullName>Wireless</fullName>
                </value>
                <value>
                    <fullName>Simulink and Model-Based Design</fullName>
                </value>
                <value>
                    <fullName>EDU</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P{000000}</displayFormat>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Team_Member__c.object
<CustomObject>
    <description>This object is for AE / PE Resource Requests and Tracking (User Story: 317488)</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>MW_Project__c</referenceTo>
        <relationshipName>Project_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Requester__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Copied from the Project record to be used in Project Team Member Workflow Email Alerts</description>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Team Member</label>
    <nameField>
        <displayFormat>PT-{00000}</displayFormat>
        <label>Project Team ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ProjectTMDMLTest.cls
/**
 * Modified : Faina Gorelik
 * Date modified: 29 Nov 2016 AtTask #1777908 
 * description: This class contains unit tests for validating the behavior of ProjectDML, ProjectTriggerHandler classes
 * and ProjectMasterTrigger trigger.
 */
@isTest
private class ProjectTMDMLTest {
  
 
 
 static testMethod void testCreateProjectTM()
 {
 
    User usrObj=TestDataBuilder.buildTestUser(2);
    insert usrObj;
    string TeamMemberUser1 = string.valueof(usrObj.Id).substring(0,15).substring(10,15);
    User usrObjRef=TestDataBuilder.buildTestUser(3);
    insert usrObjRef;
    string TeamMemberUser2 = string.valueof(usrObjRef.Id).substring(0,15).substring(10,15);
    List<MW_Project__c> testList = TestDataBuilder.buildTestMWProject(2, 'Sales - Qualifications');
    for(MW_Project__c objMWProj : testList)
    {
        objMWProj.Requester__c = usrObj.Id;
        objMWProj.Purpose__c='Opportunity Support';
        objMWProj.outcome__c = 'WebEx';  
        objMWProj.Selling_Priorities__c ='None';
       
    }
    insert testList;
  
   
    Project_Team_Member__c objProjecTM = new Project_Team_Member__c();
    objProjecTM.Resource__c = usrObj.ID;
    objProjecTM.Project__c = testList[0].ID;
    if(testList[0].First_Assigned_Date__c == null){
    //MW_Project__c proj = new MW_Project__c();
    //proj.id=testList[0].ID;
    testList[0].First_Assigned_Date__c = DateTime.now();
    //testList.add(proj);
    }
    
    
    Project_Team_Member__c projecTM = new Project_Team_Member__c();
    projecTM.Resource__c = usrObjRef.ID;
    projecTM.Project__c = testList[0].ID;
    if(testList[0].First_Assigned_Date__c == null){
    testList[0].First_Assigned_Date__c = DateTime.now().addHours(3) ;
     }
    
   
    List<MW_Project__c> updatedProj0 = [Select Id, project_team_members__c from mw_project__c where id=:testList[0].Id];
    insert objProjecTM;
    
    List<MW_Project__c> updatedProj1 = [Select Id, project_team_members__c from mw_project__c where id=:testList[0].Id];
    System.assertEquals(TeamMemberUser1+',' + updatedProj0[0].project_team_members__c , updatedProj1[0].project_team_members__c);
    
    update objProjecTM;
    
    Update testList;
     
    insert projecTM;
   
    Update testList;
    
    List<MW_Project__c> updatedProj2 = [Select Id, project_team_members__c from mw_project__c where id=:testList[0].Id];
    System.assertEquals(TeamMemberUser2+',' + updatedProj1[0].project_team_members__c , updatedProj2[0].project_team_members__c);
    
    System.assertNotEquals(testList[0].First_Assigned_Date__c,DateTime.now().addHours(3));
    
    delete objProjecTM;
    List<MW_Project__c> updatedProj3 = [Select Id, project_team_members__c from mw_project__c where id=:testList[0].Id];
    System.assertEquals(TeamMemberUser2+',' + updatedProj0[0].project_team_members__c , updatedProj3[0].project_team_members__c);
    
    Undelete objProjecTM;
    List<MW_Project__c> updatedProj4 = [Select Id, project_team_members__c from mw_project__c where id=:testList[0].Id];
    System.assertEquals(TeamMemberUser2+',' + updatedProj1[0].project_team_members__c , updatedProj4[0].project_team_members__c);
 }
 
 
 
}