objects/Project_Time_Card__c.object
<CustomObject>
    <fields>
        <fullName>Project_Status__c</fullName>
        <description>Pulls the Project Status value from the related project, used in validation rules and time card entry behavior</description>
        <formula>TEXT(Project__r.Project_Status__c)</formula>
        <label>Project Status</label>
        <type>Text</type>
    </fields>
    <label>Time Card</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Project Time Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Project_Validation_Rule_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to manage the profiles and users that are subject to Project validation rules.</description>
    <fields>
        <fullName>Prevent_Deleting_Closed_Projects__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Prevent Deleting Closed Projects</label>
        <type>Checkbox</type>
    </fields>
    <label>Project Validation Rule Settings</label>
</CustomObject>

classes/TimecardTriggerHandler.cls
/**
 *author Original: Sagar Talele - Cloud Sherpas/Mathworks, Last Modified: Sagar - Cloud Sherpas/Mathworks
 *date Original: 26 September 2014, Last Modified: 26 September 2014
 *description: This  is handler class for 'TimecardMasterTrigger' . 
 */
public with sharing class TimecardTriggerHandler {
	/**
 *author Original: Sagar Talele - Cloud Sherpas/Mathworks, Last Modified: Sagar - Cloud Sherpas/Mathworks
 *date Original: 26 September 2014, Last Modified: 26 September 2014
 *description: check if project related to timecard is closed show error else delete Timecard 
 */
	public void onBeforeDelete(List<Project_Time_Card__c> List_projTimecard){
		
		Logger.push('onBeforeDelete','TimecardTriggerHandler ');
		//create a list that contains timecard id.
		List<Id> timecardId = new list<Id>();
		String deleteEroror = Label.TimecardDeleteErrorMessage;
		//fetch general setting instance
		Project_Validation_Rule_Settings__c settings  =Project_Validation_Rule_Settings__c.getInstance();
		
		// Iterate over the  List_projTimecard
		for(Project_Time_Card__c timecardObj :List_projTimecard){
          // checks if Project_Status__c=='closed' do not allow to delete the timecard and show error message. 
            if(timecardObj.Project_Status__c=='closed' &&  settings.Prevent_Deleting_Closed_Projects__c == true ){
            	//Show error message 
            	timecardObj.adderror(deleteEroror);
            }
           
        }
        
       Logger.pop(); 
	}
	
}